!                   *********************
                    PROGRAM PARTEL_PRELIM
!                   *********************
!
!***********************************************************************
! PARALLEL   V6P2                                   20/02/2012
!***********************************************************************
!
!BRIEF    PREPROCESSING STEP BEFORE A PARALLEL COMPUTATION
!HISTORY   R. KOPMANN (BAW)
!+
!+
!+         FIRST  VERSION JANUARY-MARCH 2000
!
!HISTORY   JAJ
!+      12/12/2000
!+      SECOND VERSION PINXIT
!+     PARTITIONING OF GEOMETRY AND 2D RESULT FILES POSSIBLE

!HISTORY   JAJ
!+      22/02/2002
!+      THIRD VERSION
!+     ERRORS IN BC VALUES IN DECOMPOSED BC FILES REMOVED
!+     ERRONEOUS TREATMENT OF ISLANDS DEBUGGED
!
!HISTORY   J-M HERVOUET ; JAJ
!+      17/04/2002
!+     FOURTH VERSION
!+     PARTITIONING FOR 3D RESULT FILES DONE BY JMH
!+     INCLUDING BOTH PARTITIONING METHODS AND BEAUTIFYING BY JAJ
!
!HISTORY  J-M HERVOUET
!+     21/01/2003
!+     FIFTH VERSION
!+     CORRECTED A WRONG DIMENSION OF THE ARRAY CUT, AN ERROR
!+     OCCURING BY A LARGER NUMBER OF PROCESSORS
!
!HISTORY  JAJ; MATTHIEU GONZALES DE LINARES
!+        27/01/2003
!+        SIXTH VERSION
!+    CORRECTED A WRONG DIMENSION OF THE ARRAY ALLVAR
!
!HISTORY  J-M HERVOUET
!+       12/03/2003
!+      SEVENTH VERSION
!+      ALGORITHM CHANGED : A SEGMENT IS IN A SUBDOMAIN IF IT BELONGS
!+      TO AN ELEMENT IN THE SUBDOMAIN NOT IF THE 2 POINTS OF THE
!+      SEGMENT BELONG TO THE SUBDOMAIN.
!+       SPECIFIC ELEBD INCLUDED, ALL REFERENCE TO MPI OR BIEF REMOVED
!
!HISTORY  J-M HERVOUET
!+        01/09/2003
!+      EIGHTH VERSION
!+      UBOR AND VBOR INVERTED LINE 613 WHEN READING THE CLI FILE.
!
!HISTORY   C. MOULINEC, P. VEZOLLE, O. BOITEAU
!+
!+      NEXT VERSION
!+      SOME CHANGES
!
!HISTORY   C. DENIS (EDF-SINETICS)
!+        31/05/2010
!+      V6P2
!+      FURTHER DEVELOPPED IN ORDER TO DECREASE THE AMOOUT OF MEMORY
!
!HISTORY  N.DURAND (HRW), S.E.BOURBAN (HRW)
!+        21/02/2012
!+        V6P2
!+   CREATION OF DOXYGEN TAGS FOR AUTOMATED DOCUMENTATION AND
!+   CROSS-REFERENCING OF THE FORTRAN SOURCES
!
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
      IMPLICIT NONE
!
!   MAXIMUM GEOMETRICAL MULTIPLICITY OF A NODE (VARIABLE AUSSI
!   PRESENTE DANS LA BIEF, NE PAS CHANGER L'UNE SANS L'AUTRE)
      INTEGER, PARAMETER :: NBMAXNSHARE =  10
!     
      INTEGER, PARAMETER :: MAXNPROC = 100000 ! MAX PARTITION NUMBER [00000..99999]
      INTEGER, PARAMETER :: MAXLENSOFT = 144 ! SOFT MAX FILE NAME LENGTH
      INTEGER, PARAMETER :: MAXLENHARD = 250 ! HARD MAX FILE NAME LENGTH
      INTEGER, PARAMETER :: MAXADDCH = 10 ! MAX ADDED SUFFIX LENGTH
      INTEGER, PARAMETER :: MAXVAR = 100  ! MAX NUMBER OF VARIABLES
      INTEGER, PARAMETER :: MAXALLVARLENGTH = 3200 ! MAXVAR*32 FOR ALLVAR
!
      INTEGER PMETHOD
      INTEGER NVAR, NREC, NPLAN, NPTFR, NPTIR, NPTFRMAX
      INTEGER NELEM, NPOIN, NDP, NELEM2, NPOIN2, NDUM
      INTEGER FILE_MPI
      INTEGER IB(10)
!
      INTEGER, ALLOCATABLE :: IKLES(:), IKLES_P(:)
      INTEGER, ALLOCATABLE :: IKLES3D(:),IKLES3D_P(:,:,:)
      INTEGER, ALLOCATABLE :: IRAND(:), IRAND_P(:)
      INTEGER, ALLOCATABLE :: LIHBOR(:), LIUBOR(:), LIVBOR(:)
      INTEGER, ALLOCATABLE :: LITBOR(:)
      INTEGER ::  NPOIN_P, NELEM_P , NPTFR_P,NPTIR_P
      INTEGER, ALLOCATABLE :: NBOR(:), NBOR_P(:)
      INTEGER, ALLOCATABLE :: NUMLIQ(:), NUMSOL(:)
      INTEGER, ALLOCATABLE :: KNOLG(:), KNOGL(:),CHECK(:)
      INTEGER, ALLOCATABLE :: ELELG(:), ELEGL(:)
      INTEGER, ALLOCATABLE :: CUT(:), CUT_P(:), SORT(:)
      INTEGER, ALLOCATABLE :: PART_P(:,:), PART(:),PART_P1(:,:)
!
      REAL, ALLOCATABLE    :: F(:,:), F_P(:,:)
      REAL, ALLOCATABLE    :: HBOR(:) 
      REAL, ALLOCATABLE    :: UBOR(:), VBOR(:), AUBOR(:)
      REAL, ALLOCATABLE    :: TBOR(:), ATBOR(:), BTBOR(:)
!
      REAL TIMES, TIMED
!
      INTEGER :: NINP=10, NCLI=11, NMET=12,NINPFORMAT=52
      INTEGER :: NEPART=15, NNPART=16, NOUT=17, NCLM=18
      INTEGER TIME(3), DATE(3)
!
      CHARACTER(LEN=80)  :: TITLE
      CHARACTER(LEN=32)  :: VARI, VARIABLE(MAXVAR)
      CHARACTER(LEN=MAXALLVARLENGTH) :: ALLVAR 
      CHARACTER(LEN=MAXLENHARD)  :: NAMEINP, NAMECLI, NAMEOUT, NAMECLM,
     &     NAMECLMP,NAMEOUTP
      CHARACTER(LEN=MAXLENHARD)  :: NAMEMET,NAMEEPART,NAMENPART,
     &     NAMENINPFORMAT,NAMEOUTFORMA
      CHARACTER(LEN=5)   :: CHCH  
      CHARACTER(LEN=12)  :: FMT4
!
      INTEGER MAX_NELEM_P, MIN_NELEM_P
      INTEGER  MAX_NPOIN_P,MAX_N_NEIGH
      INTEGER I, J, K, L , M, N, P, ERR, ISO, IDUM
      INTEGER ISTOP, ISTART, ISEG, II, ILOOP
      INTEGER I_LEN, I_S, I_SP, I_LENCLI, I_LENINP
      INTEGER IELEM_P, IPOIN_P, IPTFR_P
!
      REAL XSEG, YSEG, BAL, RDUM
      DOUBLE PRECISION AREA, X1, X2, X3, Y1, Y2, Y3
      LOGICAL IS, WRT, TIMECOUNT
!
!   METISOLOGY
!
      INTEGER NPARTS, ETYPE, NUMFLAG, EDGECUT
      INTEGER, ALLOCATABLE :: EPART(:), NPART(:)
      CHARACTER(LEN=10) FMT1, FMT2, FMT3
!
!   FOR CALLING FRONT2
!
      INTEGER, PARAMETER :: MAXFRO = 300   ! MAX NUMBER OF BOUNDARIES
      INTEGER NFRLIQ, NFRSOL, DEBLIQ(MAXFRO), FINLIQ(MAXFRO)
      INTEGER DEBSOL(MAXFRO), FINSOL(MAXFRO)
      INTEGER, ALLOCATABLE :: DEJAVU(:), KP1BOR(:,:)

!
!   FOR CALLING BIEF MESH SUBROUTINES (TO BE OPTIMISED SOON):
      INTEGER, ALLOCATABLE :: IFABOR(:,:), IFANUM(:,:), NELBOR(:)
      INTEGER, ALLOCATABLE :: NULONE(:,:)
      INTEGER, ALLOCATABLE :: IKLE(:,:), IKLBOR(:,:), ISEGF(:)
      INTEGER, ALLOCATABLE :: IT1(:), IT2(:), IT3(:)
!
      INTEGER LNG,LU,LI
      COMMON /INFO/ LNG,LU
!
!   TIME MEASURING 
!
      INTEGER  TDEB, TFIN, TDEBP, TFINP, TEMPS, PARSEC
      INTEGER  TDEB_GLOB, TFIN_GLOB
      INTEGER  TIME_IN_SECONDS
      EXTERNAL TIME_IN_SECONDS
!
!   EXTENS FUNCTION
!
      CHARACTER(LEN=11) :: EXTENS
      EXTERNAL EXTENS   
!
!----------------------------------------------------------------------
!
!   JAJ NEW FOR PARALLEL CHARACTERISTICS ////
!   HALO ELEMENTS: THESE ADJACENT TO THE INTERFACE EDGES HAVING 
!   NEIGHBOURS BEHIND A BOUNDARY 
!
      ! THE ELEMENTAL GLOBAL->LOCAL NUMBERING TRANSLATION TABLE 
      ! THIS IS ELEGL SAVED FROM ALL PARTITIONS FOR FURTHER USE
      DOUBLE PRECISION :: STARTTIME,ENDTIME,STARTIOTIME,STARTCTIME
      INTEGER, ALLOCATABLE :: GELEGL(:),GELEGL1(:)
!
      ! THE HALO ELEMENTS NEIGHBOURHOOD DESCRIPTION FOR A HALO CELL 
      INTEGER, ALLOCATABLE :: IFAPAR(:,:)
!
      ! THE NUMBER OF HALO CELLS PRO PARTITION 
      INTEGER :: NHALO 
!
      ! WORK VARIABLES 
      INTEGER IFALOC(3)
      INTEGER TEMP_I(8)
      DOUBLE PRECISION TEMP_F(9)
      LOGICAL FOUND
      INTEGER NDP_2D,NDP_3D,NB_INTER_GLOB,COMPT
      INTEGER EF,POS
      INTEGER, ALLOCATABLE :: NBRE_EF(:),NBRE_EF_LOC(:),EF_I(:),
     &     TAB_TMP(:),EF_II(:),GLOBAL_INTER_NODE_REORD(:)
      INTEGER, ALLOCATABLE :: PART_P_TMP1(:),PART_P_TMP2(:)
      LOGICAL TROUVE,HALO
      INTEGER NOEUD,NBRE_NOEUD_INTERNE
      INTEGER NBRE_NOEUD_INTERF
      INTEGER FRONTIERE, NBRE_EF_I,IER,ID,NBRE_NPTIR
      LOGICAL INTERFACE  
      CHARACTER (LEN=5) :: III
!   FOR SCOTCH 
   
!      DOUBLEPRECISION    GRAPH  (SCOTCH_GRAPHDIM)
!      DOUBLEPRECISION    STRADAT (SCOTCH_STRATDIM)
      INTEGER BASEVAL
      INTEGER VERTNBR
      INTEGER EDGENBR
      INTEGER, ALLOCATABLE :: VER (:)
      INTEGER, ALLOCATABLE :: EDGETAB (:)
!     
      NDP_2D=3
      NDP_3D=6
!    
!----------------------------------------------------------------------
!
      CALL SYSTEM_CLOCK (COUNT=TEMPS, COUNT_RATE=PARSEC)
      TIMECOUNT = .TRUE.
      IF (PARSEC==0) TIMECOUNT = .FALSE.  ! COUNT_RATE == 0 : NO CLOCK
      IF (TIMECOUNT) TDEB = TEMPS
!
      LNG=2 ! JE NE PARLE FRANCAIS, JE SUIS BARBARIEN
      LU=6  ! FORTRAN STANDARD OUPUT CHANNEL
      LI=5  ! FORTRAN STANDARD INPUT CHANNEL
!
! INTRODUCE YOURSELF
!
!      IF (ID .EQ. 0) THEN 
!       WRITE(LU,*) ' '
!       WRITE(LU,*) '+-------------------------------------------------+'
!       WRITE(LU,*) '  PRELIMINARY TASK FOR PARTEL                    '
!       WRITE(LU,*) '  PARALLEL VERSION DEVELOPPED BY                   '          
!       WRITE(LU,*) '  CHRISTOPHE DENIS  (SINETICS)'
!       WRITE(LU,*) '  PARTEL (C) COPYRIGHT 2000-2002 '
!       WRITE(LU,*) '  BUNDESANSTALT FUER WASSERBAU, KARLSRUHE'
!       WRITE(LU,*) ' '
!       WRITE(LU,*) '  METIS 4.0.1 (C) COPYRIGHT 1998 '
!       WRITE(LU,*) '  REGENTS OF THE UNIVERSITY OF MINNESOTA '
!       WRITE(LU,*) ' '
!       WRITE(LU,*) '  BIEF 5.9 (C) COPYRIGHT 2010 EDF'
!       WRITE(LU,*) '+-------------------------------------------------+'
!       WRITE(LU,*) '    LUN MAI 31 17:21:20 CEST 2010               ' 
!       WRITE(LU,*) ' '
!       WRITE(LU,*) '+-----------------------------------------------+'
!      END IF
!     
!----------------------------------------------------------------------
! NAMES OF THE INPUT FILES:
!      INQUIRE (FILE='PARTEL.PAR',EXIST=IS)
!      IF (.NOT.IS) THEN 
!        WRITE (LU,'('' FILE DOES NOT EXIST: '',A30)') 
!        CALL PLANTE2(-1)
!        STOP
!      END IF  
!###> SEB@HRW: SO YOU DO THIS ONLY ONCE
      INQUIRE (FILE='RESULT_SEQ_METIS',EXIST=IS)
      IF (IS) THEN 
        CALL PLANTE2(0)
        STOP
      END IF  
!###< SEB@HRW
!
!###> SEB@HRW: EASIER TO DO WITH ONE FILE ONLY
!      OPEN(UNIT=74,FILE='PARTEL_PRELIM.PAR')
      OPEN(UNIT=72,FILE='PARTEL.PAR')
      READ(72,*) NAMEINP
      READ(72,*) 
      READ(72,*) NPARTS
      READ(72,*) 
      CLOSE(72)
!###< SEB@HRW
!
      INQUIRE (FILE=NAMEINP,EXIST=IS)
      IF (.NOT.IS) THEN 
         WRITE (LU,'('' FILE DOES NOT EXIST: '',A30)') NAMEINP
         CALL PLANTE2(-1)
         STOP
      END IF
!
      PMETHOD=1
!
      I_S  = LEN(NAMEINP)
      I_SP = I_S + 1
      DO I=1,I_S
         IF (NAMEINP(I_SP-I:I_SP-I) .NE. ' ') EXIT
      ENDDO
      I_LEN=I_SP - I
      I_LENINP = I_LEN
!
      IF (I_LENINP > MAXLENSOFT) THEN
         WRITE(LU,*) ' '
         WRITE(LU,*) 'ATTENTION:'
         WRITE(LU,*) 'THE NAME OF THE INPUT FILE:'
         WRITE(LU,*) NAMEINP
         WRITE(LU,*) 'IS LONGER THAN ',MAXLENSOFT,' CHARACTERS' 
         WRITE(LU,*) 'WHICH IS THE LONGEST APPLICABLE NAME FOR TELEMAC '
         WRITE(LU,*) 'INPUT AND OUTPUT FILES. STOPPED. '
         CALL PLANTE2(-1)
         STOP
      ENDIF
!
      OPEN(NINP,FILE=NAMEINP,STATUS='OLD',FORM='UNFORMATTED')
      REWIND NINP
!
      READ (NINP) TITLE
      READ (NINP) I, J
      NVAR = I + J 
      ALLVAR(1:41) = 'X-COORDINATE----M---,Y-COORDINATE----M---'
      ISTART = 42
      DO I=1,NVAR
         READ(NINP) VARI
         VARIABLE(I) = VARI
         DO J=1,32
            IF(VARI(J:J).EQ.' ') VARI(J:J) = '-'
         END DO
         ISTOP = ISTART+20
         IF (ISTOP.GT.MAXALLVARLENGTH) THEN
            WRITE(LU,*) 'VARIABLE NAMES TOO LONG FOR STRING ALLVAR'
            WRITE(LU,*) 'STOPPED.'
            CALL PLANTE2(-1)
            STOP
         ENDIF
         ALLVAR(ISTART:ISTART) = ','
         ALLVAR(ISTART+1:ISTOP) = VARI
         ISTART=ISTOP+1
      ENDDO
!
!  READ THE REST OF THE SELAFIN FILE
!  10 INTEGERS, THE FIRST IS THE NUMBER OF RECORDS (TIMESTEPS)
!
      READ (NINP) (IB(I), I=1,10)
      IF (IB(8).NE.0.OR.IB(9).NE.0) THEN
         WRITE(LU,*) 'THIS IS A PARTIAL OUTPUT FILE'
         WRITE(LU,*) 'MAYBE MEET GRETEL BEFORE...'
      ENDIF 
      NREC  = IB(1)
      NPLAN = IB(7)
!
      IF (IB(10).EQ.1) THEN
         READ(NINP) DATE(1), DATE(2), DATE(3), TIME(1), TIME(2), TIME(3)
      ENDIF 
!
      READ (NINP) NELEM,NPOIN,NDP,NDUM
      IF (NPLAN.GT.1) THEN
         NPOIN2 = NPOIN/NPLAN
         NELEM2 = NELEM/(NPLAN-1)
         IF (MOD(NPOIN,NPLAN).NE.0) THEN 
            WRITE (LU,*) 'BUT NPOIN2 /= NPOIN3/NPLAN!'
            CALL PLANTE2(-1)
            STOP   
         ENDIF
         IF (MOD(NELEM,(NPLAN-1)).NE.0) THEN 
            WRITE (LU,*) 'BUT NELEM2 /= NELEM3/NPLAN!'
            CALL PLANTE2(-1)
            STOP
         ENDIF
      ELSE
         NPOIN2 = NPOIN
         NELEM2 = NELEM
      ENDIF
!
      IF (NDP.EQ.3) THEN  
!         WRITE(LU,*) 'THE INPUT FILE ASSUMED TO BE 2D SELAFIN'
      ELSEIF (NDP.EQ.6) THEN
!         WRITE(LU,*) 'THE INPUT FILE ASSUMED TO BE 3D SELAFIN'
      ELSE   
!         WRITE(LU,*) 'THE ELEMENTS ARE NEITHER TRIANGLES NOR PRISMS!'
!         WRITE(LU,*) 'NDP = ',NDP
         CALL PLANTE2(-1)
         STOP
      ENDIF
!
! NOW LET US ALLOCATE 
!
      ALLOCATE (IKLES(NELEM2*3),STAT=ERR)
      IF (ERR.NE.0) CALL ALLOER (LU, 'IKLES')
      IF(NPLAN.GT.1) THEN
         ALLOCATE (IKLES3D(NELEM*NDP),STAT=ERR)
         IF (ERR.NE.0) CALL ALLOER (LU, 'IKLES3D')
      ENDIF 
      ALLOCATE (IRAND(NPOIN),STAT=ERR)
      IF (ERR.NE.0) CALL ALLOER (LU, 'IRAND')
!   NVAR+2 : FIRST TWO FUNCTIONS ARE X AND Y
!   NPOIN IS 3D HERE IN 3D
      ALLOCATE (F(NPOIN,NVAR+2),STAT=ERR)
      IF (ERR.NE.0) CALL ALLOER (LU, 'IRAND')
!
! CONNECTIVITY TABLE:
!
      IF(NPLAN.EQ.0) THEN
         READ(NINP) ((IKLES((K-1)*NDP+J),J=1,NDP),K=1,NELEM)
      ELSE
         READ(NINP) ((IKLES3D((K-1)*NDP+J),J=1,NDP),K=1,NELEM)
         DO J=1,3
            DO K=1,NELEM2
               IKLES((K-1)*3+J)=IKLES3D((K-1)*6+J)
            ENDDO
         ENDDO
      ENDIF
!
      READ(NINP) (IRAND(J),J=1,NPOIN)
      READ(NINP) (F(J,1),J=1,NPOIN)
      READ(NINP) (F(J,2),J=1,NPOIN)
!
      ILOOP = 0
!      DO 
!
!  READ THE TIME STEP
!
      READ(NINP) TIMES
!      WRITE(NINPFORMAT,*) TIMES
      ILOOP = ILOOP + 1
!
      TIMED = TIMES/3600
!      WRITE(LU,*) 'TIMESTEP: ',TIMES,'S = ',TIMED,'H'
!
! READ THE TIME VARIABLES; NO 1 AND 2 ARE X,Y
!
      DO K=3,NVAR+2
!         WRITE(LU,*) 'NOW READING VARIABLE',K-2
         READ(NINP) (F(J,K), J=1,NPOIN)
!         WRITE(NINPFORMAT,*) (F(J,K), J=1,NPOIN)
!         WRITE(LU,*) 'READING VARIABLE',K-2,' SUCCESSFUL'
      END DO
!     END DO
!     STOP
 111  CLOSE (NINP)
!
      NUMFLAG = 1
!
      ETYPE = 1
!
      IF (TIMECOUNT) THEN 
         CALL SYSTEM_CLOCK (COUNT=TEMPS, COUNT_RATE=PARSEC)
         TDEBP = TEMPS
      ENDIF
      ALLOCATE (EPART(NELEM2),STAT=ERR)
      IF (ERR.NE.0) CALL ALLOER (LU, 'EPART')
      ALLOCATE (NPART(NPOIN2),STAT=ERR)
      IF (ERR.NE.0) CALL ALLOER (LU, 'NPART')
      !WRITE(*,*) NELEM2,NPOIN2,NPARTS
!
      CALL METIS_PARTMESHDUAL 
     &     (NELEM2, NPOIN2, IKLES, ETYPE, NUMFLAG, 
     &     NPARTS, EDGECUT, EPART, NPART)
!
      OPEN(UNIT=256,FILE='RESULT_SEQ_METIS')
      DO I=1,NELEM2
         WRITE(256,*) EPART(I)
      END DO 

      !WRITE(*,*) 'END OF THE PRELIMINARY PART OF PARTEL'
      END PROGRAM PARTEL_PRELIM


      SUBROUTINE ALLOER (N, CHFILE)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: N
      CHARACTER*(*), INTENT(IN) :: CHFILE
      WRITE(N,*) 'ERROR BY ALLOCATION OF ',CHFILE
      CALL PLANTE2(-1)
      STOP
      END SUBROUTINE ALLOER
      
      SUBROUTINE ALLOER2(N,CHFILE)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: N
      CHARACTER*(*), INTENT(IN) :: CHFILE
      WRITE(N,*)TRIM(CHFILE)
      CALL PLANTE2(-1)
      STOP
      END SUBROUTINE ALLOER2


      SUBROUTINE PLANTE2 (IVAL)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: IVAL
      INTEGER ICODE      
      IF (IVAL < 0) THEN      ! THIS INDICATES A CONTROLLED ERROR
        ICODE = 1 
      ELSE IF (IVAL==0) THEN  ! THIS INDICATES A PROGRAM FAILURE
        ICODE = -1
      ELSE                    ! THIS INDICATES A NORMAL STOP
        ICODE = 0
      ENDIF 
      !!! WRITE(*,*) 'RETURNING EXIT CODE: ', ICODE
      CALL EXIT(ICODE)
      STOP    ! WHICH IS USUALLY EQUIVALENT TO CALL EXIT(0)
      END SUBROUTINE PLANTE2
