!                    **************************
                     SUBROUTINE DEALL_TELEMAC2D
!                    **************************
!
!
!***********************************************************************
! TELEMAC2D   V6P3                                   21/08/2010
!***********************************************************************
!
!brief    Memory allocation of structures, aliases, blocks...
!
!history  J-M HERVOUET (LNHE)
!+        02/04/2009
!+
!+   T2D_FILES(T2DGEO)%LU REPLACES NGEO
!
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
      USE BIEF
      USE DECLARATIONS_TELEMAC
      USE DECLARATIONS_TELEMAC2D
!
      IMPLICIT NONE
      INTEGER LNG,LU
      COMMON/INFO/LNG,LU
!
!+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
!
      INTEGER :: I
!
!+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
!

!
!-----------------------------------------------------------------------
!
      CALL OUTBIEF(MESH)
      ! Deallocate the mesh structure
      CALL DEALMESH(MESH)
      NULLIFY(IKLE)
      NULLIFY(X)
      NULLIFY(Y)
      NULLIFY(NELEM)
      NULLIFY(NELMAX)
      NULLIFY(NPTFR)
      NULLIFY(NPTFRX)
      NULLIFY(TYPELM)
      NULLIFY(NPOIN)
      NULLIFY(NPMAX)
      NULLIFY(MXPTVS)
      NULLIFY(LV)
!
      DEALLOCATE(W)
!
      ! Deallocating all the blocks first
      CALL BIEF_DEALLOBJ(T     )
      CALL BIEF_DEALLOBJ(VARSOR)
      CALL BIEF_DEALLOBJ(UNK)
      CALL BIEF_DEALLOBJ(DIRBOR)
      CALL BIEF_DEALLOBJ(MAT)
      CALL BIEF_DEALLOBJ(RHS)
      CALL BIEF_DEALLOBJ(TB)
      CALL BIEF_DEALLOBJ(MSKSEC)
      CALL BIEF_DEALLOBJ(MASK)
      CALL BIEF_DEALLOBJ(TTILD )
      CALL BIEF_DEALLOBJ(TN    )
      CALL BIEF_DEALLOBJ(TEXP  )
      CALL BIEF_DEALLOBJ(TIMP  )
      CALL BIEF_DEALLOBJ(TSCEXP)
      CALL BIEF_DEALLOBJ(VISCT )
      CALL BIEF_DEALLOBJ(MASKTR)
      CALL BIEF_DEALLOBJ(TBOR  )
      CALL BIEF_DEALLOBJ(ATBOR )
      CALL BIEF_DEALLOBJ(BTBOR )
      CALL BIEF_DEALLOBJ(LITBOR)
      CALL BIEF_DEALLOBJ(FN)
      CALL BIEF_DEALLOBJ(F )
      CALL BIEF_DEALLOBJ(FTILD)
      CALL BIEF_DEALLOBJ(FNCAR)
      CALL BIEF_DEALLOBJ(FTILD2)
      CALL BIEF_DEALLOBJ(FNCAR2)
      CALL BIEF_DEALLOBJ(TSIP)
      CALL BIEF_DEALLOBJ(TBUS )
      CALL BIEF_DEALLOBJ(PRIVE)
      CALL BIEF_DEALLOBJ(VARCL)
      CALL BIEF_DEALLOBJ(SMTR     )
      CALL BIEF_DEALLOBJ(FLUXT    )
      CALL BIEF_DEALLOBJ(FLUXTEMP )
      CALL BIEF_DEALLOBJ(FLUHBTEMP)
      CALL BIEF_DEALLOBJ(FLUHBOR  )
      CALL BIEF_DEALLOBJ(HT       )
      CALL BIEF_DEALLOBJ(AMPL)
      CALL BIEF_DEALLOBJ(PHAS)
!
      CALL BIEF_DEALLOBJ(S)
!
      CALL BIEF_DEALLOBJ(H)
      CALL BIEF_DEALLOBJ(U)
      CALL BIEF_DEALLOBJ(V)
!
      CALL BIEF_DEALLOBJ(UTILD)
      CALL BIEF_DEALLOBJ(VTILD)
      CALL BIEF_DEALLOBJ(HTILD)
!
      CALL BIEF_DEALLOBJ(U)
      CALL BIEF_DEALLOBJ(V)
      CALL BIEF_DEALLOBJ(UN)
      CALL BIEF_DEALLOBJ(VN)
      CALL BIEF_DEALLOBJ(HN)
!
      CALL BIEF_DEALLOBJ(DH)
      CALL BIEF_DEALLOBJ(DU)
      CALL BIEF_DEALLOBJ(DV)
      CALL BIEF_DEALLOBJ(DHN)
!
!
      CALL BIEF_DEALLOBJ(HBOR    )
      CALL BIEF_DEALLOBJ(UBOR    )
      CALL BIEF_DEALLOBJ(VBOR    )
      CALL BIEF_DEALLOBJ(AUBOR   )
      CALL BIEF_DEALLOBJ(CFBOR   )
      CALL BIEF_DEALLOBJ(UETUTA  )
      CALL BIEF_DEALLOBJ(FLBOR   )
      CALL BIEF_DEALLOBJ(FLBORTRA)
!
      CALL BIEF_DEALLOBJ(HBTIDE )
      CALL BIEF_DEALLOBJ(UBTIDE )
      CALL BIEF_DEALLOBJ(VBTIDE )
      CALL BIEF_DEALLOBJ(NUMTIDE)
!
!
      CALL BIEF_DEALLOBJ(ZF    )
      CALL BIEF_DEALLOBJ(ZFE   )
      CALL BIEF_DEALLOBJ(VISC  )
      CALL BIEF_DEALLOBJ(VISC_S)
      CALL BIEF_DEALLOBJ(CHESTR)
      CALL BIEF_DEALLOBJ(PATMOS)
      CALL BIEF_DEALLOBJ(RO    )
      CALL BIEF_DEALLOBJ(WINDX )
      CALL BIEF_DEALLOBJ(WINDY )
      CALL BIEF_DEALLOBJ(FU    )
      CALL BIEF_DEALLOBJ(FV    )
      CALL BIEF_DEALLOBJ(FXWAVE)
      CALL BIEF_DEALLOBJ(FYWAVE)
!
      CALL BIEF_DEALLOBJ(BM1S)
      CALL BIEF_DEALLOBJ(BM2S)
      CALL BIEF_DEALLOBJ(CV1S)
      CALL BIEF_DEALLOBJ(TM1 )
      CALL BIEF_DEALLOBJ(MBOR)
      CALL BIEF_DEALLOBJ(AM1)
      CALL BIEF_DEALLOBJ(BM1)
      CALL BIEF_DEALLOBJ(BM2)
      CALL BIEF_DEALLOBJ(CM1)
      CALL BIEF_DEALLOBJ(AM2)
      CALL BIEF_DEALLOBJ(A23)
      CALL BIEF_DEALLOBJ(CM2)
      CALL BIEF_DEALLOBJ(A32)
      CALL BIEF_DEALLOBJ(AM3)
!
      CALL BIEF_DEALLOBJ(W1 )
      CALL BIEF_DEALLOBJ(CV1)
      CALL BIEF_DEALLOBJ(CV2)
      CALL BIEF_DEALLOBJ(CV3)
!
      CALL BIEF_DEALLOBJ(SMH   )
      CALL BIEF_DEALLOBJ(UCONV )
      CALL BIEF_DEALLOBJ(VCONV )
      CALL BIEF_DEALLOBJ(HPROP )
      CALL BIEF_DEALLOBJ(VOLU2D)
      CALL BIEF_DEALLOBJ(V2DPAR)
      CALL BIEF_DEALLOBJ(UNSV2D)
      CALL BIEF_DEALLOBJ(XLAG  )
      CALL BIEF_DEALLOBJ(YLAG  )
      CALL BIEF_DEALLOBJ(SHPLAG)
!
!
      CALL BIEF_DEALLOBJ(TE1)
      CALL BIEF_DEALLOBJ(TE2)
      CALL BIEF_DEALLOBJ(TE3)
      CALL BIEF_DEALLOBJ(ZFLATS)
      CALL BIEF_DEALLOBJ(TE4)
      CALL BIEF_DEALLOBJ(TE5)
!
!
      CALL BIEF_DEALLOBJ(MASKEL)
      CALL BIEF_DEALLOBJ(MASKPT)
!
!
      CALL BIEF_DEALLOBJ(CF    )
      CALL BIEF_DEALLOBJ(NKFROT)
      CALL BIEF_DEALLOBJ(CHBORD)
      IF(FRICTB) THEN
        DO I=1,NZONMX
          DEALLOCATE(FRTAB%ADR(I)%P)
        ENDDO
        DEALLOCATE(FRTAB%ADR)
      ENDIF
!
      CALL BIEF_DEALLOBJ(KFROPT)
      CALL BIEF_DEALLOBJ(NDEFMA)
      CALL BIEF_DEALLOBJ(LINDDP)
      CALL BIEF_DEALLOBJ(LINDSP)
      CALL BIEF_DEALLOBJ(NDEF_B)
      CALL BIEF_DEALLOBJ(KFRO_B)
      CALL BIEF_DEALLOBJ(AK    )
      CALL BIEF_DEALLOBJ(EP    )
      CALL BIEF_DEALLOBJ(AKN   )
      CALL BIEF_DEALLOBJ(EPN   )
      CALL BIEF_DEALLOBJ(AKTILD)
      CALL BIEF_DEALLOBJ(EPTILD)
      CALL BIEF_DEALLOBJ(KBOR  )
      CALL BIEF_DEALLOBJ(EBOR  )
      CALL BIEF_DEALLOBJ(UDEL  )
      CALL BIEF_DEALLOBJ(VDEL  )
      CALL BIEF_DEALLOBJ(DM1   )
      CALL BIEF_DEALLOBJ(ZCONV )
      CALL BIEF_DEALLOBJ(FLODEL)
      CALL BIEF_DEALLOBJ(FLULIM)
      CALL BIEF_DEALLOBJ(PLUIE )
      CALL BIEF_DEALLOBJ(DIRMOY)
      CALL BIEF_DEALLOBJ(HM0   )
      CALL BIEF_DEALLOBJ(TPR5  )
!
!
!
      CALL BIEF_DEALLOBJ(XFLOT )
      CALL BIEF_DEALLOBJ(YFLOT )
      CALL BIEF_DEALLOBJ(SHPFLO)
      CALL BIEF_DEALLOBJ(ZDIG  )
      CALL BIEF_DEALLOBJ(PHIDIG)
      CALL BIEF_DEALLOBJ(ENTSIP)
      CALL BIEF_DEALLOBJ(SORSIP)
      CALL BIEF_DEALLOBJ(SECSIP)
      CALL BIEF_DEALLOBJ(ALTSIP)
      CALL BIEF_DEALLOBJ(CSSIP )
      CALL BIEF_DEALLOBJ(CESIP )
      CALL BIEF_DEALLOBJ(DELSIP)
      CALL BIEF_DEALLOBJ(ANGSIP)
      CALL BIEF_DEALLOBJ(LSIP  )
      CALL BIEF_DEALLOBJ(USIP  )
      CALL BIEF_DEALLOBJ(VSIP  )
      CALL BIEF_DEALLOBJ(DSIP  )
!
!
      CALL BIEF_DEALLOBJ(ENTBUS)
      CALL BIEF_DEALLOBJ(SORBUS)
      CALL BIEF_DEALLOBJ(ALTBUS)
      CALL BIEF_DEALLOBJ(CSBUS )
      CALL BIEF_DEALLOBJ(CEBUS )
      CALL BIEF_DEALLOBJ(ANGBUS)
      CALL BIEF_DEALLOBJ(LBUS  )
      CALL BIEF_DEALLOBJ(UBUS  )
      CALL BIEF_DEALLOBJ(VBUS  )
      CALL BIEF_DEALLOBJ(DBUS  )
      CALL BIEF_DEALLOBJ(LRGBUS)
      CALL BIEF_DEALLOBJ(HAUBUS)
      CALL BIEF_DEALLOBJ(CLPBUS)
!
!
!
      CALL BIEF_DEALLOBJ(IFAMAS)
      CALL BIEF_DEALLOBJ(LIUBOR)
      CALL BIEF_DEALLOBJ(LIVBOR)
      CALL BIEF_DEALLOBJ(LIHBOR)
      CALL BIEF_DEALLOBJ(CLU   )
      CALL BIEF_DEALLOBJ(CLV   )
      CALL BIEF_DEALLOBJ(CLH   )
      CALL BIEF_DEALLOBJ(BOUNDARY_COLOUR)
      CALL BIEF_DEALLOBJ(NUMLIQ)
      CALL BIEF_DEALLOBJ(LIMKEP)
      CALL BIEF_DEALLOBJ(LIMPRO)
      CALL BIEF_DEALLOBJ(LIMTRA)
      CALL BIEF_DEALLOBJ(SECMOU)
      CALL BIEF_DEALLOBJ(IT1   )
      CALL BIEF_DEALLOBJ(IT2   )
      CALL BIEF_DEALLOBJ(IT3   )
      CALL BIEF_DEALLOBJ(IT4   )
      CALL BIEF_DEALLOBJ(DEBFLO)
      CALL BIEF_DEALLOBJ(FINFLO)
      CALL BIEF_DEALLOBJ(ELTFLO)
      CALL BIEF_DEALLOBJ(TAGFLO)
      CALL BIEF_DEALLOBJ(DEBLAG)
      CALL BIEF_DEALLOBJ(FINLAG)
      CALL BIEF_DEALLOBJ(ELTLAG)
      CALL BIEF_DEALLOBJ(ZONE  )
!
!
      CALL BIEF_DEALLOBJ(QU       )
      CALL BIEF_DEALLOBJ(QV       )
      CALL BIEF_DEALLOBJ(HSTOK    )
      CALL BIEF_DEALLOBJ(HCSTOK   )
      CALL BIEF_DEALLOBJ(LOGFR    )
      CALL BIEF_DEALLOBJ(HC       )
      CALL BIEF_DEALLOBJ(DSZ      )
      CALL BIEF_DEALLOBJ(FLUX_OLD )
      CALL BIEF_DEALLOBJ(NEISEG   )
      CALL BIEF_DEALLOBJ(H0   )
      CALL BIEF_DEALLOBJ(MAXZ )
      CALL BIEF_DEALLOBJ(TMAXZ)
      CALL BIEF_DEALLOBJ(MAXV )
      CALL BIEF_DEALLOBJ(TMAXV)
!
!
!
      ! Deallocate some global variables allocated at some point in the code
      IF(ALLOCATED(CTRLSC)) THEN
        DEALLOCATE(CTRLSC)
      ENDIF
      IF(ALLOCATED(W)) THEN
        DEALLOCATE(W)
      ENDIF
      IF(ALLOCATED(QZ)) THEN
        DEALLOCATE(QZ)
      ENDIF
      IF(ALLOCATED(CHAIN)) THEN
        DEALLOCATE(CHAIN)
      ENDIF
 
!
!=======================================================================
!
! WRITES OUT TO LISTING :
!
      IF(LISTIN) THEN
        IF(LNG.EQ.1) WRITE(LU,22)
        IF(LNG.EQ.2) WRITE(LU,23)
      ENDIF
22    FORMAT(1X,///,21X,'****************************************',/,
     &21X,              '* FIN DE LA DEALLOCATION DE LA MEMOIRE  : *',/,
     &21X,              '****************************************',/)
23    FORMAT(1X,///,21X,'*************************************',/,
     &21X,              '*    END OF MEMORY ORGANIZATION:    *',/,
     &21X,              '*************************************',/)
!
!-----------------------------------------------------------------------
!
      RETURN
      END SUBROUTINE DEALL_TELEMAC2D
