!
!  INTERFACES OF TOMAWAC SUBROUTINES
!
      MODULE INTERFACE_TOMAWAC
!
!=======================================================================
!
!     DEFINITION OF STRUCTURES
!
      USE BIEF_DEF
!
!-----------------------------------------------------------------------
!
!     DEFINITION OF INTERFACES
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE ANACOS(UC,VC,X,Y,NPOIN2)
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NPOIN2
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN2),Y(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: UC(NPOIN2), VC(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE ANAMAR
     &( UC  , VC  , ZM  , ZM1 , ZM2 , DZHDT , X  , Y  , NPOIN2 ,
     &  AT  , DDC , LT  )
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NPOIN2,LT
      DOUBLE PRECISION, INTENT(IN)    :: AT,DDC
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN2),Y(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: ZM1(NPOIN2),ZM2(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: UC(NPOIN2),VC(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: DZHDT(NPOIN2),ZM(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE ANAVEN
     &( UV , VV , X , Y , NPOIN2, AT , DDC , VX_CTE, VY_CTE)
      IMPLICIT NONE
      INTEGER, INTENT(IN)             ::  NPOIN2
      DOUBLE PRECISION, INTENT(IN)    ::  AT, DDC, VX_CTE, VY_CTE
      DOUBLE PRECISION, INTENT(IN)    ::  X (NPOIN2)    , Y (NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) ::  UV(NPOIN2)    , VV(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE ANGLES(XLAMD , DTPLUS, DTMOIN)
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN)    :: XLAMD
      DOUBLE PRECISION, INTENT(INOUT) :: DTPLUS, DTMOIN
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE BORNES(B , N , A , XM , X0 , X1 )
      IMPLICIT NONE
      INTEGER, INTENT(IN)             ::  N
      DOUBLE PRECISION, INTENT(IN)    :: B , A , XM
      DOUBLE PRECISION, INTENT(INOUT) :: X0 , X1
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE CONDIW
     &( AT, LT , TC1, TC2, TV1, TV2, TM1, TM2 ,
     &  NVHMA,NVCOU,NVWIN,PART , U_TEL, V_TEL , H_TEL )
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: PART,LT
      INTEGER, INTENT(INOUT)          :: NVHMA,NVCOU,NVWIN
      DOUBLE PRECISION, INTENT(INOUT) :: AT,TC1,TC2,TV1,TV2,TM1,TM2
      TYPE(BIEF_OBJ), INTENT(IN)      :: U_TEL,V_TEL,H_TEL
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE CONW4D
     &(CX,CY,CT,CF,U,V,XK,CG,COSF,TGF,DEPTH,DZHDT,DZX,DZY,DUX,DUY,
     & DVX,DVY,FREQ,COSTET,SINTET,NPOIN2,NPLAN,JF,NF,PROINF,SPHE,
     & TRA01)
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NF,NPLAN,NPOIN2,JF
      DOUBLE PRECISION, INTENT(INOUT) :: CX(NPOIN2,NPLAN,JF)
      DOUBLE PRECISION, INTENT(INOUT) :: CY(NPOIN2,NPLAN,JF)
      DOUBLE PRECISION, INTENT(INOUT) :: CT(NPOIN2,NPLAN,JF)
      DOUBLE PRECISION, INTENT(INOUT) :: CF(NPOIN2,NPLAN,JF)
      DOUBLE PRECISION, INTENT(IN)    :: FREQ(NF)
      DOUBLE PRECISION, INTENT(IN)    :: CG(NPOIN2,NF),XK(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(IN)    :: DEPTH(NPOIN2),DZHDT(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: U(NPOIN2),V(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: DZX(NPOIN2),DZY(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: DUX(NPOIN2),DUY(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: DVX(NPOIN2),DVY(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: COSTET(NPLAN),SINTET(NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: COSF(NPOIN2),TGF(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA01(NPOIN2)
      LOGICAL, INTENT(IN)             :: PROINF,SPHE
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE CONWAC
     &( CX    , CY    , CT    , XK    , CG    , COSF  , TGF   , DEPTH ,
     &  DZX   , DZY   , FREQ  , COSTET, SINTET, NPOIN2, NPLAN , JF    ,
     &  NF    , PROINF, SPHE  , PROMIN, TRA01 )
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NF,NPLAN,NPOIN2,JF
      DOUBLE PRECISION, INTENT(IN)    :: PROMIN
      DOUBLE PRECISION, INTENT(IN)    :: DEPTH(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: DZX(NPOIN2),DZY(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: COSF(NPOIN2),TGF(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: FREQ(NF)
      DOUBLE PRECISION, INTENT(IN)    :: COSTET(NPLAN),SINTET(NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA01(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: CG(NPOIN2,NF),XK(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: CX(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: CY(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: CT(NPOIN2,NPLAN)
      LOGICAL, INTENT(IN)             :: PROINF,SPHE
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE CORMAR
     &( AT    , LT    , TC1   , TC2   , TM1   , TM2   ,
     &  NVHMA , NVCOU , PART, U_TEL, V_TEL , H_TEL )
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: LT
      INTEGER, INTENT(INOUT)          :: NVCOU,NVHMA
      DOUBLE PRECISION, INTENT(IN)    :: AT
      DOUBLE PRECISION, INTENT(INOUT) :: TC1,TC2,TM1,TM2
      INTEGER,           INTENT(IN) :: PART
      TYPE(BIEF_OBJ),    INTENT(IN) :: U_TEL,V_TEL,H_TEL
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        FUNCTION COUPLE
     &( XK1   , YK1   , XK2   , YK2   , XK3   , YK3   , XK4   , YK4   ,
     &  GRAVIT, PI    )
      IMPLICIT NONE
      DOUBLE PRECISION , INTENT(IN)    :: XK1   , YK1   , XK2   , YK2
      DOUBLE PRECISION , INTENT(IN)    :: XK3   , YK3
      DOUBLE PRECISION , INTENT(IN)    :: XK4   , YK4   , GRAVIT, PI
      DOUBLE PRECISION COUPLE
        END FUNCTION
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE COUUTI
     &(X,Y,NPOIN,NCOU,FMTCOU,NBOR,NPTFR,AT,DDC,TC1,TC2,UC1,VC1,UC2,VC2)
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NCOU,NPOIN,NPTFR
      INTEGER, INTENT(IN)             :: NBOR(NPTFR,2)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN),Y(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: UC1(NPOIN),VC1(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: UC2(NPOIN),VC2(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: AT,DDC,TC1,TC2
      CHARACTER(LEN=8), INTENT(IN)    :: FMTCOU
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE CQUEUE
     &( NF    , RAISF , TAILF , JFRE  , JBIS  , COEF1 )
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NF    , JFRE
      DOUBLE PRECISION, INTENT(IN)    :: RAISF , TAILF
      DOUBLE PRECISION, INTENT(INOUT) :: COEF1
      INTEGER, INTENT(INOUT)          :: JBIS
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        FUNCTION DELFRA( SS    , DEUPI )
      IMPLICIT NONE
      DOUBLE PRECISION DELFRA, SS    , DEUPI
        END FUNCTION
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE DIFFRAC
     &( CX    , CY    , CT    , XK    , CG    , 
     &  FREQ  , COSTET, SINTET, NPOIN2, NPLAN , IFF   , NF    , PROINF,
     &  SPHE  , A     , DFREQ , F     , CCG   , DIV   , DELTA , DDX   ,
     &  DDY   , EPS   , NBOR  , NPTFR , XKONPT, RX    , RY    ,
     &  RXX   , RYY   , NEIGB , NB_CLOSE, DIFFRA, MAXNSP, FLTDIF,OPTDER)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NF,NPLAN,NPOIN2,NPTFR,IFF,MAXNSP,OPTDER
      INTEGER, INTENT(IN) :: NB_CLOSE(NPOIN2),NEIGB(NPOIN2,MAXNSP)
      INTEGER, INTENT(IN)             :: DIFFRA,NBOR(NPTFR)
      DOUBLE PRECISION, INTENT(INOUT) :: CX(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: CY(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: FREQ(NF)
      DOUBLE PRECISION, INTENT(INOUT) :: CT(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: CG(NPOIN2,NF),XK(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(IN)    :: COSTET(NPLAN),SINTET(NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: A(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: DFREQ(NF)
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: CCG(NPOIN2), DIV(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: DELTA(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: DDX(NPOIN2), DDY(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: EPS
      DOUBLE PRECISION, INTENT(IN)    :: RX(MAXNSP,NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: RY(MAXNSP,NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: RXX(MAXNSP,NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: RYY(MAXNSP,NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: XKONPT(NPOIN2)
      LOGICAL, INTENT(IN)             :: PROINF,SPHE,FLTDIF
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE DUMP2D(  XF1 , NP1 )
      IMPLICIT NONE
      INTEGER, INTENT(IN)          :: NP1
      DOUBLE PRECISION, INTENT(IN) :: XF1(NP1)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE ECRETE
     &( F     , DEPTH , NPOIN2, NPLAN , NF    , PROMIN)
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NPOIN2 , NPLAN, NF
      DOUBLE PRECISION, INTENT(IN)    :: DEPTH(NPOIN2),PROMIN
      DOUBLE PRECISION, INTENT(INOUT) :: F(NPOIN2,NPLAN,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE ECRSPE
     &( F     , TETA  , NPLAN , FREQ  , NF    , NK    ,
     &  NPOIN2, AT, LT, AUXIL , NOLEO , NLEO  , NSCO  ,
     &  FMTSCO, NAMSCO, DEBRES, TITCAS, DATE  , TIME  , KNOLG , MESH ,
     &  NSPE  , TISPEF)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NPOIN2,NLEO,NSCO,NF,NK,NPLAN
      INTEGER, INTENT(IN)             :: KNOLG(NPOIN2),NOLEO(NLEO)
      INTEGER, INTENT(IN)             :: DATE(3),TIME(3),LT
      DOUBLE PRECISION, INTENT(IN)    :: AT
      DOUBLE PRECISION, INTENT(INOUT) :: AUXIL(NPLAN,NK)
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)    :: TETA(NPLAN),FREQ(NF)
      LOGICAL, INTENT(IN)             :: DEBRES
      CHARACTER(LEN=72), INTENT(IN)   :: TITCAS
      CHARACTER(LEN=8) , INTENT(IN)   :: FMTSCO
      TYPE(BIEF_MESH), INTENT(INOUT)  :: MESH
      CHARACTER(LEN=144), INTENT(IN)  :: TISPEF, NAMSCO
      INTEGER, INTENT(IN)             :: NSPE
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE F1F1F1
     &( F1SF  , NF1   , IQ_OM1)
      IMPLICIT NONE
      INTEGER,          INTENT(IN)    :: IQ_OM1
      INTEGER,          INTENT(INOUT) :: NF1
      DOUBLE PRECISION, INTENT(INOUT) :: F1SF(*)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FILT_SA
        IMPLICIT NONE
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        FUNCTION FONCRO
     &( X     , B     , N     , A     , XM    )
      IMPLICIT NONE
      INTEGER,          INTENT(IN)    :: N
      DOUBLE PRECISION, INTENT(IN)    :: X      , B     , A     , XM
      DOUBLE PRECISION FONCRO
        END FUNCTION
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FPREAD
     &( FREAD , F     , FREQ  , DFREQ , NF    , NPLAN , NPOIN2, EXPO  ,
     &  TAILF )
      IMPLICIT NONE
      INTEGER,          INTENT(IN) :: NF    , NPLAN , NPOIN2
      DOUBLE PRECISION, INTENT(IN) :: EXPO  , TAILF, F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN) :: FREQ(NF), DFREQ(NF)
      DOUBLE PRECISION, INTENT(INOUT) :: FREAD(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FREM01
     &( FM01  , F     , FREQ  , DFREQ , TAILF , NF    , NPLAN , NPOIN2)
      IMPLICIT NONE
      INTEGER,          INTENT(IN) ::  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION, INTENT(IN) :: TAILF
      DOUBLE PRECISION, INTENT(IN) :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN) :: FREQ(NF), DFREQ(NF)
      DOUBLE PRECISION, INTENT(INOUT) :: FM01(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FREM02
     &( FM02  , F     , FREQ  , DFREQ , TAILF , NF    , NPLAN , NPOIN2)
      IMPLICIT NONE
      INTEGER,          INTENT(IN) ::  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION, INTENT(IN) :: TAILF
      DOUBLE PRECISION, INTENT(IN) :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN) :: FREQ(NF), DFREQ(NF)
      DOUBLE PRECISION, INTENT(INOUT) :: FM02(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FREMOY
     &( FMOY  , F     , FREQ  , DFREQ , TAILF , NF    , NPLAN , NPOIN2)
      IMPLICIT NONE
      INTEGER,         INTENT(IN) ::  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION,INTENT(IN) :: TAILF
      DOUBLE PRECISION,INTENT(IN) :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION,INTENT(IN) :: FREQ(NF), DFREQ(NF)
      DOUBLE PRECISION,INTENT(INOUT) :: FMOY(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FREPIC
     &( FPIC  , F     , FREQ  , NF    , NPLAN , NPOIN2)
      IMPLICIT NONE
      INTEGER,INTENT(IN)             :: NF    , NPLAN , NPOIN2
      DOUBLE PRECISION,INTENT(IN)    :: F(NPOIN2,NPLAN,NF), FREQ(NF)
      DOUBLE PRECISION,INTENT(INOUT) :: FPIC(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
!V6P2 New subroutine
      INTERFACE
        SUBROUTINE FRMSET
     &( X     , Y     , NEIGB , NB_CLOSE, NPOIN2,MAXNSP, NRD, NELEM2,
     &  IKLE  , RK    , RX    , RY    , RXX   , RYY )
      IMPLICIT NONE
      INTEGER,INTENT(IN)            :: NPOIN2, MAXNSP, NRD, NELEM2
      INTEGER,INTENT(INOUT)         :: NB_CLOSE(NPOIN2)
      INTEGER,INTENT(INOUT)         :: NEIGB(NPOIN2,MAXNSP)
      INTEGER,INTENT(IN)            :: IKLE(NELEM2,3)
      DOUBLE PRECISION,INTENT(IN)   :: X(NPOIN2), Y(NPOIN2)
      DOUBLE PRECISION,INTENT(INOUT):: RK(MAXNSP,NPOIN2)
      DOUBLE PRECISION,INTENT(INOUT):: RX(MAXNSP,NPOIN2)
      DOUBLE PRECISION,INTENT(INOUT):: RY(MAXNSP,NPOIN2)
      DOUBLE PRECISION,INTENT(INOUT):: RXX(MAXNSP,NPOIN2)
      DOUBLE PRECISION,INTENT(INOUT):: RYY(MAXNSP,NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FSPRD1
     &( FRA   , DIREC , NPLAN , SPRED1, TETA1 , SPRED2, TETA2 , XLAMDA)
      IMPLICIT NONE
      INTEGER,INTENT(IN)             :: NPLAN
      DOUBLE PRECISION,INTENT(IN)    :: SPRED1, TETA1 , SPRED2, TETA2
      DOUBLE PRECISION,INTENT(IN)    :: XLAMDA, DIREC(NPLAN)
      DOUBLE PRECISION,INTENT(INOUT) :: FRA(NPLAN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FSPRD2
     &( FRA   , DIREC , NPLAN , SPRED1, TETA1 , SPRED2, TETA2 , XLAMDA)
      IMPLICIT NONE
      INTEGER,INTENT(IN)             :: NPLAN
      DOUBLE PRECISION,INTENT(IN)    :: SPRED1, TETA1 , SPRED2, TETA2
      DOUBLE PRECISION,INTENT(IN)    :: XLAMDA, DIREC(NPLAN)
      DOUBLE PRECISION,INTENT(INOUT) :: FRA(NPLAN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FSPRD3
     &( FRA   , DIREC , NPLAN , SPRED1, TETA1 , SPRED2, TETA2 , XLAMDA)
      IMPLICIT NONE
      INTEGER,INTENT(IN)             :: NPLAN
      DOUBLE PRECISION,INTENT(IN)    :: SPRED1, TETA1 , SPRED2, TETA2
      DOUBLE PRECISION,INTENT(IN)    :: XLAMDA, DIREC(NPLAN)
      DOUBLE PRECISION,INTENT(INOUT) :: FRA(NPLAN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        FUNCTION GAMMLN
     &( XX    , DEUPI )
      IMPLICIT NONE
      DOUBLE PRECISION GAMMLN
      DOUBLE PRECISION,INTENT(IN)    :: XX    , DEUPI
        END FUNCTION
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE GAULEG
     &( W_LEG , X_LEG , NPOIN )
      IMPLICIT NONE
      INTEGER ,INTENT(IN)             :: NPOIN
      DOUBLE PRECISION ,INTENT(INOUT) :: W_LEG(NPOIN) , X_LEG(NPOIN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE IFABTOM(IFABOR,NELEM2,NETAGE)
      IMPLICIT NONE
      INTEGER, INTENT(IN)          :: NELEM2,NETAGE
      INTEGER, INTENT(INOUT)       :: IFABOR(NELEM2,5,NETAGE)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE IMPR(LISPRD,LT,AT,ISITS,ICOD)
      IMPLICIT NONE
      INTEGER,INTENT(IN)           :: LT,ICOD,LISPRD,ISITS
      DOUBLE PRECISION,INTENT(IN)  :: AT
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE INIPHY
     &( XK    , CG    , B     , DEPTH , FREQ  , COSPHI, NPOIN2, NF    ,
     &  PROINF, SPHE  )
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NF    , NPOIN2
      DOUBLE PRECISION, INTENT(IN)    :: DEPTH(NPOIN2), COSPHI(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: FREQ(NF)
      DOUBLE PRECISION, INTENT(INOUT) :: B(NPOIN2,NF)  , XK(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: CG(NPOIN2,NF)
      LOGICAL, INTENT(IN)    ::          PROINF, SPHE
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE INITAB(IBOR1,IFABOR1,NELEM2_DIM,PART)
      IMPLICIT NONE
      INTEGER, INTENT(IN)    :: PART,NELEM2_DIM
      INTEGER, INTENT(IN)    :: IFABOR1(NELEM2_DIM,3)
      INTEGER, INTENT(INOUT) :: IBOR1(NELEM2_DIM,7)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE INTANG
     &( LAVANT, LAPRES, IPLAN , NPLAN , DELTAD)
      IMPLICIT NONE
      INTEGER, INTENT(IN)          :: NPLAN , IPLAN
      DOUBLE PRECISION, INTENT(IN) :: DELTAD
      INTEGER, INTENT(INOUT)       :: LAVANT, LAPRES
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE INVERT( RN    , N     , NP    )
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: N, NP
      DOUBLE PRECISION, INTENT(INOUT) :: RN(NP,NP)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        DOUBLE PRECISION FUNCTION KERBOU
     &(XK1,XK2,FREQ1,FREQ2,DEPTH,TETA1,TETA2)
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN) :: XK1,XK2,FREQ1,FREQ2,TETA1,TETA2
      DOUBLE PRECISION, INTENT(IN) :: DEPTH
        END FUNCTION
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE KMOYE2
     &( XKMOY , XK    , F     , FREQ  , DFREQ , TAILF , NF    , NPLAN ,
     &  NPOIN2, AUX1  , AUX2  , AUX3  )
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NF,NPLAN,NPOIN2
      DOUBLE PRECISION, INTENT(IN)    :: TAILF
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)    :: XK(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(IN)    :: FREQ(NF),DFREQ(NF)
      DOUBLE PRECISION, INTENT(INOUT) :: AUX1(NPOIN2),AUX2(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: AUX3(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: XKMOY(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE KMOYEN
     &( XKMOY , XK    , F     , FREQ  , DFREQ , TAILF , NF    , NPLAN ,
     &  NPOIN2, AUX1  , AUX2  , AUX3  )
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NF,NPLAN,NPOIN2
      DOUBLE PRECISION, INTENT(IN)    :: TAILF
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)    :: XK(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(IN)    :: FREQ(NF),DFREQ(NF)
      DOUBLE PRECISION, INTENT(INOUT) :: AUX1(NPOIN2),AUX2(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: AUX3(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: XKMOY(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE LECDOI
     &(F1,NAME1FR,NAME1GB,MODE1,
     & F2,NAME2FR,NAME2GB,MODE2,
     & F3,NAME3FR,NAME3GB,MODE3,
     & X,Y,NPOIN2,NDON,FMTDON,NBOR,NPTFR,
     & AT,DDC,TV1,TV2,F11,F12,F21,F22,F31,F32,INDIC,CHDON,NVAR,
     & TEXTE,TROUVE,UNITIME,PHASTIME)
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NDON,NPOIN2,NPTFR,INDIC
      INTEGER, INTENT(IN)             :: MODE1,MODE2,MODE3
      INTEGER, INTENT(INOUT)          :: NVAR
      INTEGER, INTENT(IN)             :: NBOR(NPTFR,2)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN2),Y(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: F1(NPOIN2),F2(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: F3(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: F11(NPOIN2),F12(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: F21(NPOIN2),F22(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: F31(NPOIN2),F32(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: AT,DDC,UNITIME,PHASTIME
      DOUBLE PRECISION, INTENT(INOUT) :: TV1,TV2
      CHARACTER(LEN=8), INTENT(IN)    :: FMTDON
      CHARACTER(LEN=7), INTENT(IN)    :: CHDON
      CHARACTER(LEN=32),INTENT(IN)    :: NAME1FR,NAME2FR,NAME3FR
      CHARACTER(LEN=32),INTENT(IN)    :: NAME1GB,NAME2GB,NAME3GB
      CHARACTER(LEN=32),INTENT(INOUT) :: TEXTE(30)
      LOGICAL, INTENT(INOUT)          :: TROUVE(3)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE LECDON
     &(F1,NAME1FR,NAME1GB,MODE1,
     & F2,NAME2FR,NAME2GB,MODE2,
     & F3,NAME3FR,NAME3GB,MODE3,
     & X,Y,NPOIN2,NDON,FFORMAT,NBOR,NPTFR,NPTT,INDIC,CHDON,TEXTE,TROUVE)
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NDON,NPOIN2,NPTFR,INDIC,NPTT
      INTEGER, INTENT(IN)             :: MODE1,MODE2,MODE3
      INTEGER, INTENT(IN)             :: NBOR(NPTFR,2)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN2),Y(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: F1(NPOIN2),F2(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: F3(NPOIN2)
      CHARACTER(LEN=8), INTENT(IN)    :: FFORMAT
      CHARACTER(LEN=7), INTENT(IN)    :: CHDON
      CHARACTER(LEN=32),INTENT(IN)    :: NAME1FR,NAME2FR,NAME3FR
      CHARACTER(LEN=32),INTENT(IN)    :: NAME1GB,NAME2GB,NAME3GB
      CHARACTER(LEN=32),INTENT(INOUT) :: TEXTE(30)
      LOGICAL, INTENT(INOUT)          :: TROUVE(3)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE LECDON_TOMAWAC(FILE_DESC,PATH,NCAR,CODE)
        USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      CHARACTER(LEN=24), INTENT(IN)     :: CODE
      CHARACTER(LEN=144), INTENT(INOUT) :: FILE_DESC(4,MAXKEYWORD)
      INTEGER, INTENT(IN)               :: NCAR
      CHARACTER(LEN=250), INTENT(IN)    :: PATH
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE LECSUI
     &(F,NPLAN,NF,NPOIN2,AT,UC,VC,UC1,VC1,UC2,VC2,
     & UV,VV,UV1,VV1,UV2,VV2,VENT,TV1,TV2,COURAN,NPRE,FMTPRE,DEPTH,
     & TC1,TC2,ZM1,ZM2,DZHDT,TM1,TM2,MAREE,TRA01)
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NPRE,NF,NPLAN,NPOIN2
      DOUBLE PRECISION, INTENT(INOUT) :: F(NPOIN2,NPLAN,NF),AT
      DOUBLE PRECISION, INTENT(INOUT) :: TV1,TV2,TC1,TC2,TM1,TM2
      DOUBLE PRECISION, INTENT(INOUT) :: UC(NPOIN2),VC(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: UV(NPOIN2),VV(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: UV1(NPOIN2),VV1(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: UV2(NPOIN2),VV2(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: UC1(NPOIN2),VC1(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: UC2(NPOIN2),VC2(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: DEPTH(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: ZM1(NPOIN2),ZM2(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: DZHDT(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA01(NPOIN2*NPLAN)
      LOGICAL, INTENT(IN)             :: COURAN,VENT,MAREE
      CHARACTER(LEN=8), INTENT(IN)    :: FMTPRE
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE LIMITE( F , FREQ  , NPOIN2, NPLAN , NF    )
        IMPLICIT NONE
        INTEGER, INTENT(IN)             :: NF,NPLAN,NPOIN2
        DOUBLE PRECISION, INTENT(IN)    :: FREQ(NF)
        DOUBLE PRECISION, INTENT(INOUT) :: F(NPOIN2,NPLAN,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE LIMWAC
     &(F     , FBOR  , LIFBOR, NPTFR , NPLAN , NF    ,  TETA , FREQ  ,
     & NPOIN2, NBOR  , AT    , LT    , DDC   , LIMSPE, FPMAXL, FETCHL,
     & SIGMAL, SIGMBL, GAMMAL, FPICL , HM0L  , APHILL, TETA1L, SPRE1L,
     & TETA2L, SPRE2L, XLAMDL, X ,Y  , KENT  , KSORT , NFO1  , NBI1  ,
     & FMTBI1, UV    , VV    , SPEULI, VENT  , VENSTA, GRAVIT,
     & PRIVE , NPRIV , SPEC  , FRA   , DEPTH , FRABL ,BOUNDARY_COLOUR,
     & IMP_FILE)
      USE BIEF_DEF, ONLY : BIEF_FILE
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NPTFR,NPLAN,NF,NPOIN2,LT,NPRIV
      INTEGER, INTENT(IN)             :: LIMSPE,KENT,KSORT,FRABL
      INTEGER, INTENT(IN)             :: NFO1,NBI1
      INTEGER, INTENT(IN)             :: LIFBOR(NPTFR),NBOR(NPTFR)
      INTEGER, INTENT(IN) :: BOUNDARY_COLOUR(NPTFR)
      DOUBLE PRECISION, INTENT(IN):: TETA(NPLAN),FREQ(NF)
      DOUBLE PRECISION, INTENT(IN):: X(NPOIN2),Y(NPOIN2)
      DOUBLE PRECISION, INTENT(IN):: UV(NPOIN2),VV(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT):: SPEC(NF)
      DOUBLE PRECISION, INTENT(IN):: PRIVE(NPOIN2,NPRIV),DEPTH(NPOIN2)
      DOUBLE PRECISION, INTENT(IN):: AT,DDC,FPMAXL,FETCHL,SIGMAL, SIGMBL
      DOUBLE PRECISION, INTENT(IN):: GAMMAL,FPICL
      DOUBLE PRECISION, INTENT(IN):: HM0L  , APHILL,TETA1L,SPRE1L,TETA2L
      DOUBLE PRECISION, INTENT(IN):: SPRE2L,XLAMDL
      DOUBLE PRECISION, INTENT(IN):: GRAVIT
      LOGICAL, INTENT(IN):: SPEULI, VENT, VENSTA
      CHARACTER(LEN=8), INTENT(IN):: FMTBI1
      TYPE(BIEF_FILE), INTENT(IN)    :: IMP_FILE
      DOUBLE PRECISION, INTENT(INOUT):: F(NPOIN2,NPLAN,NF), FRA(NPLAN)
      DOUBLE PRECISION, INTENT(INOUT):: FBOR(NPTFR,NPLAN,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE MARUTI
     &(X,Y,NPOIN,NMAR,FMTMAR,NBOR,NPTFR,AT,DDC,TV1,TV2,Z1,Z2)
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NMAR,NPOIN,NPTFR
      INTEGER, INTENT(IN)             :: NBOR(NPTFR,2)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN),Y(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: Z1(NPOIN),Z2(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: AT,DDC,TV1,TV2
      CHARACTER(LEN=8), INTENT(IN)    :: FMTMAR
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE NOMVAR_TOMAWAC
     &(TEXTE,TEXTPR,MNEMO,MAXVAR)
      IMPLICIT NONE
      INTEGER, INTENT(IN)         ::      MAXVAR
      CHARACTER(LEN=32), INTENT(INOUT) :: TEXTE(MAXVAR),TEXTPR(MAXVAR)
      CHARACTER(LEN=8) , INTENT(INOUT) :: MNEMO(MAXVAR)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE NOUDON
     &(F1,NAME1FR,NAME1GB,MODE1,
     & F2,NAME2FR,NAME2GB,MODE2,
     & F3,NAME3FR,NAME3GB,MODE3,X,Y,NPOIN,NDON,FFORMAT,NBOR,NPTFR,
     & AT,DDC,TV1,TV2,F11,F12,F21,F22,F31,F32,INDIC,CHDON,NVAR,TEXTE,
     & TROUVE,UNITIME,PHASTIME)
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NDON,NPOIN,NPTFR,INDIC
      INTEGER, INTENT(INOUT)          :: NVAR
      INTEGER, INTENT(IN)             :: MODE1,MODE2,MODE3
      INTEGER, INTENT(IN)             :: NBOR(NPTFR,2)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN),Y(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: F1(NPOIN),F2(NPOIN),F3(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: F11(NPOIN),F21(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: F12(NPOIN),F22(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: F31(NPOIN),F32(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: AT,DDC,UNITIME,PHASTIME
      DOUBLE PRECISION, INTENT(INOUT) :: TV1,TV2
      CHARACTER(LEN=8), INTENT(IN)    :: FFORMAT
      CHARACTER(LEN=7), INTENT(IN)    :: CHDON
      CHARACTER(LEN=32),INTENT(IN)    :: NAME1FR,NAME2FR,NAME3FR
      CHARACTER(LEN=32),INTENT(IN)    :: NAME1GB,NAME2GB,NAME3GB
      CHARACTER(LEN=32),INTENT(IN)    :: TEXTE(30)
      LOGICAL, INTENT(INOUT)          :: TROUVE(3)
!
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PREDIF
     &(CX    , CY    , CT    , DT    , TETA  , COSTET,
     & SINTET, FREQ  , IKLE2 , IFABOR, TRA01 , SHP   ,
     & SHZ   , ELT   , ETA   , DEPTH , DZX   , DZY   , XK    ,
     &        CG    , ITR01 , NPOIN3, NPOIN2, NELEM2, NPLAN , NF    ,
     & COURAN, SPHE  , PROINF, A     , DFREQ , F     , CCG   , DIV   ,
     & DELTA , DDX   , DDY   , EPS   , NBOR  , NPTFR , XKONPT,
     & RX    , RY    , RXX   , RYY   , NEIGB , NB_CLOSE,DIFFRA,MAXNSP,
     & FLTDIF, MESH3D, MESH  , IELM3 , TB    , ISUB  , SIKLE2)
      USE BIEF_DEF
      IMPLICIT NONE

      INTEGER,INTENT(IN)    :: NPOIN3,NPOIN2,NELEM2,NPLAN,NF,NPTFR
      INTEGER,INTENT(IN)    :: NBOR(NPTFR),DIFFRA ,MAXNSP
      INTEGER,INTENT(IN)    :: IKLE2(NELEM2,3)
      INTEGER,INTENT(IN)    :: NB_CLOSE(NPOIN2),NEIGB(NPOIN2,MAXNSP)
      INTEGER,INTENT(INOUT) :: ISUB(NPOIN3,NF),IFABOR(NELEM2,7),IELM3
      INTEGER,INTENT(INOUT) :: ELT(NPOIN3,NF), ETA(NPOIN3,NF)
      INTEGER,INTENT(INOUT) :: ITR01(NPOIN3,3)
      DOUBLE PRECISION,INTENT(IN) :: RX(MAXNSP,NPOIN2),RY(MAXNSP,NPOIN2)
      DOUBLE PRECISION,INTENT(IN) :: RXX(MAXNSP,NPOIN2)
      DOUBLE PRECISION,INTENT(IN) :: RYY(MAXNSP,NPOIN2)
      DOUBLE PRECISION,INTENT(IN) :: XK(NPOIN2,NF),CG(NPOIN2,NF)
      DOUBLE PRECISION,INTENT(IN) :: FREQ(NF)
      DOUBLE PRECISION,INTENT(IN) :: SINTET(NPLAN),COSTET(NPLAN)
      DOUBLE PRECISION,INTENT(IN) :: DT,EPS
      DOUBLE PRECISION,INTENT(INOUT) :: TRA01(NPOIN3,8),A(NPOIN2)
      DOUBLE PRECISION,INTENT(INOUT) :: CCG(NPOIN2),DIV(NPOIN2)
      DOUBLE PRECISION,INTENT(INOUT) ::DELTA(NPOIN2),XKONPT(NPOIN2)
      DOUBLE PRECISION,INTENT(IN) :: DEPTH(NPOIN2)
      DOUBLE PRECISION,INTENT(IN) :: DZX(NPOIN2),DZY(NPOIN2)
      DOUBLE PRECISION,INTENT(IN) :: DDX(NPOIN2),DDY(NPOIN2)
      DOUBLE PRECISION,INTENT(IN) :: DFREQ(NF)
      DOUBLE PRECISION,INTENT(IN) :: F(NPOIN2,NPLAN,NF)
      LOGICAL,INTENT(IN) :: COURAN,SPHE,PROINF,FLTDIF
      TYPE(BIEF_OBJ), INTENT(IN)    :: TETA,SIKLE2
      TYPE(BIEF_OBJ), INTENT(INOUT) :: SHP,SHZ,CX,CY,CT,TB
      TYPE(BIEF_MESH),INTENT(INOUT) :: MESH3D,MESH
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PRENL1
     &( IANGNL, COEFNL, NPLAN , NF    , RAISF , XLAMD )
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NPLAN , NF
      INTEGER, INTENT(INOUT)          :: IANGNL(NPLAN,8)
      DOUBLE PRECISION, INTENT(IN)    :: RAISF , XLAMD
      DOUBLE PRECISION, INTENT(INOUT) :: COEFNL(16)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
!V6P1 New subroutine
      INTERFACE
        SUBROUTINE PRENL2
     &( IANGNL, COEFNL, NPLAN , NF    , RAISF , XLAMD , XMU   )
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NPLAN , NF
      INTEGER, INTENT(INOUT)          :: IANGNL(NPLAN,16)
      DOUBLE PRECISION, INTENT(IN)    :: RAISF , XLAMD , XMU
      DOUBLE PRECISION, INTENT(INOUT) :: COEFNL(32)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
!V6P1 New subroutine
      INTERFACE
        SUBROUTINE PRENL3
     &( NF    , NT    , RAISF , TAILF , FREQ  , TB_SCA, LBUF  , DIMBUF,
     &  F_POIN, F_COEF, T_POIN, F_PROJ, IQ_OM1, NQ_TE1, NQ_OM2, NF1   ,
     &  NT1   , K_IF1 , K_IF2 , K_IF3 , TB_V14, TB_V24, TB_V34, K_1P  ,
     &  K_1M  , K_1P2P, K_1P3M, K_1P2M, K_1P3P, K_1M2P, K_1M3M, K_1M2M,
     &  K_1M3P, TB_TPM, TB_TMP, TB_FAC, SEUIL1, SEUIL2, ELIM  , NCONF ,
     &  NCONFM, IDCONF)
      IMPLICIT NONE
      INTEGER, INTENT(IN)   ::NF    , NT
      INTEGER, INTENT(IN)   ::LBUF  , DIMBUF
      INTEGER, INTENT(IN)   ::IQ_OM1 , NQ_TE1, NQ_OM2
! TF : INOUT FOR DIMENSION IS NOT LOGICAL BUT NF1 CHANGES IN F1F1F1
      INTEGER, INTENT(INOUT):: NF1
      INTEGER, INTENT(IN)   :: NT1
      INTEGER, INTENT(IN)   ::NCONFM
      INTEGER, INTENT(INOUT)::NCONF , IDCONF(NCONFM,3)
      INTEGER, INTENT(INOUT)::F_POIN(DIMBUF), T_POIN(DIMBUF)
      INTEGER, INTENT(INOUT)::K_IF1(NF1), K_1P(NT1,NF1), K_1M(NT1,NF1)
      INTEGER, INTENT(INOUT)::K_IF2 (NQ_OM2,NT1,NF1)
      INTEGER, INTENT(INOUT)::K_IF3 (NQ_OM2,NT1,NF1)
      INTEGER, INTENT(INOUT)::K_1P2P(NQ_OM2,NT1,NF1)
      INTEGER, INTENT(INOUT)::K_1P3M(NQ_OM2,NT1,NF1)
      INTEGER, INTENT(INOUT)::K_1P2M(NQ_OM2,NT1,NF1)
      INTEGER, INTENT(INOUT)::K_1P3P(NQ_OM2,NT1,NF1)
      INTEGER, INTENT(INOUT)::K_1M2P(NQ_OM2,NT1,NF1)
      INTEGER, INTENT(INOUT)::K_1M3M(NQ_OM2,NT1,NF1)
      INTEGER, INTENT(INOUT)::K_1M2M(NQ_OM2,NT1,NF1)
      INTEGER, INTENT(INOUT)::K_1M3P(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION, INTENT(IN)   :: RAISF , TAILF , FREQ(NF)
      DOUBLE PRECISION, INTENT(IN)   :: SEUIL1, SEUIL2
      DOUBLE PRECISION, INTENT(INOUT):: F_COEF(DIMBUF), F_PROJ(DIMBUF)
      DOUBLE PRECISION, INTENT(INOUT):: TB_SCA(DIMBUF)
      DOUBLE PRECISION, INTENT(INOUT):: TB_V14(NF1)
      DOUBLE PRECISION, INTENT(INOUT):: TB_V24(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION, INTENT(INOUT):: TB_V34(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION, INTENT(INOUT):: TB_TPM(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION, INTENT(INOUT):: TB_TMP(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION, INTENT(INOUT):: TB_FAC(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION, INTENT(INOUT):: ELIM
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PREPRO
     &( CX    , CY    , CT    , CF    , DT    ,
     &  TETA  , COSTET, SINTET, FREQ  , IKLE2 , IFABOR, TRA01 ,
     &  SHP   , SHZ   , SHF   , ELT   , ETA   , FRE   ,
     &  DEPTH , DZHDT , DZX   , DZY   , U     , V     , DUX   , DUY   ,
     &  DVX   , DVY   , XK    , CG    , COSF  , TGF   , ITR01 , NPOIN3,
     &  NPOIN2, NELEM2, NPLAN , NF    , COURAN, SPHE  ,
     &  PROINF, PROMIN, MESH  , MESH3D,SIKLE2,TB,IELM3,
     &  ISUB)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)    :: NPOIN3,NPOIN2,NELEM2,NPLAN,NF
      INTEGER, INTENT(INOUT) :: IELM3
      DOUBLE PRECISION, INTENT(IN) :: DT,PROMIN
      DOUBLE PRECISION, INTENT(IN) :: DZHDT(NPOIN2)
      DOUBLE PRECISION, INTENT(IN) :: XK(NPOIN2,NF),CG(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(IN) :: SINTET(NPLAN),COSTET(NPLAN)
      DOUBLE PRECISION, INTENT(IN) :: COSF(NPOIN2),TGF(NPOIN2)
      DOUBLE PRECISION, INTENT(IN) :: DEPTH(NPOIN2)
      DOUBLE PRECISION, INTENT(IN) :: DZX(NPOIN2),DZY(NPOIN2)
      DOUBLE PRECISION, INTENT(IN) :: U(NPOIN2),DUX(NPOIN2),DUY(NPOIN2)
      DOUBLE PRECISION, INTENT(IN) :: V(NPOIN2),DVX(NPOIN2),DVY(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA01(NPOIN3,6)
      INTEGER, INTENT(INOUT) :: ELT(NPOIN3,NF),ETA(NPOIN3,NF)
      INTEGER, INTENT(INOUT) :: ISUB(NPOIN3,NF)
      INTEGER, INTENT(INOUT) :: FRE(NPOIN3,NF)
      INTEGER, INTENT(IN)    :: IKLE2(NELEM2,3)
      INTEGER, INTENT(INOUT) :: ITR01(NPOIN3,3),IFABOR(NELEM2,7)
      LOGICAL, INTENT(IN)    :: COURAN,SPHE,PROINF
      TYPE(BIEF_OBJ), INTENT(INOUT) :: SHP,SHZ,SHF,CX,CY,CT,CF,TB
      TYPE(BIEF_OBJ), INTENT(IN)    :: SIKLE2,TETA,FREQ
      TYPE(BIEF_MESH), INTENT(INOUT):: MESH,MESH3D
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PREQT2
     &( TETA  , NPLAN , BDISPB, BDSSPB, NBD , INDI )
      IMPLICIT NONE
      INTEGER, INTENT(IN)          :: NPLAN
      INTEGER, INTENT(INOUT)       :: INDI(NPLAN), NBD
      DOUBLE PRECISION, INTENT(IN) :: BDISPB , BDSSPB
      DOUBLE PRECISION, INTENT(IN) :: TETA(NPLAN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PROPA
     &(F,B,SHP,SHZ,SHF,ELT,ETA,FRE,IKLE_EXT,NPOIN3,NPOIN2,
     & NPLAN,NF,COURAN,TRA01,TRA02,ITR01,T3_01,T3_02,ISUB,MESH3D)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NPOIN3,NPOIN2,NPLAN,NF
      DOUBLE PRECISION, INTENT(INOUT) :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)    :: B(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA01(NPOIN3,8)
      INTEGER, INTENT(INOUT) :: ELT(NPOIN3,NF),ETA(NPOIN3,NF)
      INTEGER, INTENT(INOUT) :: FRE(NPOIN3,NF)
      INTEGER, INTENT(IN)    :: ISUB(NPOIN3,NF)
      INTEGER, INTENT(INOUT) :: ITR01(NPOIN3*3)
      LOGICAL, INTENT(IN)    :: COURAN
      TYPE(BIEF_OBJ), INTENT(INOUT)  :: SHP,SHZ,SHF,T3_01,T3_02,TRA02
      TYPE(BIEF_OBJ), INTENT(IN)     :: IKLE_EXT
      TYPE(BIEF_MESH), INTENT(INOUT) :: MESH3D
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        FUNCTION QBBJ78( B     , IQBBJ )
      IMPLICIT NONE
      DOUBLE PRECISION QBBJ78
      DOUBLE PRECISION, INTENT(IN) ::  B
      INTEGER, INTENT(IN)     ::  IQBBJ
        END FUNCTION
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QBREK1
     &( TSTOT , F     , FCAR  , VARIAN, DEPTH , ALFABJ, GAMBJ1,
     &  GAMBJ2, IQBBJ , IHMBJ , NF    , NPLAN , NPOIN2, BETA  )
      IMPLICIT NONE
      INTEGER, INTENT(IN)            :: IQBBJ, IHMBJ, NF, NPLAN, NPOIN2
      DOUBLE PRECISION, INTENT(IN)   :: ALFABJ, GAMBJ1, GAMBJ2
      DOUBLE PRECISION, INTENT(IN)   :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)   :: VARIAN(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)   :: DEPTH(NPOIN2),FCAR(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT):: BETA(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT):: TSTOT(NPOIN2,NPLAN,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QBREK2
     &( TSTOT , F     , FCAR  , VARIAN, DEPTH , BORETG, GAMATG,
     &  IWHTG , NF    , NPLAN , NPOIN2, BETA  )
      IMPLICIT NONE
      INTEGER, INTENT(IN)            :: NF, NPLAN, NPOIN2, IWHTG
      DOUBLE PRECISION, INTENT(IN)   :: BORETG, GAMATG
      DOUBLE PRECISION, INTENT(IN)   :: DEPTH(NPOIN2), FCAR(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)   :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)   :: VARIAN(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT):: BETA(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT):: TSTOT(NPOIN2,NPLAN,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QBREK3
     &( TSTOT , F     , FCAR  , VARIAN, DEPTH , ALFARO, GAMARO,
     &  GAM2RO, IEXPRO, IDISRO, NF    , NPLAN , NPOIN2, BETA  )
      IMPLICIT NONE
      INTEGER, INTENT(IN)   :: IEXPRO, IDISRO, NF    , NPLAN , NPOIN2
      DOUBLE PRECISION, INTENT(IN)   :: ALFARO, GAMARO, GAM2RO
      DOUBLE PRECISION, INTENT(IN)   :: DEPTH(NPOIN2), FCAR(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)   :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)   :: VARIAN(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT):: BETA(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT):: TSTOT(NPOIN2,NPLAN,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QBREK4
     &( TSTOT , F     , FCAR  , VARIAN, DEPTH , BETAIH, EM2SIH,
     &  GRAVIT, NF    , NPLAN , NPOIN2, BETA  )
      IMPLICIT NONE
      INTEGER, INTENT(IN)   ::          NF    , NPLAN , NPOIN2
      DOUBLE PRECISION, INTENT(IN)   :: BETAIH, EM2SIH, GRAVIT
      DOUBLE PRECISION, INTENT(IN)   :: DEPTH(NPOIN2),FCAR(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)   :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)   :: VARIAN(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT):: BETA(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT):: TSTOT(NPOIN2,NPLAN,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QDSCUR
     &( TSTOT , TSDER , F     , CF    , XK    , FREQ  , USOLD , USNEW ,
     &  DEPTH , PROINF, CDSCUR, CMOUT4, NF    , NPLAN , NPOIN2, CIMPLI,
     &  F_INT  , BETOTO, BETOTN)
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NF,NPLAN,NPOIN2
      DOUBLE PRECISION, INTENT(IN)    :: CMOUT4, CDSCUR
      DOUBLE PRECISION, INTENT(IN)    :: CIMPLI
      DOUBLE PRECISION, INTENT(IN)    :: USNEW(NPOIN2),USOLD(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: FREQ(NF),DEPTH(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: XK(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: F_INT(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: BETOTO(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: BETOTN(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: TSTOT(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)    :: CF(NPOIN2,NPLAN,NF)
      LOGICAL, INTENT(IN)             :: PROINF
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QFROT1
     &( TSTOT , TSDER , F     , XK    , DEPTH , CFROT1, GRAVIT, NF    ,
     &  NPLAN , NPOIN2, BETA  )
      IMPLICIT NONE
      INTEGER, INTENT(IN)    ::  NF , NPLAN , NPOIN2
      DOUBLE PRECISION, INTENT(IN)    :: CFROT1, GRAVIT
      DOUBLE PRECISION, INTENT(IN)    :: DEPTH(NPOIN2), XK(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: TSTOT(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: BETA(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        FUNCTION QGAUSS
     &( B     , N     , A     , XM    )
      IMPLICIT NONE
      INTEGER, INTENT(IN)    ::  N
      DOUBLE PRECISION QGAUSS
      DOUBLE PRECISION, INTENT(IN)    :: B , A , XM
        END FUNCTION
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QMOUT1
     &( TSTOT , TSDER , F     , XK    , ENRJ  , FREQ  , FMOY  , XKMOY ,
     &  PROINF, CMOUT1, CMOUT2, NF  , NPLAN , NPOIN2, TAUX1   , BETA  )
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NF,NPLAN,NPOIN2
      DOUBLE PRECISION, INTENT(IN)    :: CMOUT1,CMOUT2
      DOUBLE PRECISION, INTENT(IN)    :: XKMOY(NPOIN2),ENRJ(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: FREQ(NF),FMOY(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TAUX1(NPOIN2),BETA(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TSTOT(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)    :: XK(NPOIN2,NF)
      LOGICAL, INTENT(IN)             :: PROINF
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QMOUT2
     &( TSTOT , TSDER , F     , XK    , ENRJ  , FREQ  , FMOY  , XKMOY ,
     &  USOLD , USNEW , DEPTH , PROINF, CMOUT3, CMOUT4, CMOUT5, CMOUT6,
     &  NF    , NPLAN , NPOIN2, CIMPLI, TAUX1 ,F_INT  , BETOTO, BETOTN)
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NF,NPLAN,NPOIN2
      DOUBLE PRECISION, INTENT(IN)    :: CMOUT3,CMOUT4
      DOUBLE PRECISION, INTENT(IN)    :: CMOUT5,CMOUT6,CIMPLI
      DOUBLE PRECISION, INTENT(IN)    :: USNEW(NPOIN2),USOLD(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: FREQ(NF),DEPTH(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: FMOY(NPOIN2),XK(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(IN)    :: ENRJ(NPOIN2),XKMOY(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: F_INT(NPOIN2),TAUX1(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: BETOTO(NPOIN2),BETOTN(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TSTOT(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: F(NPOIN2,NPLAN,NF)
      LOGICAL, INTENT(IN)             :: PROINF
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QNLIN1
     &( TSTOT , TSDER , IANGNL, COEFNL, NF    , NPLAN , F1    , RAISF ,
     &  TAILF , PROINF, NPOIN2, F     , DEPTH , XKMOY , TAUX1 , TAUX2 ,
     &  TAUX3 , TAUX4 , TAUX5 , DFINI )
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NPOIN2,NPLAN,NF
      INTEGER, INTENT(IN)             :: IANGNL(NPLAN,8)
      DOUBLE PRECISION, INTENT(IN)    :: F1,RAISF,TAILF
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF),COEFNL(16)
      DOUBLE PRECISION, INTENT(IN)    :: XKMOY(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TSTOT(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: TAUX1(NPOIN2),TAUX2(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TAUX3(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TAUX4(NPOIN2),TAUX5(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: DFINI(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: DEPTH(NPOIN2)
      LOGICAL, INTENT(IN)             :: PROINF
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
!V6P1 New subroutine
      INTERFACE
        SUBROUTINE QNLIN2
     &( TSTOT , TSDER , IANGNL, COEFNL, NF    , NPLAN , F1    , RAISF ,
     &  TAILF , PROINF, NPOIN2, F     , DEPTH , XKMOY , TAUX1 , DFINI ,
     &  XCOEF )
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NPOIN2, NPLAN , NF
      INTEGER, INTENT(IN)             :: IANGNL(NPLAN,16)
      DOUBLE PRECISION, INTENT(IN)    :: F1  , RAISF , TAILF, XCOEF
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF), COEFNL(32)
      DOUBLE PRECISION, INTENT(IN)    :: DEPTH(NPOIN2), XKMOY(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TAUX1(NPOIN2), DFINI(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TSTOT(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: TSDER(NPOIN2,NPLAN,NF)
      LOGICAL, INTENT(IN)    ::   PROINF
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
!V6P1 New subroutine
      INTERFACE
        SUBROUTINE QNLIN3
     &( TSTOT , TSDER , F     , NB_NOD, NT    , NF    ,
     &  RAISF , SEUIL , FSEUIL, LBUF  , DIMBUF, F_POIN, F_COEF,
     &  F_PROJ, T_POIN, TB_SCA, NQ_OM2, NF1   , NT1   ,
     &  K_IF1 , K_IF2 , K_IF3 , TB_V14, TB_V24, TB_V34, K_1P  , K_1M  ,
     &  K_1P2P, K_1P3M, K_1P2M, K_1P3P, K_1M2P, K_1M3M, K_1M2M, K_1M3P,
     &  TB_TPM, TB_TMP, TB_FAC, NCONF , NCONFM, IDCONF)
      IMPLICIT NONE
      INTEGER, INTENT(IN)    :: NF    , NT    , NB_NOD
      INTEGER, INTENT(IN)    :: LBUF  , DIMBUF
      INTEGER, INTENT(IN)    :: F_POIN(DIMBUF), T_POIN(DIMBUF)
      INTEGER, INTENT(IN)    :: NQ_OM2, NF1   , NT1
      INTEGER, INTENT(IN)    :: K_IF1(NF1), K_1P(NT1,NF1), K_1M(NT1,NF1)
      INTEGER, INTENT(IN)    :: K_IF2 (NQ_OM2,NT1,NF1)
      INTEGER, INTENT(IN)    :: K_IF3 (NQ_OM2,NT1,NF1)
      INTEGER, INTENT(IN)    :: K_1P2P(NQ_OM2,NT1,NF1)
      INTEGER, INTENT(IN)    :: K_1P3M(NQ_OM2,NT1,NF1)
      INTEGER, INTENT(IN)    :: K_1P2M(NQ_OM2,NT1,NF1)
      INTEGER, INTENT(IN)    :: K_1P3P(NQ_OM2,NT1,NF1)
      INTEGER, INTENT(IN)    :: K_1M2P(NQ_OM2,NT1,NF1)
      INTEGER, INTENT(IN)    :: K_1M3M(NQ_OM2,NT1,NF1)
      INTEGER, INTENT(IN)    :: K_1M2M(NQ_OM2,NT1,NF1)
      INTEGER, INTENT(IN)    :: K_1M3P(NQ_OM2,NT1,NF1)
      INTEGER, INTENT(IN)    :: NCONF, NCONFM, IDCONF(NCONFM,3)
      DOUBLE PRECISION, INTENT(IN)    :: RAISF , SEUIL
      DOUBLE PRECISION, INTENT(IN)    :: F(NB_NOD,NT,NF)
      DOUBLE PRECISION, INTENT(IN)    :: F_COEF(DIMBUF), F_PROJ(DIMBUF)
      DOUBLE PRECISION, INTENT(IN)    :: TB_SCA(DIMBUF)
      DOUBLE PRECISION, INTENT(IN)    :: TB_V14(NF1)
      DOUBLE PRECISION, INTENT(IN)    :: TB_FAC(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION, INTENT(IN)    :: TB_V24(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION, INTENT(IN)    :: TB_V34(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION, INTENT(IN)    :: TB_TPM(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION, INTENT(IN)    :: TB_TMP(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION, INTENT(INOUT) :: FSEUIL(NB_NOD)
      DOUBLE PRECISION, INTENT(INOUT) :: TSTOT(NB_NOD,NT,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: TSDER(NB_NOD,NT,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QTRIA1
     &( F     , XK    , FREQ  , DEPTH , RAISF , ALFLTA, RFMLTA,
     &  NF    , NPLAN , NPOIN2, TSTOT , FTOT  , FMOY  )
      IMPLICIT NONE
      INTEGER, INTENT(IN)    ::  NF, NPLAN, NPOIN2
      DOUBLE PRECISION, INTENT(IN)    :: RAISF , ALFLTA, RFMLTA
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)    :: XK(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(IN)    :: FREQ(NF), DEPTH(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: FTOT(NPOIN2) , FMOY(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TSTOT(NPOIN2,NPLAN,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QTRIA2
     &( F     , XK    , FREQ  , DFREQ , DEPTH , TETA  , SINTET, COSTET ,
     &  KSPB  , BDISPB, BDSSPB, RAISF , NF    , NPLAN , NPOIN2 ,
     &  NBD   , INDI  , TSTOT )
      IMPLICIT NONE
      INTEGER, INTENT(IN)    ::  NF, NPLAN, NPOIN2, NBD
      INTEGER, INTENT(IN)    ::           INDI(NBD)
      DOUBLE PRECISION, INTENT(IN)    :: BDISPB, BDSSPB, KSPB, RAISF
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)    :: XK(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(IN)    :: DFREQ(NF), FREQ(NF)
      DOUBLE PRECISION, INTENT(IN)    :: DEPTH(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: TETA(NPLAN), SINTET(NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: COSTET(NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: TSTOT(NPOIN2,NPLAN,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!=======================================================================
!VBA AJOUT SUBROUTINE QVEG1 12/09/2014
!=======================================================================
!
      INTERFACE
        SUBROUTINE QVEG
     &( TSTOT , TSDER , F , VARIAN , DEPTH, FMOY ,
     &  XKMOY , NF    , NPLAN  , NPOIN2   , BETA  )
!
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NF,NPLAN,NPOIN2
      DOUBLE PRECISION, INTENT(IN)    :: XKMOY(NPOIN2),VARIAN(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: DEPTH(NPOIN2),FMOY(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: BETA(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TSTOT(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF)
        END SUBROUTINE
      END INTERFACE
!
!=========================================================================
!VBA FIN AJOUT SUBROUTINE QVEG1
!=========================================================================
!
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QWIND1
     &( TSTOT , TSDER , F     , XK    , FREQ  , USOLD , USNEW , TWOLD ,
     &  TWNEW , Z0OLD , Z0NEW , TETA  , ROAIR , ROEAU , BETAM , XKAPPA,
     &  DECAL , GRAVIT, NF    , NPLAN , NPOIN2, CIMPLI, TOLD  , TNEW  ,
     &  CPHAS , USN   , USO   , OMNEW , OMOLD , BETAN , BETAO )
      IMPLICIT NONE
      INTEGER, INTENT(IN)   ::  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION, INTENT(IN)   :: GRAVIT,ROAIR,ROEAU,BETAM,XKAPPA
      DOUBLE PRECISION, INTENT(IN)   :: DECAL,CIMPLI
      DOUBLE PRECISION, INTENT(IN)   :: F(NPOIN2,NPLAN,NF),XK(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(IN)   :: FREQ(NF),TWOLD(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)   :: USOLD(NPOIN2), USNEW(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)   :: Z0OLD(NPOIN2), Z0NEW(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)   :: TWNEW(NPOIN2), TETA(NPLAN)
      DOUBLE PRECISION, INTENT(INOUT):: TNEW(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT):: TOLD(NPOIN2,NPLAN),CPHAS(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT):: USO(NPOIN2),U SN(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT):: OMNEW(NPOIN2),OMOLD(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT):: BETAN(NPOIN2), BETAO(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT):: TSTOT(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT):: TSDER(NPOIN2,NPLAN,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QWIND2
     &( TSTOT , TSDER , F     , XK    , FREQ  , USOLD , USNEW , TWOLD ,
     &  TWNEW , TETA  , ROAIR , ROEAU , NF    , NPLAN , NPOIN2,
     &  CIMPLI, USN   , USO   )
      IMPLICIT NONE
      INTEGER, INTENT(IN)            :: NF,NPLAN,NPOIN2
      DOUBLE PRECISION, INTENT(IN)   :: ROAIR,ROEAU,CIMPLI
      DOUBLE PRECISION, INTENT(IN)   :: FREQ(NF),TETA(NPLAN)
      DOUBLE PRECISION, INTENT(IN)   :: TWOLD(NPOIN2),TWNEW(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)   :: USNEW(NPOIN2),USOLD(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT):: USO(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT):: USN(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT):: TSTOT(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT):: TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)   :: F(NPOIN2,NPLAN,NF),XK(NPOIN2,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QWIND3
     &( TSTOT , TSDER , F     , XK    , FREQ  , USOLD , USNEW , TWOLD ,
     &  TWNEW , TETA  , NF    , NPLAN , NPOIN2, CIMPLI, COEFWD,
     &  COEFWE, COEFWF, COEFWH, BETAN , BETAO , DIRN  , DIRO  )
      IMPLICIT NONE
      INTEGER, INTENT(IN)   ::    NF  , NPLAN        , NPOIN2
      DOUBLE PRECISION, INTENT(IN)   :: CIMPLI
      DOUBLE PRECISION, INTENT(IN)   :: FREQ(NF)     , TETA(NPLAN)
      DOUBLE PRECISION, INTENT(IN)   :: TWOLD(NPOIN2), TWNEW(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)   :: USOLD(NPOIN2), USNEW(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)   :: F(NPOIN2,NPLAN,NF),XK(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(IN)   :: COEFWD, COEFWE, COEFWF, COEFWH
      DOUBLE PRECISION, INTENT(INOUT):: DIRO(NPOIN2) , DIRN(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT):: BETAN(NPOIN2), BETAO(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT):: TSTOT(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT):: TSDER(NPOIN2,NPLAN,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QWINDL
     &( TSTOT , FREQ  , USOLD , USNEW , TWOLD , TWNEW , TETA  ,
     &  NF    , NPLAN , NPOIN2, CIMPLI, USN   , USO   , FPMO  , FPMN )
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NF,NPLAN,NPOIN2
      DOUBLE PRECISION, INTENT(IN)    :: CIMPLI
      DOUBLE PRECISION, INTENT(IN)    :: FREQ(NF),TETA(NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: FPMO(NPOIN2),FPMN(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: TWOLD(NPOIN2),TWNEW(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: USNEW(NPOIN2),USOLD(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: USO(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: USN(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: TSTOT(NPOIN2,NPLAN,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE RADIAT
     &        ( FX    , FY    ,XK1   , FS    , CG1   ,
!        SXX   , SXY   , SYY   , XK1   , FS    , CG1   ,
!     &        DEPTH1,
     &        CGSUC1, DSXXDX, DSXYDX, DSXYDY, DSYYDY )
      USE BIEF_DEF
      USE DECLARATIONS_TOMAWAC, ONLY : NPLAN,NF,NPOIN2
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN)    :: FS(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)    :: CG1(NPOIN2,NF),XK1(NPOIN2,NF)
!      DOUBLE PRECISION, INTENT(IN)    :: DEPTH1(NPOIN2)
!      DOUBLE PRECISION, INTENT(INOUT) :: SXX(NPOIN2),SXY(NPOIN2)
!      DOUBLE PRECISION, INTENT(INOUT) :: SYY(NPOIN2),
      DOUBLE PRECISION, INTENT(INOUT) :: CGSUC1(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: FX(NPOIN2),FY(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: DSXXDX(NPOIN2),DSXYDX(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: DSXYDY(NPOIN2),DSYYDY(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE READ_SPECTRA_COORDS
     &(FID,NP,XP,YP)
      IMPLICIT NONE
      INTEGER, INTENT(IN)                         :: FID
      INTEGER, INTENT(IN)                         :: NP
      DOUBLE PRECISION,ALLOCATABLE, INTENT(INOUT) :: XP(:),YP(:)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE RPI_INTR
     &(NEIGB  , NB_CLOSE, RX  , RY      , RXX     , RYY ,
     & NPOIN2 , I       , MAXNSP  , FFD , FIRDIV1 , FIRDIV2 ,
     & SECDIV1, SECDIV2 , SECDIV3, FRSTDIV , SCNDDIV)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NPOIN2, MAXNSP,I
      INTEGER, INTENT(IN) :: NEIGB(NPOIN2,MAXNSP),NB_CLOSE(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: RX(MAXNSP),RY(MAXNSP)
      DOUBLE PRECISION, INTENT(IN)    :: RXX(MAXNSP),RYY(MAXNSP)
      DOUBLE PRECISION, INTENT(INOUT) :: SECDIV1,SECDIV2,SECDIV3
      DOUBLE PRECISION, INTENT(INOUT) :: FIRDIV1,FIRDIV2
      DOUBLE PRECISION, INTENT(IN)    :: FFD(NPOIN2)
      LOGICAL, INTENT(IN)             :: FRSTDIV,SCNDDIV
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
!V6P2 New subroutine
      INTERFACE
        SUBROUTINE RPI_INVR
     &( X     , Y     , NEIGB , NB_CLOSE, RK_D , RX_D , RY_D  , RXX_D ,
     &  RYY_D , NPOIN2, I     , QUO   , AC    , MAXNSP, MINDIST )
      IMPLICIT NONE
      INTEGER, INTENT(IN)    :: NPOIN2, MAXNSP, I
      INTEGER, INTENT(IN)    :: NEIGB(NPOIN2,MAXNSP), NB_CLOSE(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: QUO, AC
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN2), Y(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: MINDIST(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: RK_D(MAXNSP)
      DOUBLE PRECISION, INTENT(INOUT) :: RX_D(MAXNSP), RY_D(MAXNSP)
      DOUBLE PRECISION, INTENT(INOUT) :: RXX_D(MAXNSP), RYY_D(MAXNSP)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE SEMIMP
     &( F ,CF ,XK    ,FREQ  ,DFREQ ,DEPTH ,VENTX ,VENTY ,X     ,Y     ,
     &  NVEB  ,NVEF  ,NBOR  ,NPTFR ,DDC   ,TV1   ,TV2   ,
     &  U1    ,V1    ,U2    ,V2    ,TETA  ,SINTET,COSTET,INDIC ,
     &  TAILF ,RAISF ,GRAVIT,CFROT1,CMOUT1,CMOUT2,CMOUT3,CMOUT4,CMOUT5,
     &  CMOUT6,TPROP ,DTSI  ,ROAIR ,ROEAU ,XKAPPA,BETAM ,DECAL ,CDRAG ,
     &  ALPHA ,ZVENT ,NF    ,NPLAN ,NPOIN2,IANGNL,COEFNL,F1    ,NSITS ,
     &  SMOUT ,SFROT ,SVENT ,LVENT ,STRIF ,VENT  ,VENSTA,VX_CTE,VY_CTE,
     &  SBREK ,ALFABJ,GAMBJ1,GAMBJ2,IQBBJ ,IHMBJ ,IFRBJ ,BORETG,GAMATG,
     &  IWHTG ,IFRTG ,ALFARO,GAMARO,GAM2RO,IDISRO,IEXPRO,IFRRO ,BETAIH,
     &  EM2SIH,IFRIH ,COEFHS,XDTBRK,NDTBRK,STRIA ,ALFLTA,RFMLTA,KSPB  ,
     &  BDISPB,BDSSPB,PROINF,DF_LIM,LIMIT ,CIMPLI,COEFWD,COEFWE,COEFWF,
     &  COEFWH,NOMVEB,FMTVEB,NOMVEF,FMTVEF,NBD   ,QINDI ,TAUWAV,USOLD ,
     &  TWOLD ,
     &  Z0OLD ,TSTOT ,TSDER ,TOLD  ,TNEW  ,VARIAN,FMOY  ,XKMOY ,USNEW ,
     &  Z0NEW ,TWNEW ,TAUX1 ,TAUX2 ,TAUX3 ,TAUX4 ,TAUX5 ,TAUX6 ,TAUX7 ,
     &  BETA  ,NQ_OM2,NF1   ,NF2   ,NT1   ,NCONF ,NCONFM,
     &  SEUIL ,LBUF  ,DIMBUF,F_POIN,T_POIN,F_COEF,F_PROJ,TB_SCA,K_IF1 ,
     &  K_1P  ,K_1M  ,K_IF2 ,K_IF3 ,K_1P2P,K_1P2M,K_1P3P,K_1P3M,K_1M2P,
     &  K_1M2M,K_1M3P,K_1M3M,IDCONF,TB_V14,TB_V24,TB_V34,TB_TPM,TB_TMP,
     &  TB_FAC,MDIA,IANMDI,COEMDI,NVWIN,DIAGHF,VEGETATION,SDSCU,CDSCUR,
     &  CBAJ,LIFBOR,FBOR)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NPOIN2,NPLAN,NF,NSITS,NPTFR,NVEB
      INTEGER, INTENT(INOUT) :: NVWIN,NVEF
      INTEGER, INTENT(IN) :: SMOUT , SFROT , SVENT , STRIF ,
     &                   SBREK , INDIC
      INTEGER, INTENT(IN) :: IQBBJ, IHMBJ, IFRBJ, IWHTG , IFRTG , IFRRO
      INTEGER, INTENT(IN) :: IEXPRO, IFRIH, NDTBRK, IDISRO, STRIA
      INTEGER, INTENT(IN) :: NBOR(NPTFR)   , IANGNL(NPLAN,8)
      INTEGER, INTENT(IN) :: NBD   , QINDI(NBD), DIAGHF,SDSCU
      DOUBLE PRECISION, INTENT(IN) :: TAILF, CFROT1, GRAVIT, RAISF,DTSI,
     &                  CMOUT1, CMOUT2, DDC   , ZVENT , TPROP ,
     &                  ROAIR , ROEAU , XKAPPA, BETAM , DECAL , CDRAG ,
     &                  ALPHA , GAMBJ1, GAMBJ2, ALFABJ,BORETG, GAMATG,
     &                  COEFHS, VX_CTE, VY_CTE, CIMPLI,
     &                  GAMARO, ALFARO, GAM2RO, EM2SIH, BETAIH, XDTBRK,
     &                  ALFLTA, RFMLTA, KSPB  , BDISPB, BDSSPB, F1
      DOUBLE PRECISION, INTENT(INOUT) :: TV1   ,TV2
      DOUBLE PRECISION, INTENT(IN) ::  DEPTH(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: USNEW(NPOIN2) , USOLD(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: VARIAN(NPOIN2),  FMOY(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: XKMOY(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TWOLD(NPOIN2), TWNEW(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: Z0OLD(NPOIN2), Z0NEW(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: VENTX(NPOIN2), VENTY(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: U1(NPOIN2),    U2(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: V1(NPOIN2), V2(NPOIN2)
      DOUBLE PRECISION, INTENT(IN) ::    X(NPOIN2)   ,   Y(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TAUWAV(NPOIN2), TAUX1(NPOIN2),
     &                                   TAUX2(NPOIN2),TAUX3(NPOIN2),
     &                                   TAUX4(NPOIN2),TAUX5(NPOIN2),
     &                                   TAUX6(NPOIN2),TAUX7(NPOIN2)
      DOUBLE PRECISION, INTENT(IN) ::  COEFNL(16)
      DOUBLE PRECISION, INTENT(IN) :: TETA(NPLAN), SINTET(NPLAN)
      DOUBLE PRECISION, INTENT(IN) :: COSTET(NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN) :: XK(NPOIN2,NF), FREQ(NF), DFREQ(NF)
      DOUBLE PRECISION, INTENT(INOUT) :: DF_LIM(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: TSTOT(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: TOLD(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: TNEW(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: BETA(NPOIN2)
      DOUBLE PRECISION, INTENT(IN) :: CF(NPOIN2,NPLAN,NF)
     &                   ,CDSCUR
      INTEGER, INTENT(IN) :: CBAJ
      INTEGER, INTENT(INOUT) :: LIMIT
      CHARACTER(LEN=144), INTENT(IN) :: NOMVEB, NOMVEF
      CHARACTER(LEN=8), INTENT(IN) :: FMTVEB,FMTVEF
      LOGICAL, INTENT(IN) ::  PROINF, VENT , VENSTA,VEGETATION
!....Linear wind growth declaration
      INTEGER, INTENT(IN) :: LVENT
!....Yan expression declarations
      DOUBLE PRECISION, INTENT(IN) :: CMOUT3, CMOUT4, CMOUT5, CMOUT6
!....Westhuysen expression decalaration
      DOUBLE PRECISION, INTENT(IN) :: COEFWD, COEFWE, COEFWF, COEFWH
!....MDIA method declarations
      INTEGER, INTENT(IN) :: MDIA, IANMDI(NPLAN,16,MDIA)
      DOUBLE PRECISION, INTENT(IN) ::  COEMDI(32,MDIA)
!....GQM method declarations
      INTEGER, INTENT(IN) :: NQ_OM2, NF1, NF2 , NT1
      INTEGER, INTENT(IN) :: NCONF , NCONFM
      DOUBLE PRECISION, INTENT(IN) ::  SEUIL
      INTEGER, INTENT(IN) :: LBUF  , DIMBUF
      INTEGER, INTENT(IN) :: F_POIN(DIMBUF), T_POIN(DIMBUF)
      DOUBLE PRECISION, INTENT(IN) ::  F_COEF(DIMBUF), F_PROJ(DIMBUF),
     &                                TB_SCA(DIMBUF)
      INTEGER, INTENT(IN) :: K_IF1 (NF1)
      INTEGER, INTENT(IN) :: K_1P  (NT1,NF1), K_1M(NT1,NF1)
      INTEGER, INTENT(IN) :: K_IF2 (NF2,NT1,NF1),
     &                       K_IF3 (NF2,NT1,NF1),
     &        K_1P2P(NF2,NT1,NF1), K_1P2M(NF2,NT1,NF1),
     &        K_1P3P(NF2,NT1,NF1), K_1P3M(NF2,NT1,NF1),
     &        K_1M2P(NF2,NT1,NF1), K_1M2M(NF2,NT1,NF1),
     &        K_1M3P(NF2,NT1,NF1), K_1M3M(NF2,NT1,NF1)
      INTEGER, INTENT(IN) :: IDCONF(NCONFM,3)
      DOUBLE PRECISION, INTENT(IN) :: TB_V14(NF1)
      DOUBLE PRECISION, INTENT(IN) :: TB_V24(NF2,NT1,NF1),
     &                                TB_V34(NF2,NT1,NF1),
     &                                TB_TPM(NF2,NT1,NF1),
     &                                TB_TMP(NF2,NT1,NF1),
     &                                TB_FAC(NF2,NT1,NF1)
      INTEGER, INTENT(IN)            :: LIFBOR(NPTFR)
      DOUBLE PRECISION, INTENT(IN)   :: FBOR(NPTFR,NPLAN,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE SOR3D
     &(F,NPLAN,NF,NPOIN2,AT,U,V,UV,VV,DEPTH,VENT,
     & COURAN,MAREE,TITRE,NR3D,FMTR3D,TRA01,MESH3D)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NR3D,NF,NPLAN,NPOIN2
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF),AT
      DOUBLE PRECISION, INTENT(IN)    :: U(NPOIN2),V(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: UV(NPOIN2),VV(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: DEPTH(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA01(NPOIN2*NPLAN)
      LOGICAL, INTENT(IN)             :: COURAN,VENT,MAREE
      CHARACTER(LEN=3), INTENT(IN)    :: FMTR3D
      CHARACTER(LEN=80), INTENT(IN)   :: TITRE
      TYPE(BIEF_MESH), INTENT(IN)     :: MESH3D
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE SPEINI
     &( F     , SPEC  , FRA   , UV    , VV    , FREQ  , TETA  , GRAVIT,
     &  FREMAX, FETCH , SIGMAA, SIGMAB, GAMMA , FPIC  , HM0   , ALPHIL,
     &  TETA1 , SPRED1, TETA2 , SPRED2, XLAMDA, NPOIN2, NPLAN , NF    ,
     &  INISPE, E2FMIN, DEPTH , FRABI )
      IMPLICIT NONE
      INTEGER, INTENT(IN)    ::  NPOIN2, NPLAN , NF    , INISPE, FRABI
      DOUBLE PRECISION, INTENT(IN)    :: GRAVIT, FREMAX, FETCH , SIGMAA
      DOUBLE PRECISION, INTENT(IN)    :: SIGMAB, GAMMA
      DOUBLE PRECISION, INTENT(IN)    :: FPIC  , HM0   , ALPHIL, TETA1
      DOUBLE PRECISION, INTENT(IN)    :: SPRED1, TETA2
      DOUBLE PRECISION, INTENT(IN)    :: SPRED2, XLAMDA, E2FMIN
      DOUBLE PRECISION, INTENT(IN)    :: FREQ(NF), TETA(NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: UV(NPOIN2) , VV(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: DEPTH(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: FRA(NPLAN), SPEC(NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE SPEJON
     &( SPEC  , FREQ  , NF    , AL    , FP     , GAMMA , SIGMAA, SIGMAB,
     &  DEUPI, GRAVIT, E2FMIN, FPMIN )
      IMPLICIT NONE
      INTEGER, INTENT(IN)    ::  NF
      DOUBLE PRECISION, INTENT(IN)    :: GRAVIT, SIGMAA, SIGMAB, GAMMA
      DOUBLE PRECISION, INTENT(IN)    :: DEUPI, FPMIN
      DOUBLE PRECISION, INTENT(IN)    :: FP    , E2FMIN, AL , FREQ(NF)
      DOUBLE PRECISION, INTENT(INOUT) :: SPEC(NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE SPETMA
     &( SPEC  , FREQ  , NF    , AL    , FP     , GAMMA , SIGMAA, SIGMAB,
     &  DEUPI , GRAVIT, E2FMIN, FPMIN , DEPTH  )
      IMPLICIT NONE
      INTEGER, INTENT(IN)    ::  NF
      DOUBLE PRECISION, INTENT(IN)    :: GRAVIT, SIGMAA, SIGMAB, GAMMA
      DOUBLE PRECISION, INTENT(IN)    :: DEUPI , FPMIN
      DOUBLE PRECISION, INTENT(IN)    :: FP, E2FMIN, AL, DEPTH, FREQ(NF)
      DOUBLE PRECISION, INTENT(INOUT) :: SPEC(NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE DIR_SPREAD
     &( DIRSPR, F     , COSTET, SINTET, NPLAN , FREQ  , DFREQ , NF    ,
     &        NPOIN2, TAILF)
      IMPLICIT NONE
      INTEGER, INTENT(IN)    :: NF    , NPLAN , NPOIN2
      DOUBLE PRECISION, INTENT(IN)    :: TAILF
      DOUBLE PRECISION, INTENT(IN)    :: COSTET(NPLAN) , SINTET(NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: FREQ(NF), DFREQ(NF)
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: DIRSPR(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE STRESS
     &( TAUWAV, TSTOT , F     , USNEW , TWNEW , Z0NEW , FREQ  , DFREQ ,
     &  TETA  , SINTET, COSTET, ROAIR , ROEAU , XKAPPA, BETAM , DECAL ,
     &  GRAVIT, NPOIN2, NPLAN , NF    , XTAUW , YTAUW , TAUHF )
      IMPLICIT NONE
      INTEGER, INTENT(IN)    ::  NPOIN2, NPLAN , NF
      DOUBLE PRECISION, INTENT(IN)    :: ROAIR , ROEAU , XKAPPA , BETAM
      DOUBLE PRECISION, INTENT(IN)    :: DECAL , GRAVIT
      DOUBLE PRECISION, INTENT(IN)    :: USNEW(NPOIN2), TWNEW(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: Z0NEW(NPOIN2), FREQ(NF)
      DOUBLE PRECISION, INTENT(IN)    :: TSTOT(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF), DFREQ(NF)
      DOUBLE PRECISION, INTENT(IN)    :: TETA(NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: SINTET(NPLAN), COSTET(NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: TAUWAV(NPOIN2), TAUHF(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: XTAUW(NPOIN2) , YTAUW(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE TAUTOT
     &( TAUT  , UVENT , TAUW  , CDRAG , ALPHA , XKAPPA, ZVENT , SEUIL ,
     &  GRAVIT, ITR   , ITRMIN, ITRMAX)
      IMPLICIT NONE
      INTEGER, INTENT(IN)    ::  ITRMIN, ITRMAX
      INTEGER, INTENT(INOUT) ::  ITR
      DOUBLE PRECISION, INTENT(IN)    :: UVENT , TAUW  , ALPHA , XKAPPA
      DOUBLE PRECISION, INTENT(IN)    :: ZVENT
      DOUBLE PRECISION, INTENT(IN)    :: SEUIL , CDRAG , GRAVIT
      DOUBLE PRECISION, INTENT(INOUT) :: TAUT
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE TETMOY
     &( TETAM , F     , COSTET, SINTET, NPLAN , FREQ  , DFREQ , NF    ,
     &  NPOIN2, TAILF)
      IMPLICIT NONE
      INTEGER, INTENT(IN)    ::  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION, INTENT(IN)    :: TAILF
      DOUBLE PRECISION, INTENT(IN)    :: DFREQ(NF)
      DOUBLE PRECISION, INTENT(IN)    :: COSTET(NPLAN) , SINTET(NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF), FREQ(NF)
      DOUBLE PRECISION, INTENT(INOUT) :: TETAM(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE TOM_CORFON
      IMPLICIT NONE
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE TOTNRJ
     &( VARIAN, F     , FREQ  , DFREQ , TAILF , NF    , NPLAN , NPOIN2)
      IMPLICIT NONE
      INTEGER, INTENT(IN)    ::          NF    , NPLAN , NPOIN2
      DOUBLE PRECISION, INTENT(IN)    :: TAILF , FREQ(NF), DFREQ(NF)
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: VARIAN(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE TRANSF
     &( FA    , FR    , FREQ  , DFREQ , COSTET, SINTET, UC    , VC    ,
     &  XK    , KNEW  , NEWF  , NEWF1 , TAUX1 , TAUX2 , NPOIN2, NPLAN ,
     &  NF    , RAISF , LT    , GRADEB, GRAPRD)
      IMPLICIT NONE
      INTEGER, INTENT(IN)    :: NPOIN2, NPLAN, NF, LT, GRADEB, GRAPRD
      INTEGER, INTENT(INOUT) :: KNEW(NPOIN2),NEWF(NPOIN2), NEWF1(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: RAISF,FR(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)    :: FREQ(NF),DFREQ(NF)
      DOUBLE PRECISION, INTENT(IN)    :: COSTET(NPLAN),SINTET(NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: UC(NPOIN2),VC(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: XK(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: TAUX1(NPOIN2),TAUX2(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: FA(NPOIN2,NPLAN,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE USTAR1
     &( USTAR , Z0    , TAUWAV, UV    , VV    , CDRAG , ALPHA , XKAPPA,
     &  ZVENT , GRAVIT, NPOIN2)
      IMPLICIT NONE
      INTEGER, INTENT(IN)    ::  NPOIN2
      DOUBLE PRECISION, INTENT(IN)    :: TAUWAV(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: UV(NPOIN2) , VV(NPOIN2), GRAVIT
      DOUBLE PRECISION, INTENT(IN)    :: CDRAG, ALPHA, XKAPPA, ZVENT
      DOUBLE PRECISION, INTENT(INOUT) :: USTAR(NPOIN2), Z0(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE USTAR2
     &( USTAR , UV    , VV    , NPOIN2)
      IMPLICIT NONE
      INTEGER, INTENT(IN)    ::  NPOIN2
      DOUBLE PRECISION, INTENT(IN)    :: UV(NPOIN2) , VV(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: USTAR(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE VENUTI
     &(X,Y,NPOIN,NVEN,FMTVEN,NBOR,NPTFR,AT,DDC,TV1,TV2,U1,V1,U2,V2)
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NVEN,NPOIN,NPTFR
      INTEGER, INTENT(IN)             :: NBOR(NPTFR,2)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN),Y(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: U1(NPOIN),V1(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: U2(NPOIN),V2(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: AT,DDC
      DOUBLE PRECISION, INTENT(INOUT) :: TV1,TV2
      CHARACTER(LEN=8), INTENT(IN)    :: FMTVEN
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE VITFON(UWBM,F,XK,DEPTH,DFREQ,NF,NPOIN2,NPLAN)
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NF,NPLAN,NPOIN2
      DOUBLE PRECISION, INTENT(INOUT) :: UWBM(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)    :: XK(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(IN)    :: DEPTH(NPOIN2),DFREQ(NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE WAC
     &(PART, U_TEL, V_TEL, H_TEL, FX_WAC, FY_WAC, UV_WAC, VV_WAC,
     & CODE, T_TEL, DT_TEL,NIT_TEL,PERCOU_WAC,
     & DIRMOY_TEL,HM0_TEL,TPR5_TEL,ORBVEL_TEL)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER,           INTENT(IN)      :: PART,NIT_TEL,PERCOU_WAC
      CHARACTER(LEN=24), INTENT(IN)      :: CODE
      TYPE(BIEF_OBJ),    INTENT(IN)      :: U_TEL,V_TEL,H_TEL
      TYPE(BIEF_OBJ),    INTENT(INOUT)   :: DIRMOY_TEL,HM0_TEL,TPR5_TEL
      TYPE(BIEF_OBJ),    INTENT(INOUT)   :: FX_WAC,FY_WAC,ORBVEL_TEL
      TYPE(BIEF_OBJ),    INTENT(INOUT)   :: UV_WAC,VV_WAC
      DOUBLE PRECISION,  INTENT(IN)      :: DT_TEL,T_TEL
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE WNSCOU
     &( CK2   , FREQ  , DEPTH )
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN)    :: FREQ  , DEPTH
      DOUBLE PRECISION, INTENT(INOUT) :: CK2
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE WPOWER
     &( POWER , F     , DFREQ , CG    , TAILF , NF    , NPLAN ,
     &  NPOIN2, ROEAU )
      IMPLICIT NONE
      INTEGER, INTENT(IN)    ::          NF    , NPLAN , NPOIN2
      DOUBLE PRECISION, INTENT(IN)    :: TAILF 
      DOUBLE PRECISION, INTENT(IN)    :: DFREQ(NF)
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)    :: CG(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(IN)    :: ROEAU
      DOUBLE PRECISION, INTENT(INOUT) :: POWER(NPOIN2)!
        END SUBROUTINE
      END INTERFACE
!
!=======================================================================
!
      END MODULE INTERFACE_TOMAWAC
