      SUBROUTINE AD_SISYPHE_LOOPRECORDS_END

        IMPLICIT NONE

        INTEGER     LNG,LU
        COMMON/INFO/LNG,LU

!       DEBUG IS NOT AVAILABLE HERE YET
!        IF(DEBUG.GT.0) WRITE(LU,*) 'AD_SISYPHE_LOOPRECORDS_END [lib]'

      END SUBROUTINE AD_SISYPHE_LOOPRECORDS_END
