      SUBROUTINE AD_SISYPHE_SUBITERATION_BEGIN

        IMPLICIT NONE

        INTEGER     LNG,LU
        COMMON/INFO/LNG,LU

!       DEBUG IS NOT AVAILABLE HERE YET
!        IF(DEBUG.GT.0) WRITE(LU,*) 'AD_SISYPHE_SUBITERATION_BEGIN [lib]'

      END SUBROUTINE AD_SISYPHE_SUBITERATION_BEGIN
