      SUBROUTINE AD_SISYPHE_MAIN_INIT
  
        USE DECLARATIONS_SISYPHE
        
        IMPLICIT NONE

        INTEGER     LNG,LU
        COMMON/INFO/LNG,LU
        
!!        WRITE(LU,*) 'AD_SISYPHE_MAIN_INIT [lib]'
        IF(DEBUG.GT.0) WRITE(LU,*) 'AD_SISYPHE_MAIN_INIT [lib]'

      END SUBROUTINE AD_SISYPHE_MAIN_INIT
