      SUBROUTINE AD_TELEMAC2D_MAIN_AFTER_LECDON_TELEMAC2D
        USE DECLARATIONS_SISYPHE
        
        IMPLICIT NONE

        INTEGER     LNG,LU
        COMMON/INFO/LNG,LU
        
!!        WRITE(LU,*) 'AD_TELEMAC2D_MAIN_AFTER_LECDON_TELEMAC2D [lib]'
        IF(DEBUG.GT.0) THEN
           WRITE(LU,*) 'AD_TELEMAC2D_MAIN_AFTER_LECDON_TELEMAC2D [lib]'
        END IF

      END SUBROUTINE AD_TELEMAC2D_MAIN_AFTER_LECDON_TELEMAC2D
