      SUBROUTINE AD_TELEMAC3D_MAIN_AFTER_LECDON_SISYPHE
        USE DECLARATIONS_SISYPHE
        
        IMPLICIT NONE

        
!!        WRITE(LU,*) 'AD_TELEMAC3D_MAIN_AFTER_LECDON_SISYPHE [lib]'
        IF(DEBUG.GT.0) THEN
           WRITE(LU,*) 'AD_TELEMAC3D_MAIN_AFTER_LECDON_SISYPHE [lib]'
        END IF

      END SUBROUTINE AD_TELEMAC3D_MAIN_AFTER_LECDON_SISYPHE
