      SUBROUTINE AD_TELEMAC2D_MAIN_AFTER_LECDON_SISYPHE

        IMPLICIT NONE

        INTEGER     LNG,LU
        COMMON/INFO/LNG,LU

!       DEBUG IS NOT AVAILABLE HERE YET
!        IF(DEBUG.GT.0)
!     &     WRITE(LU,*) 'AD_TELEMAC2D_MAIN_AFTER_LECDON_SISYPHE [lib]'

      END SUBROUTINE AD_TELEMAC2D_MAIN_AFTER_LECDON_SISYPHE
