      SUBROUTINE AD_TELEMAC2D_BEGIN

        IMPLICIT NONE

        INTEGER     LNG,LU
        COMMON/INFO/LNG,LU

!       DEBUG IS NOT AVAILABLE HERE YET
!        IF(DEBUG.GT.0) WRITE(LU,*) 'AD_TELEMAC2D_BEGIN [lib]'

      END SUBROUTINE AD_TELEMAC2D_BEGIN
