      SUBROUTINE AD_TELEMAC3D_INITIALISATION_END

        USE DECLARATIONS_TELEMAC3D

        IMPLICIT NONE


        IF(DEBUG.GT.0)
     &      WRITE(LU,*) 'AD_TELEMAC3D_INITIALISATION_END [lib]'

      END SUBROUTINE AD_TELEMAC3D_INITIALISATION_END
