!        **********************************************
                   MODULE DECLARATIONS_WAQTEL
!        **********************************************
!
!
!***********************************************************************
! WAQTEL   V7P3
!***********************************************************************
!
!brief    DECLARATION OF PRINCIPAL WAQTEL VARIABLES
!
!history  R. ATA (EDF-LNHE)
!+
!+
!history  M.JODEAU (EDF-LNHE)
!+        08/2016
!+        V7P3
!+        AED2 coupling
!+
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
      USE BIEF_DEF
!
!       NOTE: THIS MODULE IS ORGANIZED IN 6 PARTS
!
!       (1) VECTORS (WILL BE DECLARED AS BIEF_OBJ STRUCTURES)
!       (2) INTEGERS
!       (3) LOGICAL VALUES
!       (4) REALS
!       (5) STRINGS
!       (6) ALIASES (IF NECESSARY)
!
!-----------------------------------------------------------------------
! (1) VECTORS (REAL AND INTEGER)
!-----------------------------------------------------------------------
!
!
!     COEFFICIENT OF REAERATION
!
      TYPE(BIEF_OBJ), TARGET :: K2
!
!     EFFECT OF SUNSHINE ON ALGAE GROWTH (BIOMASS PROCESS)
!
      TYPE(BIEF_OBJ), TARGET :: RAYEFF
!-----------------------------------------------------------------------
!
!       2) INTEGERS
!
!-----------------------------------------------------------------------
!
!     MAXIMUM NUMBER OF VALUES OF KEY-WORDS OF ONE KIND (INTEGER, LOGICAL, ETC.)
!
      INTEGER, PARAMETER :: MAXKEY = 300
!     GRAPHIC PRINTOUT PERIOD WAQ
!
      INTEGER LEOPRD
!
!     LISTING PRINTOUT PERIOD WAQ
!
      INTEGER LISPRD
!
!     MAXIMUM NUMBER OF OUTPUT VARIABLES
!
      INTEGER, PARAMETER :: MAXWQVAR = 50
!
!-----------------------------------------------------------------------
!
!
!     WAQ PROCESS (1-O2, 2-BIOMASS, 3-EUTRO 4-MICROPOL 5-THERMIC)
!
      INTEGER WAQPROCESS
!
!     NUMBER OF TRACERS ADDED WHEN USING WAQPROCESS
!
      INTEGER  ADDTR
!
!     TO KNOW IF A VARIABLE WILL BE EXITED ON FILE, ON LISTING
!
      LOGICAL SORLEO(MAXWQVAR),SORIMP(MAXWQVAR)
!
!     WAQ result FILE NUMBER
!
      INTEGER WAQRES
!
!     WAQ boundary condition FILE NUMBER
!
      INTEGER WAQCLI
!
!     WAQ GEOMETRY FILE NUMBER
!
      INTEGER WAQGEO
!
!     WAQ HYDRODYNAMICS FILE NUMBER
!
      INTEGER WAQHYD
!
!     WAQ STEERING FILE NUMBER
!
      INTEGER WAQCAS
!
!     WAQ REFERENCE FILE NUMBER
!
      INTEGER WAQREF
!
!     DEBUGGER
!
      INTEGER DEBUG
!
!     FORMULA FOR COMPUTING K2
!
      INTEGER FORMK2
!
!     FORMULA FOR COMPUTING RS
!
      INTEGER FORMRS
!
!     FORMULA FOR COMPUTING CS
!
      INTEGER FORMCS
!
!     COEFFICIENTS OF AERATION FORMULA
!
      INTEGER CFORMAERA(2)
!
!     ATMOSPHERE-WATER EXCHANGE MODEL
!
      INTEGER ATMOSEXCH
!
!     BRIGHTNESS OF THE SKY
!
      INTEGER ISKYTYPE
!
!     METHOD OF COMPUTATION OF EXTINCTION OF SUN RAY
!
      INTEGER MEXTINC
!
!     FORMULA OF ATMOSPHERIC RADIATION (GLM)
!
      INTEGER IRAY_ATM
!
!-----------------------------------------------------------------------
!
!       3) LOGICAL
!
!-----------------------------------------------------------------------
!
!     IF YES, MASS-BALANCE
!
      LOGICAL WQBILMAS
!
!     IF YES, VALIDATION
!
      LOGICAL WQVALID
!
!     STEADY HYDRODYNAMICS
!
      LOGICAL  PERMA
!
!     IF TEMPERATURE IS VARIABLE
!
      LOGICAL YATEMP
!-----------------------------------------------------------------------
!
!       4) REALS
!
!-----------------------------------------------------------------------
!
!     WATER DENSITY
!
      DOUBLE PRECISION RO0 ! (RHO ZERO)
!
!     KINEMATIC VISCOSITY
!
      DOUBLE PRECISION VCE

!     LONGITUDINAL DISPERSION
!
      DOUBLE PRECISION LDISP
!
!     TRANSVERSAL DISPERSION
!
      DOUBLE PRECISION TDISP
!
!     WATER QUALITY VARIABLES PCO2
!
      DOUBLE PRECISION PCO2
!
!     WATER QUALITY VARIABLES PVAP
!
      DOUBLE PRECISION PVAP
!
!     WATER QUALITY VARIABLES RAY3
!
      DOUBLE PRECISION RAY3
!
!     WATER QUALITY VARIABLES NEBU
!
      DOUBLE PRECISION NEBU
!
!     WATER QUALITY VARIABLES - RELATIVE HUMIDITY
!
      DOUBLE PRECISION HREL
!
!     WATER QUALITY VARIABLES - RAINFALL
!
      DOUBLE PRECISION RAINFALL
!
!     WATER QUALITY VARIABLES - AIR TEMPERATURE
!
      TYPE(BIEF_OBJ), TARGET :: TAIR
!
!     VALUE OF THE AIR TEMPERATURE
!
      DOUBLE PRECISION TAIR_VALUE
!
!     WATER QUALITY VARIABLES ZSD (SECCHI LENGTH)
!
      DOUBLE PRECISION ZSD
!
!     WATER QUALITY VARIABLES NWIND (IF CONSTANT WIND IN SPACE)
!
      DOUBLE PRECISION NWIND
!
!     WATER QUALITY VARIABLES C14_ATM
!
      DOUBLE PRECISION C14_ATM
!
!     WATER QUALITY VARIABLES HTO_ATM
!
      DOUBLE PRECISION HTO_ATM
!
!     WEIR COEFFICIENT OF REAERATION
!
      DOUBLE PRECISION RSW
!
!     COEFFICIENT TO CALIBRATE THE ATMOSPHERE-WATER EXCHANGE MODEL
!
      DOUBLE PRECISION C_ATMOS
!
!     WATER QUALITY VARIABLE: EVAPORATION
!
      DOUBLE PRECISION EVAPORATION
!
! Water quality specific key-words
!
!
!     EUTRO PROCESS
!
!
!     CONSTANT OF DEGRADATION OF ORGANIC LOAD K120
!
      DOUBLE PRECISION K120
!
!     CONSTANT OF NITRIFICATION KINETIC K520
!
      DOUBLE PRECISION K520
!
!     O2 PRODUCED BY PHOTOSYNTHESIS (F FOR TRACER)
!
      DOUBLE PRECISION O2PHOTO
!
!     O2 CONSUMED BY NITRIFICATION (N FOR TRACER)
!
      DOUBLE PRECISION O2NITRI
!
!     BENTHIC DEMAND
!
      DOUBLE PRECISION DEMBEN
!
!      COEFFICIENT A AND B USED IN RS FORMULA
!
      DOUBLE PRECISION ABRS(2)
!
!     O2 SATURATION DENSITY OF WATER (CS)
!
      DOUBLE PRECISION O2SATU
!
!     SEDIMENTATION VELOCITY OF ORGANIC PHOSPHORUS
!
      DOUBLE PRECISION WPOR
!
!     SEDIMENTATION VELOCITY OF ORGANIC NITROGEN
!
      DOUBLE PRECISION WNOR
!
!     MAXIMUM ALGAL GROWTH
!
      DOUBLE PRECISION CMAX
!
!     COEF VEGETAL TURBIDITY WITHOUT PHYTOPLANKTON
!
      DOUBLE PRECISION KPE
!
!     PARAMETER OF CALIBRATION OF SMITH FORMULA
!
      DOUBLE PRECISION IK
!
!     CONSTANT OF HALF-SATURATION WITH PHOSPHATE
!
      DOUBLE PRECISION KP
!
!     CONSTANT OF HALF-SATURATION WITH PHOSPHA
!
      DOUBLE PRECISION KN
!
!     ALGAL COEFF OF TOXICITY (ALPHA; ALPHA2)
!
      DOUBLE PRECISION CTOXIC(2)
!
!     RESPIRATION RATE OF ALGAL BIOMASS (RP)
!
      DOUBLE PRECISION TRESPIR
!
!     PROPORTION OF PHOSPHORUS WITHIN PHYTO CELLS (FP)
!
      DOUBLE PRECISION PROPHOC
!
!     PERCENTAGE OF PHYSPHORUS ASSIMILABLE IN DEAD PHYTO
!
      DOUBLE PRECISION DTP
!
!     RATE OF TRANSFORMATION OF POR INTO PO
!
      DOUBLE PRECISION K320
!
!     PROPORTION OF NITROGEN WITHIN PHYTO CELLS (FN)
!
      DOUBLE PRECISION PRONITC
!
!     PERCENTAGE OF NITROGEN ASSIMILABLE IN DEAD PHYTO (DTN)
!
      DOUBLE PRECISION PERNITS
!
!     RATE OF TRANSFORMATION OF NOR INTO NO3
!
      DOUBLE PRECISION K360
!
!     COEF OF ALGAL MORTALITY (M1 AND M2)
!
      DOUBLE PRECISION CMORALG(2)
!
!     SEDIMENTATION VELOCITY OF ORGANIC LOAD
!
      DOUBLE PRECISION WLOR
!
!
!     BIOMASS PROCESS
!
!
!
!     EFFECTS OF PHOSPHORIOUS AND NITROGENIOUS NUTRIMENTS ON ALGAE GROWTH
!
!      DOUBLE PRECISION LNUT
!
!     DENSITY OF SUNSHINE FLUX ON WATER SURFACE
!
      DOUBLE PRECISION I0
!
!
!     O2 PROCESS
!
!
!     CONSTANT OF DEGRADATION OF ORGANIC LOAD K1
!
      DOUBLE PRECISION K1
!
!     COEFFICIENT OF REAERATION K2 (if constant)
!
      DOUBLE PRECISION K22
!
!     CONSTANT OF NITRIFICATION KINETIC K4
!
      DOUBLE PRECISION K44
!
!     PHOTOSYNTHESIS P
!
      DOUBLE PRECISION PHOTO
!
!     VEGATAL RESPIRATION
!
      DOUBLE PRECISION  RESP
!
!     WATER TEMPERATURE
!
      DOUBLE PRECISION WATTEMP
!
!
!     MICROPOL PROCESS (MOSTLY COMMON WITH EUTRO)
!
!
!     EROSION RATE
!
      DOUBLE PRECISION ERO
!
!     SEDIMENTATION CRITICAL STRESS
!
      DOUBLE PRECISION TAUS
!
!     CRITICAL STRESS OF RESUSPENSION
!
      DOUBLE PRECISION TAUR
!
!     SEDIMENT SETTLING VELOCITY
!
      DOUBLE PRECISION VITCHU
!
!     COEFF OF DISTRIBUTION (KD)
!
      DOUBLE PRECISION CDISTRIB
!
!     CONSTANT OF DESORPTION KINETIC (KDESORP)
!
      DOUBLE PRECISION KDESORP
!
!
!
!     THERMIC PROCESS (COMMON VARIABLES WITH EWCHANGE_WITH_ATMOSPHERE MODULE)
!
!
!     WATER SPECIFIC HEAT
!
      DOUBLE PRECISION CP_EAU
!
!     AIR SPECIFIC HEAT
!
      DOUBLE PRECISION CP_AIR
!
!     COEFF OF CLOUDING RATE
!
      DOUBLE PRECISION COEF_K
!
!     COEFFICIENTS FOR CALIBRATING ATMOSPHERIC RADIATION
!
      DOUBLE PRECISION EMA
!
!     COEFFICIENTS FOR CALIBRATING FREE SURFACE RADIATION
!
      DOUBLE PRECISION EMI_EAU
!
!     BOLTZMANN CONSTANT (wM-2K-4)
!
      DOUBLE PRECISION, PARAMETER :: BOLTZ=5.67D-8
!
!     CONVERSION SECOND TO DAYS
!
      DOUBLE PRECISION, PARAMETER :: SECTODAY=1.D0/86400.D0
!
!     COEFFICIENTS OF RAERATION FORMULA
!
      DOUBLE PRECISION CFAER(2)
!
!
!     MES PROCESS
!
!
!     EXPONENTIAL DESINTEGRATION CONSTANT (LAMBD)
!
      DOUBLE PRECISION CCSEDIM
!
!     EVAPORATION
!
      DOUBLE PRECISION EVAPOR
!
!     AED2 COUPLING
!
      INTEGER NWQVARS,NWQBEN,NWQDIAGS
!
!-----------------------------------------------------------------------
!
!       5) STRINGS
!
!-----------------------------------------------------------------------
!
!     TITLE OF STUDY
!
      CHARACTER(LEN=72) TITWAQCAS
!
!     COPY OF SUBMIT STRINGS IN THE DICTIONARY
!
      CHARACTER(LEN=144) SUBMIT(4,300)

!     MAXIMUM OF LOGICAL UNITS NUMBERS
!
      INTEGER, PARAMETER :: MAXLU_WAQ = 14
!
!     BIEF_FILES STRUCTURES
!
      TYPE(BIEF_FILE) :: WAQ_FILES(MAXLU_WAQ)
!
!##> JR @ RWTH: MODULE VARIABLE WITH DEFAULT INITIALISATION FOR USER
!     TYPE COMPONENTS MUST BE SAVED
      SAVE :: Default, VCE, LDISP, TDISP, PCO2, PVAP, RAY3, NEBU, HREL,
     $     RAINFALL, TAIR, ZSD, NWIND, C14_ATM, HTO_ATM, RSW, C_ATMOS,
     $     EVAPORATION, K120, K520, O2PHOTO, O2NITRI, DEMBEN, ABRS,
     $     O2SATU, WPOR, WNOR, CMAX, KPE, IK, KP, KN, CTOXIC, TRESPIR,
     $     PROPHOC, DTP, K320, PRONITC, PERNITS, K360, CMORALG, WLOR, I0
     $     , K1, K22, K44, PHOTO, RESP, WATTEMP, ERO, TAUS, TAUR, VITCHU
     $     , CDISTRIB, KDESORP, CP_EAU, CP_AIR, COEF_K, EMA, EMI_EAU,
     $     CFAER, CCSEDIM, EVAPOR, RO0, TAIR_VALUE
!##< JR @ RWTH
!
      END MODULE DECLARATIONS_WAQTEL


