!
!  INTERFACES OF TOMAWAC SUBROUTINES
!
      MODULE INTERFACE_TOMAWAC
!
!=======================================================================
!
!     DEFINITION OF STRUCTURES
!
!     BIEF_DEF VERSION 6.1
!
      USE BIEF_DEF
!
!-----------------------------------------------------------------------
!
!     DEFINITION OF INTERFACES
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE ANACOS(UC,VC,X,Y,NPOIN2)
      IMPLICIT NONE
      INTEGER  NPOIN2
      DOUBLE PRECISION X(NPOIN2),Y(NPOIN2),UC(NPOIN2),VC(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE ANAMAR
     &( UC  , VC  , ZM  , ZM1 , ZM2 , DZHDT , X  , Y  , NPOIN2 ,
     &  AT  , DDC , LT  )
      IMPLICIT NONE
      INTEGER  NPOIN2
      INTEGER  LT
      DOUBLE PRECISION AT    , DDC
      DOUBLE PRECISION X (NPOIN2), Y (NPOIN2), ZM1(NPOIN2), ZM2(NPOIN2)
      DOUBLE PRECISION UC(NPOIN2), VC(NPOIN2), DZHDT(NPOIN2),ZM(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE ANAVEN
     &( UV , VV , X , Y , NPOIN2, AT , DDC , VX_CTE, VY_CTE)
      IMPLICIT NONE
      INTEGER  NPOIN2
      DOUBLE PRECISION AT    , DDC   , VX_CTE, VY_CTE
      DOUBLE PRECISION X (NPOIN2)    , Y (NPOIN2)
      DOUBLE PRECISION UV(NPOIN2)    , VV(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE ANGLES(XLAMD , DTPLUS, DTMOIN)
      IMPLICIT NONE
      DOUBLE PRECISION XLAMD , DTPLUS, DTMOIN
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE BORNES(B , N , A , XM , X0 , X1 )
      IMPLICIT NONE
      INTEGER  N
      DOUBLE PRECISION B , A , XM , X0 , X1
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
!V6P1 new arguments
      INTERFACE
        SUBROUTINE CONDIW
     &( AT, LT , DPI, TC1, TC2, NPC , TV1, TV2, NPV, TM1, TM2 , NPM ,
     &  NVHMA  , NVCOU , PART , U_TEL, V_TEL , H_TEL )
      USE BIEF_DEF
      IMPLICIT NONE
      DOUBLE PRECISION AT , DPI, TC1, TC2, TV1, TV2, TM1, TM2
      INTEGER          NPC, NPV, NPM
      INTEGER          LT
      INTEGER          NVHMA, NVCOU
      INTEGER,           INTENT(IN)      :: PART
      TYPE(BIEF_OBJ),    INTENT(IN)      :: U_TEL,V_TEL,H_TEL
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE CONW4D
     &(CX,CY,CT,CF,U,V,XK,CG,COSF,TGF,DEPTH,DZHDT,DZX,DZY,DUX,DUY,
     & DVX,DVY,FREQ,COSTET,SINTET,NPOIN2,NPLAN,JF,NF,PROINF,SPHE,
     & COURAN,TRA01,TRA02)
      IMPLICIT NONE
      INTEGER NF,NPLAN,NPOIN2
      INTEGER JF
      DOUBLE PRECISION CX(NPOIN2,NPLAN,JF),CY(NPOIN2,NPLAN,JF)
      DOUBLE PRECISION CT(NPOIN2,NPLAN,JF),CF(NPOIN2,NPLAN,JF)
      DOUBLE PRECISION FREQ(NF)
      DOUBLE PRECISION CG(NPOIN2,NF),XK(NPOIN2,NF)
      DOUBLE PRECISION DEPTH(NPOIN2),DZHDT(NPOIN2)
      DOUBLE PRECISION U(NPOIN2),V(NPOIN2),DZX(NPOIN2),DZY(NPOIN2)
      DOUBLE PRECISION DUX(NPOIN2),DUY(NPOIN2),DVX(NPOIN2),DVY(NPOIN2)
      DOUBLE PRECISION COSTET(NPLAN),SINTET(NPLAN)
      DOUBLE PRECISION COSF(NPOIN2),TGF(NPOIN2)
      DOUBLE PRECISION TRA01(NPLAN),TRA02(NPLAN)
      LOGICAL PROINF,SPHE,COURAN
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE CONWAC
     &( CX    , CY    , CT    , XK    , CG    , COSF  , TGF   , DEPTH ,
     &  DZX   , DZY   , FREQ  , COSTET, SINTET, NPOIN2, NPLAN , JF    ,
     &  NF    , PROINF, SPHE  , PROMIN, TRA01 , TRA02 )
      IMPLICIT NONE
      INTEGER          NF    , NPLAN , NPOIN2, JF
      DOUBLE PRECISION PROMIN
      DOUBLE PRECISION DEPTH(NPOIN2) , DZX(NPOIN2)   , DZY(NPOIN2)
      DOUBLE PRECISION COSF(NPOIN2)  , TGF(NPOIN2)   , FREQ(NF)
      DOUBLE PRECISION COSTET(NPLAN) , SINTET(NPLAN)
      DOUBLE PRECISION TRA01(NPLAN)  , TRA02(NPLAN)
      DOUBLE PRECISION CG(NPOIN2,NF) , XK(NPOIN2,NF)
      DOUBLE PRECISION CX(NPOIN2,NPLAN),CY(NPOIN2,NPLAN)
      DOUBLE PRECISION CT(NPOIN2,NPLAN)
      LOGICAL          PROINF, SPHE
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
!V6P1 new arguments
      INTERFACE
        SUBROUTINE CORMAR
     &( AT    , LT    , TC1   , TC2   , TV1   , TV2   , TM1   , TM2   ,
     &  NPC   , NPM   , NVHMA , NVCOU , PART, U_TEL, V_TEL , H_TEL )
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER          NPC , NPM, NVHMA, NVCOU,LT
      DOUBLE PRECISION AT, TC1, TC2 , TV1, TV2, TM1 , TM2
      INTEGER,           INTENT(IN)      :: PART
      TYPE(BIEF_OBJ),    INTENT(IN)      :: U_TEL,V_TEL,H_TEL
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
! 
      INTERFACE
        FUNCTION COUPLE
     &( XK1   , YK1   , XK2   , YK2   , XK3   , YK3   , XK4   , YK4   ,
     &  GRAVIT, PI    )
      IMPLICIT NONE
      DOUBLE PRECISION XK1   , YK1   , XK2   , YK2   , XK3   , YK3
      DOUBLE PRECISION XK4   , YK4   , GRAVIT, PI    , COUPLE
        END FUNCTION
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE COUUTI
     &(X,Y,NPOIN,NCOU, BINCOU,NBOR,NPTFR,AT,DDC,TC1,TC2,
     & NP,XRELC,YRELC,UR,VR,UC1,VC1,UC2,VC2,NPMAX)
      IMPLICIT NONE
      INTEGER NCOU,NPOIN,NPMAX,NP,NPTFR,NBOR(NPTFR,2)
      DOUBLE PRECISION X(NPOIN),Y(NPOIN)
      DOUBLE PRECISION XRELC(NPMAX),YRELC(NPMAX), UR(NPMAX),VR(NPMAX)
      DOUBLE PRECISION UC1(NPMAX),VC1(NPMAX),UC2(NPMAX),VC2(NPMAX)
      DOUBLE PRECISION AT,DDC,TC1,TC2
      CHARACTER*3 BINCOU
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE CQUEUE
     &( NF    , RAISF , TAILF , JFRE  , JBIS  , COEF1 )
      IMPLICIT NONE
      INTEGER  NF    , JFRE  , JBIS
      DOUBLE PRECISION RAISF , TAILF , COEF1
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        FUNCTION DELFRA( SS    , DEUPI )
      IMPLICIT NONE
      DOUBLE PRECISION DELFRA, SS    , DEUPI
        END FUNCTION
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE DUMP2D( LT , DEUPI , XF1 , NP1 )
      IMPLICIT NONE
      INTEGER          LT    , NP1
      DOUBLE PRECISION DEUPI , XF1(NP1)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE ECRETE
     &( F     , DEPTH , NPOIN2, NPLAN , NF    , PROMIN)
      IMPLICIT NONE
      INTEGER          NPOIN2 , NPLAN, NF
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF), DEPTH(NPOIN2)
      DOUBLE PRECISION PROMIN
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE ECRSPE
     &( F     , B     , TETA  , NPLAN , FREQ  , NF    , NK    ,
     &  NPOIN2, AT    , LT    , AUXIL , INUTIL, NOLEO , NLEO  , NSCO  ,
     &  BINSCO, DEBRES, TITCAS, DATE  , TIME ,ISLEO ,KNOLG)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER  LT, NPOIN2, NLEO  , NSCO  , NF , NK , NPLAN
      INTEGER  NOLEO(NLEO)   , INUTIL(1)
      INTEGER  DATE(3),TIME(3)
      INTEGER :: KNOLG(NPOIN2)
!
      DOUBLE PRECISION AT    , AUXIL(NPLAN,NK)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF) , TETA(NPLAN), FREQ(NF)
      DOUBLE PRECISION B(NPOIN2,NPLAN)
      LOGICAL DEBRES
      LOGICAL         :: ISLEO(NLEO) !
      CHARACTER*72 TITCAS
      CHARACTER(LEN=*)   BINSCO
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
! 
!V6P1 New subroutine
      INTERFACE
        SUBROUTINE F1F1F1
     &( F1SF  , NF1   , IQ_OM1)
      IMPLICIT NONE
      INTEGER          NF1   , IQ_OM1
      DOUBLE PRECISION F1SF(*)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        FUNCTION FONCRO
     &( X     , B     , N     , A     , XM    )
      IMPLICIT NONE
      INTEGER  N
      DOUBLE PRECISION X      , B     , A     , XM , FONCRO
        END FUNCTION
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FPREAD
     &( FREAD , F     , FREQ  , DFREQ , NF    , NPLAN , NPOIN2, EXPO  ,
     &  TAILF , DENOM , E     )
      IMPLICIT NONE
      INTEGER  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION EXPO  , TAILF
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF), FREQ(NF), DFREQ(NF)
      DOUBLE PRECISION DENOM(NPOIN2), E(NPOIN2), FREAD(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FREM01
     &( FM01  , F     , FREQ  , DFREQ , TAILF , NF    , NPLAN , NPOIN2,
     &  AUX1  , AUX2  )
      IMPLICIT NONE
      INTEGER  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION TAILF
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION FREQ(NF), DFREQ(NF), FM01(NPOIN2)
      DOUBLE PRECISION AUX1(NPOIN2), AUX2(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FREM02
     &( FM02  , F     , FREQ  , DFREQ , TAILF , NF    , NPLAN , NPOIN2,
     &  AUX1  , AUX2  )
      IMPLICIT NONE
      INTEGER  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION TAILF
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION FREQ(NF), DFREQ(NF), FM02(NPOIN2)
      DOUBLE PRECISION AUX1(NPOIN2), AUX2(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FREMOY
     &( FMOY  , F     , FREQ  , DFREQ , TAILF , NF    , NPLAN , NPOIN2,
     &  AUX1  , AUX2  )
      IMPLICIT NONE
      INTEGER  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION TAILF
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION FREQ(NF), DFREQ(NF), FMOY(NPOIN2)
      DOUBLE PRECISION AUX1(NPOIN2), AUX2(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FREPIC
     &( FPIC  , F     , FREQ  , NF    , NPLAN , NPOIN2, EMAX  , E     )
      IMPLICIT NONE
      INTEGER  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF), FREQ(NF)  , FPIC(NPOIN2)
      DOUBLE PRECISION EMAX(NPOIN2),E(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FSPRD1
     &( FRA   , DIREC , NPLAN , SPRED1, TETA1 , SPRED2, TETA2 , XLAMDA,
     &  DEUPI )
      IMPLICIT NONE
      INTEGER  NPLAN
      DOUBLE PRECISION SPRED1, TETA1 , SPRED2, TETA2 , XLAMDA, DEUPI
      DOUBLE PRECISION FRA(NPLAN)    , DIREC(NPLAN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FSPRD2
     &( FRA   , DIREC , NPLAN , SPRED1, TETA1 , SPRED2, TETA2 , XLAMDA,
     &  DEUPI )
      IMPLICIT NONE
      INTEGER  NPLAN
      DOUBLE PRECISION SPRED1, TETA1 , SPRED2, TETA2 , XLAMDA, DEUPI
      DOUBLE PRECISION FRA(NPLAN)    , DIREC(NPLAN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FSPRD3
     &( FRA   , DIREC , NPLAN , SPRED1, TETA1 , SPRED2, TETA2 , XLAMDA,
     &  DEUPI )
      IMPLICIT NONE
      INTEGER  NPLAN
      DOUBLE PRECISION SPRED1, TETA1 , SPRED2, TETA2 , XLAMDA, DEUPI
      DOUBLE PRECISION FRA(NPLAN)    , DIREC(NPLAN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        FUNCTION GAMMLN
     &( XX    , DEUPI )
      IMPLICIT NONE
      DOUBLE PRECISION GAMMLN, XX    , DEUPI
        END FUNCTION
      END INTERFACE
!
!-----------------------------------------------------------------------
! 
!V6P1 New subroutine
      INTERFACE
        SUBROUTINE GAULEG
     &( W_LEG , X_LEG , NPOIN )
      IMPLICIT NONE
      INTEGER           NPOIN
      DOUBLE PRECISION  W_LEG(NPOIN) , X_LEG(NPOIN)
        END SUBROUTINE 
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE IMPR
     &(LISPRD,LT,AT,ISITS,ICOD)
      IMPLICIT NONE
      INTEGER LISPRD,LT,ISITS,ICOD
      DOUBLE PRECISION AT
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE INIP4D
     &( U , V , T , W , X , Y , SHP1 ,SHP2 , SHP3 , SHT , SHF , ELT ,
     & ETA , FRE , XCONV , YCONV , TCONV, FCONV , TETA , FREQ ,IKLE2 ,
     & NPOIN2 , NELEM2 , NPLAN  , IFF , NF  ,IFABOR,GOODELT)
      IMPLICIT NONE
      INTEGER NPOIN2,NELEM2,NPLAN,NF,IFF
      DOUBLE PRECISION U(NPOIN2,NPLAN),V(NPOIN2,NPLAN)
      DOUBLE PRECISION T(NPOIN2,NPLAN),W(NPOIN2,NPLAN)
      DOUBLE PRECISION TETA(*),FREQ(NF)
      DOUBLE PRECISION X(NPOIN2),Y(NPOIN2)
      DOUBLE PRECISION XCONV(NPOIN2,NPLAN),YCONV(NPOIN2,NPLAN)
      DOUBLE PRECISION TCONV(NPOIN2,NPLAN),FCONV(NPOIN2,NPLAN)
      DOUBLE PRECISION SHP1(NPOIN2,NPLAN),SHP2(NPOIN2,NPLAN)
      DOUBLE PRECISION SHP3(NPOIN2,NPLAN),SHT(NPOIN2,NPLAN)
      DOUBLE PRECISION SHF(NPOIN2,NPLAN)
      INTEGER IFABOR(NELEM2,7),GOODELT(NPOIN2,NPLAN)
      INTEGER IKLE2(NELEM2,3),ELT(NPOIN2,NPLAN),ETA(NPOIN2,NPLAN)
      INTEGER FRE(NPOIN2,NPLAN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE INIPHY
     &( XK    , CG    , B     , DEPTH , FREQ  , COSPHI, NPOIN2, NF    ,
     &  PROINF, SPHE  )
      IMPLICIT NONE
      INTEGER          NF    , NPOIN2
      DOUBLE PRECISION DEPTH(NPOIN2)    , COSPHI(NPOIN2), FREQ(NF)
      DOUBLE PRECISION B(NPOIN2,NF)  , XK(NPOIN2,NF) , CG(NPOIN2,NF)
      LOGICAL          PROINF, SPHE
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE INIPIE
     &( U , V , W , X , Y , SHP1 ,SHP2 , SHP3 , SHZ , ELT , ETA ,
     & XCONV , YCONV , ZCONV, TETA , IKLE2 , NPOIN2 , NELEM2 , NPLAN  ,
     & ELI , KNOGL , KNI , NELE2L , NPOI2L ,IFABOR,GOODELT)
      IMPLICIT NONE
      INTEGER NPOIN2 , NELEM2 , NPLAN , NELE2L , NPOI2L
      INTEGER ELI(NELE2L),KNOGL(NPOIN2),KNI(NPOI2L)
      INTEGER IKLE2(NELEM2,3),ELT(NPOI2L,NPLAN),ETA(NPOI2L,NPLAN)
      INTEGER IFABOR(NELEM2,5),GOODELT(NPOI2L,NPLAN)
      DOUBLE PRECISION U(NPOIN2,NPLAN),V(NPOIN2,NPLAN)
      DOUBLE PRECISION W(NPOIN2,NPLAN)
      DOUBLE PRECISION X(NPOIN2),Y(NPOIN2),TETA(*)
      DOUBLE PRECISION XCONV(NPOI2L,NPLAN),YCONV(NPOI2L,NPLAN)
      DOUBLE PRECISION ZCONV(NPOI2L,NPLAN)
      DOUBLE PRECISION SHP1(NPOI2L,NPLAN),SHP2(NPOI2L,NPLAN)
      DOUBLE PRECISION SHP3(NPOI2L,NPLAN),SHZ(NPOI2L,NPLAN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
!V6P1 New arguments
      INTERFACE
        SUBROUTINE INITAB
     & (IBOR1 , IFABOR1 , NELEM2_DIM , PART)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER NELEM2_DIM
      INTEGER IBOR1(NELEM2_DIM,7),IFABOR1(NELEM2_DIM,3)
      INTEGER,           INTENT(IN)      :: PART
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE INTANG
     &( LAVANT, LAPRES, IPLAN , NPLAN , DELTAD)
      IMPLICIT NONE
      INTEGER  LAVANT, LAPRES, NPLAN , IPLAN
      DOUBLE PRECISION DELTAD
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE INTER4D
     & ( F , B , SHP1 , SHP2 , SHP3 , SHZ , SHF , ELT , ETA , FRE ,
     &   IKLE2 , ETAP1, NPOIN2 , NELEM2 , NPLAN , NF , TRA01)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER NPOIN2 , NELEM2 , NPLAN , NF
      INTEGER IKLE2(NELEM2,3),ELT(NPOIN2,NPLAN,NF),ETA(NPOIN2,NPLAN,NF)
      INTEGER ETAP1(NPLAN),FRE(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF)   ,B(NPOIN2,NF)
      DOUBLE PRECISION SHP1(NPOIN2,NPLAN,NF),SHP2(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION SHP3(NPOIN2,NPLAN,NF),SHZ(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION SHF(NPOIN2,NPLAN,NF) ,TRA01(NPOIN2,NPLAN,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE INTERP_TOMAWAC
     & ( F , B , SHP1 , SHP2 , SHP3 , SHZ , ELT , ETA , IKLE2,
     &   ETAP1, NPOIN2 , NELEM2 , NPLAN , TRA01)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER NELEM2,NPOIN2,NPLAN
      INTEGER IKLE2(NELEM2,3),ELT(NPOIN2,NPLAN),ETA(NPOIN2,NPLAN)
      INTEGER ETAP1(NPLAN)
      DOUBLE PRECISION F(NPOIN2,NPLAN),B(NPOIN2)
      DOUBLE PRECISION SHP1(NPOIN2,NPLAN),SHP2(NPOIN2,NPLAN)
      DOUBLE PRECISION SHP3(NPOIN2,NPLAN),SHZ(NPOIN2,NPLAN)
      DOUBLE PRECISION TRA01(NPOIN2,NPLAN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        FUNCTION KERBOU
     &( XK1   , XK2   , FREQ1  , FREQ2  , DEPTH , TETA1 , TETA2 )
      IMPLICIT NONE
      DOUBLE PRECISION KERBOU
      DOUBLE PRECISION  XK1, XK2, FREQ1, FREQ2 , DEPTH, TETA1 , TETA2
        END FUNCTION
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE KMOYEN
     &( XKMOY , XK    , F     , FREQ  , DFREQ , TAILF , NF    , NPLAN ,
     &  NPOIN2, AUX1  , AUX2  , AUX3  )
      IMPLICIT NONE
      INTEGER  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION TAILF
      DOUBLE PRECISION XKMOY(NPOIN2), XK(NPOIN2,NF),F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION FREQ(NF)  , DFREQ(NF)
      DOUBLE PRECISION AUX1(NPOIN2) , AUX2(NPOIN2) , AUX3(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE LECDOI
     &( UD , VD  , X  , Y  , NPOIN2, NDON , BINDON, NBOR , NPTFR,
     &  AT , DDC , TV1, TV2, NP   , XRELV, YRELV , UR   , VR   ,
     &  TRA, U1  , V1 , U2 , V2   , INDIC, NPMAX , CHDON, NVAR )
      IMPLICIT NONE
      INTEGER NPOIN2,NDON,NPTFR,NP,INDIC,NPMAX,NVAR
      INTEGER NBOR(NPTFR,2)
      DOUBLE PRECISION X(NPOIN2)    , Y(NPOIN2)
      DOUBLE PRECISION UD(NPOIN2)   , VD(NPOIN2)
      DOUBLE PRECISION XRELV(NPMAX) , YRELV(NPMAX)
      DOUBLE PRECISION UR(NPMAX)    , VR(NPMAX), TRA(NPMAX)
      DOUBLE PRECISION U1(NPOIN2)   , V1(NPOIN2)
      DOUBLE PRECISION U2(NPOIN2)   , V2(NPOIN2)
      DOUBLE PRECISION AT,DDC,TV1,TV2
      CHARACTER*3  BINDON
      CHARACTER*7  CHDON
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE LECDON
     &( U , V , X, Y, NPOIN2, NDON, BINDON, NBOR, NPTFR, XRELV, YRELV,
     &  UR, VR, TRA01,TRA02,TRA03,IDTEL,NPTT,DONTEL,COURAN,INDIC,NPMAX,
     &  CHDON)
      IMPLICIT NONE
      INTEGER NPOIN2, NDON,NPTFR,IDTEL,NPTT,INDIC,NPMAX
      INTEGER NBOR(NPTFR,2)
      DOUBLE PRECISION X(NPOIN2),Y(NPOIN2),U(NPOIN2),V(NPOIN2)
      DOUBLE PRECISION TRA01(NPMAX),TRA02(NPMAX),TRA03(NPOIN2)
      DOUBLE PRECISION XRELV(NPMAX),YRELV(NPMAX),UR(NPMAX),VR(NPMAX)
      LOGICAL DONTEL,COURAN
      CHARACTER*3  BINDON
      CHARACTER*7  CHDON
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE LECDON_TOMAWAC(FILE_DESC,PATH,NCAR,CODE)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, PARAMETER :: NMAX = 300
      CHARACTER(LEN=24), INTENT(IN)     :: CODE
      CHARACTER(LEN=144), INTENT(INOUT) :: FILE_DESC(4,NMAX)
      INTEGER, INTENT(IN)               :: NCAR
      CHARACTER(LEN=250), INTENT(IN)    :: PATH
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE LECHAM
     &( ZM , DZHDT, X    , Y     , NPOIN2, NDON , BINDON, NBOR  , NPTFR,
     &  AT , DDC  , TM1  , TM2   , NP   , XRELV , YRELV , ZR   ,
     &  Z1 , Z2   , INDIM, NPMAX , IDHMA, NVAR  )
      IMPLICIT NONE
      INTEGER NPOIN2, NDON ,NPTFR,NP,INDIM,NPMAX,IDHMA,NVAR
      INTEGER NBOR(NPTFR,2)
      DOUBLE PRECISION X(NPOIN2)    , Y(NPOIN2)
      DOUBLE PRECISION ZM(NPOIN2)   , DZHDT(NPOIN2)
      DOUBLE PRECISION XRELV(NPMAX) , YRELV(NPMAX)
      DOUBLE PRECISION ZR(NPMAX)    , Z1(NPMAX)   , Z2(NPMAX)
      DOUBLE PRECISION AT , DDC  , TM1  , TM2
      CHARACTER*3  BINDON
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE LECLIM_TOMAWAC
     &(LIHBOR, HBOR , NPTFR, NBOR  , STDGEO, NLIM,
     & ISEG  , XSEG , YSEG , NACHB , MESH,BOUNDARY_COLOUR)
      USE BIEF_DEF
      IMPLICIT NONE
      TYPE(BIEF_MESH) :: MESH
      INTEGER NPTFR,STDGEO,NLIM
      INTEGER LIHBOR(NPTFR),NBOR(NPTFR),ISEG(NPTFR)
      INTEGER NACHB(NBMAXNSHARE*NPTIR),BOUNDARY_COLOUR(NPTFR)
      DOUBLE PRECISION HBOR(NPTFR),XSEG(NPTFR),YSEG(NPTFR)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE LECSUI
     &(F,NPLAN,NF,TETA,FREQ,NELEM2,NPOIN2,AT,UC,VC,UC1,VC1,UC2,VC2,
     & UV,VV,UV1,VV1,UV2,VV2,VENT,TV1,TV2,COURAN,NPRE,BINPRE,
     & DEPTH,TC1,TC2,ZM1,ZM2,DZHDT,TM1,TM2,MAREE)
      IMPLICIT NONE
      INTEGER NPLAN,NF,NELEM2,NPOIN2,NPRE
      DOUBLE PRECISION AT,TV1,TV2,TC1,TC2,TM1,TM2
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF),TETA(NPLAN+1),FREQ(NF)
      DOUBLE PRECISION UC(NPOIN2),VC(NPOIN2),UV(NPOIN2),VV(NPOIN2)
      DOUBLE PRECISION UV1(NPOIN2),VV1(NPOIN2),UV2(NPOIN2),VV2(NPOIN2)
      DOUBLE PRECISION UC1(NPOIN2),VC1(NPOIN2),UC2(NPOIN2),VC2(NPOIN2)
      DOUBLE PRECISION DEPTH(NPOIN2),ZM1(NPOIN2),ZM2(NPOIN2)
      DOUBLE PRECISION DZHDT(NPOIN2)
      LOGICAL COURAN,VENT,MAREE
      CHARACTER*3 BINPRE
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE LECUTI
     &(X,Y,NPOIN,NCOU,XRELV,YRELV,UR,VR,TRA01,NP,NPMAX)
      IMPLICIT NONE
      INTEGER NPOIN,NCOU,NP,NPMAX
      DOUBLE PRECISION X(NPOIN),Y(NPOIN)
      DOUBLE PRECISION XRELV(NPMAX),YRELV(NPMAX),UR(NPMAX),VR(NPMAX)
      DOUBLE PRECISION TRA01(NPMAX)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE LIMWAC
     &(F     , FBOR  , LIFBOR, NPTFR , NPLAN , NF    ,  TETA , FREQ  ,
     & NPOIN2, NBOR  , AT    , LT    , DDC   , LIMSPE, FPMAXL, FETCHL,
     & SIGMAL, SIGMBL, GAMMAL, FPICL , HM0L  , APHILL, TETA1L, SPRE1L,
     & TETA2L, SPRE2L, XLAMDL, X ,Y  , KENT  , KSORT , NFO1  , NBI1  ,
     & BINBI1, UV    , VV    , SPEULI, VENT  , VENSTA, GRAVIT, DEUPI ,
     & PRIVE , NPRIV , SPEC  , FRA   , DEPTH , FRABL ,BOUNDARY_COLOUR)
      IMPLICIT NONE
      INTEGER NPTFR,NPLAN,NF,NPOIN2,LT,NPRIV,LIMSPE,KENT,KSORT,FRABL
      INTEGER NFO1,NBI1
      INTEGER LIFBOR(NPTFR),NBOR(NPTFR)
      INTEGER, INTENT(IN) :: BOUNDARY_COLOUR(NPTFR)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF),FBOR(NPTFR,NPLAN,NF)
      DOUBLE PRECISION TETA(NPLAN),FREQ(NF),X(NPOIN2),Y(NPOIN2)
      DOUBLE PRECISION UV(NPOIN2),VV(NPOIN2), SPEC(NF), FRA(NPLAN)
      DOUBLE PRECISION PRIVE(NPOIN2,NPRIV),DEPTH(NPOIN2)
      DOUBLE PRECISION AT,DDC,FPMAXL,FETCHL,SIGMAL, SIGMBL, GAMMAL,FPICL
      DOUBLE PRECISION HM0L  , APHILL,TETA1L,SPRE1L,TETA2L,SPRE2L,XLAMDL
      DOUBLE PRECISION GRAVIT,DEUPI
      LOGICAL SPEULI, VENT, VENSTA
      CHARACTER*3 BINBI1
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE MARUTI
     &(X,Y,NPOIN,NMAR, BINMAR,NBOR,NPTFR,AT,DDC,TV1,TV2,
     & NP,XRELV,YRELV,ZR,Z1,Z2,NPMAX)
      IMPLICIT NONE
      INTEGER NPOIN,NMAR, NPTFR,NP,NPMAX
      INTEGER NBOR(NPTFR,2)
      DOUBLE PRECISION X(NPOIN),Y(NPOIN)
      DOUBLE PRECISION XRELV(NPMAX),YRELV(NPMAX), ZR(NPMAX)
      DOUBLE PRECISION Z1(NPMAX),Z2(NPMAX)
      DOUBLE PRECISION AT,DDC,TV1,TV2
      CHARACTER*3 BINMAR
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE NOMVAR_TOMAWAC
     &(TEXTE,TEXTPR,MNEMO,MAXVAR)
      IMPLICIT NONE
      INTEGER      MAXVAR
      CHARACTER*32 TEXTE(MAXVAR),TEXTPR(MAXVAR)
      CHARACTER*8  MNEMO(MAXVAR)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE NOUDON
     &(UV , VV , X  , Y  , NPOIN, NDON , BINDON, NBOR, NPTFR,
     & AT , DDC, TV1, TV2, NP   , XRELV, YRELV , UR  , VR   ,
     & TRA, U1 , V1 , U2 , V2   , INDIC, CHDON , NVAR)
      IMPLICIT NONE
      INTEGER NPOIN,NDON,NPTFR,NP,INDIC,NVAR
      INTEGER NBOR(NPTFR,2)
      DOUBLE PRECISION UV(NPOIN),VV(NPOIN),X(NPOIN),Y(NPOIN)
      DOUBLE PRECISION XRELV(NP),YRELV(NP),UR(NP),VR(NP),TRA(NP)
      DOUBLE PRECISION U1(NPOIN),V1(NPOIN),U2(NPOIN),V2(NPOIN)
      DOUBLE PRECISION AT,DDC,TV1,TV2
      CHARACTER*3 BINDON
      CHARACTER*7 CHDON
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE NOUMAR
     &(ZM , DZHDT, X  , Y  , NPOIN2, NDON , BINDON, NBOR , NPTFR,
     & AT , DDC  , TM1, TM2, NP    , XRELV, YRELV , ZR   , TRA  ,
     & Z1 , Z2   , INDIM, IDHMA , NVHMA )
      IMPLICIT NONE
      INTEGER NPOIN2,NDON,NPTFR,NP,INDIM,IDHMA,NVHMA
      INTEGER NBOR(NPTFR,2)
      DOUBLE PRECISION ZM(NPOIN2),DZHDT(NPOIN2),X(NPOIN2) ,Y(NPOIN2)
      DOUBLE PRECISION XRELV(NP),YRELV(NP),ZR(NP),TRA(NP)
      DOUBLE PRECISION Z1(NPOIN2),Z2(NPOIN2)
      DOUBLE PRECISION AT,DDC,TM1,TM2
      CHARACTER*3 BINDON
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE P_READ2(BUFFER,NBYTES,SOURCE,TYPE)
      IMPLICIT NONE
      INTEGER NBYTES, SOURCE, TYPE
      INTEGER BUFFER(*)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE P_WRIT2(BUFFER, NBYTES, DEST, TYPE)
      IMPLICIT NONE
      INTEGER NBYTES,DEST,TYPE
      INTEGER BUFFER(*)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PIED4D
     &  (U , V , T , W , DT , NRK , X , Y , TETA , FREQ , IKLE2 ,
     &   IFABOR , ETAS , XPLOT , YPLOT , TPLOT , FPLOT , DX , DY , DW ,
     &   DF , SHP1 , SHP2 , SHP3 , SHT , SHF , ELT , ETA , FRE , NSP ,
     &   NPLOT , NPOIN2 , NELEM2 , NPLAN , NF , SURDET , SENS ,
     &   ISO )
      IMPLICIT NONE
      INTEGER NRK,NPLOT,NPOIN2,NELEM2,NPLAN,NF,SENS
      INTEGER IKLE2(NELEM2,3),IFABOR(NELEM2,7),ETAS(NPLAN)
      INTEGER ELT(NPLOT),ETA(NPLOT),FRE(NPLOT),NSP(NPLOT),ISO(NPLOT)
      DOUBLE PRECISION DT
      DOUBLE PRECISION U(NPOIN2,NPLAN,NF),V(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION T(NPOIN2,NPLAN,NF),W(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION XPLOT(NPLOT),YPLOT(NPLOT)
      DOUBLE PRECISION TPLOT(NPLOT),FPLOT(NPLOT)
      DOUBLE PRECISION SURDET(NELEM2),SHT(NPLOT),SHF(NPLOT)
      DOUBLE PRECISION SHP1(NPLOT),SHP2(NPLOT),SHP3(NPLOT)
      DOUBLE PRECISION X(NPOIN2),Y(NPOIN2),TETA(NPLAN+1),FREQ(NF)
      DOUBLE PRECISION DX(NPLOT),DY(NPLOT),DW(NPLOT),DF(NPLOT)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PIEDS
     &  (U , V , W , DT , NRK , X , Y , TETA , IKLE2 , IFABOR , ETAS ,
     &   XPLOT , YPLOT , ZPLOT , DX , DY , DZ , SHP1 , SHP2 , SHP3 ,
     &   SHZ , ELT , ETA , NSP , NPLOT , NPOIN2 , NELEM2 , NPLAN ,
     &   IFF , SURDET , SENS , ISO )
      IMPLICIT NONE
      INTEGER NRK,NPLOT,NPOIN2,NELEM2,NPLAN,SENS,IFF
      INTEGER IKLE2(NELEM2,3),IFABOR(NELEM2,5),ETAS(NPLAN)
      INTEGER ELT(NPLOT),ETA(NPLOT),NSP(NPLOT),ISO(NPLOT)
      DOUBLE PRECISION DT
      DOUBLE PRECISION U(NPOIN2,NPLAN),V(NPOIN2,NPLAN)
      DOUBLE PRECISION W(NPOIN2,NPLAN)
      DOUBLE PRECISION XPLOT(NPLOT),YPLOT(NPLOT),ZPLOT(NPLOT)
      DOUBLE PRECISION SURDET(NELEM2),SHZ(NPLOT)
      DOUBLE PRECISION SHP1(NPLOT),SHP2(NPLOT),SHP3(NPLOT)
      DOUBLE PRECISION X(NPOIN2),Y(NPOIN2),TETA(NPLAN+1)
      DOUBLE PRECISION DX(NPLOT),DY(NPLOT),DZ(NPLOT)
         END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PIED_MPI
     &(CX,CY,CT,DT,NRK,X,Y,TETA,IKLE2,IFABOR,ETAP1,
     & TRA01,SHP1,SHP2,SHP3,SHZ,JF,ELT,ETA,ITR01,
     & GOODELT,NPLAN,NPOIN2,NPOIN3,NF,NELEM2,MESH)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER NRK,JF,NPLAN,NPOIN2,NPOIN3,NF,NELEM2
      INTEGER IKLE2(NELEM2,3),IFABOR(NELEM2,7),ETAP1(NPLAN)
      INTEGER ELT(NPOIN3,NF),ETA(NPOIN3,NF),ITR01(NPOIN3,3)
      INTEGER GOODELT(NPOIN2,NPLAN)
      DOUBLE PRECISION DT,CX(NPOIN3,NF),CY(NPOIN3,NF),CT(NPOIN3,NF)
      DOUBLE PRECISION SHP1(NPOIN3,NF),SHP2(NPOIN3,NF),SHP3(NPOIN3,NF)
      DOUBLE PRECISION SHZ(NPOIN3,NF)
      DOUBLE PRECISION X(NPOIN2),Y(NPOIN2),TETA(NPLAN)
      DOUBLE PRECISION TRA01(NPOIN3,8)
      TYPE(BIEF_MESH)  ::  MESH
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PRELEO_MPI
     &(XLEO,YLEO,NLEO,X,Y,IKLE,SURDET,NPOIN2,NELEM2,NOLEO,ISLEO)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER NLEO,NPOIN2,NELEM2
      INTEGER IKLE(NELEM2,3),NOLEO(NLEO)
      DOUBLE PRECISION X(NPOIN2),Y(NPOIN2),XLEO(NLEO),YLEO(NLEO)
      DOUBLE PRECISION SURDET(NELEM2)
      LOGICAL ISLEO(NLEO)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PRELEO
     &(XLEO,YLEO,NLEO,X,Y,NPOIN2,NOLEO)
      IMPLICIT NONE
      INTEGER NLEO,NPOIN2
      INTEGER NOLEO(NLEO)
      DOUBLE PRECISION X(NPOIN2),Y(NPOIN2),XLEO(NLEO),YLEO(NLEO)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PRENL1
     &( IANGNL, COEFNL, NPLAN , NF    , RAISF , XLAMD )
      IMPLICIT NONE
      INTEGER  NPLAN , NF
      INTEGER  IANGNL(NPLAN,8)
      DOUBLE PRECISION COEFNL(16)
      DOUBLE PRECISION RAISF , XLAMD
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
! 
!V6P1 New subroutine
      INTERFACE
        SUBROUTINE PRENL2
     &( IANGNL, COEFNL, NPLAN , NF    , RAISF , XLAMD , XMU   )
      IMPLICIT NONE
      INTEGER  NPLAN , NF
      INTEGER  IANGNL(NPLAN,16)
      DOUBLE PRECISION RAISF , XLAMD , XMU
      DOUBLE PRECISION COEFNL(32)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
! 
!V6P1 New subroutine
      INTERFACE
        SUBROUTINE PRENL3
     &( NF    , NT    , RAISF , TAILF , FREQ  , TB_SCA, LBUF  , DIMBUF,
     &  F_POIN, F_COEF, T_POIN, F_PROJ, IQ_OM1, NQ_TE1, NQ_OM2, NF1   ,
     &  NT1   , K_IF1 , K_IF2 , K_IF3 , TB_V14, TB_V24, TB_V34, K_1P  , 
     &  K_1M  , K_1P2P, K_1P3M, K_1P2M, K_1P3P, K_1M2P, K_1M3M, K_1M2M,
     &  K_1M3P, TB_TPM, TB_TMP, TB_FAC, SEUIL1, SEUIL2, ELIM  , NCONF ,
     &  NCONFM, IDCONF)
      IMPLICIT NONE
      INTEGER           NF    , NT
      DOUBLE PRECISION  RAISF , TAILF , FREQ(NF)
      INTEGER           LBUF  , DIMBUF
      INTEGER           F_POIN(DIMBUF), T_POIN(DIMBUF)
      DOUBLE PRECISION  F_COEF(DIMBUF), F_PROJ(DIMBUF), TB_SCA(DIMBUF)
      INTEGER           IQ_OM1 , NQ_TE1, NQ_OM2
      INTEGER           NF1   , NT1
      INTEGER           K_IF1(NF1), K_1P(NT1,NF1), K_1M(NT1,NF1)
      DOUBLE PRECISION  TB_V14(NF1)
      INTEGER           K_IF2 (NQ_OM2,NT1,NF1), K_IF3 (NQ_OM2,NT1,NF1)
      INTEGER           K_1P2P(NQ_OM2,NT1,NF1), K_1P3M(NQ_OM2,NT1,NF1)
      INTEGER           K_1P2M(NQ_OM2,NT1,NF1), K_1P3P(NQ_OM2,NT1,NF1)
      INTEGER           K_1M2P(NQ_OM2,NT1,NF1), K_1M3M(NQ_OM2,NT1,NF1)
      INTEGER           K_1M2M(NQ_OM2,NT1,NF1), K_1M3P(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION  TB_V24(NQ_OM2,NT1,NF1), TB_V34(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION  TB_TPM(NQ_OM2,NT1,NF1), TB_TMP(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION  TB_FAC(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION  SEUIL1, SEUIL2, ELIM
      INTEGER           NCONF , NCONFM, IDCONF(NCONFM,3)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PREPRO
     &( CX    , CY    , CT    , CF    , DT    , NRK   , X     , Y     ,
     &  TETA  , COSTET, SINTET, FREQ  , IKLE2 , IFABOR, ETAP1 , TRA01 ,
     &  SHP1  , SHP2  , SHP3  , SHZ   , SHF   , ELT   , ETA   , FRE   ,
     &  DEPTH , DZHDT , DZX   , DZY   , U     , V     , DUX   , DUY   ,
     &  DVX   , DVY   , XK    , CG    , COSF  , TGF   , ITR01 , NPOIN3,
     &  NPOIN2, NELEM2, NPLAN , NF    , SURDET, COURAN, SPHE  , PROINF,
     &  PROMIN, MESH)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER NRK,NPOIN3,NPOIN2,NELEM2,NPLAN,NF
      INTEGER IKLE2(NELEM2,3),IFABOR(NELEM2,7),ETAP1(NPLAN)
      INTEGER ITR01(NPOIN3,3),ELT(NPOIN3,NF),ETA(NPOIN3,NF)
      INTEGER FRE(NPOIN3,NF)
      DOUBLE PRECISION DT,PROMIN
      DOUBLE PRECISION CX(NPOIN3,NF),CY(NPOIN3,NF),CT(NPOIN3,NF)
      DOUBLE PRECISION CF(NPOIN3,NF),X(NPOIN2),Y(NPOIN2)
      DOUBLE PRECISION TETA(NPLAN),COSTET(NPLAN),SINTET(NPLAN)
      DOUBLE PRECISION FREQ(NF),SHP1(NPOIN3,NF),SHP2(NPOIN3,NF)
      DOUBLE PRECISION SHP3(NPOIN3,NF),SHZ(NPOIN3,NF),SHF(NPOIN3,NF)
      DOUBLE PRECISION DZHDT(NPOIN2),XK(NPOIN2,NF),CG(NPOIN2,NF)
      DOUBLE PRECISION COSF(NPOIN2),TGF(NPOIN2),SURDET(NELEM2)
      DOUBLE PRECISION DEPTH(NPOIN2),DZX(NPOIN2),DZY(NPOIN2)
      DOUBLE PRECISION U(NPOIN2),V(NPOIN2),DUX(NPOIN2),DUY(NPOIN2)
      DOUBLE PRECISION DVX(NPOIN2),DVY(NPOIN2),TRA01(NPOIN3,8)
      LOGICAL COURAN,SPHE,PROINF
      TYPE(BIEF_MESH)  ::  MESH
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PREQT2
     &( TETA  , NPLAN , BDISPB, BDSSPB, NBD , INDI )
      IMPLICIT NONE
      INTEGER           NPLAN,NBD
      INTEGER           INDI(NPLAN)
      DOUBLE PRECISION  BDISPB , BDSSPB
      DOUBLE PRECISION  TETA(NPLAN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PROPA
     &   (F,B,SHP1,SHP2,SHP3,SHZ,SHF,ELT,ETA,FRE,IKLE2,ETAP1,
     &    NPOIN3,NPOIN2,NELEM2,NPLAN,NF,COURAN,TRA01,TRA02)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER NPOIN3,NPOIN2,NELEM2,NPLAN,NF
      INTEGER ELT(NPOIN3,NF),ETA(NPOIN3,NF),FRE(NPOIN3,NF)
      INTEGER IKLE2(NELEM2,3),ETAP1(NPLAN)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION SHP1(NPOIN3,NF) , SHP2(NPOIN3,NF)
      DOUBLE PRECISION SHP3(NPOIN3,NF) , SHZ(NPOIN3,NF)
      DOUBLE PRECISION SHF(NPOIN3,NF),B(NPOIN2,NF)
      DOUBLE PRECISION TRA01(NPOIN3,8),TRA02(NPOIN2,NPLAN,NF)
      LOGICAL COURAN
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        FUNCTION QBBJ78
     &( B     , IQBBJ )
      IMPLICIT NONE
      DOUBLE PRECISION QBBJ78, B
      INTEGER  IQBBJ
        END FUNCTION
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QBREK1
     &( TSTOT , TSDER , F     , FCAR  , VARIAN, DEPTH , ALFABJ, GAMBJ1,
     &  GAMBJ2, IQBBJ , IHMBJ , NF    , NPLAN , NPOIN2, BETA  )
      IMPLICIT NONE
      INTEGER IQBBJ,IHMBJ,NF,NPLAN,NPOIN2
      DOUBLE PRECISION ALFABJ,GAMBJ1,GAMBJ2
      DOUBLE PRECISION TSTOT(NPOIN2,NPLAN,NF), TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF), VARIAN(NPOIN2),FCAR(NPOIN2)
      DOUBLE PRECISION DEPTH(NPOIN2), BETA(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QBREK2
     &( TSTOT , TSDER , F     , FCAR  , VARIAN, DEPTH , BORETG, GAMATG,
     &  IWHTG , NF    , NPLAN , NPOIN2, BETA  )
      IMPLICIT NONE
      INTEGER  NF    , NPLAN , NPOIN2, IWHTG
      DOUBLE PRECISION BORETG, GAMATG
      DOUBLE PRECISION DEPTH(NPOIN2), BETA(NPOIN2), FCAR(NPOIN2)
      DOUBLE PRECISION TSTOT(NPOIN2,NPLAN,NF), TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION     F(NPOIN2,NPLAN,NF), VARIAN(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QBREK3
     &( TSTOT , TSDER , F     , FCAR  , VARIAN, DEPTH , ALFARO, GAMARO,
     &  GAM2RO, IEXPRO, IDISRO, NF    , NPLAN , NPOIN2, BETA  )
      IMPLICIT NONE
      INTEGER IEXPRO, IDISRO, NF    , NPLAN , NPOIN2
      DOUBLE PRECISION ALFARO, GAMARO, GAM2RO
      DOUBLE PRECISION DEPTH(NPOIN2), BETA(NPOIN2), FCAR(NPOIN2)
      DOUBLE PRECISION TSTOT(NPOIN2,NPLAN,NF), TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF), VARIAN(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QBREK4
     &( TSTOT , TSDER , F     , FCAR  , VARIAN, DEPTH , BETAIH, EM2SIH,
     &  GRAVIT, NF    , NPLAN , NPOIN2, BETA  )
      IMPLICIT NONE
      INTEGER          NF    , NPLAN , NPOIN2
      DOUBLE PRECISION BETAIH, EM2SIH, GRAVIT
      DOUBLE PRECISION DEPTH(NPOIN2), BETA(NPOIN2), FCAR(NPOIN2)
      DOUBLE PRECISION TSTOT(NPOIN2,NPLAN,NF), TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF), VARIAN(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QFROT1
     &( TSTOT , TSDER , F     , XK    , DEPTH , CFROT1, GRAVIT, NF    ,
     &  NPLAN , NPOIN2, BETA  )
      IMPLICIT NONE
      INTEGER  NF , NPLAN , NPOIN2
      DOUBLE PRECISION CFROT1, GRAVIT
      DOUBLE PRECISION DEPTH(NPOIN2), BETA(NPOIN2)
      DOUBLE PRECISION TSTOT(NPOIN2,NPLAN,NF), TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF),    XK(NPOIN2,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        FUNCTION QGAUSS
     &( B     , N     , A     , XM    )
      IMPLICIT NONE
      INTEGER  N
      DOUBLE PRECISION QGAUSS
      DOUBLE PRECISION B , A , XM
        END FUNCTION
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QMOUT1
     &( TSTOT , TSDER , F     , XK    , ENRJ  , FREQ  , FMOY  , XKMOY ,
     &  PROINF, CMOUT1, CMOUT2, GRAVIT, NF    , NPLAN , NPOIN2, TAUX1 ,
     &  BETA  )
      IMPLICIT NONE
      INTEGER  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION CMOUT1, CMOUT2, GRAVIT
      DOUBLE PRECISION XKMOY(NPOIN2), ENRJ(NPOIN2) ,  BETA(NPOIN2)
      DOUBLE PRECISION      FREQ(NF), FMOY(NPOIN2) , TAUX1(NPOIN2)
      DOUBLE PRECISION TSTOT(NPOIN2,NPLAN,NF), TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION     F(NPOIN2,NPLAN,NF),    XK(NPOIN2,NF)
      LOGICAL PROINF
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
! 
!V6P1 New subroutine
      INTERFACE
        SUBROUTINE QMOUT2
     &( TSTOT , TSDER , F     , XK    , ENRJ  , FREQ  , FMOY  , XKMOY , 
     &  USOLD , USNEW , DEPTH , PROINF, CMOUT3, CMOUT4, CMOUT5, CMOUT6,
     &  GRAVIT, NF    , NPLAN , NPOIN2, CIMPLI, TAUX1 , BETA  , BETAO ,
     &  BETAN , BETOTO, BETOTN)
      IMPLICIT NONE
      INTEGER   NF  , NPLAN , NPOIN2
      DOUBLE PRECISION CMOUT3, CMOUT4, GRAVIT
      DOUBLE PRECISION CMOUT5, CMOUT6, CIMPLI
      DOUBLE PRECISION USNEW (NPOIN2), USOLD (NPOIN2)
      DOUBLE PRECISION FREQ  (NF)    , DEPTH (NPOIN2), FMOY(NPOIN2) 
      DOUBLE PRECISION ENRJ  (NPOIN2), XKMOY (NPOIN2)
      DOUBLE PRECISION BETAN (NPOIN2), BETAO (NPOIN2)
      DOUBLE PRECISION BETA  (NPOIN2), TAUX1 (NPOIN2)
      DOUBLE PRECISION BETOTO(NPOIN2), BETOTN(NPOIN2)
      DOUBLE PRECISION TSTOT (NPOIN2,NPLAN,NF), TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION F     (NPOIN2,NPLAN,NF), XK   (NPOIN2,NF)
      LOGICAL PROINF
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QNLIN1
     &( TSTOT , TSDER , IANGNL, COEFNL, NF    , NPLAN , F1    , RAISF ,
     &  TAILF , PROINF, NPOIN2, F     , DEPTH , XKMOY , TAUX1 , TAUX2 ,
     &  TAUX3 , TAUX4 , TAUX5 , DFINI )
      IMPLICIT NONE
      INTEGER  NF, NPLAN , NPOIN2
      INTEGER  IANGNL(NPLAN,8)
      DOUBLE PRECISION F1  , RAISF , TAILF
      DOUBLE PRECISION COEFNL(16), F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION TSTOT(NPOIN2,NPLAN,NF), TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION TAUX1(NPOIN2), TAUX2(NPOIN2), TAUX3(NPOIN2)
      DOUBLE PRECISION TAUX4(NPOIN2), TAUX5(NPOIN2), XKMOY(NPOIN2)
      DOUBLE PRECISION DFINI(NPOIN2), DEPTH(NPOIN2)
      LOGICAL  PROINF
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
! 
!V6P1 New subroutine
      INTERFACE
        SUBROUTINE QNLIN2
     &( TSTOT , TSDER , IANGNL, COEFNL, NF    , NPLAN , F1    , RAISF ,
     &  TAILF , PROINF, NPOIN2, F     , DEPTH , XKMOY , TAUX1 , DFINI ,
     &  XCOEF )
      IMPLICIT NONE
      INTEGER  NPOIN2, NPLAN , NF
      INTEGER  IANGNL(NPLAN,16)
      DOUBLE PRECISION F1  , RAISF , TAILF
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF), COEFNL(32), XCOEF
      DOUBLE PRECISION TSTOT(NPOIN2,NPLAN,NF), TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION TAUX1(NPOIN2), DFINI(NPOIN2), DEPTH(NPOIN2)
      DOUBLE PRECISION XKMOY(NPOIN2)
      LOGICAL  PROINF
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
! 
!V6P1 New subroutine
      INTERFACE
        SUBROUTINE QNLIN3
     &( TSTOT , TSDER , F     , NB_NOD, FREQ  , TETA  , NT    , NF    ,
     &  RAISF , TAILF , SEUIL , FSEUIL, LBUF  , DIMBUF, F_POIN, F_COEF,
     &  F_PROJ, T_POIN, TB_SCA, NQ_TE1, NQ_OM2, NF1   , NT1   , DFREQ ,
     &  K_IF1 , K_IF2 , K_IF3 , TB_V14, TB_V24, TB_V34, K_1P  , K_1M  ,
     &  K_1P2P, K_1P3M, K_1P2M, K_1P3P, K_1M2P, K_1M3M, K_1M2M, K_1M3P,
     &  TB_TPM, TB_TMP, TB_FAC, NCONF , NCONFM, IDCONF)
      IMPLICIT NONE
      INTEGER           NF    , NT    , NB_NOD
      DOUBLE PRECISION  TAILF , RAISF , SEUIL
      DOUBLE PRECISION  FREQ(NF), DFREQ(NF), TETA(NT), FSEUIL(NB_NOD)
      DOUBLE PRECISION  F(NB_NOD,NT,NF), TSTOT(NB_NOD,NT,NF)
      DOUBLE PRECISION  TSDER(NB_NOD,NT,NF)
      INTEGER           LBUF  , DIMBUF
      INTEGER           F_POIN(DIMBUF), T_POIN(DIMBUF)
      DOUBLE PRECISION  F_COEF(DIMBUF), F_PROJ(DIMBUF), TB_SCA(DIMBUF)
      INTEGER           NQ_TE1, NQ_OM2, NF1   , NT1
      INTEGER           K_IF1(NF1), K_1P(NT1,NF1), K_1M(NT1,NF1)
      INTEGER           K_IF2 (NQ_OM2,NT1,NF1), K_IF3 (NQ_OM2,NT1,NF1)
      INTEGER           K_1P2P(NQ_OM2,NT1,NF1), K_1P3M(NQ_OM2,NT1,NF1)
      INTEGER           K_1P2M(NQ_OM2,NT1,NF1), K_1P3P(NQ_OM2,NT1,NF1)
      INTEGER           K_1M2P(NQ_OM2,NT1,NF1), K_1M3M(NQ_OM2,NT1,NF1)
      INTEGER           K_1M2M(NQ_OM2,NT1,NF1), K_1M3P(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION  TB_V14(NF1)           , TB_FAC(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION  TB_V24(NQ_OM2,NT1,NF1), TB_V34(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION  TB_TPM(NQ_OM2,NT1,NF1), TB_TMP(NQ_OM2,NT1,NF1)
      INTEGER           NCONF , NCONFM, IDCONF(NCONFM,3)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
       SUBROUTINE QTRIA1
     &( F     , XK    , FREQ  , DEPTH , RAISF , GRAVIT, ALFLTA, RFMLTA,
     &  NF    , NPLAN , NPOIN2, TSTOT , TSDER , FTOT  , FMOY  )
      IMPLICIT NONE
      INTEGER  NF, NPLAN, NPOIN2
      DOUBLE PRECISION  RAISF , GRAVIT, ALFLTA, RFMLTA
      DOUBLE PRECISION  F(NPOIN2,NPLAN,NF), XK(NPOIN2,NF)
      DOUBLE PRECISION  FREQ(NF), DEPTH(NPOIN2)
      DOUBLE PRECISION  TSTOT(NPOIN2,NPLAN,NF), TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION  FTOT(NPOIN2) , FMOY(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QTRIA2
     &( F     , XK    , FREQ  , DFREQ , DEPTH , TETA  , SINTET, COSTET ,
     &  KSPB  , BDISPB, BDSSPB, RAISF , GRAVIT, NF    , NPLAN , NPOIN2 ,
     &  NBD   , INDI  , TSTOT , TSDER )
      IMPLICIT NONE
      INTEGER  NF, NPLAN, NPOIN2, NBD
      INTEGER           INDI(NBD)
      DOUBLE PRECISION  BDISPB , BDSSPB, KSPB  , RAISF, GRAVIT
      DOUBLE PRECISION  F(NPOIN2,NPLAN,NF), XK(NPOIN2,NF)
      DOUBLE PRECISION  DFREQ(NF) , FREQ(NF), DEPTH(NPOIN2)
      DOUBLE PRECISION  TETA(NPLAN) , SINTET(NPLAN) , COSTET(NPLAN)
      DOUBLE PRECISION  TSTOT(NPOIN2,NPLAN,NF), TSDER(NPOIN2,NPLAN,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QWIND1
     &( TSTOT , TSDER , F     , XK    , FREQ  , USOLD , USNEW , TWOLD ,
     &  TWNEW , Z0OLD , Z0NEW , TETA  , ROAIR , ROEAU , BETAM , XKAPPA,
     &  DECAL , GRAVIT, NF    , NPLAN , NPOIN2, CIMPLI, TOLD  , TNEW  ,
     &  CPHAS , USN   , USO   , OMNEW , OMOLD , BETAN , BETAO )
      IMPLICIT NONE
      INTEGER  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION GRAVIT,ROAIR,ROEAU,BETAM,XKAPPA,DECAL,CIMPLI
      DOUBLE PRECISION TSTOT(NPOIN2,NPLAN,NF),TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF),XK(NPOIN2,NF),FREQ(NF)
      DOUBLE PRECISION USOLD(NPOIN2), USNEW(NPOIN2),TWOLD(NPOIN2)
      DOUBLE PRECISION TWNEW(NPOIN2),Z0OLD(NPOIN2),Z0NEW(NPOIN2)
      DOUBLE PRECISION TETA(NPLAN),TOLD(NPOIN2,NPLAN)
      DOUBLE PRECISION TNEW(NPOIN2,NPLAN), CPHAS(NPOIN2),USN(NPOIN2)
      DOUBLE PRECISION USO(NPOIN2), OMNEW(NPOIN2),OMOLD(NPOIN2)
      DOUBLE PRECISION BETAN(NPOIN2), BETAO(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QWIND2
     &( TSTOT , TSDER , F     , XK    , FREQ  , USOLD , USNEW , TWOLD ,
     &  TWNEW , TETA  , ROAIR , ROEAU , GRAVIT, NF    , NPLAN , NPOIN2,
     &  CIMPLI, CPHAS , USN   , USO   , BETAN , BETAO )
      IMPLICIT NONE
      INTEGER  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION GRAVIT, ROAIR , ROEAU , CIMPLI
      DOUBLE PRECISION  FREQ(NF)    , TETA(NPLAN)
      DOUBLE PRECISION TWOLD(NPOIN2), TWNEW(NPOIN2), USNEW(NPOIN2)
      DOUBLE PRECISION BETAO(NPOIN2), BETAN(NPOIN2), USOLD(NPOIN2)
      DOUBLE PRECISION CPHAS(NPOIN2),   USO(NPOIN2),   USN(NPOIN2)
      DOUBLE PRECISION TSTOT(NPOIN2,NPLAN,NF), TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION     F(NPOIN2,NPLAN,NF),    XK(NPOIN2,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
! 
!V6P1 New subroutine
      INTERFACE
        SUBROUTINE QWIND3
     &( TSTOT , TSDER , F     , XK    , FREQ  , USOLD , USNEW , TWOLD ,
     &  TWNEW , TETA  , GRAVIT, NF    , NPLAN , NPOIN2, CIMPLI, COEFWD,
     &  COEFWE, COEFWF, COEFWH, BETAN , BETAO , DIRN  , DIRO  )
      IMPLICIT NONE
      INTEGER    NF  , NPLAN        , NPOIN2
      DOUBLE PRECISION GRAVIT       , CIMPLI
      DOUBLE PRECISION FREQ(NF)     , TETA(NPLAN)
      DOUBLE PRECISION TWOLD(NPOIN2), TWNEW(NPOIN2), USNEW(NPOIN2)
      DOUBLE PRECISION BETAO(NPOIN2), BETAN(NPOIN2), USOLD(NPOIN2)
      DOUBLE PRECISION DIRO(NPOIN2) , DIRN(NPOIN2)
      DOUBLE PRECISION TSTOT(NPOIN2,NPLAN,NF), TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF)    , XK(NPOIN2,NF)
      DOUBLE PRECISION COEFWD , COEFWE , COEFWF , COEFWH
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
! 
!V6P1 New subroutine
      INTERFACE
        SUBROUTINE QWINDL
     &( TSTOT , FREQ  , USOLD , USNEW , TWOLD , TWNEW , TETA  , GRAVIT,
     &  NF    , NPLAN , NPOIN2, CIMPLI, USN   , USO   , ALPHAN, ALPHAO, 
     &  FPMO  , FPMN )
      IMPLICIT NONE
      INTEGER     NF ,  NPLAN         , NPOIN2
      DOUBLE PRECISION  GRAVIT        , CIMPLI
      DOUBLE PRECISION  FREQ(NF)      , TETA(NPLAN)
      DOUBLE PRECISION  FPMO(NPOIN2)  , FPMN(NPOIN2)
      DOUBLE PRECISION  TWOLD(NPOIN2) , TWNEW(NPOIN2) , USNEW(NPOIN2)
      DOUBLE PRECISION  ALPHAO(NPOIN2), ALPHAN(NPOIN2), USOLD(NPOIN2)
      DOUBLE PRECISION  USO(NPOIN2)   , USN(NPOIN2)
      DOUBLE PRECISION  TSTOT(NPOIN2,NPLAN,NF) 
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE RADIAT
     &( FX    , FY    , SXX   , SXY   , SYY   , XK1   , FS    , CG1   ,
     &  DEPTH1, CGSUC1, DSXXDX, DSXYDX, DSXYDY, DSYYDY, NPOIN2_DIM    )
      USE BIEF_DEF
      USE DECLARATIONS_TOMAWAC, ONLY : NPLAN,NF
      IMPLICIT NONE
      INTEGER NPOIN2_DIM
      DOUBLE PRECISION FS(NPOIN2_DIM,NPLAN,NF),CG1(NPOIN2_DIM,NF)
      DOUBLE PRECISION DEPTH1(NPOIN2_DIM), CGSUC1(NPOIN2_DIM,NF)
      DOUBLE PRECISION XK1(NPOIN2_DIM,NF)
      DOUBLE PRECISION DSXXDX(NPOIN2_DIM),DSXYDX(NPOIN2_DIM),
     &                 FX(NPOIN2_DIM)
      DOUBLE PRECISION DSXYDY(NPOIN2_DIM),DSYYDY(NPOIN2_DIM),
     &                 FY(NPOIN2_DIM)
      DOUBLE PRECISION SXX(NPOIN2_DIM),SXY(NPOIN2_DIM),SYY(NPOIN2_DIM)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
!V6P1 New arguments
      INTERFACE
        SUBROUTINE SEMIMP 
     &( F     ,XK    ,FREQ  ,DFREQ ,DEPTH ,VENTX ,VENTY ,X     ,Y     ,
     &  NVEB  ,NVEF  ,NBOR  ,NPTFR ,DDC   ,TV1   ,TV2   ,NP    ,XRELV ,
     &  YRELV ,U1    ,V1    ,U2    ,V2    ,TETA  ,SINTET,COSTET,INDIC ,
     &  TAILF ,RAISF ,GRAVIT,CFROT1,CMOUT1,CMOUT2,CMOUT3,CMOUT4,CMOUT5,
     &  CMOUT6,TPROP ,DTSI  ,ROAIR ,ROEAU ,XKAPPA,BETAM ,DECAL ,CDRAG ,
     &  ALPHA ,ZVENT ,NF    ,NPLAN ,NPOIN2,IANGNL,COEFNL,F1    ,NSITS ,
     &  SMOUT ,SFROT ,SVENT ,LVENT ,STRIF ,VENT  ,VENSTA,VX_CTE,VY_CTE,
     &  SBREK ,ALFABJ,GAMBJ1,GAMBJ2,IQBBJ ,IHMBJ ,IFRBJ ,BORETG,GAMATG, 
     &  IWHTG ,IFRTG ,ALFARO,GAMARO,GAM2RO,IDISRO,IEXPRO,IFRRO ,BETAIH,
     &  EM2SIH,IFRIH ,COEFHS,XDTBRK,NDTBRK,STRIA ,ALFLTA,RFMLTA,KSPB  ,
     &  BDISPB,BDSSPB,PROINF,DF_LIM,LIMIT ,CIMPLI,COEFWD,COEFWE,COEFWF,
     &  COEFWH,NOMVEB,NOMVEF,BINVEN,NBD   ,QINDI ,TAUWAV,USOLD ,TWOLD ,
     &  Z0OLD ,TSTOT ,TSDER ,TOLD  ,TNEW  ,VARIAN,FMOY  ,XKMOY ,USNEW ,
     &  Z0NEW ,TWNEW ,TAUX1 ,TAUX2 ,TAUX3 ,TAUX4 ,TAUX5 ,TAUX6 ,TAUX7 ,
     &  TRA01 ,BETA  ,NQ_TE1,NQ_OM2,NF1   ,NF2   ,NT1   ,NCONF ,NCONFM,
     &  SEUIL ,LBUF  ,DIMBUF,F_POIN,T_POIN,F_COEF,F_PROJ,TB_SCA,K_IF1 ,
     &  K_1P  ,K_1M  ,K_IF2 ,K_IF3 ,K_1P2P,K_1P2M,K_1P3P,K_1P3M,K_1M2P,
     &  K_1M2M,K_1M3P,K_1M3M,IDCONF,TB_V14,TB_V24,TB_V34,TB_TPM,TB_TMP, 
     &  TB_FAC,MDIA  ,IANMDI,COEMDI) 
      IMPLICIT NONE
      INTEGER          NPOIN2, NPLAN , NF    , NSITS , NPTFR , NVEB  ,
     &                 NVEF  , LIMIT ,
     &                 SMOUT , SFROT , SVENT , STRIF , SBREK , INDIC ,
     &                 IQBBJ , IHMBJ , IFRBJ , IWHTG , IFRTG , IFRRO ,
     &                 IEXPRO, IFRIH , NDTBRK, NP    , IDISRO, STRIA ,
     &                 NBOR(NPTFR)   , IANGNL(NPLAN,8)
      INTEGER          NBD   , QINDI(NBD)
      DOUBLE PRECISION TAILF , CFROT1, GRAVIT, RAISF , DTSI  , TPROP ,
     &                 CMOUT1, CMOUT2, DDC   , TV1   , TV2   , ZVENT ,
     &                 ROAIR , ROEAU , XKAPPA, BETAM , DECAL , CDRAG ,
     &                 ALPHA , GAMBJ1, GAMBJ2, ALFABJ, BORETG, GAMATG,
     &                 COEFHS, VX_CTE, VY_CTE, CIMPLI,
     &                 GAMARO, ALFARO, GAM2RO, EM2SIH, BETAIH, XDTBRK,
     &                 ALFLTA, RFMLTA, KSPB  , BDISPB, BDSSPB, F1
      DOUBLE PRECISION  DEPTH(NPOIN2), USNEW(NPOIN2) , USOLD(NPOIN2) ,
     &                 VARIAN(NPOIN2),  FMOY(NPOIN2) , XKMOY(NPOIN2) ,
     &                  TWOLD(NPOIN2), TWNEW(NPOIN2) , Z0OLD(NPOIN2) ,
     &                  Z0NEW(NPOIN2), VENTX(NPOIN2) , VENTY(NPOIN2) ,
     &                     U1(NPOIN2),    U2(NPOIN2) ,    V1(NPOIN2) ,
     &                     V2(NPOIN2),     X(NPOIN2) ,     Y(NPOIN2) ,
     &                 TAUWAV(NPOIN2), TAUX1(NPOIN2) , TAUX2(NPOIN2) ,
     &                  TAUX3(NPOIN2), TAUX4(NPOIN2) , TAUX5(NPOIN2) ,
     &                  TAUX6(NPOIN2), TAUX7(NPOIN2) , COEFNL(16)    ,
     &                    TETA(NPLAN), SINTET(NPLAN) , COSTET(NPLAN) ,
     &                    F(NPOIN2,NPLAN,NF),   XK(NPOIN2,NF)        ,
     &                    DF_LIM(NPOIN2,NF) ,
     &                 TSDER(NPOIN2,NPLAN,NF),TSTOT(NPOIN2,NPLAN,NF) ,
     &                 FREQ(NF), DFREQ(NF), XRELV(NP), YRELV(NP)     ,
     &                 TOLD(NPOIN2,NPLAN), TNEW(NPOIN2,NPLAN)
      DOUBLE PRECISION BETA(NPOIN2)
      DOUBLE PRECISION TRA01(NPOIN2,NPLAN)
      CHARACTER*144 NOMVEB, NOMVEF
      CHARACTER*3 BINVEN
      LOGICAL  PROINF, VENT , VENSTA
      INTEGER           LVENT 
      DOUBLE PRECISION  CMOUT3, CMOUT4, CMOUT5, CMOUT6
      DOUBLE PRECISION  COEFWD, COEFWE, COEFWF, COEFWH
      INTEGER           MDIA
      INTEGER           IANMDI(NPLAN,16,MDIA)
      DOUBLE PRECISION  COEMDI(32,MDIA)
      INTEGER  NQ_TE1, NQ_OM2, NF1, NF2 , NT1
      INTEGER  NCONF , NCONFM
      DOUBLE PRECISION SEUIL
      INTEGER  LBUF  , DIMBUF
      INTEGER           F_POIN(DIMBUF), T_POIN(DIMBUF)
      DOUBLE PRECISION  F_COEF(DIMBUF), F_PROJ(DIMBUF), TB_SCA(DIMBUF)
      INTEGER K_IF1 (1:NF1) 
      INTEGER K_1P  (1:NT1,1:NF1), K_1M(1:NT1,1:NF1)
      INTEGER K_IF2 (1:NF2,1:NT1,1:NF1), K_IF3 (1:NF2,1:NT1,1:NF1),
     &        K_1P2P(1:NF2,1:NT1,1:NF1), K_1P2M(1:NF2,1:NT1,1:NF1),
     &        K_1P3P(1:NF2,1:NT1,1:NF1), K_1P3M(1:NF2,1:NT1,1:NF1),
     &        K_1M2P(1:NF2,1:NT1,1:NF1), K_1M2M(1:NF2,1:NT1,1:NF1),
     &        K_1M3P(1:NF2,1:NT1,1:NF1), K_1M3M(1:NF2,1:NT1,1:NF1)
      INTEGER IDCONF(1:NCONFM,1:3)
      DOUBLE PRECISION TB_V14(1:NF1)
      DOUBLE PRECISION 
     &        TB_V24(1:NF2,1:NT1,1:NF1), TB_V34(1:NF2,1:NT1,1:NF1),
     &        TB_TPM(1:NF2,1:NT1,1:NF1), TB_TMP(1:NF2,1:NT1,1:NF1),
     &        TB_FAC(1:NF2,1:NT1,1:NF1)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE SOR3D
     &(F,NPLAN,NF,TETA,FREQ,NELEM2,NPOIN2,AT,U,V,UV,VV,DEPTH,VENT,
     & COURAN,MAREE,TITRE,NR3D,BINR3D)
      IMPLICIT NONE
      INTEGER NPLAN,NF,NELEM2,NPOIN2,NR3D
      DOUBLE PRECISION AT
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF),TETA(NPLAN),FREQ(NF)
      DOUBLE PRECISION U(NPOIN2),V(NPOIN2),UV(NPOIN2),VV(NPOIN2)
      DOUBLE PRECISION DEPTH(NPOIN2)
      LOGICAL COURAN,VENT,MAREE
      CHARACTER*3 BINR3D
      CHARACTER*72 TITRE
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE SPEINI
     &( F     , SPEC  , FRA   , UV    , VV    , FREQ  , TETA  , GRAVIT,
     &  FREMAX, FETCH , SIGMAA, SIGMAB, GAMMA , FPIC  , HM0   , ALPHIL,
     &  TETA1 , SPRED1, TETA2 , SPRED2, XLAMDA, NPOIN2, NPLAN , NF    ,
     &  INISPE, E2FMIN, DEPTH , FRABI )
      IMPLICIT NONE
      INTEGER  NPOIN2, NPLAN , NF    , INISPE, FRABI
      DOUBLE PRECISION GRAVIT, FREMAX, FETCH , SIGMAA, SIGMAB, GAMMA
      DOUBLE PRECISION FPIC  , HM0   , ALPHIL, TETA1 , SPRED1, TETA2
      DOUBLE PRECISION SPRED2, XLAMDA, E2FMIN
      DOUBLE PRECISION FREQ(NF) , TETA(NPLAN), SPEC(NF), FRA(NPLAN)
      DOUBLE PRECISION UV(NPOIN2) , VV(NPOIN2), DEPTH(NPOIN2)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE SPEJON
     &( SPEC  , FREQ  , NF    , AL    , FP     , GAMMA , SIGMAA, SIGMAB,
     &  DEUPI , GRAVIT, E2FMIN, FPMIN )
      IMPLICIT NONE
      INTEGER  NF
      DOUBLE PRECISION GRAVIT, SIGMAA, SIGMAB, GAMMA , DEUPI , FPMIN
      DOUBLE PRECISION FP    , E2FMIN, AL
      DOUBLE PRECISION SPEC(NF)      , FREQ(NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE SPETMA
     &( SPEC  , FREQ  , NF    , AL    , FP     , GAMMA , SIGMAA, SIGMAB,
     &  DEUPI , GRAVIT, E2FMIN, FPMIN , DEPTH  )
      IMPLICIT NONE
      INTEGER  NF
      DOUBLE PRECISION GRAVIT, SIGMAA, SIGMAB, GAMMA , DEUPI , FPMIN
      DOUBLE PRECISION FP    , E2FMIN, AL    , DEPTH
      DOUBLE PRECISION SPEC(NF)      , FREQ(NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE SPREAD
     &( DIRSPR, F     , COSTET, SINTET, NPLAN , FREQ  , DFREQ , NF    ,
     &  NPOIN2, TAILF , COSMOY, SINMOY, VARIAN, TAUXC , TAUXS , TAUXE )
      IMPLICIT NONE
      INTEGER  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION TAILF
      DOUBLE PRECISION DIRSPR(NPOIN2), SINMOY(NPOIN2), COSMOY(NPOIN2)
      DOUBLE PRECISION TAUXS (NPOIN2), TAUXC (NPOIN2), TAUXE (NPOIN2)
      DOUBLE PRECISION COSTET(NPLAN) , SINTET(NPLAN)
      DOUBLE PRECISION FREQ(NF), DFREQ(NF)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF), VARIAN(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE RE_INITIALISE_CHARS(NSEND,NLOSTCHAR,NLOSTAGAIN,NARRV)
          IMPLICIT NONE
          INTEGER, INTENT(OUT) :: NSEND,NLOSTCHAR,NLOSTAGAIN,NARRV
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PREP_LOST_AGAIN(NOMB,NSEND,NLOSTAGAIN,NARRV)
          IMPLICIT NONE
          INTEGER,INTENT(IN)   :: NOMB,NLOSTAGAIN,NARRV
          INTEGER, INTENT(OUT) :: NSEND
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PREP_SENDBACK(NOMB,NCHARA)
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: NOMB
          INTEGER, INTENT(INOUT) :: NCHARA
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE INTERP_RECVCHAR_41
     &      (VAL,N,IKLE,ELT,ETA,SHP,SHZ,NELEM,NPOIN2,NPLAN,NRANGE)
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: N,NELEM,NPOIN2,NPLAN,NRANGE
          INTEGER, INTENT(IN) :: IKLE(NELEM,3)
          INTEGER, INTENT(IN) :: ELT(NRANGE), ETA(NRANGE)
          DOUBLE PRECISION, INTENT(IN) :: SHP(3,NRANGE), SHZ(NRANGE)
          DOUBLE PRECISION, INTENT(IN) :: VAL(NPOIN2,NPLAN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE INTERP_RECVCHAR_41_MOD
     &      (VAL,IKLE,ELT,ETA,SHP1,SHP2,SHP3,SHZ,
     &                            NELEM,NPOIN2,NPLAN,NRANGE)
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: NELEM,NPOIN2,NPLAN,NRANGE
          INTEGER, INTENT(IN) :: IKLE(NELEM,3)
          INTEGER, INTENT(IN) :: ELT(NRANGE), ETA(NRANGE)
          DOUBLE PRECISION, INTENT(IN) :: SHP1(NRANGE),SHP2(NRANGE),
     &                                    SHP3(NRANGE),SHZ(NRANGE)
          DOUBLE PRECISION, INTENT(IN) :: VAL(NPOIN2,NPLAN,2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE INTERP_RECVCHAR_11
     &      (VAL,N,IKLE,ELT,SHP,NELEM,NPOIN,NRANGE,IELM)
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: N,NELEM,NPOIN,NRANGE,IELM
          INTEGER, INTENT(IN) :: IKLE(NELEM,*)
          INTEGER, INTENT(IN) :: ELT(NRANGE)
          DOUBLE PRECISION, INTENT(IN) :: SHP(3,NRANGE)
          DOUBLE PRECISION, INTENT(IN) :: VAL(NPOIN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE INTRODUCE_RECVCHAR(VAL,N,NPOIN,NOMB,NARRV)
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: N,NPOIN,NOMB,NARRV
          DOUBLE PRECISION, INTENT(INOUT) :: VAL(NPOIN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE INTRODUCE_RECVCHAR_MOD(VAL,NPOIN,NARRV)
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: NPOIN,NARRV
          DOUBLE PRECISION, INTENT(INOUT) :: VAL(NPOIN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PRINT_HEAPCHAR(MESSAGE,NOMB,NCHARA)
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: NOMB,NCHARA
          CHARACTER(LEN=*), INTENT(IN) :: MESSAGE
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PRINT_SENDCHAR(MESSAGE,NOMB,NSEND)
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: NOMB,NSEND
          CHARACTER(LEN=*), INTENT(IN) :: MESSAGE
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PRINT_RECVCHAR(MESSAGE,NOMB,NARRV)
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: NOMB,NARRV
          CHARACTER(LEN=*), INTENT(IN) :: MESSAGE
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE SCHAR41
     &( U , V , W , DT , NRK , X , Y , ZSTAR , Z , IKLE2 , IBOR ,
     &  XPLOT , YPLOT , ZPLOT , DX , DY , DZ , SHP , SHZ , ELT , ETA ,
     &  NSP   , NPLOT , NPOIN2 , NELEM2 , NPLAN , SURDET ,
     &  SENS  , TEST  , IFAPAR, NCHDIM,NCHARA)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER         , INTENT(IN)    :: SENS,NPLAN,NCHDIM
      INTEGER         , INTENT(IN)    :: NPOIN2,NELEM2,NPLOT,NRK
      INTEGER         , INTENT(IN)    :: IKLE2(NELEM2,3)
      INTEGER         , INTENT(INOUT) :: ELT(NPLOT),NSP(NPLOT),NCHARA
      DOUBLE PRECISION, INTENT(IN)    :: U(NPOIN2,NPLAN),V(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: W(NPOIN2,NPLAN),SURDET(NELEM2)
      DOUBLE PRECISION, INTENT(INOUT) :: XPLOT(NPLOT),YPLOT(NPLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: ZPLOT(NPLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: SHP(3,NPLOT),SHZ(NPLOT)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN2),Y(NPOIN2),DT
      DOUBLE PRECISION, INTENT(IN)    :: Z(NPOIN2,NPLAN),ZSTAR(NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: DX(NPLOT),DY(NPLOT),TEST(NPLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: DZ(NPLOT)
      INTEGER         , INTENT(IN)    :: IBOR(NELEM2,5,NPLAN-1)
      INTEGER         , INTENT(INOUT) :: ETA(NPLOT)
      INTEGER         , INTENT(IN)    :: IFAPAR(6,*)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE ADD_CHAR41
     & ( U , V , W , DT , NRK , X , Y , ZSTAR , Z , IKLE2 , IBOR ,
     &   XPLOT , YPLOT , ZPLOT , DX , DY , DZ , SHP , SHZ , ELT , ETA,
     &   NSP , ISPDONE, NPLOT , NPOIN2 , NELEM2 , NPLAN ,
     &   SURDET , SENS , TEST, IFAPAR, NOMB,NARRV)
      IMPLICIT NONE
      INTEGER         , INTENT(IN)    :: SENS,NPLAN,NOMB,NARRV
      INTEGER         , INTENT(IN)    :: NPOIN2,NELEM2,NPLOT,NRK
      INTEGER         , INTENT(IN)    :: IKLE2(NELEM2,3)
      INTEGER         , INTENT(INOUT) :: ELT(NPLOT),NSP(NPLOT)
      INTEGER         , INTENT(INOUT) :: ISPDONE(NPLOT)
      DOUBLE PRECISION, INTENT(IN)    :: U(NPOIN2,NPLAN),V(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: W(NPOIN2,NPLAN),SURDET(NELEM2)
      DOUBLE PRECISION, INTENT(INOUT) :: XPLOT(NPLOT),YPLOT(NPLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: ZPLOT(NPLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: SHP(3,NPLOT),SHZ(NPLOT)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN2),Y(NPOIN2),DT
      DOUBLE PRECISION, INTENT(IN)    :: Z(NPOIN2,NPLAN),ZSTAR(NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: DX(NPLOT),DY(NPLOT),TEST(NPLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: DZ(NPLOT)
      INTEGER         , INTENT(IN)    :: IBOR(NELEM2,5,NPLAN-1)
      INTEGER         , INTENT(INOUT) :: ETA(NPLOT)
      INTEGER, INTENT(IN)             :: IFAPAR(6,*)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE ADD_CHAR41_MOD
     & ( U , V , W , DT , NRK , X , Y , ZSTAR , Z , IKLE2 , IBOR ,
     &   XPLOT,YPLOT,ZPLOT,DX,DY,DZ,SHP1,SHP2,SHP3,SHZ,ELT,ETA,
     &   NSP , ISPDONE, NPLOT , NPOIN2 , NELEM2 , NPLAN ,
     &   SURDET , SENS , TEST, IFAPAR, NOMB,NARRV)
      IMPLICIT NONE
      INTEGER         , INTENT(IN)    :: SENS,NPLAN,NOMB,NARRV
      INTEGER         , INTENT(IN)    :: NPOIN2,NELEM2,NPLOT,NRK
      INTEGER         , INTENT(IN)    :: IKLE2(NELEM2,3)
      INTEGER         , INTENT(INOUT) :: ELT(NPLOT),NSP(NPLOT)
      INTEGER         , INTENT(INOUT) :: ISPDONE(NPLOT)
      DOUBLE PRECISION, INTENT(IN)    :: U(NPOIN2,NPLAN),V(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: W(NPOIN2,NPLAN),SURDET(NELEM2)
      DOUBLE PRECISION, INTENT(INOUT) :: XPLOT(NPLOT),YPLOT(NPLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: ZPLOT(NPLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: SHP1(NPLOT),SHP2(NPLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: SHP3(NPLOT),SHZ(NPLOT)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN2),Y(NPOIN2),DT
      DOUBLE PRECISION, INTENT(IN)    :: Z(NPOIN2,NPLAN),ZSTAR(NPLAN+1)
      DOUBLE PRECISION, INTENT(INOUT) :: DX(NPLOT),DY(NPLOT),TEST(NPLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: DZ(NPLOT)
      INTEGER         , INTENT(IN)    :: IBOR(NELEM2,5)
      INTEGER         , INTENT(INOUT) :: ETA(NPLOT)
      INTEGER, INTENT(IN)             :: IFAPAR(6,*)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE SCHAR11
     & ( U , V , DT , NRK , X , Y , IKLE , IFABOR ,
     &   XPLOT , YPLOT , DX , DY , SHP , ELT , NSP ,
     &   NPLOT , NPOIN , NELEM , NELMAX , SURDET , SENS , TEST,
     &   IFAPAR, MESH,NCHDIM,NCHARA)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER         , INTENT(IN)    :: SENS,NCHDIM
      INTEGER         , INTENT(IN)    :: NPOIN,NELEM,NELMAX,NPLOT,NRK
      INTEGER         , INTENT(IN)    :: IKLE(NELMAX,3),IFABOR(NELMAX,3)
      INTEGER         , INTENT(INOUT) :: ELT(NPLOT),NCHARA
      INTEGER         , INTENT(OUT)   :: NSP(NPLOT)
      DOUBLE PRECISION, INTENT(IN)    :: U(NPOIN),V(NPOIN),SURDET(NELEM)
      DOUBLE PRECISION, INTENT(INOUT) :: XPLOT(NPLOT),YPLOT(NPLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: SHP(3,NPLOT)
      DOUBLE PRECISION, INTENT(IN)    :: DT
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN),Y(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: DX(NPLOT),DY(NPLOT),TEST(NPLOT)
      INTEGER, INTENT(IN)             :: IFAPAR(6,*)
      TYPE (BIEF_MESH), INTENT(INOUT) :: MESH
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE ADD_CHAR11
     & ( U , V , DT , NRK , X , Y , IKLE , IFABOR ,
     &   XPLOT , YPLOT , DX , DY , SHP , ELT , NSP , ISPDONE,
     &   NPLOT , NPOIN , NELEM , NELMAX , SURDET , SENS , TEST,
     &   IFAPAR, NOMB,NARRV)
      IMPLICIT NONE
      INTEGER         , INTENT(IN)    :: SENS,NOMB,NARRV
      INTEGER         , INTENT(IN)    :: NPOIN,NELEM,NELMAX,NPLOT,NRK
      INTEGER         , INTENT(IN)    :: IKLE(NELMAX,3),IFABOR(NELMAX,3)
      INTEGER         , INTENT(INOUT) :: ELT(NPLOT),NSP(NPLOT)
      INTEGER         , INTENT(INOUT) :: ISPDONE(NPLOT)
      DOUBLE PRECISION, INTENT(IN)    :: U(NPOIN),V(NPOIN),SURDET(NELEM)
      DOUBLE PRECISION, INTENT(INOUT) :: XPLOT(NPLOT),YPLOT(NPLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: SHP(3,NPLOT)
      DOUBLE PRECISION, INTENT(IN)    :: DT
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN),Y(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: DX(NPLOT),DY(NPLOT),TEST(NPLOT)
      INTEGER, INTENT(IN) :: IFAPAR(6,*)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE UPDATE_TEST(TEST,MESH,SHP1,SHP2,SHP3,NPOINT)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER NPOINT
      DOUBLE PRECISION TEST(NPOINT),SHP1(NPOINT),
     &SHP2(NPOINT),SHP3(NPOINT)
      TYPE(BIEF_MESH), INTENT(INOUT)   :: MESH
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE SEND_RECV_TOMAWAC(U,UTILD,UCONV,VCONV,WCONV,DT,NRK,
     &              X, Y, ZSTAR, Z,
     &              IKLE, IFABOR, XCONV, YCONV, ZCONV, DX, DY, DZ,
     &              SHP1,SHP2,SHP3, SHZ, ELT, ETA, ITRAV1,ITRAV2,NARRV,
     &              NPOIN2, NELEM, NPLAN, SURDET,
     &              TEST,NPOIN,NCHDIM,NCHARA,NOMB,MESH,LAST_NOMB)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(INOUT)          :: NELEM,NPOIN,NPOIN2
      INTEGER, INTENT(IN)             :: NOMB,NPLAN
      TYPE(BIEF_OBJ)  , INTENT(INOUT) :: U
      TYPE(BIEF_OBJ)  , INTENT(INOUT) :: UTILD
      DOUBLE PRECISION, INTENT(IN)    :: UCONV(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: VCONV(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: WCONV(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: Y(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: Z(NPOIN2,NPLAN),ZSTAR(NPLAN+1)
      DOUBLE PRECISION, INTENT(INOUT) :: ZCONV(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: DX(NPOIN),DY(NPOIN),DZ(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: SHP1(NPOIN),SHP2(NPOIN),
     &                    SHP3(NPOIN),SHZ(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: SURDET(NELEM)
      DOUBLE PRECISION, INTENT(IN)    :: DT
      INTEGER, INTENT(IN)             :: IKLE(NELEM,3)
      INTEGER, INTENT(IN)             :: IFABOR(NELEM,*)
      INTEGER, INTENT(INOUT)          :: ELT(NPOIN),ETA(NPOIN)
      INTEGER, INTENT(INOUT)          :: ITRAV1(NPOIN),ITRAV2(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: TEST(NPOIN)
      TYPE(BIEF_MESH) , INTENT(INOUT) :: MESH
      DOUBLE PRECISION, INTENT(INOUT) :: XCONV(NPOIN2,NPLAN),
     &                                   YCONV(NPOIN2,NPLAN)
      INTEGER NRK,NCHARA,NARRV,NCHDIM,LAST_NOMB
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE SCARACT
     & ( U , UTILD , UCONV , VCONV , WCONV , X , Y , ZSTAR ,
     &   XCONV , YCONV , ZCONV , DX , DY , DZ , Z , SHP , SHZ , SURDET ,
     &   DT , IKLE , IFABOR , ELT , ETA , ITRAV1, ITRAV2, IELM ,
     &   IELMU , NELEM , NELMAX , NOMB , NPOIN , NPOIN2 , NDP , NPLAN ,
     &   LV , MSK , MASKEL , MESH , FAC , TEST , STEST , INITLOC)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NELEM,NELMAX,NPOIN,NPOIN2
      INTEGER, INTENT(IN)             :: NOMB,NDP,NPLAN,IELM,IELMU,LV
      TYPE(BIEF_OBJ)  , INTENT(IN)    :: U
      TYPE(BIEF_OBJ)  , INTENT(INOUT) :: UTILD
      DOUBLE PRECISION, INTENT(IN)    :: UCONV(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: VCONV(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: WCONV(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: Y(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: Z(NPOIN2,NPLAN),ZSTAR(NPLAN)
      DOUBLE PRECISION, INTENT(OUT)   :: ZCONV(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(OUT)   :: DX(NPOIN),DY(NPOIN),DZ(NPOIN)
      DOUBLE PRECISION, INTENT(OUT)   :: SHP(NDP,NPOIN),SHZ(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: MASKEL(NELMAX)
      DOUBLE PRECISION, INTENT(IN)    :: SURDET(NELEM)
      DOUBLE PRECISION, INTENT(IN)    :: DT
      INTEGER, INTENT(IN)             :: IKLE(NELMAX,NDP)
      INTEGER, INTENT(IN)             :: IFABOR(NELMAX,*)
      INTEGER, INTENT(OUT)            :: ELT(NPOIN),ETA(NPOIN)
      INTEGER, INTENT(OUT)            :: ITRAV1(NPOIN),ITRAV2(NPOIN)
      LOGICAL, INTENT(IN)             :: MSK,INITLOC
      DOUBLE PRECISION, INTENT(OUT)   :: TEST(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: FAC(NPOIN)
      TYPE(BIEF_MESH) , INTENT(INOUT) :: MESH
      TYPE(BIEF_OBJ)  , INTENT(INOUT) :: STEST,XCONV,YCONV
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE STRESS
     &( TAUWAV, TSTOT , F     , USNEW , TWNEW , Z0NEW , FREQ  , DFREQ ,
     &  TETA  , SINTET, COSTET, ROAIR , ROEAU , XKAPPA, BETAM , DECAL ,
     &  GRAVIT, NPOIN2, NPLAN , NF    , XTAUW , YTAUW , TAUHF )
      IMPLICIT NONE
      INTEGER  NPOIN2, NPLAN , NF
      DOUBLE PRECISION ROAIR , ROEAU , XKAPPA , BETAM , DECAL , GRAVIT
      DOUBLE PRECISION TAUWAV(NPOIN2), USNEW(NPOIN2), TWNEW(NPOIN2)
      DOUBLE PRECISION  Z0NEW(NPOIN2), FREQ(NF) , DFREQ(NF)
      DOUBLE PRECISION TSTOT(NPOIN2,NPLAN,NF), F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION TETA(NPLAN), SINTET(NPLAN), COSTET(NPLAN)
      DOUBLE PRECISION XTAUW(NPOIN2) , YTAUW(NPOIN2), TAUHF(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE TAUTOT
     &( TAUT  , UVENT , TAUW  , CDRAG , ALPHA , XKAPPA, ZVENT , SEUIL ,
     &  GRAVIT, ITR   , ITRMIN, ITRMAX)
      IMPLICIT NONE
      INTEGER  ITRMIN, ITRMAX, ITR
      DOUBLE PRECISION TAUT  , UVENT , TAUW  , ALPHA , XKAPPA , ZVENT
      DOUBLE PRECISION SEUIL , CDRAG , GRAVIT
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE TEMP(TV ,DAT,DDC)
      IMPLICIT NONE
      DOUBLE PRECISION TV,DDC,DAT
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE TETMOY
     &( TETAM , F     , COSTET, SINTET, NPLAN , FREQ  , DFREQ , NF    ,
     &  NPOIN2, TAILF , COSMOY, SINMOY, TAUXC , TAUXS )
      IMPLICIT NONE
      INTEGER  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION TAILF
      DOUBLE PRECISION TETAM(NPOIN2) , DFREQ(NF)    , COSMOY(NPOIN2)
      DOUBLE PRECISION COSTET(NPLAN) , SINTET(NPLAN), SINMOY(NPOIN2)
      DOUBLE PRECISION TAUXC(NPOIN2) , TAUXS(NPOIN2)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF), FREQ(NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE TOTNRJ
     &( VARIAN, F     , FREQ  , DFREQ , TAILF , NF    , NPLAN , NPOIN2)
      IMPLICIT NONE
      INTEGER          NF    , NPLAN , NPOIN2
      DOUBLE PRECISION TAILF , VARIAN(NPOIN2), FREQ(NF), DFREQ(NF)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE TRANSF
     &( FA    , FR    , FREQ  , DFREQ , COSTET, SINTET, UC    , VC    ,
     &  XK    , KNEW  , NEWF  , NEWF1 , TAUX1 , TAUX2 , NPOIN2, NPLAN ,
     &  NF    , RAISF , LT    , GRADEB, GRAPRD)
      IMPLICIT NONE
      INTEGER          NPOIN2, NPLAN , NF    , LT    , GRADEB, GRAPRD
      INTEGER          KNEW(NPOIN2)  , NEWF(NPOIN2)  , NEWF1(NPOIN2)
      DOUBLE PRECISION RAISF
      DOUBLE PRECISION FA(NPOIN2,NPLAN,NF),FR(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION FREQ(NF),DFREQ(NF),COSTET(NPLAN),SINTET(NPLAN)
      DOUBLE PRECISION UC(NPOIN2),VC(NPOIN2),TAUX1(NPOIN2),TAUX2(NPOIN2)
      DOUBLE PRECISION XK(NPOIN2,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE USTAR1
     &( USTAR , Z0    , TAUWAV, UV    , VV    , CDRAG , ALPHA , XKAPPA,
     &  ZVENT , GRAVIT, NPOIN2)
      IMPLICIT NONE
      INTEGER  NPOIN2
      DOUBLE PRECISION USTAR(NPOIN2) , Z0(NPOIN2) , TAUWAV(NPOIN2)
      DOUBLE PRECISION    UV(NPOIN2) , VV(NPOIN2)
      DOUBLE PRECISION CDRAG , ALPHA , XKAPPA , ZVENT, GRAVIT
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE USTAR2
     &( USTAR , UV    , VV    , NPOIN2)
      IMPLICIT NONE
      INTEGER  NPOIN2
      DOUBLE PRECISION USTAR(NPOIN2) , UV(NPOIN2) , VV(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE VARTEL
     &( VAR, X, Y, DEPTH, UC, VC, ZREPOS, TRA01, F, NPLAN, NF, NPOIN2)
      IMPLICIT NONE
      INTEGER  NPOIN2,NPLAN,NF
      DOUBLE PRECISION F (NPOIN2,NPLAN,NF) , TRA01(NPOIN2)
      DOUBLE PRECISION X (NPOIN2) , Y (NPOIN2) , DEPTH(NPOIN2)
      DOUBLE PRECISION UC(NPOIN2) , VC(NPOIN2) , VAR(NPOIN2)
      DOUBLE PRECISION ZREPOS
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE VENUTI
     &(X,Y,NPOIN,NVEN, BINVEN,NBOR,NPTFR,AT,DDC,TV1,TV2,
     & NP,XRELV,YRELV,UR,VR,U1,V1,U2,V2,NPMAX)
      IMPLICIT NONE
      INTEGER NVEN,NPOIN,NPMAX,NP,NPTFR,NBOR(NPTFR,2)
      DOUBLE PRECISION X(NPOIN),Y(NPOIN)
      DOUBLE PRECISION XRELV(NPMAX),YRELV(NPMAX), UR(NPMAX),VR(NPMAX)
      DOUBLE PRECISION U1(NPMAX),V1(NPMAX),U2(NPMAX),V2(NPMAX)
      DOUBLE PRECISION AT,DDC,TV1,TV2
      CHARACTER*3 BINVEN
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE VITFON
     &( UWBM  , F     , XK    , DEPTH , DFREQ , NF    , NPOIN2, NPLAN ,
     &      GRAVIT, BETA  )
      IMPLICIT NONE
      INTEGER  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION GRAVIT
      DOUBLE PRECISION UWBM(NPOIN2), DEPTH(NPOIN2), BETA(NPOIN2)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF), XK(NPOIN2,NF), DFREQ(NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
!V6P1 New arguments
      INTERFACE
        SUBROUTINE WAC
     &(PART, U_TEL, V_TEL, H_TEL, FX_WAC, FY_WAC, UV_WAC, VV_WAC,
     & CODE, T_TEL, DT_TEL,NIT_TEL,PERCOU_WAC)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER,           INTENT(IN)      :: PART,NIT_TEL,PERCOU_WAC
      CHARACTER(LEN=24), INTENT(IN)      :: CODE
      TYPE(BIEF_OBJ),    INTENT(IN)      :: U_TEL,V_TEL,H_TEL
      TYPE(BIEF_OBJ),    INTENT(INOUT)   :: FX_WAC,FY_WAC
      TYPE(BIEF_OBJ),    INTENT(INOUT)   :: UV_WAC,VV_WAC
      DOUBLE PRECISION,  INTENT(IN)      :: DT_TEL,T_TEL
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE WNSCOU
     &( CK2   , FREQ  , DEPTH )
      IMPLICIT NONE
      DOUBLE PRECISION CK2   , FREQ  , DEPTH
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE WPOWER
     &( POWER , F     , FREQ  , DFREQ , CG    , TAILF , NF    , NPLAN ,
     &  NPOIN2, ROEAU , GRAVIT)
      IMPLICIT NONE
      INTEGER          NF    , NPLAN , NPOIN2
      DOUBLE PRECISION TAILF , POWER(NPOIN2), FREQ(NF), DFREQ(NF)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF), CG(NPOIN2,NF)
      DOUBLE PRECISION GRAVIT, ROEAU
        END SUBROUTINE
      END INTERFACE
!
!=======================================================================
!
      END MODULE INTERFACE_TOMAWAC
