#!/bin/sh
#-----------------------------------------------------
#
# lancement sous unix de justmake
#
#-----------------------------------------------------
#
PERL5LIB=`getperl5lib`
export PERL5LIB
#
PERLPATH=`getperlpath`
export PERLPATH
#
$PERLPATH/perl -x -S cfgmak.pl
$PERLPATH/perl -w -x -S justmake.pl $1 $2 $3 $4 $5 

