C
      MODULE INTERFACE_TELEMAC3D
C
C~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C
      USE BIEF_DEF
C
C-----------------------------------------------------------------------
C
C     DEFINITION OF INTERFACES
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE ACTUZF(IVIDE,EPAI,ZF,NPOIN2,NPFMAX,NPF)
       IMPLICIT NONE
       INTEGER, INTENT(IN)             :: NPOIN2, NPFMAX
       DOUBLE PRECISION, INTENT(IN)    :: IVIDE(NPFMAX,NPOIN2)
       DOUBLE PRECISION, INTENT(IN)    :: EPAI(NPFMAX-1,NPOIN2)
       DOUBLE PRECISION, INTENT(INOUT) :: ZF(NPOIN2)
       INTEGER, INTENT(IN)             :: NPF(NPOIN2)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE AIRWIK1
     &(LIHBOR,UBORF,VBORF,LIUBOF,LIVBOF,UBORL,VBORL,LIUBOL,LIVBOL,
     & UBORS,VBORS,LIUBOS,LIVBOS,U,V,UD,VD,DELWAQ,
     & U2D,V2D,XNEBOR,YNEBOR,NBOR,
     & UMOY,VMOY,TRA01,TRA02,TRA03,Z,NPTFR,NPLAN,NPOIN2,
     & KENT,KADH,KLOG,KDEB,OPTBAN,KP1BOR)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NPTFR, NPLAN, NPOIN2,OPTBAN
      INTEGER, INTENT(IN) :: KENT, KADH, KLOG, KDEB
      INTEGER, INTENT(IN) :: KP1BOR(NPTFR,2)
      INTEGER, INTENT(IN) :: LIUBOF(NPOIN2), LIUBOS(NPOIN2)
      INTEGER, INTENT(IN) :: LIUBOL(NPTFR,NPLAN)
      INTEGER, INTENT(IN) :: LIHBOR(NPTFR)
      INTEGER, INTENT(IN) :: LIVBOF(NPOIN2), LIVBOS(NPOIN2)
      INTEGER, INTENT(IN) :: LIVBOL(NPTFR,NPLAN)
      INTEGER, INTENT(IN) :: NBOR(NPTFR)
      DOUBLE PRECISION, INTENT(IN)    :: UBORF(NPOIN2),UBORS(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: UBORL(NPTFR,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: VBORF(NPOIN2),VBORS(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: VBORL(NPTFR,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: Z(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: XNEBOR(NPTFR),YNEBOR(NPTFR)
      DOUBLE PRECISION, INTENT(INOUT) :: U(NPOIN2,NPLAN),V(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: UD(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: VD(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: U2D(NPOIN2),V2D(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: UMOY(NPOIN2),VMOY(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA01(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA02(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA03(NPOIN2,NPLAN)
      LOGICAL, INTENT(IN)             :: DELWAQ
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE AIRWIK2
     &(LIHBOR,UBORF,VBORF,WBORF,LIUBOF,LIVBOF,LIWBOF,UBORL,VBORL,WBORL,
     & LIUBOL,LIVBOL,LIWBOL,
     & UBORS,VBORS,WBORS,LIUBOS,LIVBOS,LIWBOS,U,V,W,XNEBOR,YNEBOR,NBOR,
     & NPTFR,NPLAN,NPOIN2,KENT,KADH,KLOG,KDEB,KP1BOR,VELPROLAT)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NPTFR, NPLAN, NPOIN2
      INTEGER, INTENT(IN) :: KENT, KADH, KLOG, KDEB
      INTEGER, INTENT(IN) :: KP1BOR(NPTFR,2)
      INTEGER, INTENT(IN) :: LIUBOF(NPOIN2), LIUBOS(NPOIN2)
      INTEGER, INTENT(IN) :: LIUBOL(NPTFR,NPLAN),LIWBOF(NPOIN2)
      INTEGER, INTENT(IN) :: LIHBOR(NPTFR),LIWBOS(NPOIN2)
      INTEGER, INTENT(IN) :: LIVBOF(NPOIN2), LIVBOS(NPOIN2)
      INTEGER, INTENT(IN) :: LIVBOL(NPTFR,NPLAN),LIWBOL(NPTFR,NPLAN)
      INTEGER, INTENT(IN) :: NBOR(NPTFR)
      DOUBLE PRECISION, INTENT(IN)    :: UBORF(NPOIN2),UBORS(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: WBORF(NPOIN2),WBORS(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: UBORL(NPTFR,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: WBORL(NPTFR,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: VBORF(NPOIN2), VBORS(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: VBORL(NPTFR,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: XNEBOR(NPTFR),YNEBOR(NPTFR)
      DOUBLE PRECISION, INTENT(INOUT) :: U(NPOIN2,NPLAN),V(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: W(NPOIN2,NPLAN)
      LOGICAL, INTENT(IN)             :: VELPROLAT
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE AMR_PLAN
     &(ZVALS,OBJSOL,REFTYPE,NPOIN2,NPLAN,NSEG2,GLOSEG,DIMGLO,
     & Z0,NEWZ,ZEXT,INTSOL,MONITOR,SSMONITOR,SMONITOR,NEXTR,SNNEIGH,
     & NNEIGH,MCOEFF,MESH2D,MESH3D)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER,          INTENT(IN)    :: NPLAN,NPOIN2,NSEG2,DIMGLO
      DOUBLE PRECISION, INTENT(IN)    :: OBJSOL(NPOIN2,NPLAN)
      CHARACTER,        INTENT(IN)    :: REFTYPE
      INTEGER,          INTENT(IN)    :: GLOSEG(DIMGLO,2)
      DOUBLE PRECISION, INTENT(INOUT) :: ZVALS(NPOIN2,NPLAN) 
      DOUBLE PRECISION, INTENT(INOUT) :: Z0(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: NEWZ(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: ZEXT(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: INTSOL(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: MONITOR(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: SMONITOR(NPOIN2,NPLAN)
      INTEGER,          INTENT(INOUT) :: NEXTR(NPOIN2),MCOEFF(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: NNEIGH(NPOIN2)
      TYPE(BIEF_OBJ),   INTENT(INOUT) :: SNNEIGH,SSMONITOR
      TYPE(BIEF_MESH),  INTENT(INOUT) :: MESH2D,MESH3D     
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE AIRWIK3
     & (LIHBOR,U,V,XNEBOR,YNEBOR,NBOR,NPTFR,NPLAN,NPOIN2,KLOG)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NPTFR,NPLAN,NPOIN2,KLOG
      INTEGER, INTENT(IN) :: LIHBOR(NPTFR),NBOR(NPTFR)
      DOUBLE PRECISION, INTENT(IN)    :: XNEBOR(NPTFR),YNEBOR(NPTFR)
      DOUBLE PRECISION, INTENT(INOUT) :: U(NPOIN2,NPLAN),V(NPOIN2,NPLAN)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE BIL3D(LT,IKLBORL,IKLE2L,NPTFR,NETAG,NELEM)
          USE BIEF_DEF
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: LT,NPTFR,NETAG,NELEM
          INTEGER, INTENT(IN) :: IKLBORL(NPTFR,NETAG,4)
          INTEGER, INTENT(IN) :: IKLE2L(NELEM,3)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE BISSEL(IVIDE,TRA01,NPFMAX,IMAX,NDEB)
          IMPLICIT NONE
          INTEGER, INTENT(IN)             :: NPFMAX,IMAX,NDEB
          DOUBLE PRECISION, INTENT(INOUT) :: IVIDE(NPFMAX)
          DOUBLE PRECISION, INTENT(INOUT) :: TRA01(NPFMAX,6)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE BORD3D(AAT,LT,IINFOGR,NPTFR2_DIM,NFRLIQ)
          IMPLICIT NONE
          DOUBLE PRECISION, INTENT(IN)    :: AAT
          INTEGER         , INTENT(IN)    :: LT
          LOGICAL         , INTENT(IN)    :: IINFOGR
          INTEGER         , INTENT(IN)    :: NPTFR2_DIM
          INTEGER         , INTENT(IN)    :: NFRLIQ
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE BYPASS_CRUSHED_POINTS
     & (VOLU,SVOLU,VOLUN,SVOLUN,FLUX,TRA01,MESH2,MESH3,
     &  NPOIN3,SCHCF,NPOIN2,GLOSEG,DIMGLO,NSEG,NPLAN)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: SCHCF,NPOIN3,NPOIN2
      INTEGER, INTENT(IN)             :: NSEG,NPLAN,DIMGLO
      INTEGER, INTENT(IN)             :: GLOSEG(DIMGLO,2)
      DOUBLE PRECISION, INTENT(IN)    :: VOLUN(NPOIN3),VOLU(NPOIN3)
      TYPE(BIEF_OBJ), INTENT(IN)      :: SVOLU,SVOLUN
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: TRA01
      TYPE(BIEF_MESH), INTENT(INOUT)  :: MESH2,MESH3
      DOUBLE PRECISION, INTENT(INOUT) :: FLUX(*)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE CALCG(TRAV2,TRAV3,U,V,UETCAR,NPOIN2,NPLAN)
          IMPLICIT NONE
          INTEGER         , INTENT(IN)    :: NPOIN2,NPLAN
          DOUBLE PRECISION, INTENT(IN)    :: U(NPOIN2),V(NPOIN2)
          DOUBLE PRECISION, INTENT(IN)    :: UETCAR(NPOIN2)
          DOUBLE PRECISION, INTENT(IN)    :: TRAV2(NPOIN2*NPLAN)
          DOUBLE PRECISION, INTENT(INOUT) :: TRAV3(NPOIN2*NPLAN)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE CALCOT(ZZ,HH)
          USE DECLARATIONS_TELEMAC3D
          IMPLICIT NONE
          DOUBLE PRECISION, INTENT(IN)    :: HH(NPOIN2)
          DOUBLE PRECISION, INTENT(INOUT) :: ZZ(NPOIN2,NPLAN)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE CHECK
     &(IKLE2,NBOR,NELBOR,IKLBOR,IKLE3,NELBO3,NULONE,NBOR3,NELEM2,NPOIN2,
     & NPTFR,NETAGE,NELEM3,NPTFR3,NTRAC,INFO)
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: NELEM2, NPOIN2, NPTFR, NETAGE, NELEM3
          INTEGER, INTENT(IN) :: NPTFR3, NTRAC
          INTEGER, INTENT(IN) :: NELBOR(NPTFR), NBOR(NPTFR)
          INTEGER, INTENT(IN) :: IKLE2(NELEM2,3)
          INTEGER, INTENT(IN) :: IKLBOR(NPTFR,NETAGE,4),IKLE3(NELEM3,6)
          INTEGER, INTENT(IN) :: NELBO3(NPTFR,NETAGE)
          INTEGER, INTENT(IN) :: NULONE(NPTFR,NETAGE,4)
          INTEGER, INTENT(IN) :: NBOR3(NPTFR3)
          LOGICAL, INTENT(IN) :: INFO
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE CLSEDI
     &( ATABOF , BTABOF , ATABOS , BTABOS , TA     ,
     &  WC     , GRADZFX, GRADZFY, GRADZSX, GRADZSY,
     &  X      , Y      , Z      , HN     , DELTAR ,
     &  TOB    , DENSI  , TRA03  ,  IVIDE  , EPAI   ,
     &  CONC   , HDEP   , FLUER  , PDEPOT , LITABF ,
     &  LITABS , KLOG   , NPOIN3 , NPOIN2 , NPLAN  ,
     &  NPFMAX , NCOUCH , NPF    , ITURBV , DT     , RHO0   ,
     &  RHOS   , CFDEP  , TOCD   , MPART  , TOCE   , TASSE  ,
     &  GIBSON , PRIVE  , UETCAR ,
     &  GRAV   , SEDCO  , DMOY   , CREF   , ZREF,CF,
     &  AC     , KSPRATIO,ICR,ICQ,RUGOF)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NPOIN2, NPOIN3, KLOG , NPFMAX
      INTEGER, INTENT(IN) :: NCOUCH, ITURBV, NPLAN, ICR,ICQ
      DOUBLE PRECISION, INTENT(INOUT) :: ATABOF(NPOIN2), BTABOF(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: ATABOS(NPOIN2), BTABOS(NPOIN2)
      DOUBLE PRECISION, INTENT(IN) :: X(NPOIN3), Y(NPOIN3), Z(NPOIN3)
      DOUBLE PRECISION, INTENT(IN) :: TA(NPOIN3)
      DOUBLE PRECISION, INTENT(IN) :: WC(NPOIN3), DELTAR(NPOIN3)
      TYPE(BIEF_OBJ), INTENT(INOUT) :: PRIVE,TOB,CREF,ZREF,RUGOF
      TYPE(BIEF_OBJ), INTENT(IN)    :: DMOY,HN,CF
      DOUBLE PRECISION, INTENT(INOUT) :: EPAI(NPFMAX-1,NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: IVIDE(NPFMAX,NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: CONC(NCOUCH)
      DOUBLE PRECISION, INTENT(INOUT) :: DENSI(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA03(NPOIN2),UETCAR(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: HDEP(NPOIN2),FLUER(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: PDEPOT(NPOIN2)
      DOUBLE PRECISION, INTENT(IN) :: GRADZFX(NPOIN2),GRADZFY(NPOIN2)
      DOUBLE PRECISION, INTENT(IN) :: GRADZSX(NPOIN2),GRADZSY(NPOIN2)
      DOUBLE PRECISION, INTENT(IN) :: DT    , RHO0   , RHOS
      DOUBLE PRECISION, INTENT(IN) :: CFDEP , TOCD   , GRAV
      DOUBLE PRECISION, INTENT(IN) :: MPART , TOCE
      INTEGER, INTENT(INOUT) :: LITABF(NPOIN2), LITABS(NPOIN2)
      INTEGER, INTENT(INOUT) :: NPF(NPOIN2)
      LOGICAL, INTENT(IN)             :: TASSE , GIBSON , SEDCO
      DOUBLE PRECISION, INTENT(IN)    :: AC, KSPRATIO
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE COEF
     &     (IVIDE , EPAI , TRA01 ,
     &      NPFMAX, IMAX , NDEB  ,
     &      RHOS  , GRAV , DTC   , DSIG1    )
         IMPLICIT NONE
         INTEGER, INTENT(IN) ::  NPFMAX , IMAX,NDEB
         DOUBLE PRECISION, INTENT(INOUT) :: TRA01(NPFMAX,6)
         DOUBLE PRECISION, INTENT(IN) :: EPAI(NPFMAX-1), IVIDE(NPFMAX)
         DOUBLE PRECISION, INTENT(IN) :: RHOS , GRAV ,DTC , DSIG1
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE CONDIM
          IMPLICIT NONE
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE CONDIS
     &(IVIDE, EPAI  , TREST , CONC , TEMP   , HDEP   ,
     & ZR   , ZF    , X     , Y    , NPOIN2 , NPOIN3 ,
     & NPF  , NPFMAX, NCOUCH, TASSE, GIBSON , PRIVE  , CONSOL)
          USE BIEF_DEF
          IMPLICIT NONE
          INTEGER, INTENT(IN)             :: NPOIN2,NPOIN3,NPFMAX,NCOUCH
          DOUBLE PRECISION, INTENT(INOUT) :: IVIDE(NPFMAX,NPOIN2)
          DOUBLE PRECISION, INTENT(INOUT) :: EPAI(NPFMAX-1,NPOIN2)
          DOUBLE PRECISION, INTENT(INOUT) :: CONC(NCOUCH)
          DOUBLE PRECISION, INTENT(INOUT) :: TEMP(NCOUCH,NPOIN2)
          DOUBLE PRECISION, INTENT(INOUT) :: HDEP(NPOIN2)
          DOUBLE PRECISION, INTENT(INOUT) :: ZR(NPOIN2)
          DOUBLE PRECISION, INTENT(IN)    :: ZF(NPOIN2)
          DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN2),Y(NPOIN2)
          DOUBLE PRECISION, INTENT(INOUT) :: TREST(NCOUCH)
          INTEGER, INTENT(INOUT)          :: NPF(NPOIN2)
          TYPE(BIEF_OBJ)                  :: PRIVE
          LOGICAL, INTENT(IN)             :: TASSE,GIBSON,CONSOL
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE CORFON
     &(SZF, ST1, ST2, ZF, T1, T2, X, Y, PRIVE, NPOIN2,
     & LISFON, MSK, MASKEL, MATR2D, MESH2D, S)
          USE BIEF_DEF
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: NPOIN2, LISFON
          LOGICAL, INTENT(IN) :: MSK
          TYPE (BIEF_OBJ), INTENT(INOUT) :: SZF, ST1, ST2
          DOUBLE PRECISION, DIMENSION(NPOIN2), INTENT(INOUT) :: ZF,T1,T2
          DOUBLE PRECISION, DIMENSION(NPOIN2), INTENT(IN) :: X,Y
          TYPE (BIEF_OBJ),  INTENT(INOUT) :: PRIVE
          TYPE (BIEF_OBJ),  INTENT(IN)    :: MASKEL
          TYPE (BIEF_OBJ),  INTENT(INOUT) :: MATR2D
          TYPE (BIEF_MESH), INTENT(INOUT) :: MESH2D
          TYPE (BIEF_OBJ),  INTENT(IN)    :: S
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE CORPAR(FVERT,FHORI,PHILATI)
          IMPLICIT NONE
          DOUBLE PRECISION, INTENT(INOUT) :: FVERT,FHORI
          DOUBLE PRECISION, INTENT(IN)    :: PHILATI
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE CORRECTION_DEPTH_3D(W2D,W3D,GLOSEG,DIMGLO)
        USE DECLARATIONS_TELEMAC3D
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: DIMGLO
      INTEGER, INTENT(IN)             :: GLOSEG(DIMGLO,2)
      DOUBLE PRECISION, INTENT(INOUT) :: W2D(NELEM2,3),W3D(NELEM3,6)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE COUPE
     & (F,FINT,SCURV,NPOIN,IKLE3,IFABOR,X,Y,Z,SURFAC,NELEM2,NPOIN3,
     &  NETAGE,X1,Y1,Z1,X2,Y2,Z2)
      IMPLICIT NONE
      INTEGER, INTENT(IN) ::  NPOIN, NELEM2, NPOIN3, NETAGE
      INTEGER, INTENT(IN) ::  IKLE3(NELEM2,NETAGE,6)
      INTEGER, INTENT(IN) ::  IFABOR(NELEM2,3)
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN3)
      DOUBLE PRECISION, INTENT(INOUT) :: FINT(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: SCURV(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN3),Y(NPOIN3),Z(NPOIN3)
      DOUBLE PRECISION, INTENT(IN)    :: SURFAC(NELEM2)
      DOUBLE PRECISION, INTENT(IN)    :: X1,Y1,Z1,X2,Y2,Z2
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE CSTKEP
     & (KARMAN,CMU,C1,C2,SIGMAK,SIGMAE,VIRT,SCHMIT,
     &  KMIN,KMAX,EMIN,EMAX,PRANDTL,ALPHA,BETA,BETAS,OMSTAR,ITURBV)
      IMPLICIT NONE
      INTEGER LNG,LU
      COMMON/INFO/LNG,LU
      INTEGER,          INTENT(IN )   :: ITURBV
      DOUBLE PRECISION, INTENT(INOUT) :: KMIN,KMAX,EMIN,EMAX
      DOUBLE PRECISION, INTENT(INOUT) :: KARMAN,CMU,C1,C2,SIGMAK,SIGMAE
      DOUBLE PRECISION, INTENT(INOUT) :: VIRT,PRANDTL,SCHMIT
      DOUBLE PRECISION, INTENT(INOUT) :: ALPHA,BETA,BETAS,OMSTAR
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE CVDF3D
     & (FD,FC,FN,VISCF,SIGMAF,S0F,YAS0F,S1F,YAS1F,
     &  FBORL, FBORF, FBORS, AFBORL, AFBORF, AFBORS,
     &  BFBORL, BFBORF, BFBORS, LIFBOL, LIFBOF, LIFBOS,
     &  FLUXF, FLUEXTF, FLUEXTPAR,FMIN, CLIMIN, FMAX, CLIMAX,
     &  SCHCF, SCHDF, SLVDIF, TRBAF, INFOR, NEWDIF, CALFLU,
     &  T2_01,T2_02,T2_03,
     &  T3_01,T3_02,T3_03,T3_04, MESH3D , IKLE3 , MASKEL , MTRA1,
     &  W1,NPTFR3,MMURD,MURD_TF,VOLU,VOLUPAR,VOLUN,VOLUNPAR,
     &  NBOR3,NPOIN3,NPOIN2,DT,MSK,NELEM2,NELEM3,
     &  NPLAN,LV,IELM3,MSUPG,IELM2H,IELM2V,MDIFF,MTRA2,
     &  INCHYD,MASKBR,MASKPT,SEM3D,YASEM3D,SVIDE,IT1,IT2,
     &  TRAV3,MESH2D,MATR2H,H,OPTBAN,OPTDIF,TETADI,
     &  YAWCC,WCC,AGGLOD,NSCE,SOURCES,FSCE,NUMLIQ,DIRFLU,NFRLIQ,
     &  VOLUT,ZT,ZPROP,RAIN,PLUIE,PARAPLUIE,
     &  FLODEL,FLOPAR,SIGMAG,IPBOT)
      USE BIEF_DEF
      IMPLICIT NONE
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: FD,FC,FN
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: S0F,S1F,VISCF
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: LIFBOL,LIFBOF,LIFBOS
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: FBORL,FBORF,FBORS
      TYPE(BIEF_OBJ), INTENT(IN)      :: AFBORL,AFBORF,AFBORS
      TYPE(BIEF_OBJ), INTENT(IN)      :: BFBORL,BFBORF,BFBORS,PARAPLUIE
      TYPE(BIEF_OBJ), INTENT(IN)      :: FLUEXTF,PLUIE,FLODEL,FLOPAR
      TYPE(BIEF_OBJ), INTENT(IN)      :: FLUEXTPAR
      DOUBLE PRECISION, INTENT(IN)    :: SIGMAF,FMIN,FMAX,DT
      DOUBLE PRECISION, INTENT(IN)    :: AGGLOD
      DOUBLE PRECISION, INTENT(INOUT) :: FLUXF,TETADI
      INTEGER, INTENT(IN)             :: SCHCF,SCHDF,TRBAF,NPTFR3,NFRLIQ
      INTEGER, INTENT(IN)             :: NUMLIQ(*),DIRFLU(*)
      LOGICAL, INTENT(IN)             :: CLIMIN,CLIMAX,YAS0F,YAS1F
      LOGICAL, INTENT(IN)             :: INFOR,NEWDIF,CALFLU,MSK
      LOGICAL, INTENT(IN)             :: SIGMAG
      TYPE(SLVCFG)                    :: SLVDIF
      TYPE(BIEF_OBJ), INTENT(IN)      :: MASKEL,IKLE3
      TYPE(BIEF_OBJ), INTENT(IN)      :: NBOR3,WCC,SOURCES,ZPROP
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: T3_01,T3_02,T3_03,T3_04,W1
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: T2_01,T2_02,T2_03,ZT
      TYPE(BIEF_OBJ), TARGET, INTENT(INOUT) :: VOLUT
      TYPE(BIEF_MESH), INTENT(INOUT)  :: MESH3D
      INTEGER, INTENT(IN)             :: NPOIN3,NPOIN2
      INTEGER, INTENT(IN)             :: NPLAN,NELEM2,NELEM3,LV
      INTEGER, INTENT(IN)             :: OPTBAN,OPTDIF
      INTEGER, INTENT(IN)             :: IPBOT(NPOIN2)
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: MMURD,MURD_TF,MTRA1
      TYPE(BIEF_OBJ), INTENT(IN)      :: VOLUN,VOLUNPAR,VOLUPAR
      TYPE(BIEF_OBJ), TARGET, INTENT(IN) :: VOLU
      LOGICAL, INTENT(IN)             :: INCHYD,YASEM3D,YAWCC,RAIN
      TYPE(BIEF_OBJ), INTENT(IN)      :: MASKPT,MASKBR,H,SVIDE
      TYPE(BIEF_MESH), INTENT(INOUT)  :: MESH2D
      INTEGER, INTENT(IN)             :: IELM3,IELM2H,IELM2V,NSCE
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: SEM3D,IT1,IT2,TRAV3,MTRA2
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: MSUPG,MDIFF,MATR2H
      DOUBLE PRECISION, INTENT(IN)    :: FSCE(NSCE)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE DEBIMP3D
     &(Q,UBOR,VBOR,WBOR,U,V,H,NUMLIQ,IFRLIQ,
     & T3_01,T3_02,T3_03,
     & NPTFR,NETAGE,MASK,MESH,FORMUL,NPOIN2,
     & IELM2V,SIGMAG,SVIDE,MASKBR,ZPROP)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NPTFR,NETAGE,NPOIN2,IFRLIQ
      INTEGER, INTENT(IN) :: NUMLIQ(NPTFR)
      DOUBLE PRECISION, INTENT(INOUT) :: UBOR(*),VBOR(*),WBOR(*)
      DOUBLE PRECISION, INTENT(IN) :: MASK(*)
      DOUBLE PRECISION, INTENT(IN) :: Q
      CHARACTER(LEN=16) FORMUL
      INTEGER, INTENT(IN) :: IELM2V
      LOGICAL, INTENT(IN) :: SIGMAG
      TYPE(BIEF_MESH) :: MESH
      TYPE(BIEF_OBJ), INTENT(INOUT) :: MASKBR
      TYPE(BIEF_OBJ) , INTENT(INOUT):: H,U,V
      TYPE(BIEF_OBJ) , INTENT(INOUT):: T3_01,T3_02,T3_03
      TYPE(BIEF_OBJ) , INTENT(INOUT) :: ZPROP
      TYPE(BIEF_OBJ) , INTENT(INOUT) :: SVIDE
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE DERI3D
     &(U,V,W,DT,X,Y,ZSTAR,Z,IKLE2,IBOR,LT,NPOIN2,NELEM2,NPLAN,NPLINT,
     & SURDET,XFLOT,YFLOT,ZFLOT,ZSFLOT,SHPFLO,SHZFLO,DEBFLO,FINFLO,
     & ELTFLO,ETAFLO,NFLOT,NITFLO,FLOPRD)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NPOIN2,NELEM2,NPLAN,NPLINT,LT
      INTEGER, INTENT(IN) :: NFLOT,NITFLO,FLOPRD
      INTEGER, INTENT(IN) :: IKLE2(NELEM2,3),IBOR(NELEM2,5,NPLAN-1)
      INTEGER, INTENT(INOUT) :: DEBFLO(NFLOT), FINFLO(NFLOT)
      INTEGER, INTENT(INOUT) :: ELTFLO(NFLOT), ETAFLO(NFLOT)
      DOUBLE PRECISION, INTENT(IN)    :: U(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: V(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: W(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN2),Y(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: Z(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: ZSTAR(NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: XFLOT(NITFLO,NFLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: YFLOT(NITFLO,NFLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: ZFLOT(NITFLO,NFLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: ZSFLOT(NITFLO,NFLOT)
      DOUBLE PRECISION, INTENT(IN)    :: SURDET(NELEM2)
      DOUBLE PRECISION, INTENT(INOUT) :: SHPFLO(3,NFLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: SHZFLO(NFLOT)
      DOUBLE PRECISION, INTENT(IN)    :: DT
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE DESSED
     & (NPF,IVIDE,EPAI,HDEP,CONC,TEMP,ZR,NPOIN2,NPFMAX,NCOUCH,
     &  NIT,GRAPRD,LT,DTC,TASSE,GIBSON,NRSED,TITCAS,BIRSED,GRADEB)
      IMPLICIT NONE
      INTEGER, INTENT(IN)          :: NPOIN2, NPFMAX, NRSED
      INTEGER, INTENT(IN)          :: LT, NIT , NCOUCH
      INTEGER, INTENT(IN)          :: GRAPRD, GRADEB
      INTEGER, INTENT(IN)          :: NPF(NPOIN2)
      DOUBLE PRECISION, INTENT(IN) :: EPAI((NPFMAX-1)*NPOIN2)
      DOUBLE PRECISION, INTENT(IN) :: IVIDE(NPFMAX*NPOIN2)
      DOUBLE PRECISION, INTENT(IN) :: HDEP(NPOIN2), ZR(NPOIN2)
      DOUBLE PRECISION, INTENT(IN) :: CONC(NCOUCH), TEMP(NCOUCH*NPOIN2)
      DOUBLE PRECISION, INTENT(IN) :: DTC
      LOGICAL, INTENT(IN)          :: TASSE,GIBSON
      CHARACTER(LEN=72), INTENT(IN):: TITCAS
      CHARACTER(LEN=3), INTENT(IN) :: BIRSED
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE DIFF3D
     & (FD,FC,FN,VISCF,SIGMAF,S0F,YAS0F,S1F,YAS1F,
     &  FBORL,FBORF,FBORS,AFBORL,AFBORF,AFBORS,
     &  BFBORL,BFBORF,BFBORS,LIFBOF,LIFBOL,LIFBOS,
     &  FMIN,CLIMIN,FMAX,CLIMAX,
     &  SCHCF,SCHDF,SLVDIF,TRBAF,INFO,
     &  NEWDIF,DT,T2_01,T2_02,T2_03,T3_01,T3_02,T3_03,T3_04,
     &  NPOIN2,NPOIN3,INCHYD,SEM3D,YASEM3D,IT1,NPTFR3,NBOR3,MASKPT,
     &  TRAV3,MESH2D,MESH3D,MTRA1,MTRA2,IELM3,MSUPG,IELM2H,IELM2V,
     &  MDIFF,MATR2H,MASKBR,SVIDE,MSK,MASKEL,H,
     &  NPLAN,OPTBAN,OPTDIF,TETADI,YAWCC,WCC,AGGLOD,VOLU,
     &  YASCE,NSCE,FSCE,SOURCES,TETASUPG,VELOCITY,RAIN,PLUIE,
     &  SIGMAG,IPBOT)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: SCHCF,SCHDF,TRBAF,OPTDIF,NSCE
      INTEGER, INTENT(IN)             :: NPOIN2
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: FD,FC,FN,S0F,S1F,VISCF
      TYPE(BIEF_OBJ), INTENT(IN)      :: LIFBOL,LIFBOF,LIFBOS
      TYPE(BIEF_OBJ), INTENT(IN)      :: FBORL,FBORF,FBORS
      TYPE(BIEF_OBJ), INTENT(IN)      :: AFBORL,AFBORF,AFBORS
      TYPE(BIEF_OBJ), INTENT(IN)      :: BFBORL,BFBORF,BFBORS,H,WCC
      DOUBLE PRECISION, INTENT(IN)    :: SIGMAF,FMIN,FMAX,DT,AGGLOD
      DOUBLE PRECISION, INTENT(IN)    :: FSCE(NSCE),TETASUPG
      DOUBLE PRECISION, INTENT(IN)    :: PLUIE(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TETADI
      LOGICAL, INTENT(IN)             :: CLIMIN,CLIMAX,YASCE,VELOCITY
      LOGICAL, INTENT(IN)             :: INFO,NEWDIF,YASEM3D
      LOGICAL, INTENT(IN)             :: YAS0F,YAS1F,SIGMAG
      TYPE(SLVCFG)                    :: SLVDIF
      LOGICAL, INTENT(IN)             :: INCHYD,MSK,YAWCC,RAIN
      TYPE(BIEF_OBJ), INTENT(IN)      :: MASKPT,MASKBR,MASKEL,VOLU
      TYPE(BIEF_OBJ), INTENT(IN)      :: NBOR3,SVIDE,SOURCES
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: T3_01,T3_02,T3_03,T3_04
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: T2_01,T2_02,T2_03
      TYPE(BIEF_MESH), INTENT(INOUT)  :: MESH3D,MESH2D
      INTEGER, INTENT(IN)             :: NPOIN3,IELM3,IELM2H,IELM2V
      INTEGER, INTENT(IN)             :: NPTFR3,NPLAN,OPTBAN
      INTEGER, INTENT(IN)             :: IPBOT(NPOIN2)
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: SEM3D,IT1,TRAV3,MTRA1,MTRA2
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: MSUPG,MDIFF
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: MATR2H
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE DRIALG(FRV,FRT,RI,NPOIN3)
          IMPLICIT NONE
          INTEGER         , INTENT(IN)    :: NPOIN3
          DOUBLE PRECISION, INTENT(INOUT) :: FRV(NPOIN3), FRT(NPOIN3)
          DOUBLE PRECISION, INTENT(INOUT) :: RI(NPOIN3)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE DRICV(FRI,FRT,RI,NPOIN3)
          IMPLICIT NONE
          INTEGER, INTENT(IN)             :: NPOIN3
          DOUBLE PRECISION, INTENT(INOUT) :: FRI(NPOIN3),FRT(NPOIN3)
          DOUBLE PRECISION, INTENT(IN)    :: RI(NPOIN3)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE DRIUTI(FRI,RI,ITYP,ITRAC,NPOIN3)
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: ITYP, ITRAC, NPOIN3
          DOUBLE PRECISION, INTENT(INOUT) :: FRI(NPOIN3)
          DOUBLE PRECISION, INTENT(INOUT) :: RI(NPOIN3)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE DRSURR
     & (DELTAR, TA, BETAC,T0AC,RHO,RHO0,RHOS,DENLAW,SEDI,NTRAC,
     &  IND_T,IND_S)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)           :: NTRAC, DENLAW,IND_T,IND_S
      DOUBLE PRECISION, INTENT(IN)  :: RHO0,RHOS
      DOUBLE PRECISION, INTENT(IN)  :: BETAC(NTRAC), T0AC(NTRAC)
      TYPE(BIEF_OBJ), INTENT(INOUT) :: DELTAR
      TYPE(BIEF_OBJ), INTENT(IN)    :: TA
      TYPE(BIEF_OBJ), INTENT(INOUT) :: RHO
      LOGICAL, INTENT(IN)           :: SEDI
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE ERODC( CONC  , EPAI   , FLUER  , TOB    , DENSI  ,
     &                    MPART , DT     , NPOIN2 , NCOUCH )
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NPOIN2, NCOUCH
      DOUBLE PRECISION, INTENT(IN)    :: CONC(NCOUCH)
      DOUBLE PRECISION, INTENT(INOUT) :: EPAI(NCOUCH,NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: FLUER(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: TOB(NPOIN2), DENSI(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: MPART, DT
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE ERODNC
     &(CFDEP  , WC     , HDEP     , FLUER , TOB   , DT    ,
     & NPOIN2 , NPOIN3 , KSPRATIO , AC    , RHOS  , RHO0  , HN ,
     & GRAV   , DMOY   , CREF     ,ZREF, CF,ICQ ,RUGOF)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NPOIN2,NPOIN3,ICQ
      DOUBLE PRECISION, INTENT(INOUT) :: HDEP(NPOIN2),FLUER(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: WC(NPOIN3)
      DOUBLE PRECISION, INTENT(IN)    :: DT,CFDEP,GRAV,RHOS,RHO0
      DOUBLE PRECISION, INTENT(IN)    :: KSPRATIO,AC
      TYPE(BIEF_OBJ)  , INTENT(IN)    :: DMOY,TOB,CF,HN
      TYPE(BIEF_OBJ)  , INTENT(INOUT) :: CREF,ZREF,RUGOF
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE EXTMSK(MASKBR,MASK,NPTFR,NETAGE)
          USE BIEF_DEF
          IMPLICIT NONE
          INTEGER, INTENT(IN)           :: NPTFR,NETAGE
          DOUBLE PRECISION, INTENT(IN)  :: MASK(*)
          TYPE(BIEF_OBJ), INTENT(INOUT) :: MASKBR
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE FINDKSCE(NPOIN2,NPLAN,Z,NSCE,ISCE,ZSCE,KSCE,INFO)
          IMPLICIT NONE
          INTEGER, INTENT(IN)    :: NPOIN2,NPLAN,NSCE
          INTEGER, INTENT(IN)    :: ISCE(NSCE)
          INTEGER, INTENT(INOUT) :: KSCE(NSCE)
          DOUBLE PRECISION, INTENT(IN) :: Z(NPOIN2,NPLAN)
          DOUBLE PRECISION, INTENT(IN) :: ZSCE(NSCE)
          LOGICAL, INTENT(IN) :: INFO
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE FLOT3D
     &(XFLOT,YFLOT,ZFLOT,NFLOT,NITFLO,FLOPRD,X,Y,Z,NPOIN,DEBFLO,FINFLO,
     & NIT)
      IMPLICIT NONE
      INTEGER, INTENT(IN)    :: NFLOT, NITFLO, FLOPRD, NPOIN, NIT
      INTEGER, INTENT(INOUT) :: DEBFLO(NFLOT), FINFLO(NFLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: XFLOT(NITFLO,NFLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: YFLOT(NITFLO,NFLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: ZFLOT(NITFLO,NFLOT)
      DOUBLE PRECISION, INTENT(IN)  :: X(NPOIN), Y(NPOIN), Z(NPOIN)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE FLUSED
     & (ATABOF , BTABOF , ATABOS , BTABOS ,
     &  LITABF , LITABS , TA     , WC     ,
     &  X      , Y      , Z      , HN     ,
     &  GRADZFX, GRADZFY, GRADZSX, GRADZSY,
     &  TOB    , PDEPOT , FLUER  , TOCD   ,
     &  NPOIN3 , NPOIN2 , NPLAN  , KLOG   , SEDCO)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NPOIN3, NPOIN2, NPLAN, KLOG
      LOGICAL, INTENT(IN) :: SEDCO
      INTEGER, INTENT(IN) :: LITABF(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: ATABOF(NPOIN2), BTABOF(NPOIN2)
      INTEGER, INTENT(INOUT) :: LITABS(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: ATABOS(NPOIN2), BTABOS(NPOIN2)
      DOUBLE PRECISION, INTENT(IN) :: X(NPOIN3), Y(NPOIN3), Z(NPOIN3)
      DOUBLE PRECISION, INTENT(IN) :: TA(NPOIN3), WC(NPOIN3)
      DOUBLE PRECISION, INTENT(IN) :: GRADZFX(NPOIN2), GRADZFY(NPOIN2)
      DOUBLE PRECISION, INTENT(IN) :: GRADZSX(NPOIN2), GRADZSY(NPOIN2)
      DOUBLE PRECISION, INTENT(IN) :: HN(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TOB(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: PDEPOT(NPOIN2), FLUER(NPOIN2)
      DOUBLE PRECISION, INTENT(IN) :: TOCD
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE FLUPRI(VEC,XMUL,U,V,W,X,Y,Z,IKLE,
     &                    NELEM,NELMAX,NELEM2D,NPOIN2,NPOIN3,T1,T2,T3)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NELEM,NELMAX,NELEM2D,NPOIN2,NPOIN3
      DOUBLE PRECISION, INTENT(INOUT) :: VEC(NPOIN3)
      INTEGER, INTENT(IN) :: IKLE(NELMAX,6)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN3),Y(NPOIN3),Z(NPOIN3)
      DOUBLE PRECISION, INTENT(IN)    :: XMUL
      DOUBLE PRECISION, INTENT(INOUT) :: T1(NELEM2D)
      DOUBLE PRECISION, INTENT(INOUT) :: T2(NELEM2D)
      DOUBLE PRECISION, INTENT(INOUT) :: T3(NELEM2D)
      DOUBLE PRECISION, INTENT(IN) :: U(*),V(*),W(*)
C
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE FLUVER_2
     &(FLUVER2,UP,VP,WP,GRADZF,VOLU2D,DSSUDT,NPLAN,NPOIN2)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)           :: NPLAN,NPOIN2
      TYPE(BIEF_OBJ), INTENT(INOUT) :: FLUVER2
      TYPE(BIEF_OBJ), INTENT(IN)    :: UP,VP,WP,GRADZF,VOLU2D,DSSUDT
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE FLUX3D
     &(FLUINT,FLUEXT,FLUEXTPAR,UCONV,VCONV,TRA01,TRA02,TRA03,
     & W1,NETAGE,NPLAN,NELEM3,IELM3,IELM2H,IELM2V,SVIDE,MESH3,
     & MASK1,MSK,MASKEL,MASKBR,LIMPRO,KDIR,NPTFR,DT,VOLU,VOLUN,
     & MESH2,GRAPRD,SIGMAG,TRAV2,NPOIN2,NPOIN3,DM1,ZCONV,
     & FLBOR,PLUIE,RAIN,FLODEL,FLOPAR,OPT_HNEG,FLULIM,YACVVF,LT,BYPASS,
     & N_ADV,MTRA1)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NETAGE,NPLAN,NELEM3,NPOIN2,NPOIN3,LT
      INTEGER, INTENT(IN) :: IELM3, IELM2H, IELM2V,OPT_HNEG
      INTEGER, INTENT(IN) :: KDIR, NPTFR, GRAPRD
      INTEGER, INTENT(IN) :: LIMPRO(NPTFR,6),N_ADV(0:15)
      TYPE(BIEF_OBJ), INTENT(INOUT) :: FLUINT,FLUEXT
      TYPE(BIEF_OBJ), INTENT(IN)    :: VOLU,VOLUN,DM1,ZCONV
      TYPE(BIEF_OBJ), INTENT(IN)    :: UCONV,VCONV,PLUIE
      TYPE(BIEF_OBJ), INTENT(INOUT) :: MASKEL,MASKBR,MTRA1
      TYPE(BIEF_OBJ), INTENT(INOUT) :: FLOPAR,FLULIM,FLUEXTPAR
      TYPE(BIEF_OBJ), INTENT(INOUT), TARGET :: FLODEL
      TYPE(BIEF_OBJ), INTENT(INOUT) :: MASK1,FLBOR
      TYPE(BIEF_OBJ), INTENT(INOUT) :: SVIDE,TRA01,TRA02,TRA03,W1,TRAV2
      TYPE(BIEF_MESH), INTENT(INOUT):: MESH3,MESH2
      DOUBLE PRECISION, INTENT(IN)    :: DT
      LOGICAL, INTENT(IN)             :: MSK,SIGMAG,RAIN,YACVVF,BYPASS
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE FONVAS
     &(IVIDE  , EPAI   , CONC  , TREST  , TEMP   , HDEP  ,
     & PDEPOT , ZR     , ZF    , TA     , WC     , TRA01 ,
     & TRA02  , TRA03  , NPOIN2, NPOIN3 , NPFMAX , NCOUCH,
     & NPF    , LT     , DT     , DTC   , GRAV   , RHOS  ,
     & CFMAX  , CFDEP  , EPAI0 , TASSE  , GIBSON )
      IMPLICIT NONE
      INTEGER, INTENT(IN) ::  LT, NPOIN2, NPOIN3
      INTEGER, INTENT(IN) ::  NPFMAX, NCOUCH
      DOUBLE PRECISION, INTENT(INOUT) :: IVIDE(NPFMAX,NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TREST(NCOUCH)
      DOUBLE PRECISION, INTENT(INOUT) :: TEMP(NCOUCH,NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: HDEP(NPOIN2), PDEPOT(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: EPAI(NPFMAX-1,NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: CONC(NCOUCH)
      DOUBLE PRECISION, INTENT(IN)    :: ZR(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: ZF(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: TA(NPOIN3), WC(NPOIN3)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA01(NPFMAX,6)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA02(NPFMAX),TRA03(NPFMAX)
      DOUBLE PRECISION, INTENT(IN) :: DT, RHOS, GRAV, DTC
      DOUBLE PRECISION, INTENT(INOUT) ::  CFMAX , CFDEP, EPAI0
      INTEGER, INTENT(INOUT) ::  NPF(NPOIN2)
      LOGICAL, INTENT(IN) :: TASSE, GIBSON
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE FSGRAD
     &(GRADZS,ZFLATS,Z,ZF,IELM2H,MESH2D,MSK,MASKEL,UNSV2D,T2_01,
     & NPOIN2,OPTBAN,S)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)                  :: IELM2H,NPOIN2,OPTBAN
      DOUBLE PRECISION, TARGET, INTENT(IN) :: Z(NPOIN2)
      LOGICAL, INTENT(IN)                  :: MSK
      TYPE(BIEF_OBJ), INTENT(INOUT)        :: GRADZS,ZFLATS,T2_01
      TYPE(BIEF_OBJ), INTENT(IN)           :: ZF,UNSV2D,S,MASKEL
      TYPE(BIEF_MESH), INTENT(INOUT)       :: MESH2D
C
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE GESTDP( IVIDE  , EPAI   , HDEP    ,
     &                     NPOIN2 , NPFMAX , NPF     ,
     &                     EPAI0  , CFDEP  , RHOS    )
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: NPOIN2 , NPFMAX
          DOUBLE PRECISION, INTENT(INOUT) :: IVIDE(NPFMAX,NPOIN2)
          DOUBLE PRECISION, INTENT(INOUT) :: EPAI(NPFMAX-1,NPOIN2)
          DOUBLE PRECISION, INTENT(INOUT) :: HDEP(NPOIN2)
          DOUBLE PRECISION, INTENT(INOUT) :: EPAI0
          DOUBLE PRECISION, INTENT(IN)    :: CFDEP , RHOS
          INTEGER, INTENT(INOUT) :: NPF(NPOIN2)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE GRAD2D
     &(DFDX,DFDY,FU,NPLAN,S,UNSV2D,FU2,FU3,FU4,IELM2,MESH2D,MSK,MASKEL)
      USE BIEF_DEF
      IMPLICIT NONE
      TYPE(BIEF_OBJ), INTENT(INOUT) :: DFDX, DFDY
      TYPE(BIEF_OBJ), INTENT(IN)    :: FU
      TYPE(BIEF_OBJ), INTENT(INOUT) :: UNSV2D,S
      TYPE(BIEF_OBJ), INTENT(IN)    :: MASKEL
      TYPE(BIEF_MESH), INTENT(INOUT):: MESH2D
      INTEGER, INTENT(IN)           :: NPLAN, IELM2
      LOGICAL, INTENT(IN)           :: MSK
!     FU2,3,4 MUST BE 2D WORK FIELD - NO CHECKING
      TYPE(BIEF_OBJ), INTENT(INOUT) :: FU2,FU3,FU4
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE IFAB3D
     &(IFABOR,LIUBOF,LIUBOL,LIUBOS,KP1BOR,NELBOR,NULONE,
     & IKLE2,NELEM2,NPOIN2,NPTFR,NPLAN,NPLINT,NETAGE,KLOG,TRANSF)
      IMPLICIT NONE
      INTEGER, INTENT(IN)          :: NELEM2,NPOIN2,NETAGE,NPLAN,TRANSF
      INTEGER, INTENT(IN)          :: NPTFR, NPLINT
      INTEGER, INTENT(INOUT)       :: IFABOR(NELEM2,5,NETAGE)
      INTEGER, INTENT(IN)          :: LIUBOF(NPOIN2),LIUBOS(NPOIN2)
      INTEGER, INTENT(IN)          :: LIUBOL(NPTFR,NPLAN)
      INTEGER, INTENT(IN)          :: IKLE2(NELEM2,3)
      INTEGER, INTENT(IN)          :: NULONE(NPTFR,NETAGE,4)
      INTEGER, INTENT(IN)          :: KP1BOR(NPTFR), NELBOR(NPTFR)
      INTEGER, INTENT(IN)          :: KLOG
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE IMPSED
     &(IVIDE , EPAI  , CONC  , TEMP  , HDEP  , PDEPOT,
     & FLUER , ZR    , ZF    , TA    , WC    , X     ,
     & Y     , NPOIN2, NPOIN3, NPFMAX, NCOUCH, NPF   ,
     & LT    , RHOS  , CFMAX , CFDEP , EPAI0 ,
     & TASSE , GIBSON, PRIVE , LISPRD)
          USE BIEF_DEF
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: NPOIN2,NPOIN3,NPFMAX,NCOUCH,LT,LISPRD
          DOUBLE PRECISION, INTENT(IN)  :: EPAI(NPFMAX-1,NPOIN2)
          DOUBLE PRECISION, INTENT(IN)  :: IVIDE(NPFMAX,NPOIN2)
          DOUBLE PRECISION, INTENT(IN)  :: HDEP(NPOIN2),PDEPOT(NPOIN2)
          DOUBLE PRECISION, INTENT(IN)  :: FLUER(NPOIN2)
          DOUBLE PRECISION, INTENT(IN)  :: CONC(NCOUCH)
          DOUBLE PRECISION, INTENT(IN)  :: TEMP(NCOUCH,NPOIN2)
          DOUBLE PRECISION, INTENT(IN)  :: ZR(NPOIN2), ZF(NPOIN2)
          DOUBLE PRECISION, INTENT(IN)  :: TA(NPOIN3)
          DOUBLE PRECISION, INTENT(IN)  :: WC(NPOIN3)
          DOUBLE PRECISION, INTENT(IN)  :: X(NPOIN3), Y(NPOIN3)
          TYPE(BIEF_OBJ), INTENT(INOUT) :: PRIVE
          DOUBLE PRECISION, INTENT(IN)  :: RHOS,CFMAX,CFDEP,EPAI0
          INTEGER, INTENT(IN) :: NPF(NPOIN2)
          LOGICAL, INTENT(IN) :: TASSE , GIBSON
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE KEPCL3
     & (KBORF,EBORF,LIKBOF,LIEBOF,LIUBOF,
     &  KBORL,EBORL,LIKBOL,LIEBOL,LIUBOL,RUGOL,
     &  KBORS,EBORS,LIKBOS,LIEBOS,LIUBOS,
     &  DISBOR,AK,U,V,H,Z,NBOR,NPOIN2,NPLAN,NPTFR,
     &  DNUVIH,DNUVIV,KARMAN,CMU,LISRUF,LISRUL,
     &  VIRT,KMIN,KMAX,EMIN,EMAX,KENT,KENTU,KSORT,KADH,KLOG,
     &  UETCAR,UETCAL)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NPTFR, NPLAN, NPOIN2,KENTU
      INTEGER, INTENT(IN) :: LISRUF,LISRUL,KENT,KSORT,KADH,KLOG
      INTEGER, INTENT(INOUT) :: LIKBOF(NPOIN2), LIKBOS(NPOIN2)
      INTEGER, INTENT(INOUT) :: LIKBOL(NPTFR,NPLAN)
      INTEGER, INTENT(INOUT) :: LIEBOF(NPOIN2), LIEBOS(NPOIN2)
      INTEGER, INTENT(INOUT) :: LIEBOL(NPTFR,NPLAN)
      INTEGER, INTENT(INOUT) :: LIUBOF(NPOIN2), LIUBOS(NPOIN2)
      INTEGER, INTENT(INOUT) :: LIUBOL(NPTFR,NPLAN)
      INTEGER, INTENT(IN) :: NBOR(NPTFR)
      DOUBLE PRECISION, INTENT(IN) :: U(NPOIN2,NPLAN),V(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN) :: Z(NPOIN2,NPLAN),AK(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN) :: H(NPOIN2) , UETCAR(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: KBORF(NPOIN2), KBORS(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: KBORL(NPTFR,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: EBORF(NPOIN2), EBORS(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: EBORL(NPTFR,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: UETCAL(NPTFR,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: DISBOR(NPTFR)
      DOUBLE PRECISION, INTENT(IN)    :: RUGOL(NPTFR,NPLAN)
      DOUBLE PRECISION, INTENT(IN) :: VIRT, DNUVIH, DNUVIV, KARMAN
      DOUBLE PRECISION, INTENT(IN) :: CMU
      DOUBLE PRECISION, INTENT(IN) :: KMIN, KMAX, EMIN, EMAX
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE KEPICL
     & (LIKBOF,LIEBOF,LIUBOF,LIKBOL,LIEBOL,LIUBOL,LIKBOS,LIEBOS,LIUBOS,
     &  NPTFR,NPLAN,NPOIN2,KENT,KSORT,KADH,KLOG)
          IMPLICIT NONE
          INTEGER, INTENT(IN)    :: NPTFR, NPLAN, NPOIN2
          INTEGER, INTENT(IN)    :: KENT, KSORT, KADH, KLOG
          INTEGER, INTENT(IN)    :: LIUBOF(NPOIN2), LIUBOS(NPOIN2)
          INTEGER, INTENT(IN)    :: LIUBOL(NPTFR,NPLAN)
          INTEGER, INTENT(INOUT) :: LIKBOF(NPOIN2), LIKBOS(NPOIN2)
          INTEGER, INTENT(INOUT) :: LIKBOL(NPTFR,NPLAN)
          INTEGER, INTENT(INOUT) :: LIEBOF(NPOIN2), LIEBOS(NPOIN2)
          INTEGER, INTENT(INOUT) :: LIEBOL(NPTFR,NPLAN)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE KEPINI
     &(AK,EP,U,V,Z,ZF,NPOIN2,NPLAN,DNUVIH,DNUVIV,KARMAN,CMU,KMIN,EMIN)
      IMPLICIT NONE
      INTEGER, INTENT(IN)            :: NPOIN2,NPLAN
      DOUBLE PRECISION, INTENT(INOUT):: AK(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT):: EP(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN)   :: U(NPOIN2,NPLAN), V(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN)   :: Z(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN)   :: ZF(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)   :: KARMAN, DNUVIH, DNUVIV
      DOUBLE PRECISION, INTENT(IN)   :: CMU
      DOUBLE PRECISION, INTENT(IN)   :: KMIN, EMIN
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE KOMCL3
     & (KBORF,EBORF,LIKBOF,LIEBOF,LIUBOF,
     &  KBORL,EBORL,LIKBOL,LIEBOL,LIUBOL,RUGOL,
     &  KBORS,EBORS,LIKBOS,LIEBOS,LIUBOS,
     &  DISBOR,AK,EP,U,V,W,H,Z,NBOR,NPOIN2,NPLAN,NPTFR,
     &  DNUVIH,DNUVIV,KARMAN, ALPHA,BETA,BETAS,OMSTAR,SCHMIT,LISRUF,
     &  LISRUL,VIRT,GRAV,KMIN,KMAX,EMIN,EMAX,KENTU,KENT,KSORT,KADH,KLOG,
     &  UETCAR,UETCAL)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NPTFR, NPLAN, NPOIN2
      INTEGER, INTENT(IN) :: LISRUF, LISRUL,KENTU,KENT,KSORT,KADH,KLOG
      INTEGER, INTENT(INOUT) :: LIKBOF(NPOIN2), LIKBOS(NPOIN2)
      INTEGER, INTENT(INOUT) :: LIKBOL(NPTFR,NPLAN)
      INTEGER, INTENT(INOUT) :: LIEBOF(NPOIN2), LIEBOS(NPOIN2)
      INTEGER, INTENT(INOUT) :: LIEBOL(NPTFR,NPLAN)
      INTEGER, INTENT(INOUT) :: LIUBOF(NPOIN2), LIUBOS(NPOIN2)
      INTEGER, INTENT(INOUT) :: LIUBOL(NPTFR,NPLAN)
      INTEGER, INTENT(IN) :: NBOR(NPTFR)
      DOUBLE PRECISION, INTENT(IN) :: U(NPOIN2,NPLAN), V(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN) :: W(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN) :: Z(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN) :: AK(NPOIN2,NPLAN),EP(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN) :: H(NPOIN2),UETCAR(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: KBORF(NPOIN2), KBORS(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: KBORL(NPTFR,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: EBORF(NPOIN2), EBORS(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: EBORL(NPTFR,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: UETCAL(NPTFR,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: DISBOR(NPTFR)
      DOUBLE PRECISION, INTENT(IN)    :: RUGOL(NPTFR,NPLAN)
      DOUBLE PRECISION, INTENT(IN) :: VIRT, DNUVIH, DNUVIV, KARMAN
      DOUBLE PRECISION, INTENT(IN) :: ALPHA,BETA,BETAS,OMSTAR
      DOUBLE PRECISION, INTENT(IN) :: SCHMIT,GRAV
      DOUBLE PRECISION, INTENT(IN) :: KMIN, KMAX, EMIN, EMAX
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE LECDON_TELEMAC3D(MOTCAR,FILE_DESC,PATH,NCAR)
          IMPLICIT NONE
          CHARACTER(LEN=144), INTENT(INOUT) :: MOTCAR(300)
          CHARACTER(LEN=144), INTENT(INOUT) :: FILE_DESC(4,300)
          CHARACTER(LEN=250), INTENT(IN) :: PATH
          INTEGER, INTENT(IN) :: NCAR
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE LICHEK(LIMPRP, NPTFR)
          IMPLICIT NONE
          INTEGER, INTENT(IN)    :: NPTFR
          INTEGER, INTENT(INOUT) :: LIMPRP(NPTFR,6)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE LIMTEL
     &(UBOR2D,VBOR2D,UBORL,VBORL,Z,TRA01,TRA02,TRA03,TRA04,NBOR,
     & NPTFR,NPLAN,NPOIN2,OPTBAN)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NPTFR, NPLAN, NPOIN2,OPTBAN
      INTEGER, INTENT(IN) :: NBOR(NPTFR)
      DOUBLE PRECISION, INTENT(INOUT) :: UBOR2D(NPTFR),VBOR2D(NPTFR)
      DOUBLE PRECISION, INTENT(IN)    :: Z(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: UBORL(NPTFR,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: VBORL(NPTFR,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA01(NPTFR,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA02(NPTFR,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA03(NPTFR,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA04(NPTFR,NPLAN)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE LONGMB
     &(LM,Z,HN,NPOIN3,NPOIN2,NPLAN,U,V,X,Y,P1,P2,P3,NTRAC,TA,KARMAN,ZF)
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NPOIN3, NPOIN2, NPLAN, NTRAC
      DOUBLE PRECISION, INTENT(INOUT) :: LM(NPOIN3) ! POINTER
      DOUBLE PRECISION, INTENT(IN)    :: Z(NPOIN3), HN(NPOIN2),KARMAN
      DOUBLE PRECISION, INTENT(IN)    :: U(NPOIN3), V(NPOIN3)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN3), Y(NPOIN3)
      DOUBLE PRECISION, INTENT(INOUT) :: P1(NPOIN3), P2(NPOIN3)
      DOUBLE PRECISION, INTENT(INOUT) :: P3(NPOIN3)
      DOUBLE PRECISION, INTENT(IN)    :: TA(NPOIN3),ZF(NPOIN2)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE LONGML
     & (LM2,Z,HN,NPOIN3,NPOIN2,NPLAN,MIXING,KARMAN,ZF)
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NPOIN3,NPOIN2,NPLAN,MIXING
      DOUBLE PRECISION, INTENT(INOUT) :: LM2(NPOIN3)
      DOUBLE PRECISION, INTENT(IN)    :: Z(NPOIN3),HN(NPOIN2),KARMAN
      DOUBLE PRECISION, INTENT(IN)    :: ZF(NPOIN2)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE MASK3D
     &(IFABOR3D,MASKEL,MASKPT,MASKBR,
     & X,Y,ZF,ZFE,H,HMIN,AT,LT,ITRA01,NELBO3,
     & NELMA2,NELEM2,NPOIN2,NPTFR,NPLAN,NETAGE,IELM3,MESH2D)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NELEM2, NPOIN2, NETAGE, NPLAN
      INTEGER, INTENT(IN)             :: NELMA2, NPTFR
      INTEGER, INTENT(INOUT)          :: IFABOR3D(NELEM2,5,NETAGE)
      DOUBLE PRECISION, INTENT(INOUT) :: MASKEL(NELEM2,NETAGE)
      DOUBLE PRECISION, INTENT(INOUT) :: MASKBR(NPTFR,NETAGE)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN2), Y(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: ZF(NPOIN2), H(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: ZFE(NELEM2)
      INTEGER, INTENT(IN)             :: NELBO3(NPTFR,NETAGE)
      INTEGER, INTENT(INOUT)          :: ITRA01(NELEM2)
      INTEGER, INTENT(IN)             :: LT, IELM3
      DOUBLE PRECISION, INTENT(IN)    :: HMIN, AT
      TYPE(BIEF_MESH), INTENT(INOUT)  :: MESH2D
      TYPE(BIEF_OBJ) , INTENT(INOUT)  :: MASKPT
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE MASS3D(INFO,LT)
          IMPLICIT NONE
          LOGICAL, INTENT(IN) :: INFO
          INTEGER, INTENT(IN) :: LT
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE MASSED
     &(MASSE,EPAI,CONC,HDEP,TRA02,NPOIN2,  
     & NPFMAX,NCOUCH,NPF,TASSE,GIBSON,RHOS,CFDEP,VOLU2D)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NPFMAX,NPOIN2,NCOUCH
      INTEGER, INTENT(IN)             :: NPF(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: MASSE
      DOUBLE PRECISION, INTENT(IN)    :: EPAI(NPFMAX-1,NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: VOLU2D(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: HDEP(NPOIN2),CONC(NCOUCH)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA02(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: RHOS,CFDEP
      LOGICAL, INTENT(IN)             :: TASSE,GIBSON
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE MESH_PROP
     &(HPROP ,HN,H,PROLIN,HAULIN,TETA,NSOUSI,ZPROP,
     & IPBOT,NPOIN2,NPLAN,OPTBAN,SIGMAG,OPT_HNEG,
     & MDIFF,MESH3D,VOLU3D,VOLU3DPAR,UNSV3D,MSK,MASKEL,IELM3)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)            :: NSOUSI,NPOIN2,NPLAN,OPT_HNEG
      INTEGER, INTENT(IN)            :: OPTBAN,IELM3
      LOGICAL, INTENT(IN)            :: PROLIN,SIGMAG,MSK
      DOUBLE PRECISION, INTENT(IN)   :: TETA,HAULIN
      TYPE(BIEF_OBJ),   INTENT(IN)   :: HN,H,IPBOT,MASKEL
      TYPE(BIEF_OBJ),  INTENT(INOUT) :: HPROP,ZPROP,MDIFF,UNSV3D,VOLU3D
      TYPE(BIEF_OBJ),  INTENT(INOUT) :: VOLU3DPAR
      TYPE(BIEF_MESH), INTENT(INOUT) :: MESH3D
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE MITCL2
     & (H,LIHBOR,NBOR,HBOR,AT,NPOIN2,NPTFR,KENT,KSORT,KADH,KLOG,KDEB)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: KENT,KSORT,KADH,KDEB,KLOG,NPTFR,NPOIN2
      INTEGER, INTENT(IN) :: LIHBOR(NPTFR),NBOR(NPTFR)
      DOUBLE PRECISION, INTENT(INOUT) :: H(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: HBOR(NPTFR),AT
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE MITTIT(IETAPE,AT,LT)
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: IETAPE,LT
          DOUBLE PRECISION, INTENT(IN) :: AT
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE MURD3D
     &(FC,FN,VOLU,VOLUN,VOLU2,SVOLU2,DA,XA,DB,XB,
     & TRA01,TRA02,TRA03,STRA01,STRA02,STRA03,W1,IKLE3,MESH3,
     & NELEM3,NPOIN3,DT,SCHCF,LV,MSK,MASKEL,INFOR,CALFLU,FLUX,FLUEXT,
     & S0F,NSCE,SOURCES,FSCE,RAIN,PLUIE,NPOIN2,MINFC,MAXFC,MASKPT,
     & OPTBAN,FLODEL,FLOPAR,GLOSEG,DIMGLO,NSEG,NPLAN)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: SCHCF,NELEM3,NPOIN3,LV,NPOIN2
      INTEGER, INTENT(IN)             :: IKLE3(NELEM3,6),NSCE,OPTBAN
      INTEGER, INTENT(IN)             :: NSEG,NPLAN,DIMGLO
      INTEGER, INTENT(IN)             :: GLOSEG(DIMGLO,2)
      DOUBLE PRECISION, INTENT(INOUT) :: FC(NPOIN3)
      DOUBLE PRECISION, INTENT(IN)    :: FN(NPOIN3),PLUIE(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: W1(NELEM3,6)
      DOUBLE PRECISION, INTENT(IN)    :: MASKEL(NELEM3), FLUEXT(NPOIN3)
      DOUBLE PRECISION, INTENT(IN)    :: VOLUN(NPOIN3), VOLU(NPOIN3)
      DOUBLE PRECISION, INTENT(INOUT) :: VOLU2(NPOIN3)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA01(NPOIN3)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA02(NPOIN3), TRA03(NPOIN3)
      DOUBLE PRECISION, INTENT(INOUT) :: FLUX
      DOUBLE PRECISION, INTENT(IN)    :: DT,FSCE(NSCE),MASKPT(NPOIN3)
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: SVOLU2,MINFC,MAXFC
      TYPE(BIEF_OBJ), INTENT(IN)      :: SOURCES,S0F
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: STRA01,STRA02,STRA03
      TYPE(BIEF_MESH), INTENT(INOUT)  :: MESH3
      DOUBLE PRECISION, INTENT(INOUT) :: DA(NPOIN3),XA(30,NELEM3)
      DOUBLE PRECISION, INTENT(INOUT) :: DB(NPOIN3),XB(30,NELEM3)
C     DIMENSION OF FLODEL AND FLOPAR=NSEG2D*NPLAN+NPOIN2*NETAGE
      DOUBLE PRECISION, INTENT(IN)    :: FLODEL(*),FLOPAR(*)
      LOGICAL, INTENT(IN)             :: MSK,INFOR,CALFLU,RAIN
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE MURD3D_POS
     &(FC,FN,VOLU,SVOLU,VOLUN,SVOLUN,VOLU2,SVOLU2,RMASS,
     & TRA01,TRA02,TRA03,STRA01,STRA02,STRA03,MESH2,MESH3,
     & NELEM3,NPOIN3,DT,SCHCF,MSK,MASKEL,INFOR,CALFLU,FLUX,FLUEXT,
     & S0F,NSCE,SOURCES,FSCE,RAIN,PLUIE,NPOIN2,
     & OPTBAN,FLODEL,FLOPAR,GLOSEG,DIMGLO,NSEG,NPLAN,
     & T5,FLUX_REMOVED,SAVED_VOLU2,SAVED_F,OPTION)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: SCHCF,NELEM3,NPOIN3,NPOIN2
      INTEGER, INTENT(IN)             :: NSCE,OPTBAN,NSEG,NPLAN,DIMGLO
      INTEGER, INTENT(IN)             :: GLOSEG(DIMGLO,2),OPTION
      DOUBLE PRECISION, INTENT(INOUT) :: FC(NPOIN3)
      DOUBLE PRECISION, INTENT(IN)    :: FN(NPOIN3),PLUIE(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: MASKEL(NELEM3)
      DOUBLE PRECISION, INTENT(IN), TARGET    :: FLUEXT(NPOIN3)
      DOUBLE PRECISION, INTENT(IN)    :: VOLUN(NPOIN3), VOLU(NPOIN3)
      DOUBLE PRECISION, INTENT(INOUT) :: VOLU2(NPOIN3)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA01(NPOIN3),FLUX
      DOUBLE PRECISION, INTENT(INOUT) :: TRA02(NPOIN3)
      DOUBLE PRECISION, INTENT(INOUT), TARGET :: TRA03(NPOIN3)
      DOUBLE PRECISION, INTENT(IN)    :: DT,FSCE(NSCE)
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: SVOLU2
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: FLUX_REMOVED
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: SAVED_VOLU2,SAVED_F,T5
      TYPE(BIEF_OBJ), INTENT(IN)      :: SOURCES,S0F,SVOLU,SVOLUN
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: STRA01,STRA02,STRA03
      TYPE(BIEF_MESH), INTENT(INOUT)  :: MESH2,MESH3
      DOUBLE PRECISION, INTENT(IN)    :: FLODEL(*),FLOPAR(*)
      DOUBLE PRECISION, INTENT(INOUT) :: RMASS(*)
      LOGICAL, INTENT(IN)             :: MSK,INFOR,CALFLU,RAIN
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE NOMVAR_2D_IN_3D(TEXTE,TEXTPR,MNEMO,NTRAC,NAMETRAC)
          IMPLICIT NONE
          CHARACTER(LEN=32), INTENT(INOUT) :: TEXTE(*),TEXTPR(*)
          CHARACTER(LEN=8) , INTENT(INOUT) :: MNEMO(*)
          CHARACTER(LEN=32), INTENT(IN)    :: NAMETRAC(32)
          INTEGER, INTENT(IN) :: NTRAC
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE NOMVAR_TELEMAC3D(TEXT3,TEXTP3,MNEMO,NTRAC,NAMETRAC)
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: NTRAC
          CHARACTER(LEN=32), INTENT(INOUT) :: TEXT3(100),TEXTP3(100)
          CHARACTER(LEN=32), INTENT(IN)    :: NAMETRAC(32)
          CHARACTER(LEN=8), INTENT(INOUT)  :: MNEMO(100)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE NUWAVE_P0
     &(NUWAVE,DM1,Z,DZ,IKLE,NPOIN2,NPLAN,NELMAX,NELEM2,XMUL)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER,          INTENT(IN)    :: NPOIN2,NPLAN,NELMAX,NELEM2
      INTEGER,          INTENT(IN)    :: IKLE(NELMAX,3)
      DOUBLE PRECISION, INTENT(INOUT) :: NUWAVE(NELEM2),DZ(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: DM1(NPOIN2,NPLAN),XMUL
      DOUBLE PRECISION, INTENT(IN)    :: Z(NPOIN2,NPLAN)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE PHSTAT
     &   (PH, DELTAR, Z, TRA01, TRA02, RHO0, GRAV,
     &    NPOIN3, NPOIN2, NPLAN, PRIVE )
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NPOIN3, NPOIN2, NPLAN
      DOUBLE PRECISION, INTENT(INOUT) :: PH(NPOIN3)
      DOUBLE PRECISION, INTENT(IN)    :: DELTAR(NPOIN3), Z(NPOIN3)
      DOUBLE PRECISION,INTENT(INOUT)  :: TRA01(NPOIN3), TRA02(NPOIN3)
      TYPE (BIEF_OBJ), INTENT(INOUT)  :: PRIVE
      DOUBLE PRECISION, INTENT(IN)    :: RHO0, GRAV
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE PRECON(WP,WPS,ZPROPS,ISOUSI,LT)
          USE BIEF_DEF
          IMPLICIT NONE
          TYPE(BIEF_OBJ), INTENT(INOUT) :: WP,WPS
          TYPE(BIEF_OBJ), INTENT(INOUT) :: ZPROPS
          INTEGER, INTENT(IN) :: ISOUSI,LT
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE PREDIV(PD,UP,VP,WP,INFO,BC,OPT,DIRSUR,DIRBOT,DIRLAT)
          USE BIEF_DEF
          IMPLICIT NONE
          INTEGER, INTENT(IN)             :: OPT
          TYPE(BIEF_OBJ), INTENT(INOUT)   :: PD
          TYPE(BIEF_OBJ), INTENT(IN)      :: UP,VP,WP
          LOGICAL, INTENT(IN)             :: INFO,BC
          LOGICAL, INTENT(IN)             :: DIRSUR,DIRBOT,DIRLAT
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE PREPARE_ADVECTION(FN,S0F,FBORL,LIFBOL,FLUXF,
     &  SCHCF,CALFLU,MESH3D,MASKEL,NPTFR3,VOLUNPAR,FLUEXT,FLUEXTPAR,
     &  NBOR3,DT,MSK,IELM3,NUMLIQ,DIRFLU,NFRLIQ)
      USE BIEF_DEF
      IMPLICIT NONE
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: FN,S0F,LIFBOL,FBORL
      TYPE(BIEF_OBJ), INTENT(IN)      :: FLUEXT,FLUEXTPAR
      DOUBLE PRECISION, INTENT(IN)    :: DT
      DOUBLE PRECISION, INTENT(INOUT) :: FLUXF
      INTEGER, INTENT(IN)             :: SCHCF,NPTFR3,NFRLIQ,IELM3
      INTEGER, INTENT(IN)             :: NUMLIQ(*),DIRFLU(*)
      LOGICAL, INTENT(IN)             :: CALFLU,MSK
      TYPE(BIEF_OBJ), INTENT(IN)      :: MASKEL,NBOR3,VOLUNPAR
      TYPE(BIEF_MESH), INTENT(INOUT)  :: MESH3D
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE PRERES_TELEMAC3D(LT)
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: LT
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        DOUBLE PRECISION FUNCTION Q3( I , AT , INFOGR )
          IMPLICIT NONE
          INTEGER          , INTENT(IN) :: I
          DOUBLE PRECISION , INTENT(IN) :: AT
          LOGICAL          , INTENT(IN) :: INFOGR
        END FUNCTION
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE RHS_PRESSURE
     &(DIVU,UP,VP,WP,IELM3,DM1,ZCONV,SVIDE,MESH3D,MSK,MASKEL,FLUEXT,
     & NSCE,RAIN,PLUIE,SOURCES,GRADZF,VOLU2D,DSSUDT,NPOIN2,NPOIN3,NPLAN)  
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER,         INTENT(IN)    :: IELM3,NSCE,NPOIN2,NPOIN3,NPLAN
      LOGICAL,         INTENT(IN)    :: MSK,RAIN
      TYPE(BIEF_OBJ),  INTENT(INOUT) :: DIVU
      TYPE(BIEF_OBJ),  INTENT(IN)    :: UP,VP,WP,PLUIE,SOURCES,GRADZF
      TYPE(BIEF_OBJ),  INTENT(IN)    :: DM1,ZCONV,SVIDE,MASKEL,FLUEXT
      TYPE(BIEF_OBJ),  INTENT(IN)    :: VOLU2D,DSSUDT
      TYPE(BIEF_MESH), INTENT(INOUT) :: MESH3D   
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE SCOPE
     & (U,V,W,HN,ZF,X,Y,Z,TRA01,TRA02,TRA03,SURFAC,IKLE3,IFABOR,NELEM3,
     &  NELEM2,NPOIN2,NPOIN3,NETAGE,NPLAN,LT,AT,DT,NIT,NSCO,PRIVE)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NSCO,NPOIN2,NELEM2,NPOIN3,NETAGE
      INTEGER, INTENT(IN) :: NIT,LT,NELEM3,NPLAN
      INTEGER, INTENT(IN) :: IKLE3(NELEM3,6), IFABOR(NELEM2,3)
      DOUBLE PRECISION, INTENT(IN)    :: U(NPOIN3),V(NPOIN3),W(NPOIN3)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN3),Y(NPOIN3),Z(NPOIN3)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA01(NPOIN3), TRA02(NPOIN3)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA03(NPOIN3)
      DOUBLE PRECISION, INTENT(IN)    :: HN(NPOIN2),ZF(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: SURFAC(NELEM2)
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: PRIVE
      DOUBLE PRECISION, INTENT(IN) :: DT,AT
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE SED3D
     &(MASSE1,WC,TA,EPAI,HDEP,CONC,FLUER,PDEPOT,TRA02,
     & NELEM2,NPOIN2,NPOIN3,NPFMAX,NCOUCH,
     & NPF,DT,TASSE,GIBSON,RHOS,CFDEP,VOLU2D)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NPFMAX,NCOUCH,NELEM2,NPOIN2,NPOIN3
      INTEGER, INTENT(IN) :: NPF(NPOIN2)
      DOUBLE PRECISION, INTENT(IN) :: MASSE1
      DOUBLE PRECISION, INTENT(IN) :: WC(NPOIN3)
      DOUBLE PRECISION, INTENT(IN) :: TA(NPOIN3),VOLU2D(NPOIN2)
      DOUBLE PRECISION, INTENT(IN) :: EPAI(NPFMAX-1,NPOIN2)
      DOUBLE PRECISION, INTENT(IN) :: HDEP(NPOIN2),FLUER(NPOIN2)
      DOUBLE PRECISION, INTENT(IN) :: PDEPOT(NPOIN2),CONC(NCOUCH)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA02(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: DT,RHOS,CFDEP
      LOGICAL, INTENT(IN)             :: TASSE , GIBSON
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE SFLO3D
     &(XFLOT,YFLOT,ZFLOT,IKLFLO,TRAFLO,DEBFLO,FINFLO,NFLOT,NITFLO,
     & FLOPRD,NREBI,LISTIN,TITCAS,BINRES,NOMRBI,NIT,
     & I_ORIG,J_ORIG)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NFLOT,NIT,NITFLO,NREBI,FLOPRD
      INTEGER, INTENT(IN) :: I_ORIG,J_ORIG
      INTEGER, INTENT(INOUT) :: IKLFLO(3*NITFLO*NFLOT)
      INTEGER, INTENT(INOUT) :: TRAFLO(3*NITFLO*NFLOT)
      INTEGER, INTENT(INOUT) :: DEBFLO(NFLOT), FINFLO(NFLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: XFLOT(NITFLO*NFLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: YFLOT(NITFLO*NFLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: ZFLOT(NITFLO*NFLOT)
      CHARACTER(LEN=72), INTENT(IN) :: TITCAS, NOMRBI
      CHARACTER(LEN=3),  INTENT(IN) :: BINRES
      LOGICAL, INTENT(IN) :: LISTIN
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        DOUBLE PRECISION FUNCTION SL3( I , AT , N , INFOGR )
          IMPLICIT NONE
          INTEGER          , INTENT(IN) :: I,N
          DOUBLE PRECISION , INTENT(IN) :: AT
          LOGICAL          , INTENT(IN) :: INFOGR
        END FUNCTION
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE SMAGO3D
     &(U,V,W,TRAV1,TRAV2,TRAV3,TRAV4,TRAV5,TRAV6,
     & SVIDE,MESH3,IELM3,MSK,MASKEL)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)            :: IELM3
      LOGICAL, INTENT(IN)            :: MSK
      TYPE (BIEF_OBJ), INTENT(IN)    :: U, V, W
      TYPE (BIEF_OBJ), INTENT(INOUT) :: TRAV1, TRAV2, TRAV3, TRAV4,TRAV6
      TYPE (BIEF_OBJ), INTENT(INOUT) :: TRAV5
      TYPE (BIEF_OBJ), INTENT(IN)    :: MASKEL
      TYPE (BIEF_OBJ), INTENT(INOUT) :: SVIDE
      TYPE (BIEF_MESH)               :: MESH3
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE SMAGO(U,V,T1,T2,T3,T4,NUSMAG,MESH3,IELM3,MSK,MASKEL)
          USE BIEF_DEF
          IMPLICIT NONE
          INTEGER, INTENT(IN)            :: IELM3
          LOGICAL, INTENT(IN)            :: MSK
          TYPE (BIEF_OBJ), INTENT(IN)    :: U, V
          TYPE (BIEF_OBJ), INTENT(INOUT) :: T1,T2,T3,T4
          TYPE (BIEF_OBJ), INTENT(INOUT) :: NUSMAG
          TYPE (BIEF_OBJ), INTENT(IN)    :: MASKEL
          TYPE (BIEF_MESH), INTENT(INOUT):: MESH3
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE SOUKEP
     &(CV1,CV2,S1K,S1E,U,V,W,DELTAR,RI,
     & DUDX,DUDY,DUDZ,DVDX,DVDY,DVDZ,DWDX,DWDY,DWDZ,DTADZ,
     & AK,EP,C1,C2,CMU,GRAV,TR,NPOIN3,MSK,MASKEL,MESH3D,IELM3,S,DT,
     & VENT,WIND,H,EBORS,NPOIN2,KMIN,EMIN,PRANDTL)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NPOIN3,IELM3,NPOIN2
      DOUBLE PRECISION, INTENT(INOUT) :: CV1(NPOIN3),CV2(NPOIN3)
      DOUBLE PRECISION, INTENT(INOUT) :: S1K(NPOIN3),S1E(NPOIN3)
      DOUBLE PRECISION, INTENT(INOUT) :: AK(NPOIN3),EP(NPOIN3)
      DOUBLE PRECISION, INTENT(INOUT) :: RI(NPOIN3)
      TYPE (BIEF_OBJ), INTENT(INOUT)  :: DUDX,DUDY,DUDZ,DVDX,DVDY,EBORS
      TYPE (BIEF_OBJ), INTENT(INOUT)  :: DVDZ,DWDX,DWDY,DWDZ,DTADZ,TR
      TYPE (BIEF_OBJ), INTENT(IN)     :: MASKEL,U,V,W,DELTAR,S,WIND,H
      DOUBLE PRECISION, INTENT(IN)    :: C1,C2,CMU,GRAV,DT,KMIN,EMIN
      DOUBLE PRECISION, INTENT(IN)    :: PRANDTL
      LOGICAL, INTENT(IN)             :: MSK,VENT
      TYPE (BIEF_MESH), INTENT(INOUT) :: MESH3D
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE SOUKOM(CV1,CV2,S1K,S1E,U,V,W,DELTAR,
     & DUDX,DUDY,DUDZ,DVDX,DVDY,DVDZ,DWDX,DWDY,DWDZ,DTADZ,
     & DKDX,DKDY,DKDZ,DODX,DODY,DODZ,ROTAT,
     & AK,EP,ALPHA,BETA,BETAS,GRAV,TR,NPOIN3,MSK,MASKEL,MESH3D,IELM3,S,
     & PRANDTL)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NPOIN3,IELM3
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: CV1,CV2,S1K,S1E
      TYPE(BIEF_OBJ), INTENT(IN)      :: AK,EP
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: ROTAT
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: DUDX,DUDY,DUDZ
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: DVDX,DVDY,DVDZ
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: DWDX,DWDY,DWDZ
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: DKDX,DKDY,DKDZ
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: DODX,DODY,DODZ
      TYPE(BIEF_OBJ), INTENT(INOUT)   :: DTADZ,TR
      TYPE(BIEF_OBJ), INTENT(IN)      :: MASKEL,U,V,W,DELTAR,S
      DOUBLE PRECISION, INTENT(IN)    :: GRAV,ALPHA,BETA,BETAS
      DOUBLE PRECISION, INTENT(IN)    :: PRANDTL
      LOGICAL, INTENT(IN)             :: MSK
      TYPE(BIEF_MESH), INTENT(INOUT)  :: MESH3D
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE SOURCE
     & (S0U,S0V,S0W,S1U,S1V,S1W,
     &  UN3,VN3,WSN3,WN3,
     &  VOLU,VOLUN,T3,NPOIN3,NTRAC,LT,AT,DT,PRIVE,NONHYD,
     &  NPOIN2,NSCE,ISCE,KSCE,QSCE,USCE,VSCE,MAXSCE)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)           :: NPOIN3, NTRAC, LT, MAXSCE
      TYPE(BIEF_OBJ), INTENT(IN)    :: UN3, VN3, WSN3, WN3
      TYPE(BIEF_OBJ), INTENT(INOUT) :: S0U,S0V,S1U,S1V,S0W,S1W
      TYPE(BIEF_OBJ), INTENT(INOUT) :: T3
      TYPE(BIEF_OBJ), INTENT(IN)    :: VOLU, VOLUN,PRIVE
      DOUBLE PRECISION, INTENT(IN)  :: AT,DT
      LOGICAL, INTENT(IN)           :: NONHYD
      INTEGER, INTENT(IN)           :: NPOIN2
      INTEGER, INTENT(IN)           :: NSCE
      INTEGER, INTENT(IN)           :: ISCE(NSCE)
      INTEGER, INTENT(IN)           :: KSCE(NSCE)
      DOUBLE PRECISION, INTENT(IN)  :: QSCE(NSCE)
      DOUBLE PRECISION, INTENT(IN)  :: USCE(NSCE)
      DOUBLE PRECISION, INTENT(IN)  :: VSCE(NSCE)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE SUISED
     &(IVIDE,EPAI,HDEP,CONC,TEMP,FLUER,PDEPOT,ZR,ZF,NPF,
     & NPOIN2,NPOIN3,NPFMAX,NCOUCH,TASSE,GIBSON,NSUIS,BISUIS)
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NPOIN2, NPOIN3, NPFMAX, NCOUCH
      DOUBLE PRECISION, INTENT(INOUT) :: IVIDE(NPFMAX*NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: EPAI((NPFMAX-1)*NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: CONC(NCOUCH)
      DOUBLE PRECISION, INTENT(INOUT) :: TEMP(NCOUCH*NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: ZR(NPOIN2), ZF(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: HDEP(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: FLUER(NPOIN2), PDEPOT(NPOIN2)
      INTEGER, INTENT(INOUT)          :: NPF(NPOIN2)
      INTEGER, INTENT(IN)             :: NSUIS
      CHARACTER(LEN=3), INTENT(IN)    :: BISUIS
      LOGICAL, INTENT(IN)             :: TASSE, GIBSON
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE SUMVER(FINT,F,NPOIN2,NPLAN,NPTFR)
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: NPOIN2,NPLAN,NPTFR
          DOUBLE PRECISION, INTENT(INOUT) :: FINT(NPTFR)
          DOUBLE PRECISION, INTENT(IN)    :: F(NPTFR,NPLAN)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE TASSEC
     &( CONC   , EPAI , TREST , TEMP , DTC , NPOIN2 , NCOUCH )
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NPOIN2, NCOUCH
      DOUBLE PRECISION, INTENT(INOUT) :: EPAI(NCOUCH,NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TEMP(NCOUCH,NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: CONC(NCOUCH), TREST(NCOUCH)
      DOUBLE PRECISION, INTENT(IN)    :: DTC
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE TASSEM
     & ( IVIDE , EPAI , NPOIN2, NPFMAX, NPF  ,
     &   GRAV  , RHOS  , DTC  , CFMAX , TRA01 , SIGMA , CHARGE)
          IMPLICIT NONE
          INTEGER, INTENT(IN)             :: NPOIN2,NPFMAX
          INTEGER, INTENT(IN)             :: NPF(NPOIN2)
          DOUBLE PRECISION, INTENT(IN)    :: EPAI(NPFMAX-1,NPOIN2)
          DOUBLE PRECISION, INTENT(INOUT) :: IVIDE(NPFMAX,NPOIN2)
          DOUBLE PRECISION, INTENT(INOUT) :: TRA01(NPFMAX,6)
          DOUBLE PRECISION, INTENT(INOUT) :: SIGMA(NPFMAX)
          DOUBLE PRECISION, INTENT(INOUT) :: CHARGE(NPFMAX)
          DOUBLE PRECISION, INTENT(IN)    :: RHOS,GRAV,DTC,CFMAX
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE TBORD
     & (AUBORL,LIUBOL,
     &  RUGOL,DISBOR,NELBOR,NULONE,IKLE,NELEM2,
     &  U,V,W,NBOR,NPOIN2,NPLAN,NPTFR,
     &  DNUVIH,DNUVIV,KARMAN,LISRUL,KFROTL,
     &  KENT,KENTU,KSORT,KADH,KLOG,UETCAL,NONHYD,UTANG,MESH2D)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NPTFR,NPLAN,NPOIN2,KENTU,NELEM2
      INTEGER, INTENT(IN) :: LISRUL,KENT,KSORT,KADH,KLOG,KFROTL
      INTEGER, INTENT(INOUT) :: LIUBOL(NPTFR,NPLAN)
      INTEGER, INTENT(IN) :: NBOR(NPTFR),NELBOR(NPTFR),NULONE(NPTFR)
      INTEGER, INTENT(IN) :: IKLE(NELEM2,3)
      DOUBLE PRECISION, INTENT(IN) :: U(NPOIN2,NPLAN),V(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN) :: W(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: UETCAL(NPTFR,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: AUBORL(NPTFR,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: UTANG(NPTFR)
      DOUBLE PRECISION, INTENT(IN) :: DISBOR(NPTFR)
      DOUBLE PRECISION, INTENT(IN) :: RUGOL(NPTFR,NPLAN)
      DOUBLE PRECISION, INTENT(IN) :: DNUVIH, DNUVIV, KARMAN
      LOGICAL, INTENT(IN) :: NONHYD
      TYPE(BIEF_MESH), INTENT(INOUT) :: MESH2D
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE TFOND
     &(AUBOR,CF,U2D,V2D,U3D,V3D,W3D,KARMAN,LISRUG,PROPNU,Z,NPOIN,KFROT,
     & RUGOF,UETCAR,NONHYD,OPTBAN,HN,GRAV,IPBOT,NPLAN)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: LISRUG,NPOIN,KFROT,OPTBAN,NPLAN
      INTEGER, INTENT(IN) :: IPBOT(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: KARMAN,PROPNU,GRAV
      DOUBLE PRECISION, INTENT(INOUT) :: AUBOR(NPOIN),UETCAR(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: HN(NPOIN)
      DOUBLE PRECISION, INTENT(IN) :: CF(*),U2D(*),V2D(*)
      DOUBLE PRECISION, INTENT(IN) :: RUGOF(*),U3D(*),V3D(*),W3D(*),Z(*)
      LOGICAL, INTENT(IN) :: NONHYD
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE TRANSF_ZCHAR(TRANSF,ZCHAR,ZSTAR,TRANSF_PLANE,NPLAN)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)           :: NPLAN
      INTEGER, INTENT(INOUT)        :: TRANSF
      TYPE(BIEF_OBJ), INTENT(INOUT) :: ZCHAR,TRANSF_PLANE
      TYPE(BIEF_OBJ), INTENT(IN)    :: ZSTAR
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        DOUBLE PRECISION FUNCTION TR3( I , ITRAC , N , AT , INFOGR )
          IMPLICIT NONE
          INTEGER, INTENT(IN)          :: I,ITRAC,N
          DOUBLE PRECISION, INTENT(IN) :: AT
          LOGICAL, INTENT(IN)          :: INFOGR
        END FUNCTION
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        DOUBLE PRECISION FUNCTION TRA_PROF_Z
     &                          (I,IPOIN2,AT,LT,IPLAN,INFOGR,IOPT,ITRAC)
        IMPLICIT NONE
        INTEGER          , INTENT(IN) :: I,IPOIN2,IPLAN,IOPT,LT
        INTEGER          , INTENT(IN) :: ITRAC
        DOUBLE PRECISION , INTENT(IN) :: AT
        LOGICAL          , INTENT(IN) :: INFOGR
        END FUNCTION
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE TRIDW2(WSS)
          USE BIEF_DEF
          IMPLICIT NONE
          TYPE(BIEF_OBJ), INTENT(INOUT) :: WSS
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE TRISOU
     & (CV1, CV2, SCV1, SCV2, UN3, VN3, TA, X, Y, Z, ZS,
     &  DELTAR,MESH3,FCOR,CORIOL,NTRAC,LT,AT,DT,SURFAC,
     &  T1,ST1, W1, W2, W3, SEDI, GRAV, NPOIN3, NELEM3, NPOIN2,
     &  NELEM2, NPLAN, NETAGE, IKLE3, PRIVE, LV, MSK, MASKEL, INCHYD,
     &  SVOLU,VOLU,SVIDE,IELM3,SMASKEL,NREJEU,ISCE,KSCE,QSCE,USCE,VSCE,
     &  IELM2H,GRADZSX,GRADZSY,Z3,TRAV2,FU2,MESH2D, ST2,T2,ST3,T3,
     &  LATIT, LONGIT, NORD,SMU,SMV,YASEM3D,SCHCVI,DENLAW,FXH,FYH,
     &  COUROU,NPTH,T3D_FILES,T3DBI1)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NPOIN3,NELEM3,NPOIN2,NELEM2
      INTEGER, INTENT(IN) :: NPLAN,NETAGE,NTRAC,NPTH,T3DBI1
      INTEGER, INTENT(IN) :: LV,LT,IELM2H,NREJEU,IELM3,SCHCVI,DENLAW
      INTEGER, INTENT(IN) :: IKLE3(NELEM3,6)
      DOUBLE PRECISION, INTENT(IN)    :: MASKEL(NELEM3)
      DOUBLE PRECISION, INTENT(IN)    :: LATIT,LONGIT,NORD
      DOUBLE PRECISION, INTENT(INOUT) :: CV1(NPOIN3),CV2(NPOIN3)
      TYPE(BIEF_OBJ),   INTENT(INOUT) :: SCV1,SCV2,FXH,FYH
      DOUBLE PRECISION, INTENT(IN)    :: UN3(NPOIN3), VN3(NPOIN3)
      DOUBLE PRECISION, INTENT(IN)    :: SURFAC(NELEM2)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN3), Y(NPOIN3), Z(NPOIN3)
      DOUBLE PRECISION, INTENT(INOUT) :: ZS(NPOIN3)
      DOUBLE PRECISION, INTENT(INOUT) :: W1(NELEM3,6), W2(NELEM3,6)
      DOUBLE PRECISION, INTENT(INOUT) :: W3(NELEM3,6)
      DOUBLE PRECISION, DIMENSION(NPOIN2,NPLAN), INTENT(INOUT) :: VOLU
      DOUBLE PRECISION, INTENT(INOUT) :: T1(NPOIN3)
      DOUBLE PRECISION, INTENT(INOUT) :: T2(NPOIN3), T3(NPOIN3)
      TYPE(BIEF_OBJ),   INTENT(INOUT) :: ST1, ST2, ST3
      TYPE(BIEF_OBJ),   INTENT(INOUT) :: TA
      TYPE(BIEF_OBJ),   INTENT(INOUT) :: PRIVE
      TYPE(BIEF_OBJ),   INTENT(INOUT) :: DELTAR
      TYPE(BIEF_MESH)                 :: MESH3
      TYPE(BIEF_OBJ),  INTENT(INOUT)  :: GRADZSX
      TYPE(BIEF_OBJ),  INTENT(INOUT)  :: GRADZSY
      TYPE(BIEF_MESH), INTENT(INOUT)  :: MESH2D
      TYPE(BIEF_OBJ),  INTENT(IN)     :: Z3
      TYPE (BIEF_OBJ), INTENT(IN)     :: SMASKEL
      TYPE (BIEF_OBJ), INTENT(INOUT)  :: SVIDE
      TYPE (BIEF_OBJ), INTENT(INOUT)  :: TRAV2, FU2
      TYPE(BIEF_OBJ),  INTENT(INOUT)  :: SVOLU,SMU,SMV
C                                 * = NSCE
      INTEGER, INTENT(IN) :: ISCE(*),KSCE(*)
      DOUBLE PRECISION, INTENT(IN) :: QSCE(*),USCE(*),VSCE(*)
      DOUBLE PRECISION, INTENT(IN) :: GRAV, DT, AT, FCOR
      LOGICAL, INTENT(IN) :: CORIOL, SEDI, MSK, INCHYD,COUROU
      LOGICAL, INTENT(INOUT) :: YASEM3D
      TYPE(BIEF_FILE), INTENT(IN) :: T3D_FILES(*)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        DOUBLE PRECISION FUNCTION T3D_DEBSCE( TIME , I , DISCE )
          IMPLICIT NONE
          DOUBLE PRECISION, INTENT(IN) :: TIME,DISCE(*)
          INTEGER         , INTENT(IN) :: I
        END FUNCTION
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        DOUBLE PRECISION FUNCTION T3D_TRSCE( TIME , I , ITRAC )
          IMPLICIT NONE
          DOUBLE PRECISION, INTENT(IN) :: TIME
          INTEGER         , INTENT(IN) :: I,ITRAC
        END FUNCTION
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE UPWIND(M,WCC,DELTA,MESH2D,MESH3D,NPLAN)
        USE BIEF_DEF
        IMPLICIT NONE
        TYPE(BIEF_OBJ), INTENT(INOUT)  :: M
        TYPE(BIEF_OBJ), INTENT(IN)     :: WCC
        DOUBLE PRECISION, INTENT(IN)   :: DELTA
        TYPE(BIEF_MESH), INTENT(IN)    :: MESH3D,MESH2D
        INTEGER, INTENT(IN)            :: NPLAN
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE UPWINDEBE
     &    (D,X,IKLE,NELMAX,NELEM3,NELEM2,SURFAC,NPLAN,WCC,DELTA)
          USE BIEF_DEF
          IMPLICIT NONE
          INTEGER, INTENT(IN)             :: NELMAX,NELEM3,NELEM2,NPLAN
          INTEGER, INTENT(IN)             :: IKLE(NELMAX,6)
          DOUBLE PRECISION, INTENT(IN   ) :: SURFAC(NELMAX),WCC(*),DELTA
          DOUBLE PRECISION, INTENT(INOUT) :: D(*),X(NELMAX,30)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE UPWINDSEG
     &  (D,X,IKLE,NELMAX,NELEM3,NELEM2,SURFAC,NPLAN,WCC,NSEG2D,DELTA)
        USE BIEF_DEF
        IMPLICIT NONE
        INTEGER, INTENT(IN)             :: NELMAX,NELEM3,NELEM2,NPLAN
        INTEGER, INTENT(IN)             :: IKLE(NELMAX,6),NSEG2D
        DOUBLE PRECISION, INTENT(IN   ) :: SURFAC(NELMAX),WCC(*),DELTA
        DOUBLE PRECISION, INTENT(INOUT) :: D(*),X(*)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE UTIMP(LT,AT,GRADEBL,GRAPRDL,LISDEBL,LISPRDL)
          IMPLICIT NONE
          DOUBLE PRECISION, INTENT(IN) :: AT
          INTEGER, INTENT(IN) :: LT,GRADEBL,GRAPRDL,LISDEBL,LISPRDL
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        DOUBLE PRECISION FUNCTION VEL_PROF_Z
     &( I , IPOIN2 , AT , LT , IPLAN , INFOGR , IOPT )
          IMPLICIT NONE
          INTEGER          , INTENT(IN) :: I,IPOIN2,IPLAN,IOPT,LT
          DOUBLE PRECISION , INTENT(IN) :: AT
          LOGICAL          , INTENT(IN) :: INFOGR
        END FUNCTION
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE VELRES
     &(U,V,W,DP,PX,PY,PZ,MSK,MASKEL,MESH3D,S,IELM3,NPLAN,OPTBAN,
     & UNSV3D,NPOIN3,NPOIN2,SIGMAG,IPBOT)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)            :: IELM3,NPLAN,OPTBAN,NPOIN3,NPOIN2
      TYPE(BIEF_OBJ),  INTENT(IN)    :: S,DP,UNSV3D
      TYPE(BIEF_OBJ),  INTENT(INOUT) :: PX,PY,PZ
      DOUBLE PRECISION, INTENT(INOUT):: U(NPOIN3),V(NPOIN3),W(NPOIN3)
      TYPE(BIEF_MESH), INTENT(INOUT) :: MESH3D
      INTEGER, INTENT(IN)            :: IPBOT(NPOIN2)
      LOGICAL, INTENT(IN)            :: MSK,SIGMAG
      TYPE(BIEF_OBJ), INTENT(INOUT)  :: MASKEL
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE VERMOY
     & (FINT1,FINT2,F1,F2,NFONC,Z,TRA01,TRA02,TRA03,
     &  IPLAN1,IPLAN2,NPOIN2,NPLAN,OPTBAN)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NPOIN2,NPLAN,NFONC,IPLAN1,IPLAN2,OPTBAN
      DOUBLE PRECISION, INTENT(INOUT) :: FINT1(NPOIN2),FINT2(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: F1(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: F2(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: Z(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA01(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA02(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA03(NPOIN2,NPLAN)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE VISCKE
     & (VISCVI,VISCTA,AK,EP,NTRAC,CMU,
     &  DNUVIH,DNUVIV,DNUTAH,DNUTAV,KMIN,EMIN,ITURBH,ITURBV,PRANDTL)
          USE BIEF_DEF
          IMPLICIT NONE
          INTEGER, INTENT(IN)          :: NTRAC,ITURBH,ITURBV
          DOUBLE PRECISION, INTENT(IN) :: CMU,PRANDTL
          DOUBLE PRECISION, INTENT(IN) :: DNUVIH,DNUVIV
          DOUBLE PRECISION, INTENT(IN) :: DNUTAH,DNUTAV,KMIN,EMIN
          TYPE(BIEF_OBJ), INTENT(INOUT):: VISCVI,VISCTA
          TYPE(BIEF_OBJ), INTENT(IN)   :: AK,EP
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE VISCKO
     & (VISCVI, VISCTA, ROTAT, AK, EP, NTRAC, CMU,
     &  DNUVIH, DNUVIV, DNUTAH, DNUTAV)
          USE BIEF_DEF
          IMPLICIT NONE
          INTEGER, INTENT(IN)          :: NTRAC
          DOUBLE PRECISION, INTENT(IN) :: CMU
          DOUBLE PRECISION, INTENT(IN) :: DNUVIH, DNUVIV
          DOUBLE PRECISION, INTENT(IN) :: DNUTAH, DNUTAV
          TYPE(BIEF_OBJ), INTENT(INOUT)  :: VISCVI, VISCTA
          TYPE(BIEF_OBJ), INTENT(IN)   :: ROTAT, AK, EP
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE VISCLIP
     & (VISCVI,VISCTA,H,NPLAN,NPOIN3,NPOIN2,NTRAC)
          USE BIEF_DEF
          IMPLICIT NONE
          INTEGER, INTENT(IN)            :: NPOIN3, NPOIN2, NPLAN
          INTEGER, INTENT(IN)            :: NTRAC
          TYPE (BIEF_OBJ), INTENT(INOUT) :: VISCVI, VISCTA
          TYPE (BIEF_OBJ), INTENT(IN)    :: H
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE VISCLM
     & (VISCVI,VISCTA,RI,U,V,DELTAR,X,Y,Z,HN,TRAV1,TRAV2,TRAV3,
     &  TRAV4,TRAV5,TRAV6,TRAV7,SVIDE,MESH3D,IELM3,GRAV,
     &  NPLAN,NPOIN3,NPOIN2,NTRAC,MSK,MASKEL,TA,MIXING,
     &  DAMPING,IND_T,DNUVIV,DNUTAV,KARMAN,PRANDTL,UETCAR,KFROT,
     &  RUGOF,ZF)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)            :: NPOIN3,NPOIN2,NPLAN,KFROT
      INTEGER, INTENT(IN)            :: NTRAC,DAMPING
      INTEGER, INTENT(IN)            :: IELM3,MIXING,IND_T
      DOUBLE PRECISION, INTENT(IN)   :: GRAV,DNUVIV,DNUTAV,KARMAN
      DOUBLE PRECISION, INTENT(IN)   :: PRANDTL
      LOGICAL, INTENT(IN)            :: MSK
      TYPE (BIEF_OBJ), INTENT(INOUT) :: VISCVI,VISCTA
      TYPE (BIEF_OBJ), INTENT(IN)    :: TA,UETCAR,RUGOF,ZF
      TYPE (BIEF_OBJ), INTENT(INOUT) :: RI
      TYPE (BIEF_OBJ), INTENT(IN)    :: U,V,DELTAR,X,Y,Z,HN
      TYPE (BIEF_OBJ), INTENT(INOUT) :: TRAV1,TRAV2,TRAV3,TRAV4
      TYPE (BIEF_OBJ), INTENT(INOUT) :: TRAV5,TRAV6,TRAV7
      TYPE (BIEF_OBJ), INTENT(IN)    :: MASKEL
      TYPE (BIEF_OBJ), INTENT(INOUT) :: SVIDE
      TYPE (BIEF_MESH)               :: MESH3D
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE VISCOS
     &(VISCVI,VISCTA,DNUTAV,DNUTAH,DNUVIV,DNUVIH,
     & NTRAC,ITURBH,ITURBV)
          USE BIEF_DEF
          IMPLICIT NONE
          INTEGER, INTENT(IN)            :: NTRAC
          INTEGER, INTENT(IN)            :: ITURBH,ITURBV
          TYPE (BIEF_OBJ), INTENT(INOUT) :: VISCVI, VISCTA
          DOUBLE PRECISION, INTENT(IN)   :: DNUVIH, DNUVIV
          DOUBLE PRECISION, INTENT(IN)   :: DNUTAH, DNUTAV
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE VISSMA
     & (VISCVI,VISCTA,DNUTAH,DNUVIH,DNUVIV,DNUTAV,
     &  U,V,W,TRAV1,TRAV2,TRAV3,TRAV4,TRAV5,TRAV6,
     &  SVIDE,MESH3,IELM3,NTRAC,MSK,MASKEL,ITURBV)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)            :: NTRAC,ITURBV
      INTEGER, INTENT(IN)            :: IELM3
      LOGICAL, INTENT(IN)            :: MSK
      TYPE (BIEF_OBJ), INTENT(IN)    :: U, V, W
      TYPE (BIEF_OBJ), INTENT(INOUT) :: VISCVI, VISCTA
      TYPE (BIEF_OBJ), INTENT(INOUT) :: TRAV1, TRAV2, TRAV3, TRAV4
      TYPE (BIEF_OBJ), INTENT(INOUT) :: TRAV5      !  NUSMAG
      TYPE (BIEF_OBJ), INTENT(INOUT) :: TRAV6
      TYPE (BIEF_OBJ), INTENT(IN)    :: MASKEL
      TYPE (BIEF_OBJ), INTENT(INOUT) :: SVIDE
      TYPE (BIEF_MESH)               :: MESH3
      DOUBLE PRECISION, INTENT(IN)   :: DNUVIH,DNUTAH,DNUVIV,DNUTAV
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        DOUBLE PRECISION FUNCTION VIT3( I , AT , N , INFOGR )
          IMPLICIT NONE
          INTEGER          , INTENT(IN) :: I,N
          DOUBLE PRECISION , INTENT(IN) :: AT
          LOGICAL          , INTENT(IN) :: INFOGR
        END FUNCTION
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE VITCHU(W_SED, WCHU_CONST)
          USE BIEF_DEF
          IMPLICIT NONE
          DOUBLE PRECISION, INTENT(IN)  :: WCHU_CONST
          TYPE(BIEF_OBJ), INTENT(INOUT) :: W_SED
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE WAVE_EQUATION(LT,ISOUSI)
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: LT,ISOUSI
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE WCTURB
     &(WC, WCHU0, U, V, W, HN, RUGOF, LISRUF, TRAV1, TRAV2, TRAV3,
     & S, MESH3, IELM3, NPOIN2, NPLAN, TURBA, TURBB, MSK, MASKEL,
     & UETCAR)
      USE BIEF_DEF
      IMPLICIT NONE
      INTEGER, INTENT(IN)           :: NPOIN2,NPLAN,IELM3,LISRUF
      DOUBLE PRECISION, INTENT(IN)  :: WCHU0,TURBA,TURBB
      LOGICAL, INTENT(IN)           :: MSK
      TYPE(BIEF_MESH), INTENT(INOUT):: MESH3
      TYPE(BIEF_OBJ), INTENT(INOUT) :: WC,TRAV1,TRAV2,TRAV3
      TYPE(BIEF_OBJ), INTENT(IN)    :: MASKEL,S,HN,RUGOF,UETCAR,U,V,W
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE WSTARW(WW,WSS,WUP,WDOWN,SOMMEW)
          USE BIEF_DEF
          IMPLICIT NONE
          TYPE(BIEF_OBJ), INTENT(IN) :: WSS
          TYPE(BIEF_OBJ), INTENT(INOUT) :: WW
          DOUBLE PRECISION,INTENT(INOUT) :: WUP(*),WDOWN(*),SOMMEW(*)
        END SUBROUTINE
      END INTERFACE
C
C-----------------------------------------------------------------------
C
      INTERFACE
        SUBROUTINE WSTAR(WS,HWSTAR,Z,NPOIN2,NPLAN)
          USE BIEF_DEF
          IMPLICIT NONE
          TYPE(BIEF_OBJ),    INTENT(IN   ) :: HWSTAR
          TYPE(BIEF_OBJ),    INTENT(INOUT) :: WS
          DOUBLE PRECISION,  INTENT(IN   ) :: Z(*)
          INTEGER,           INTENT(IN   ) :: NPOIN2,NPLAN
        END SUBROUTINE
      END INTERFACE
C
C=======================================================================
C
      END MODULE INTERFACE_TELEMAC3D
