!
!  INTERFACES OF TOMAWAC SUBROUTINES
!
      MODULE INTERFACE_TOMAWAC
!
!=======================================================================
!
!     DEFINITION OF STRUCTURES
!
      USE BIEF_DEF
!
!-----------------------------------------------------------------------
!
!     DEFINITION OF INTERFACES
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE ANACOS(UC,VC,X,Y,NPOIN2)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NPOIN2
      DOUBLE PRECISION X(NPOIN2),Y(NPOIN2),UC(NPOIN2),VC(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE ANAMAR
     &( UC  , VC  , ZM  , ZM1 , ZM2 , DZHDT , X  , Y  , NPOIN2 ,
     &  AT  , DDC , LT  )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NPOIN2,LT
      DOUBLE PRECISION, INTENT(IN)    :: AT,DDC
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN2),Y(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: ZM1(NPOIN2),ZM2(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: UC(NPOIN2),VC(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: DZHDT(NPOIN2),ZM(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE ANAVEN
     &( UV , VV , X , Y , NPOIN2, AT , DDC , VX_CTE, VY_CTE)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NPOIN2
      DOUBLE PRECISION AT    , DDC   , VX_CTE, VY_CTE
      DOUBLE PRECISION X (NPOIN2)    , Y (NPOIN2)
      DOUBLE PRECISION UV(NPOIN2)    , VV(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE ANGLES(XLAMD , DTPLUS, DTMOIN)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      DOUBLE PRECISION XLAMD , DTPLUS, DTMOIN
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE BORNES(B , N , A , XM , X0 , X1 )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  N
      DOUBLE PRECISION B , A , XM , X0 , X1
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE CONDIW
     &( AT, LT , TC1, TC2, TV1, TV2, TM1, TM2 ,
     &  NVHMA,NVCOU,NVWIN,PART , U_TEL, V_TEL , H_TEL )
      USE BIEF_DEF
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: PART,LT
      INTEGER, INTENT(INOUT)          :: NVHMA,NVCOU,NVWIN
      DOUBLE PRECISION, INTENT(INOUT) :: AT,TC1,TC2,TV1,TV2,TM1,TM2
      TYPE(BIEF_OBJ), INTENT(IN)      :: U_TEL,V_TEL,H_TEL
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE CONW4D
     &(CX,CY,CT,CF,U,V,XK,CG,COSF,TGF,DEPTH,DZHDT,DZX,DZY,DUX,DUY,
     & DVX,DVY,FREQ,COSTET,SINTET,NPOIN2,NPLAN,JF,NF,PROINF,SPHE,
     & COURAN,MAREE,TRA01)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NF,NPLAN,NPOIN2,JF
      DOUBLE PRECISION, INTENT(INOUT) :: CX(NPOIN2,NPLAN,JF)
      DOUBLE PRECISION, INTENT(INOUT) :: CY(NPOIN2,NPLAN,JF)
      DOUBLE PRECISION, INTENT(INOUT) :: CT(NPOIN2,NPLAN,JF)
      DOUBLE PRECISION, INTENT(INOUT) :: CF(NPOIN2,NPLAN,JF)
      DOUBLE PRECISION, INTENT(IN)    :: FREQ(NF)
      DOUBLE PRECISION, INTENT(IN)    :: CG(NPOIN2,NF),XK(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(IN)    :: DEPTH(NPOIN2),DZHDT(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: U(NPOIN2),V(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: DZX(NPOIN2),DZY(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: DUX(NPOIN2),DUY(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: DVX(NPOIN2),DVY(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: COSTET(NPLAN),SINTET(NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: COSF(NPOIN2),TGF(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA01(NPOIN2)
      LOGICAL, INTENT(IN)             :: PROINF,SPHE,COURAN,MAREE
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE CONWAC
     &( CX    , CY    , CT    , XK    , CG    , COSF  , TGF   , DEPTH ,
     &  DZX   , DZY   , FREQ  , COSTET, SINTET, NPOIN2, NPLAN , JF    ,
     &  NF    , PROINF, SPHE  , PROMIN, TRA01 )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NF,NPLAN,NPOIN2,JF
      DOUBLE PRECISION, INTENT(IN)    :: PROMIN
      DOUBLE PRECISION, INTENT(IN)    :: DEPTH(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: DZX(NPOIN2),DZY(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: COSF(NPOIN2),TGF(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: FREQ(NF)
      DOUBLE PRECISION, INTENT(IN)    :: COSTET(NPLAN),SINTET(NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA01(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: CG(NPOIN2,NF),XK(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: CX(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: CY(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: CT(NPOIN2,NPLAN)
      LOGICAL, INTENT(IN)             :: PROINF,SPHE
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE CORMAR
     &( AT    , LT    , TC1   , TC2   , TV1   , TV2   , TM1   , TM2   ,
     &  NVHMA , NVCOU , PART, U_TEL, V_TEL , H_TEL )
      USE BIEF_DEF
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER          NVHMA, NVCOU,LT
      DOUBLE PRECISION AT,TC1,TC2,TV1,TV2,TM1,TM2
      INTEGER,           INTENT(IN) :: PART
      TYPE(BIEF_OBJ),    INTENT(IN) :: U_TEL,V_TEL,H_TEL
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        FUNCTION COUPLE
     &( XK1   , YK1   , XK2   , YK2   , XK3   , YK3   , XK4   , YK4   ,
     &  GRAVIT, PI    )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      DOUBLE PRECISION XK1   , YK1   , XK2   , YK2   , XK3   , YK3
      DOUBLE PRECISION XK4   , YK4   , GRAVIT, PI    , COUPLE
        END FUNCTION
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE COUUTI
     &(X,Y,NPOIN,NCOU,BINCOU,NBOR,NPTFR,AT,DDC,TC1,TC2,UC1,VC1,UC2,VC2)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NCOU,NPOIN,NPTFR
      INTEGER, INTENT(IN)             :: NBOR(NPTFR,2)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN),Y(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: UC1(NPOIN),VC1(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: UC2(NPOIN),VC2(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: AT,DDC,TC1,TC2
      CHARACTER(LEN=3), INTENT(IN)    :: BINCOU
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE CQUEUE
     &( NF    , RAISF , TAILF , JFRE  , JBIS  , COEF1 )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NF    , JFRE  , JBIS
      DOUBLE PRECISION RAISF , TAILF , COEF1
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        FUNCTION DELFRA( SS    , DEUPI )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      DOUBLE PRECISION DELFRA, SS    , DEUPI
        END FUNCTION
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE DIFFRAC
     &( CX    , CY    , CT    , XK    , CG    , DEPTH , DZX   , DZY   ,
     &  FREQ  , COSTET, SINTET, NPOIN2, NPLAN , IFF   , NF    , PROINF,
     &  SPHE  , A     , DFREQ , F     , CCG   , DIV   , DELTA , DDX   ,
     &  DDY   , EPS   , NBOR  , NPTFR , XKONPT, RK    , RX    , RY    ,
     &  RXX   , RYY   , NEIGB , NB_CLOSE, DIFFRA, MAXNSP, FLTDIF,OPTDER)
      USE BIEF_DEF
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NF,NPLAN,NPOIN2,NPTFR,IFF,MAXNSP,OPTDER
      INTEGER, INTENT(IN) :: NB_CLOSE(NPOIN2),NEIGB(NPOIN2,MAXNSP)
      INTEGER, INTENT(IN)             :: DIFFRA,NBOR(NPTFR)
      DOUBLE PRECISION, INTENT(INOUT) :: CX(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: CY(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: FREQ(NF)
      DOUBLE PRECISION, INTENT(INOUT) :: CT(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: CG(NPOIN2,NF),XK(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(IN)    :: DEPTH(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: DZX(NPOIN2),DZY(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: COSTET(NPLAN),SINTET(NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: A(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: DFREQ(NF)
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: CCG(NPOIN2), DIV(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: DELTA(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: DDX(NPOIN2), DDY(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: EPS
      DOUBLE PRECISION, INTENT(IN)    :: RK(MAXNSP,NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: RX(MAXNSP,NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: RY(MAXNSP,NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: RXX(MAXNSP,NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: RYY(MAXNSP,NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: XKONPT(NPOIN2)
      LOGICAL, INTENT(IN)             :: PROINF,SPHE,FLTDIF
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE DUMP2D( LT , XF1 , NP1 )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)          :: LT,NP1
      DOUBLE PRECISION, INTENT(IN) :: XF1(NP1)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE ECRETE
     &( F     , DEPTH , NPOIN2, NPLAN , NF    , PROMIN)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER          NPOIN2 , NPLAN, NF
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF), DEPTH(NPOIN2)
      DOUBLE PRECISION PROMIN
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE ECRSPE
     &( F     , TETA  , NPLAN , FREQ  , NF    , NK    ,
     &  NPOIN2, AT    , AUXIL , NOLEO , NLEO  , NSCO  ,
     &  BINSCO, DEBRES, TITCAS, DATE  , TIME  , KNOLG , MESH ,
     &  NSPE  , TISPEF)
      USE BIEF_DEF
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NPOIN2,NLEO,NSCO,NF,NK,NPLAN
      INTEGER, INTENT(IN)             :: KNOLG(NPOIN2),NOLEO(NLEO)
      INTEGER, INTENT(IN)             :: DATE(3),TIME(3)
      DOUBLE PRECISION, INTENT(IN)    :: AT
      DOUBLE PRECISION, INTENT(INOUT) :: AUXIL(NPLAN,NK)
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)    :: TETA(NPLAN),FREQ(NF)
      LOGICAL, INTENT(IN)             :: DEBRES
      CHARACTER(LEN=72), INTENT(IN)   :: TITCAS
      CHARACTER(LEN=*) , INTENT(IN)   :: BINSCO
      TYPE(BIEF_MESH), INTENT(INOUT)  :: MESH
      CHARACTER(LEN=144), INTENT(IN)  :: TISPEF
      INTEGER, INTENT(IN)             :: NSPE
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE F1F1F1
     &( F1SF  , NF1   , IQ_OM1)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER,          INTENT(IN)    :: IQ_OM1
      INTEGER,          INTENT(INOUT) :: NF1
      DOUBLE PRECISION, INTENT(INOUT) :: F1SF(*)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FILT_SA
        USE DECLARATIONS_SPECIAL
        IMPLICIT NONE
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        FUNCTION FONCRO
     &( X     , B     , N     , A     , XM    )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  N
      DOUBLE PRECISION X      , B     , A     , XM , FONCRO
        END FUNCTION
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FPREAD
     &( FREAD , F     , FREQ  , DFREQ , NF    , NPLAN , NPOIN2, EXPO  ,
     &  TAILF , DENOM , E     )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION EXPO  , TAILF
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF), FREQ(NF), DFREQ(NF)
      DOUBLE PRECISION DENOM(NPOIN2), E(NPOIN2), FREAD(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FREM01
     &( FM01  , F     , FREQ  , DFREQ , TAILF , NF    , NPLAN , NPOIN2,
     &  AUX1  , AUX2  )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION TAILF
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION FREQ(NF), DFREQ(NF), FM01(NPOIN2)
      DOUBLE PRECISION AUX1(NPOIN2), AUX2(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FREM02
     &( FM02  , F     , FREQ  , DFREQ , TAILF , NF    , NPLAN , NPOIN2,
     &  AUX1  , AUX2  )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION TAILF
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION FREQ(NF), DFREQ(NF), FM02(NPOIN2)
      DOUBLE PRECISION AUX1(NPOIN2), AUX2(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FREMOY
     &( FMOY  , F     , FREQ  , DFREQ , TAILF , NF    , NPLAN , NPOIN2,
     &  AUX1  , AUX2  )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION TAILF
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION FREQ(NF), DFREQ(NF), FMOY(NPOIN2)
      DOUBLE PRECISION AUX1(NPOIN2), AUX2(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FREPIC
     &( FPIC  , F     , FREQ  , NF    , NPLAN , NPOIN2, EMAX  , E     )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF), FREQ(NF)  , FPIC(NPOIN2)
      DOUBLE PRECISION EMAX(NPOIN2),E(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
!V6P2 New subroutine
      INTERFACE
        SUBROUTINE FRMSET
     &( X     , Y     , NEIGB , NB_CLOSE, NPOIN2,MAXNSP, NRD, NELEM2,
     &  IKLE  , RK    , RX    , RY    , RXX   , RYY )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER NPOIN2, MAXNSP, NRD, NELEM2
      INTEGER NB_CLOSE(NPOIN2), NEIGB(NPOIN2,MAXNSP)
      INTEGER IKLE(NELEM2,3)
      DOUBLE PRECISION X(NPOIN2), Y(NPOIN2)
      DOUBLE PRECISION RK(MAXNSP,NPOIN2)
      DOUBLE PRECISION RX(MAXNSP,NPOIN2), RY(MAXNSP,NPOIN2)
      DOUBLE PRECISION RXX(MAXNSP,NPOIN2),RYY(MAXNSP,NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FSPRD1
     &( FRA   , DIREC , NPLAN , SPRED1, TETA1 , SPRED2, TETA2 , XLAMDA)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NPLAN
      DOUBLE PRECISION SPRED1, TETA1 , SPRED2, TETA2 , XLAMDA
      DOUBLE PRECISION FRA(NPLAN)    , DIREC(NPLAN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FSPRD2
     &( FRA   , DIREC , NPLAN , SPRED1, TETA1 , SPRED2, TETA2 , XLAMDA)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NPLAN
      DOUBLE PRECISION SPRED1, TETA1 , SPRED2, TETA2 , XLAMDA
      DOUBLE PRECISION FRA(NPLAN)    , DIREC(NPLAN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE FSPRD3
     &( FRA   , DIREC , NPLAN , SPRED1, TETA1 , SPRED2, TETA2 , XLAMDA)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NPLAN
      DOUBLE PRECISION SPRED1, TETA1 , SPRED2, TETA2 , XLAMDA
      DOUBLE PRECISION FRA(NPLAN)    , DIREC(NPLAN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        FUNCTION GAMMLN
     &( XX    , DEUPI )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      DOUBLE PRECISION GAMMLN, XX    , DEUPI
        END FUNCTION
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE GAULEG
     &( W_LEG , X_LEG , NPOIN )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER           NPOIN
      DOUBLE PRECISION  W_LEG(NPOIN) , X_LEG(NPOIN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE IMPR
     &(LISPRD,LT,AT,ISITS,ICOD)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER LISPRD,LT,ISITS,ICOD
      DOUBLE PRECISION AT
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE INIPHY
     &( XK    , CG    , B     , DEPTH , FREQ  , COSPHI, NPOIN2, NF    ,
     &  PROINF, SPHE  )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER          NF    , NPOIN2
      DOUBLE PRECISION DEPTH(NPOIN2)    , COSPHI(NPOIN2), FREQ(NF)
      DOUBLE PRECISION B(NPOIN2,NF)  , XK(NPOIN2,NF) , CG(NPOIN2,NF)
      LOGICAL          PROINF, SPHE
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE INITAB(IBOR1,IFABOR1,NELEM2_DIM,PART)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)    :: PART,NELEM2_DIM
      INTEGER, INTENT(IN)    :: IFABOR1(NELEM2_DIM,3)
      INTEGER, INTENT(INOUT) :: IBOR1(NELEM2_DIM,7)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE INTANG
     &( LAVANT, LAPRES, IPLAN , NPLAN , DELTAD)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  LAVANT, LAPRES, NPLAN , IPLAN
      DOUBLE PRECISION DELTAD
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        DOUBLE PRECISION FUNCTION KERBOU
     &(XK1,XK2,FREQ1,FREQ2,DEPTH,TETA1,TETA2)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      DOUBLE PRECISION, INTENT(IN) :: XK1,XK2,FREQ1,FREQ2,TETA1,TETA2
      DOUBLE PRECISION, INTENT(IN) :: DEPTH
        END FUNCTION
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE KMOYEN
     &( XKMOY , XK    , F     , FREQ  , DFREQ , TAILF , NF    , NPLAN ,
     &  NPOIN2, AUX1  , AUX2  , AUX3  )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NF,NPLAN,NPOIN2
      DOUBLE PRECISION, INTENT(IN)    :: TAILF
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)    :: XK(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(IN)    :: FREQ(NF),DFREQ(NF)
      DOUBLE PRECISION, INTENT(INOUT) :: AUX1(NPOIN2),AUX2(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: AUX3(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: XKMOY(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE LECDOI
     &(F1,NAME1FR,NAME1GB,MODE1,
     & F2,NAME2FR,NAME2GB,MODE2,
     & F3,NAME3FR,NAME3GB,MODE3,
     & X,Y,NPOIN2,NDON,BINDON,NBOR,NPTFR,
     & AT,DDC,TV1,TV2,F11,F12,F21,F22,F31,F32,INDIC,CHDON,NVAR,
     & TEXTE,TROUVE,UNITIME,PHASTIME)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NDON,NPOIN2,NPTFR,INDIC
      INTEGER, INTENT(IN)             :: MODE1,MODE2,MODE3
      INTEGER, INTENT(INOUT)          :: NVAR
      INTEGER, INTENT(IN)             :: NBOR(NPTFR,2)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN2),Y(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: F1(NPOIN2),F2(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: F3(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: F11(NPOIN2),F12(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: F21(NPOIN2),F22(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: F31(NPOIN2),F32(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: AT,DDC,UNITIME,PHASTIME
      DOUBLE PRECISION, INTENT(INOUT) :: TV1,TV2
      CHARACTER(LEN=3), INTENT(IN)    :: BINDON
      CHARACTER(LEN=7), INTENT(IN)    :: CHDON
      CHARACTER(LEN=32),INTENT(IN)    :: NAME1FR,NAME2FR,NAME3FR
      CHARACTER(LEN=32),INTENT(IN)    :: NAME1GB,NAME2GB,NAME3GB
      CHARACTER(LEN=32),INTENT(INOUT) :: TEXTE(30)
      LOGICAL, INTENT(INOUT)          :: TROUVE(3)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE LECDON
     &(F1,NAME1FR,NAME1GB,MODE1,
     & F2,NAME2FR,NAME2GB,MODE2,
     & F3,NAME3FR,NAME3GB,MODE3,
     & X,Y,NPOIN2,NDON,BINDON,NBOR,NPTFR,NPTT,INDIC,CHDON,TEXTE,TROUVE)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NDON,NPOIN2,NPTFR,INDIC,NPTT
      INTEGER, INTENT(IN)             :: MODE1,MODE2,MODE3
      INTEGER, INTENT(IN)             :: NBOR(NPTFR,2)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN2),Y(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: F1(NPOIN2),F2(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: F3(NPOIN2)
      CHARACTER(LEN=3), INTENT(IN)    :: BINDON
      CHARACTER(LEN=7), INTENT(IN)    :: CHDON
      CHARACTER(LEN=32),INTENT(IN)    :: NAME1FR,NAME2FR,NAME3FR
      CHARACTER(LEN=32),INTENT(IN)    :: NAME1GB,NAME2GB,NAME3GB
      CHARACTER(LEN=32),INTENT(INOUT) :: TEXTE(30)
      LOGICAL, INTENT(INOUT)          :: TROUVE(3)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE LECDON_TOMAWAC(FILE_DESC,PATH,NCAR,CODE)
      USE BIEF_DEF
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, PARAMETER :: NMAX = 300
      CHARACTER(LEN=24), INTENT(IN)     :: CODE
      CHARACTER(LEN=144), INTENT(INOUT) :: FILE_DESC(4,NMAX)
      INTEGER, INTENT(IN)               :: NCAR
      CHARACTER(LEN=250), INTENT(IN)    :: PATH
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE LECSUI
     &(F,NPLAN,NF,TETA,FREQ,NELEM2,NPOIN2,AT,UC,VC,UC1,VC1,UC2,VC2,
     & UV,VV,UV1,VV1,UV2,VV2,VENT,TV1,TV2,COURAN,NPRE,BINPRE,DEPTH,
     & TC1,TC2,ZM1,ZM2,DZHDT,TM1,TM2,MAREE,TRA01)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NPRE,NF,NPLAN,NELEM2,NPOIN2
      DOUBLE PRECISION, INTENT(INOUT) :: F(NPOIN2,NPLAN,NF),AT
      DOUBLE PRECISION, INTENT(INOUT) :: TV1,TV2,TC1,TC2,TM1,TM2
      DOUBLE PRECISION, INTENT(INOUT) :: TETA(NPLAN+1),FREQ(NF)
      DOUBLE PRECISION, INTENT(INOUT) :: UC(NPOIN2),VC(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: UV(NPOIN2),VV(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: UV1(NPOIN2),VV1(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: UV2(NPOIN2),VV2(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: UC1(NPOIN2),VC1(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: UC2(NPOIN2),VC2(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: DEPTH(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: ZM1(NPOIN2),ZM2(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: DZHDT(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA01(NPOIN2*NPLAN)
      LOGICAL, INTENT(IN)             :: COURAN,VENT,MAREE
      CHARACTER(LEN=3), INTENT(IN)    :: BINPRE
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE LIMWAC
     &(F     , FBOR  , LIFBOR, NPTFR , NPLAN , NF    ,  TETA , FREQ  ,
     & NPOIN2, NBOR  , AT    , LT    , DDC   , LIMSPE, FPMAXL, FETCHL,
     & SIGMAL, SIGMBL, GAMMAL, FPICL , HM0L  , APHILL, TETA1L, SPRE1L,
     & TETA2L, SPRE2L, XLAMDL, X ,Y  , KENT  , KSORT , NFO1  , NBI1  ,
     & BINBI1, UV    , VV    , SPEULI, VENT  , VENSTA, GRAVIT, DEUPI ,
     & PRIVE , NPRIV , SPEC  , FRA   , DEPTH , FRABL ,BOUNDARY_COLOUR)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER NPTFR,NPLAN,NF,NPOIN2,LT,NPRIV,LIMSPE,KENT,KSORT,FRABL
      INTEGER NFO1,NBI1
      INTEGER LIFBOR(NPTFR),NBOR(NPTFR)
      INTEGER, INTENT(IN) :: BOUNDARY_COLOUR(NPTFR)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF),FBOR(NPTFR,NPLAN,NF)
      DOUBLE PRECISION TETA(NPLAN),FREQ(NF),X(NPOIN2),Y(NPOIN2)
      DOUBLE PRECISION UV(NPOIN2),VV(NPOIN2), SPEC(NF), FRA(NPLAN)
      DOUBLE PRECISION PRIVE(NPOIN2,NPRIV),DEPTH(NPOIN2)
      DOUBLE PRECISION AT,DDC,FPMAXL,FETCHL,SIGMAL, SIGMBL, GAMMAL,FPICL
      DOUBLE PRECISION HM0L  , APHILL,TETA1L,SPRE1L,TETA2L,SPRE2L,XLAMDL
      DOUBLE PRECISION GRAVIT,DEUPI
      LOGICAL SPEULI, VENT, VENSTA
      CHARACTER(LEN=3) BINBI1
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE MARUTI
     &(X,Y,NPOIN,NMAR,BINMAR,NBOR,NPTFR,AT,DDC,TV1,TV2,Z1,Z2)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NMAR,NPOIN,NPTFR
      INTEGER, INTENT(IN)             :: NBOR(NPTFR,2)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN),Y(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: Z1(NPOIN),Z2(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: AT,DDC,TV1,TV2
      CHARACTER(LEN=3), INTENT(IN)    :: BINMAR
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE MPOINT
     &( U     , V     , W     , DT    , X     , Y     , TETA  , IKLE2 ,
     &  IFABOR, ETAS  , XPLOT , YPLOT , ZPLOT , DX    , DY    , DZ    ,
     &  SHP   , SHZ   , ELT   , ETA   , NSP   , NPLOT ,
     &  NPOIN2, NELEM2, NPLAN , IFF   , SURDET, SENS  , ISO )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER NPOIN2, NELEM2, NPLAN, NPLOT, SENS, IFF
      INTEGER ELT(NPLOT), ETA(NPLOT), NSP(NPLOT), ISO(NPLOT)
      INTEGER IKLE2(NELEM2,3), IFABOR(NELEM2,5), ETAS(NPLAN)
      DOUBLE PRECISION DT
      DOUBLE PRECISION U(NPOIN2,NPLAN), V(NPOIN2,NPLAN)
      DOUBLE PRECISION W(NPOIN2,NPLAN)
      DOUBLE PRECISION XPLOT(NPLOT), YPLOT(NPLOT), ZPLOT(NPLOT)
      DOUBLE PRECISION SHZ(NPLOT),SURDET(NELEM2),SHP(3,NPLOT)
      DOUBLE PRECISION X(NPOIN2), Y(NPOIN2), TETA(NPLAN+1)
      DOUBLE PRECISION DX(NPLOT), DY(NPLOT), DZ(NPLOT)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE NOMVAR_TOMAWAC
     &(TEXTE,TEXTPR,MNEMO,MAXVAR)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER      MAXVAR
      CHARACTER*32 TEXTE(MAXVAR),TEXTPR(MAXVAR)
      CHARACTER*8  MNEMO(MAXVAR)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE NOUDON
     &(F1,NAME1FR,NAME1GB,MODE1,
     & F2,NAME2FR,NAME2GB,MODE2,
     & F3,NAME3FR,NAME3GB,MODE3,X,Y,NPOIN,NDON,BINDON,NBOR,NPTFR,
     & AT,DDC,TV1,TV2,F11,F12,F21,F22,F31,F32,INDIC,CHDON,NVAR,TEXTE,
     & TROUVE,UNITIME,PHASTIME)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NDON,NPOIN,NPTFR,INDIC,NVAR
      INTEGER, INTENT(IN)             :: MODE1,MODE2,MODE3
      INTEGER, INTENT(IN)             :: NBOR(NPTFR,2)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN),Y(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: F1(NPOIN),F2(NPOIN),F3(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: F11(NPOIN),F21(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: F12(NPOIN),F22(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: F31(NPOIN),F32(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: AT,DDC,UNITIME,PHASTIME
      DOUBLE PRECISION, INTENT(INOUT) :: TV1,TV2
      CHARACTER(LEN=3), INTENT(IN)    :: BINDON
      CHARACTER(LEN=7), INTENT(IN)    :: CHDON
      CHARACTER(LEN=32),INTENT(IN)    :: NAME1FR,NAME2FR,NAME3FR
      CHARACTER(LEN=32),INTENT(IN)    :: NAME1GB,NAME2GB,NAME3GB
      CHARACTER(LEN=32),INTENT(IN)    :: TEXTE(30)
      LOGICAL, INTENT(INOUT)          :: TROUVE(3)
!
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE P_READ2(BUFFER,NBYTES,SOURCE,TYPE)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER NBYTES, SOURCE, TYPE
      INTEGER BUFFER(*)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE P_WRIT2(BUFFER, NBYTES, DEST, TYPE)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER NBYTES,DEST,TYPE
      INTEGER BUFFER(*)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PREDIF
     &(CX    , CY    , CT    , DT    , X     , Y     , TETA  , COSTET,
     & SINTET, FREQ  , IKLE2 , IFABOR, ETAP1 , TRA01 , SHP   ,
     & SHZ   , ELT   , ETA   , DEPTH , DZX   , DZY   , XK    ,
     & CG    , ITR01 , NPOIN3, NPOIN2, NELEM2, NPLAN , NF    , SURDET,
     & COURAN, SPHE  , PROINF, A     , DFREQ , F     , CCG   , DIV   ,
     & DELTA , DDX   , DDY   , EPS   , NBOR  , NPTFR , XKONPT, RK    ,
     & RX    , RY    , RXX   , RYY   , NEIGB , NB_CLOSE,DIFFRA,MAXNSP,
     & FLTDIF, MESH3D, MESH  , IELM3 , TB    , ISUB  , SIKLE2)
      USE BIEF_DEF
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER NPOIN3,NPOIN2,NELEM2,NPLAN,NF,NPTFR,MAXNSP,IELM3
      INTEGER NBOR(NPTFR),DIFFRA
      INTEGER ITR01(NPOIN3,3)
      INTEGER ELT(NPOIN3,NF),ETA(NPOIN3,NF)
      INTEGER IKLE2(NELEM2,3),IFABOR(NELEM2,7),ETAP1(NPLAN)
      INTEGER NB_CLOSE(NPOIN2),NEIGB(NPOIN2,MAXNSP)
      INTEGER, INTENT(INOUT) :: ISUB(NPOIN3,NF)
      DOUBLE PRECISION RK(MAXNSP,NPOIN2)
      DOUBLE PRECISION RX(MAXNSP,NPOIN2),RY(MAXNSP,NPOIN2)
      DOUBLE PRECISION RXX(MAXNSP,NPOIN2),RYY(MAXNSP,NPOIN2)
      DOUBLE PRECISION X(NPOIN2),Y(NPOIN2)
      DOUBLE PRECISION XK(NPOIN2,NF),CG(NPOIN2,NF)
      DOUBLE PRECISION FREQ(NF)
      DOUBLE PRECISION SINTET(NPLAN),COSTET(NPLAN)
      DOUBLE PRECISION SURDET(NELEM2)
      DOUBLE PRECISION DT,EPS
      DOUBLE PRECISION TRA01(NPOIN3,8)
      DOUBLE PRECISION DEPTH(NPOIN2),DZX(NPOIN2),DZY(NPOIN2)
      DOUBLE PRECISION DDX(NPOIN2),DDY(NPOIN2),A(NPOIN2)
      DOUBLE PRECISION DFREQ(NF)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION CCG(NPOIN2),DIV(NPOIN2)
      DOUBLE PRECISION DELTA(NPOIN2),XKONPT(NPOIN2)
      LOGICAL COURAN,SPHE,PROINF,FLTDIF
      TYPE(BIEF_OBJ), INTENT(IN)    :: TETA,SIKLE2
      TYPE(BIEF_OBJ), INTENT(INOUT) :: SHP,SHZ,CX,CY,CT,TB
      TYPE(BIEF_MESH),INTENT(INOUT) :: MESH3D,MESH
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PRELEO_MPI
     &(XLEO,YLEO,NLEO,X,Y,IKLE,SURDET,NPOIN2,NELEM2,NOLEO,ISLEO)
      USE BIEF_DEF
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER NLEO,NPOIN2,NELEM2
      INTEGER IKLE(NELEM2,3),NOLEO(NLEO)
      DOUBLE PRECISION X(NPOIN2),Y(NPOIN2),XLEO(NLEO),YLEO(NLEO)
      DOUBLE PRECISION SURDET(NELEM2)
      LOGICAL ISLEO(NLEO)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PRELEO
     &(XLEO,YLEO,NLEO,X,Y,NPOIN2,NOLEO)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER NLEO,NPOIN2
      INTEGER NOLEO(NLEO)
      DOUBLE PRECISION X(NPOIN2),Y(NPOIN2),XLEO(NLEO),YLEO(NLEO)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PRENL1
     &( IANGNL, COEFNL, NPLAN , NF    , RAISF , XLAMD )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NPLAN , NF
      INTEGER  IANGNL(NPLAN,8)
      DOUBLE PRECISION COEFNL(16)
      DOUBLE PRECISION RAISF , XLAMD
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
!V6P1 New subroutine
      INTERFACE
        SUBROUTINE PRENL2
     &( IANGNL, COEFNL, NPLAN , NF    , RAISF , XLAMD , XMU   )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NPLAN , NF
      INTEGER  IANGNL(NPLAN,16)
      DOUBLE PRECISION RAISF , XLAMD , XMU
      DOUBLE PRECISION COEFNL(32)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
!V6P1 New subroutine
      INTERFACE
        SUBROUTINE PRENL3
     &( NF    , NT    , RAISF , TAILF , FREQ  , TB_SCA, LBUF  , DIMBUF,
     &  F_POIN, F_COEF, T_POIN, F_PROJ, IQ_OM1, NQ_TE1, NQ_OM2, NF1   ,
     &  NT1   , K_IF1 , K_IF2 , K_IF3 , TB_V14, TB_V24, TB_V34, K_1P  ,
     &  K_1M  , K_1P2P, K_1P3M, K_1P2M, K_1P3P, K_1M2P, K_1M3M, K_1M2M,
     &  K_1M3P, TB_TPM, TB_TMP, TB_FAC, SEUIL1, SEUIL2, ELIM  , NCONF ,
     &  NCONFM, IDCONF)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER           NF    , NT
      DOUBLE PRECISION  RAISF , TAILF , FREQ(NF)
      INTEGER           LBUF  , DIMBUF
      INTEGER           F_POIN(DIMBUF), T_POIN(DIMBUF)
      DOUBLE PRECISION  F_COEF(DIMBUF), F_PROJ(DIMBUF), TB_SCA(DIMBUF)
      INTEGER           IQ_OM1 , NQ_TE1, NQ_OM2
      INTEGER           NF1   , NT1
      INTEGER           K_IF1(NF1), K_1P(NT1,NF1), K_1M(NT1,NF1)
      DOUBLE PRECISION  TB_V14(NF1)
      INTEGER           K_IF2 (NQ_OM2,NT1,NF1), K_IF3 (NQ_OM2,NT1,NF1)
      INTEGER           K_1P2P(NQ_OM2,NT1,NF1), K_1P3M(NQ_OM2,NT1,NF1)
      INTEGER           K_1P2M(NQ_OM2,NT1,NF1), K_1P3P(NQ_OM2,NT1,NF1)
      INTEGER           K_1M2P(NQ_OM2,NT1,NF1), K_1M3M(NQ_OM2,NT1,NF1)
      INTEGER           K_1M2M(NQ_OM2,NT1,NF1), K_1M3P(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION  TB_V24(NQ_OM2,NT1,NF1), TB_V34(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION  TB_TPM(NQ_OM2,NT1,NF1), TB_TMP(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION  TB_FAC(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION  SEUIL1, SEUIL2, ELIM
      INTEGER           NCONF , NCONFM, IDCONF(NCONFM,3)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PREPRO
     &( CX    , CY    , CT    , CF    , DT    , X     , Y     ,
     &  TETA  , COSTET, SINTET, FREQ  , IKLE2 , IFABOR, ETAP1 , TRA01 ,
     &  SHP   , SHZ   , SHF   , ELT   , ETA   , FRE   ,
     &  DEPTH , DZHDT , DZX   , DZY   , U     , V     , DUX   , DUY   ,
     &  DVX   , DVY   , XK    , CG    , COSF  , TGF   , ITR01 , NPOIN3,
     &  NPOIN2, NELEM2, NPLAN , NF    , SURDET, COURAN, SPHE  ,
     &  PROINF, PROMIN, MESH  , MESH3D,SIKLE2,TB,IELM3, DIFFRA,
     &  MAREE , ISUB)
      USE BIEF_DEF
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)    :: NPOIN3,NPOIN2,NELEM2,NPLAN,NF,DIFFRA
      INTEGER, INTENT(INOUT) :: IELM3
      DOUBLE PRECISION, INTENT(IN) :: DT,PROMIN
      DOUBLE PRECISION DZHDT(NPOIN2)
      DOUBLE PRECISION X(NPOIN2),Y(NPOIN2)
      DOUBLE PRECISION XK(NPOIN2,NF),CG(NPOIN2,NF)
      DOUBLE PRECISION SINTET(NPLAN),COSTET(NPLAN)
      DOUBLE PRECISION COSF(NPOIN2),TGF(NPOIN2)
      DOUBLE PRECISION DEPTH(NPOIN2),DZX(NPOIN2),DZY(NPOIN2)
      DOUBLE PRECISION U(NPOIN2),DUX(NPOIN2),DUY(NPOIN2)
      DOUBLE PRECISION V(NPOIN2),DVX(NPOIN2),DVY(NPOIN2)
      DOUBLE PRECISION SURDET(NELEM2)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA01(NPOIN3,6)
      INTEGER, INTENT(INOUT) :: ELT(NPOIN3,NF),ETA(NPOIN3,NF)
      INTEGER, INTENT(INOUT) :: ISUB(NPOIN3,NF)
      INTEGER, INTENT(INOUT) :: FRE(NPOIN3,NF)
      INTEGER, INTENT(IN)    :: IKLE2(NELEM2,3)
      INTEGER, INTENT(IN)    :: ETAP1(NPLAN)
      INTEGER, INTENT(INOUT) :: ITR01(NPOIN3,3),IFABOR(NELEM2,7)
      LOGICAL, INTENT(IN)    :: COURAN,SPHE,PROINF,MAREE
      TYPE(BIEF_OBJ), INTENT(INOUT) :: SHP,SHZ,SHF,CX,CY,CT,CF,TB
      TYPE(BIEF_OBJ), INTENT(IN)    :: SIKLE2,TETA,FREQ
      TYPE(BIEF_MESH), INTENT(INOUT):: MESH,MESH3D
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PREQT2
     &( TETA  , NPLAN , BDISPB, BDSSPB, NBD , INDI )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER           NPLAN,NBD
      INTEGER           INDI(NPLAN)
      DOUBLE PRECISION  BDISPB , BDSSPB
      DOUBLE PRECISION  TETA(NPLAN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PROPA
     &(F,B,SHP,SHZ,SHF,ELT,ETA,FRE,IKLE_EXT,NPOIN3,NPOIN2,
     & NPLAN,NF,COURAN,TRA01,TRA02,ITR01,T3_01,T3_02,ISUB,MESH3D)
      USE BIEF_DEF
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER NPOIN3,NPOIN2,NPLAN,NF
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN) :: B(NPOIN2,NF)
      DOUBLE PRECISION TRA01(NPOIN3,8)
      INTEGER, INTENT(INOUT) :: ELT(NPOIN3,NF),ETA(NPOIN3,NF)
      INTEGER, INTENT(INOUT) :: FRE(NPOIN3,NF)
      INTEGER, INTENT(IN)    :: ISUB(NPOIN3,NF)
      INTEGER, INTENT(INOUT) :: ITR01(NPOIN3*3)
      LOGICAL, INTENT(IN)            :: COURAN
      TYPE(BIEF_OBJ), INTENT(INOUT)  :: SHP,SHZ,SHF,T3_01,T3_02,TRA02
      TYPE(BIEF_OBJ), INTENT(IN)     :: IKLE_EXT
      TYPE(BIEF_MESH), INTENT(INOUT) :: MESH3D
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        FUNCTION QBBJ78( B     , IQBBJ )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      DOUBLE PRECISION QBBJ78, B
      INTEGER  IQBBJ
        END FUNCTION
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QBREK1
     &( TSTOT , TSDER , F     , FCAR  , VARIAN, DEPTH , ALFABJ, GAMBJ1,
     &  GAMBJ2, IQBBJ , IHMBJ , NF    , NPLAN , NPOIN2, BETA  )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER IQBBJ,IHMBJ,NF,NPLAN,NPOIN2
      DOUBLE PRECISION ALFABJ,GAMBJ1,GAMBJ2
      DOUBLE PRECISION TSTOT(NPOIN2,NPLAN,NF), TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF), VARIAN(NPOIN2),FCAR(NPOIN2)
      DOUBLE PRECISION DEPTH(NPOIN2), BETA(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QBREK2
     &( TSTOT , TSDER , F     , FCAR  , VARIAN, DEPTH , BORETG, GAMATG,
     &  IWHTG , NF    , NPLAN , NPOIN2, BETA  )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NF    , NPLAN , NPOIN2, IWHTG
      DOUBLE PRECISION BORETG, GAMATG
      DOUBLE PRECISION DEPTH(NPOIN2), BETA(NPOIN2), FCAR(NPOIN2)
      DOUBLE PRECISION TSTOT(NPOIN2,NPLAN,NF), TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION     F(NPOIN2,NPLAN,NF), VARIAN(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QBREK3
     &( TSTOT , TSDER , F     , FCAR  , VARIAN, DEPTH , ALFARO, GAMARO,
     &  GAM2RO, IEXPRO, IDISRO, NF    , NPLAN , NPOIN2, BETA  )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER IEXPRO, IDISRO, NF    , NPLAN , NPOIN2
      DOUBLE PRECISION ALFARO, GAMARO, GAM2RO
      DOUBLE PRECISION DEPTH(NPOIN2), BETA(NPOIN2), FCAR(NPOIN2)
      DOUBLE PRECISION TSTOT(NPOIN2,NPLAN,NF), TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF), VARIAN(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QBREK4
     &( TSTOT , TSDER , F     , FCAR  , VARIAN, DEPTH , BETAIH, EM2SIH,
     &  GRAVIT, NF    , NPLAN , NPOIN2, BETA  )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER          NF    , NPLAN , NPOIN2
      DOUBLE PRECISION BETAIH, EM2SIH, GRAVIT
      DOUBLE PRECISION DEPTH(NPOIN2), BETA(NPOIN2), FCAR(NPOIN2)
      DOUBLE PRECISION TSTOT(NPOIN2,NPLAN,NF), TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF), VARIAN(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QFROT1
     &( TSTOT , TSDER , F     , XK    , DEPTH , CFROT1, GRAVIT, NF    ,
     &  NPLAN , NPOIN2, BETA  )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NF , NPLAN , NPOIN2
      DOUBLE PRECISION CFROT1, GRAVIT
      DOUBLE PRECISION DEPTH(NPOIN2), BETA(NPOIN2)
      DOUBLE PRECISION TSTOT(NPOIN2,NPLAN,NF), TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF),    XK(NPOIN2,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        FUNCTION QGAUSS
     &( B     , N     , A     , XM    )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  N
      DOUBLE PRECISION QGAUSS
      DOUBLE PRECISION B , A , XM
        END FUNCTION
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QMOUT1
     &( TSTOT , TSDER , F     , XK    , ENRJ  , FREQ  , FMOY  , XKMOY ,
     &  PROINF, CMOUT1, CMOUT2, NF  , NPLAN , NPOIN2, TAUX1   , BETA  )
!
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NF,NPLAN,NPOIN2
      DOUBLE PRECISION, INTENT(IN)    :: CMOUT1,CMOUT2
      DOUBLE PRECISION, INTENT(IN)    :: XKMOY(NPOIN2),ENRJ(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: FREQ(NF),FMOY(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TAUX1(NPOIN2),BETA(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TSTOT(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)    :: XK(NPOIN2,NF)
      LOGICAL, INTENT(IN)             :: PROINF
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QMOUT2
     &( TSTOT , TSDER , F     , XK    , ENRJ  , FREQ  , FMOY  , XKMOY ,
     &  USOLD , USNEW , DEPTH , PROINF, CMOUT3, CMOUT4, CMOUT5, CMOUT6,
     &  NF    , NPLAN , NPOIN2, CIMPLI, TAUX1 ,F_INT  , BETOTO, BETOTN)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NF,NPLAN,NPOIN2
      DOUBLE PRECISION, INTENT(IN)    :: CMOUT3,CMOUT4
      DOUBLE PRECISION, INTENT(IN)    :: CMOUT5,CMOUT6,CIMPLI
      DOUBLE PRECISION, INTENT(IN)    :: USNEW(NPOIN2),USOLD(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: FREQ(NF),DEPTH(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: FMOY(NPOIN2),XK(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(IN)    :: ENRJ(NPOIN2),XKMOY(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: F_INT(NPOIN2),TAUX1(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: BETOTO(NPOIN2),BETOTN(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TSTOT(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: F(NPOIN2,NPLAN,NF)
      LOGICAL, INTENT(IN)             :: PROINF
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!=======================================================================
!VBA AJOUT SUBROUTINE QVEG1
!=======================================================================
      INTERFACE
        SUBROUTINE QVEG1
     &( TSTOT , TSDER , F , VARIAN , DEPTH, FMOY ,
     &  XKMOY , NF    , NPLAN  , NPOIN2   , BETA  )
!
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NF,NPLAN,NPOIN2
      DOUBLE PRECISION, INTENT(IN)    :: XKMOY(NPOIN2),VARIAN(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: DEPTH(NPOIN2),FMOY(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: BETA(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TSTOT(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF)
        END SUBROUTINE
      END INTERFACE
!
!=========================================================================
!VBA FIN AJOUT SUBROUTINE QVEG1
!=========================================================================
!
      INTERFACE
        SUBROUTINE QNLIN1
     &( TSTOT , TSDER , IANGNL, COEFNL, NF    , NPLAN , F1    , RAISF ,
     &  TAILF , PROINF, NPOIN2, F     , DEPTH , XKMOY , TAUX1 , TAUX2 ,
     &  TAUX3 , TAUX4 , TAUX5 , DFINI )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NPOIN2,NPLAN,NF
      INTEGER, INTENT(IN)             :: IANGNL(NPLAN,8)
      DOUBLE PRECISION, INTENT(IN)    :: F1,RAISF,TAILF
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF),COEFNL(16)
      DOUBLE PRECISION, INTENT(IN)    :: XKMOY(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TSTOT(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT) :: TAUX1(NPOIN2),TAUX2(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TAUX3(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TAUX4(NPOIN2),TAUX5(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: DFINI(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: DEPTH(NPOIN2)
      LOGICAL, INTENT(IN)             :: PROINF
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
!V6P1 New subroutine
      INTERFACE
        SUBROUTINE QNLIN2
     &( TSTOT , TSDER , IANGNL, COEFNL, NF    , NPLAN , F1    , RAISF ,
     &  TAILF , PROINF, NPOIN2, F     , DEPTH , XKMOY , TAUX1 , DFINI ,
     &  XCOEF )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NPOIN2, NPLAN , NF
      INTEGER  IANGNL(NPLAN,16)
      DOUBLE PRECISION F1  , RAISF , TAILF
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF), COEFNL(32), XCOEF
      DOUBLE PRECISION TSTOT(NPOIN2,NPLAN,NF), TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION TAUX1(NPOIN2), DFINI(NPOIN2), DEPTH(NPOIN2)
      DOUBLE PRECISION XKMOY(NPOIN2)
      LOGICAL  PROINF
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
!V6P1 New subroutine
      INTERFACE
        SUBROUTINE QNLIN3
     &( TSTOT , TSDER , F     , NB_NOD, FREQ  , TETA  , NT    , NF    ,
     &  RAISF , TAILF , SEUIL , FSEUIL, LBUF  , DIMBUF, F_POIN, F_COEF,
     &  F_PROJ, T_POIN, TB_SCA, NQ_TE1, NQ_OM2, NF1   , NT1   , DFREQ ,
     &  K_IF1 , K_IF2 , K_IF3 , TB_V14, TB_V24, TB_V34, K_1P  , K_1M  ,
     &  K_1P2P, K_1P3M, K_1P2M, K_1P3P, K_1M2P, K_1M3M, K_1M2M, K_1M3P,
     &  TB_TPM, TB_TMP, TB_FAC, NCONF , NCONFM, IDCONF)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER           NF    , NT    , NB_NOD
      DOUBLE PRECISION  TAILF , RAISF , SEUIL
      DOUBLE PRECISION  FREQ(NF), DFREQ(NF), TETA(NT), FSEUIL(NB_NOD)
      DOUBLE PRECISION  F(NB_NOD,NT,NF), TSTOT(NB_NOD,NT,NF)
      DOUBLE PRECISION  TSDER(NB_NOD,NT,NF)
      INTEGER           LBUF  , DIMBUF
      INTEGER           F_POIN(DIMBUF), T_POIN(DIMBUF)
      DOUBLE PRECISION  F_COEF(DIMBUF), F_PROJ(DIMBUF), TB_SCA(DIMBUF)
      INTEGER           NQ_TE1, NQ_OM2, NF1   , NT1
      INTEGER           K_IF1(NF1), K_1P(NT1,NF1), K_1M(NT1,NF1)
      INTEGER           K_IF2 (NQ_OM2,NT1,NF1), K_IF3 (NQ_OM2,NT1,NF1)
      INTEGER           K_1P2P(NQ_OM2,NT1,NF1), K_1P3M(NQ_OM2,NT1,NF1)
      INTEGER           K_1P2M(NQ_OM2,NT1,NF1), K_1P3P(NQ_OM2,NT1,NF1)
      INTEGER           K_1M2P(NQ_OM2,NT1,NF1), K_1M3M(NQ_OM2,NT1,NF1)
      INTEGER           K_1M2M(NQ_OM2,NT1,NF1), K_1M3P(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION  TB_V14(NF1)           , TB_FAC(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION  TB_V24(NQ_OM2,NT1,NF1), TB_V34(NQ_OM2,NT1,NF1)
      DOUBLE PRECISION  TB_TPM(NQ_OM2,NT1,NF1), TB_TMP(NQ_OM2,NT1,NF1)
      INTEGER           NCONF , NCONFM, IDCONF(NCONFM,3)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QTRIA1
     &( F     , XK    , FREQ  , DEPTH , RAISF , ALFLTA, RFMLTA,
     &  NF    , NPLAN , NPOIN2, TSTOT , TSDER , FTOT  , FMOY  )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NF, NPLAN, NPOIN2
      DOUBLE PRECISION  RAISF , ALFLTA, RFMLTA
      DOUBLE PRECISION  F(NPOIN2,NPLAN,NF), XK(NPOIN2,NF)
      DOUBLE PRECISION  FREQ(NF), DEPTH(NPOIN2)
      DOUBLE PRECISION  TSTOT(NPOIN2,NPLAN,NF), TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION  FTOT(NPOIN2) , FMOY(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QTRIA2
     &( F     , XK    , FREQ  , DFREQ , DEPTH , TETA  , SINTET, COSTET ,
     &  KSPB  , BDISPB, BDSSPB, RAISF , NF    , NPLAN , NPOIN2 ,
     &  NBD   , INDI  , TSTOT , TSDER )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NF, NPLAN, NPOIN2, NBD
      INTEGER           INDI(NBD)
      DOUBLE PRECISION  BDISPB , BDSSPB, KSPB  , RAISF
      DOUBLE PRECISION  F(NPOIN2,NPLAN,NF), XK(NPOIN2,NF)
      DOUBLE PRECISION  DFREQ(NF) , FREQ(NF), DEPTH(NPOIN2)
      DOUBLE PRECISION  TETA(NPLAN) , SINTET(NPLAN) , COSTET(NPLAN)
      DOUBLE PRECISION  TSTOT(NPOIN2,NPLAN,NF), TSDER(NPOIN2,NPLAN,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QWIND1
     &( TSTOT , TSDER , F     , XK    , FREQ  , USOLD , USNEW , TWOLD ,
     &  TWNEW , Z0OLD , Z0NEW , TETA  , ROAIR , ROEAU , BETAM , XKAPPA,
     &  DECAL , GRAVIT, NF    , NPLAN , NPOIN2, CIMPLI, TOLD  , TNEW  ,
     &  CPHAS , USN   , USO   , OMNEW , OMOLD , BETAN , BETAO )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION GRAVIT,ROAIR,ROEAU,BETAM,XKAPPA,DECAL,CIMPLI
      DOUBLE PRECISION TSTOT(NPOIN2,NPLAN,NF),TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF),XK(NPOIN2,NF),FREQ(NF)
      DOUBLE PRECISION USOLD(NPOIN2), USNEW(NPOIN2),TWOLD(NPOIN2)
      DOUBLE PRECISION TWNEW(NPOIN2),Z0OLD(NPOIN2),Z0NEW(NPOIN2)
      DOUBLE PRECISION TETA(NPLAN),TOLD(NPOIN2,NPLAN)
      DOUBLE PRECISION TNEW(NPOIN2,NPLAN), CPHAS(NPOIN2),USN(NPOIN2)
      DOUBLE PRECISION USO(NPOIN2), OMNEW(NPOIN2),OMOLD(NPOIN2)
      DOUBLE PRECISION BETAN(NPOIN2), BETAO(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QWIND2
     &( TSTOT , TSDER , F     , XK    , FREQ  , USOLD , USNEW , TWOLD ,
     &  TWNEW , TETA  , ROAIR , ROEAU , NF    , NPLAN , NPOIN2,
     &  CIMPLI, USN   , USO   )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)            :: NF,NPLAN,NPOIN2
      DOUBLE PRECISION, INTENT(IN)   :: ROAIR,ROEAU,CIMPLI
      DOUBLE PRECISION, INTENT(IN)   :: FREQ(NF),TETA(NPLAN)
      DOUBLE PRECISION, INTENT(IN)   :: TWOLD(NPOIN2),TWNEW(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)   :: USNEW(NPOIN2),USOLD(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT):: USO(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT):: USN(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT):: TSTOT(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(INOUT):: TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)   :: F(NPOIN2,NPLAN,NF),XK(NPOIN2,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QWIND3
     &( TSTOT , TSDER , F     , XK    , FREQ  , USOLD , USNEW , TWOLD ,
     &  TWNEW , TETA  , GRAVIT, NF    , NPLAN , NPOIN2, CIMPLI, COEFWD,
     &  COEFWE, COEFWF, COEFWH, BETAN , BETAO , DIRN  , DIRO  )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER    NF  , NPLAN        , NPOIN2
      DOUBLE PRECISION GRAVIT       , CIMPLI
      DOUBLE PRECISION FREQ(NF)     , TETA(NPLAN)
      DOUBLE PRECISION TWOLD(NPOIN2), TWNEW(NPOIN2), USNEW(NPOIN2)
      DOUBLE PRECISION BETAO(NPOIN2), BETAN(NPOIN2), USOLD(NPOIN2)
      DOUBLE PRECISION DIRO(NPOIN2) , DIRN(NPOIN2)
      DOUBLE PRECISION TSTOT(NPOIN2,NPLAN,NF), TSDER(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF)    , XK(NPOIN2,NF)
      DOUBLE PRECISION COEFWD , COEFWE , COEFWF , COEFWH
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE QWINDL
     &( TSTOT , FREQ  , USOLD , USNEW , TWOLD , TWNEW , TETA  ,
     &  NF    , NPLAN , NPOIN2, CIMPLI, USN   , USO   , FPMO  , FPMN )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NF,NPLAN,NPOIN2
      DOUBLE PRECISION, INTENT(IN)    :: CIMPLI
      DOUBLE PRECISION, INTENT(IN)    :: FREQ(NF),TETA(NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: FPMO(NPOIN2),FPMN(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: TWOLD(NPOIN2),TWNEW(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: USNEW(NPOIN2),USOLD(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: USO(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: USN(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: TSTOT(NPOIN2,NPLAN,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE RADIAT
     &( FX    , FY    , SXX   , SXY   , SYY   , XK1   , FS    , CG1   ,
     &  DEPTH1, CGSUC1, DSXXDX, DSXYDX, DSXYDY, DSYYDY )
      USE BIEF_DEF
      USE DECLARATIONS_TOMAWAC, ONLY : NPLAN,NF,NPOIN2
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      DOUBLE PRECISION FS(NPOIN2,NPLAN,NF),CG1(NPOIN2,NF)
      DOUBLE PRECISION DEPTH1(NPOIN2),CGSUC1(NPOIN2,NF),XK1(NPOIN2,NF)
      DOUBLE PRECISION DSXXDX(NPOIN2),DSXYDX(NPOIN2),FX(NPOIN2)
      DOUBLE PRECISION DSXYDY(NPOIN2),DSYYDY(NPOIN2),FY(NPOIN2)
      DOUBLE PRECISION SXX(NPOIN2),SXY(NPOIN2),SYY(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE RPI_INTR
     &(NEIGB  , NB_CLOSE, RK      , RX  , RY      , RXX     , RYY ,
     & NPOIN2 , I       , MAXNSP  , FFD , FIRDIV1 , FIRDIV2 ,
     & SECDIV1, SECDIV2 , SECDIV3, FRSTDIV , SCNDDIV)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: NPOIN2, MAXNSP,I
      INTEGER, INTENT(IN) :: NEIGB(NPOIN2,MAXNSP),NB_CLOSE(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: RK(MAXNSP)
      DOUBLE PRECISION, INTENT(IN)    :: RX(MAXNSP),RY(MAXNSP)
      DOUBLE PRECISION, INTENT(IN)    :: RXX(MAXNSP),RYY(MAXNSP)
      DOUBLE PRECISION, INTENT(INOUT) :: SECDIV1,SECDIV2,SECDIV3
      DOUBLE PRECISION, INTENT(INOUT) :: FIRDIV1,FIRDIV2
      DOUBLE PRECISION, INTENT(IN)    :: FFD(NPOIN2)
      LOGICAL, INTENT(IN)             :: FRSTDIV,SCNDDIV
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
!V6P2 New subroutine
      INTERFACE
        SUBROUTINE RPI_INVR
     &( X     , Y     , NEIGB , NB_CLOSE, RK_D , RX_D , RY_D  , RXX_D ,
     &  RYY_D , NPOIN2, I     , QUO   , AC    , MAXNSP, MINDIST )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER NPOIN2, MAXNSP, I
      INTEGER NEIGB(NPOIN2,MAXNSP), NB_CLOSE(NPOIN2)
      DOUBLE PRECISION QUO, AC
      DOUBLE PRECISION X(NPOIN2), Y(NPOIN2)
      DOUBLE PRECISION MINDIST(NPOIN2)
      DOUBLE PRECISION RK_D(MAXNSP)
      DOUBLE PRECISION RX_D(MAXNSP), RY_D(MAXNSP)
      DOUBLE PRECISION RXX_D(MAXNSP), RYY_D(MAXNSP)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE SEMIMP
     &( F     ,XK    ,FREQ  ,DFREQ ,DEPTH ,VENTX ,VENTY ,X     ,Y     ,
     &  NVEB  ,NVEF  ,NBOR  ,NPTFR ,DDC   ,TV1   ,TV2   ,
     &  U1    ,V1    ,U2    ,V2    ,TETA  ,SINTET,COSTET,INDIC ,
     &  TAILF ,RAISF ,GRAVIT,CFROT1,CMOUT1,CMOUT2,CMOUT3,CMOUT4,CMOUT5,
     &  CMOUT6,TPROP ,DTSI  ,ROAIR ,ROEAU ,XKAPPA,BETAM ,DECAL ,CDRAG ,
     &  ALPHA ,ZVENT ,NF    ,NPLAN ,NPOIN2,IANGNL,COEFNL,F1    ,NSITS ,
     &  SMOUT ,SFROT ,SVENT ,LVENT ,STRIF ,VENT  ,VENSTA,VX_CTE,VY_CTE,
     &  SBREK ,ALFABJ,GAMBJ1,GAMBJ2,IQBBJ ,IHMBJ ,IFRBJ ,BORETG,GAMATG,
     &  IWHTG ,IFRTG ,ALFARO,GAMARO,GAM2RO,IDISRO,IEXPRO,IFRRO ,BETAIH,
     &  EM2SIH,IFRIH ,COEFHS,XDTBRK,NDTBRK,STRIA ,ALFLTA,RFMLTA,KSPB  ,
     &  BDISPB,BDSSPB,PROINF,DF_LIM,LIMIT ,CIMPLI,COEFWD,COEFWE,COEFWF,
     &  COEFWH,NOMVEB,NOMVEF,BINVEN,NBD   ,QINDI ,TAUWAV,USOLD ,TWOLD ,
     &  Z0OLD ,TSTOT ,TSDER ,TOLD  ,TNEW  ,VARIAN,FMOY  ,XKMOY ,USNEW ,
     &  Z0NEW ,TWNEW ,TAUX1 ,TAUX2 ,TAUX3 ,TAUX4 ,TAUX5 ,TAUX6 ,TAUX7 ,
     &  BETA  ,NQ_TE1,NQ_OM2,NF1   ,NF2   ,NT1   ,NCONF ,NCONFM,
     &  SEUIL ,LBUF  ,DIMBUF,F_POIN,T_POIN,F_COEF,F_PROJ,TB_SCA,K_IF1 ,
     &  K_1P  ,K_1M  ,K_IF2 ,K_IF3 ,K_1P2P,K_1P2M,K_1P3P,K_1P3M,K_1M2P,
     &  K_1M2M,K_1M3P,K_1M3M,IDCONF,TB_V14,TB_V24,TB_V34,TB_TPM,TB_TMP,
     &  TB_FAC,MDIA  ,IANMDI,COEMDI,NVWIN,DIAGHF)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER          NPOIN2, NPLAN , NF    , NSITS , NPTFR , NVEB
      INTEGER          NVEF  , LIMIT , NVWIN
      INTEGER          SMOUT , SFROT , SVENT , STRIF , SBREK , INDIC
      INTEGER          IQBBJ , IHMBJ , IFRBJ , IWHTG , IFRTG , IFRRO
      INTEGER          IEXPRO, IFRIH , NDTBRK, IDISRO, STRIA
      INTEGER          NBOR(NPTFR)   , IANGNL(NPLAN,8)
      INTEGER          NBD   , QINDI(NBD)    ,DIAGHF
      DOUBLE PRECISION TAILF , CFROT1, GRAVIT, RAISF , DTSI  , TPROP ,
     &                 CMOUT1, CMOUT2, DDC   , TV1   , TV2   , ZVENT ,
     &                 ROAIR , ROEAU , XKAPPA, BETAM , DECAL , CDRAG ,
     &                 ALPHA , GAMBJ1, GAMBJ2, ALFABJ, BORETG, GAMATG,
     &                 COEFHS, VX_CTE, VY_CTE, CIMPLI,
     &                 GAMARO, ALFARO, GAM2RO, EM2SIH, BETAIH, XDTBRK,
     &                 ALFLTA, RFMLTA, KSPB  , BDISPB, BDSSPB, F1
      DOUBLE PRECISION  DEPTH(NPOIN2), USNEW(NPOIN2) , USOLD(NPOIN2) ,
     &                 VARIAN(NPOIN2),  FMOY(NPOIN2) , XKMOY(NPOIN2) ,
     &                  TWOLD(NPOIN2), TWNEW(NPOIN2) , Z0OLD(NPOIN2) ,
     &                  Z0NEW(NPOIN2), VENTX(NPOIN2) , VENTY(NPOIN2) ,
     &                     U1(NPOIN2),    U2(NPOIN2) ,    V1(NPOIN2) ,
     &                     V2(NPOIN2),     X(NPOIN2) ,     Y(NPOIN2) ,
     &                 TAUWAV(NPOIN2), TAUX1(NPOIN2) , TAUX2(NPOIN2) ,
     &                  TAUX3(NPOIN2), TAUX4(NPOIN2) , TAUX5(NPOIN2) ,
     &                  TAUX6(NPOIN2), TAUX7(NPOIN2) , COEFNL(16)    ,
     &                    TETA(NPLAN), SINTET(NPLAN) , COSTET(NPLAN) ,
     &                    F(NPOIN2,NPLAN,NF),   XK(NPOIN2,NF)        ,
     &                    DF_LIM(NPOIN2,NF) ,
     &                 TSDER(NPOIN2,NPLAN,NF),TSTOT(NPOIN2,NPLAN,NF) ,
     &                 FREQ(NF), DFREQ(NF),
     &                 TOLD(NPOIN2,NPLAN), TNEW(NPOIN2,NPLAN)
      DOUBLE PRECISION BETA(NPOIN2)
      CHARACTER*144 NOMVEB, NOMVEF
      CHARACTER*3 BINVEN
      LOGICAL  PROINF, VENT , VENSTA
      INTEGER           LVENT
      DOUBLE PRECISION  CMOUT3, CMOUT4, CMOUT5, CMOUT6
      DOUBLE PRECISION  COEFWD, COEFWE, COEFWF, COEFWH
      INTEGER           MDIA
      INTEGER           IANMDI(NPLAN,16,MDIA)
      DOUBLE PRECISION  COEMDI(32,MDIA)
      INTEGER  NQ_TE1, NQ_OM2, NF1, NF2 , NT1
      INTEGER  NCONF , NCONFM
      DOUBLE PRECISION SEUIL
      INTEGER  LBUF  , DIMBUF
      INTEGER           F_POIN(DIMBUF), T_POIN(DIMBUF)
      DOUBLE PRECISION  F_COEF(DIMBUF), F_PROJ(DIMBUF), TB_SCA(DIMBUF)
      INTEGER K_IF1 (1:NF1)
      INTEGER K_1P  (1:NT1,1:NF1), K_1M(1:NT1,1:NF1)
      INTEGER K_IF2 (1:NF2,1:NT1,1:NF1), K_IF3 (1:NF2,1:NT1,1:NF1),
     &        K_1P2P(1:NF2,1:NT1,1:NF1), K_1P2M(1:NF2,1:NT1,1:NF1),
     &        K_1P3P(1:NF2,1:NT1,1:NF1), K_1P3M(1:NF2,1:NT1,1:NF1),
     &        K_1M2P(1:NF2,1:NT1,1:NF1), K_1M2M(1:NF2,1:NT1,1:NF1),
     &        K_1M3P(1:NF2,1:NT1,1:NF1), K_1M3M(1:NF2,1:NT1,1:NF1)
      INTEGER IDCONF(1:NCONFM,1:3)
      DOUBLE PRECISION TB_V14(1:NF1)
      DOUBLE PRECISION
     &        TB_V24(1:NF2,1:NT1,1:NF1), TB_V34(1:NF2,1:NT1,1:NF1),
     &        TB_TPM(1:NF2,1:NT1,1:NF1), TB_TMP(1:NF2,1:NT1,1:NF1),
     &        TB_FAC(1:NF2,1:NT1,1:NF1)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE SOR3D
     &(F,NPLAN,NF,TETA,FREQ,NELEM2,NPOIN2,AT,U,V,UV,VV,DEPTH,VENT,
     & COURAN,MAREE,TITRE,NR3D,BINR3D,TRA01,MESH3D)
      USE BIEF_DEF
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NR3D,NF,NPLAN,NELEM2,NPOIN2
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF),AT
      DOUBLE PRECISION, INTENT(IN)    :: FREQ(NF),TETA(NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: U(NPOIN2),V(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: UV(NPOIN2),VV(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: DEPTH(NPOIN2)
      DOUBLE PRECISION, INTENT(INOUT) :: TRA01(NPOIN2*NPLAN)
      LOGICAL, INTENT(IN)             :: COURAN,VENT,MAREE
      CHARACTER(LEN=3), INTENT(IN)    :: BINR3D
      CHARACTER(LEN=80), INTENT(IN)   :: TITRE
      TYPE(BIEF_MESH), INTENT(IN)     :: MESH3D
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE SPEINI
     &( F     , SPEC  , FRA   , UV    , VV    , FREQ  , TETA  , GRAVIT,
     &  FREMAX, FETCH , SIGMAA, SIGMAB, GAMMA , FPIC  , HM0   , ALPHIL,
     &  TETA1 , SPRED1, TETA2 , SPRED2, XLAMDA, NPOIN2, NPLAN , NF    ,
     &  INISPE, E2FMIN, DEPTH , FRABI )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NPOIN2, NPLAN , NF    , INISPE, FRABI
      DOUBLE PRECISION GRAVIT, FREMAX, FETCH , SIGMAA, SIGMAB, GAMMA
      DOUBLE PRECISION FPIC  , HM0   , ALPHIL, TETA1 , SPRED1, TETA2
      DOUBLE PRECISION SPRED2, XLAMDA, E2FMIN
      DOUBLE PRECISION FREQ(NF) , TETA(NPLAN), SPEC(NF), FRA(NPLAN)
      DOUBLE PRECISION UV(NPOIN2) , VV(NPOIN2), DEPTH(NPOIN2)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE SPEJON
     &( SPEC  , FREQ  , NF    , AL    , FP     , GAMMA , SIGMAA, SIGMAB,
     &  DEUPI , GRAVIT, E2FMIN, FPMIN )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NF
      DOUBLE PRECISION GRAVIT, SIGMAA, SIGMAB, GAMMA , DEUPI , FPMIN
      DOUBLE PRECISION FP    , E2FMIN, AL
      DOUBLE PRECISION SPEC(NF)      , FREQ(NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE SPETMA
     &( SPEC  , FREQ  , NF    , AL    , FP     , GAMMA , SIGMAA, SIGMAB,
     &  DEUPI , GRAVIT, E2FMIN, FPMIN , DEPTH  )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NF
      DOUBLE PRECISION GRAVIT, SIGMAA, SIGMAB, GAMMA , DEUPI , FPMIN
      DOUBLE PRECISION FP    , E2FMIN, AL    , DEPTH
      DOUBLE PRECISION SPEC(NF)      , FREQ(NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE SPREAD
     &( DIRSPR, F     , COSTET, SINTET, NPLAN , FREQ  , DFREQ , NF    ,
     &  NPOIN2, TAILF , COSMOY, SINMOY, VARIAN, TAUXC , TAUXS , TAUXE )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION TAILF
      DOUBLE PRECISION DIRSPR(NPOIN2), SINMOY(NPOIN2), COSMOY(NPOIN2)
      DOUBLE PRECISION TAUXS (NPOIN2), TAUXC (NPOIN2), TAUXE (NPOIN2)
      DOUBLE PRECISION COSTET(NPLAN) , SINTET(NPLAN)
      DOUBLE PRECISION FREQ(NF), DFREQ(NF)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF), VARIAN(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE RE_INITIALISE_CHARS(NSEND,NLOSTCHAR,NLOSTAGAIN,NARRV)
          USE DECLARATIONS_SPECIAL
          IMPLICIT NONE
          INTEGER, INTENT(OUT) :: NSEND,NLOSTCHAR,NLOSTAGAIN,NARRV
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PREP_LOST_AGAIN(NOMB,NSEND,NLOSTAGAIN,NARRV)
          USE DECLARATIONS_SPECIAL
          IMPLICIT NONE
          INTEGER,INTENT(IN)   :: NOMB,NLOSTAGAIN,NARRV
          INTEGER, INTENT(OUT) :: NSEND
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PREP_SENDBACK(NOMB,NCHARA)
          USE DECLARATIONS_SPECIAL
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: NOMB
          INTEGER, INTENT(INOUT) :: NCHARA
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE INTERP_RECVCHAR_41
     &      (VAL,N,IKLE,ELT,ETA,SHP,SHZ,NELEM,NPOIN2,NPLAN,NRANGE)
          USE DECLARATIONS_SPECIAL
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: N,NELEM,NPOIN2,NPLAN,NRANGE
          INTEGER, INTENT(IN) :: IKLE(NELEM,3)
          INTEGER, INTENT(IN) :: ELT(NRANGE), ETA(NRANGE)
          DOUBLE PRECISION, INTENT(IN) :: SHP(3,NRANGE), SHZ(NRANGE)
          DOUBLE PRECISION, INTENT(IN) :: VAL(NPOIN2,NPLAN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE INTERP_RECVCHAR_41_MOD
     &      (VAL,IKLE,ELT,ETA,SHP1,SHP2,SHP3,SHZ,
     &                            NELEM,NPOIN2,NPLAN,NRANGE)
          USE DECLARATIONS_SPECIAL
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: NELEM,NPOIN2,NPLAN,NRANGE
          INTEGER, INTENT(IN) :: IKLE(NELEM,3)
          INTEGER, INTENT(IN) :: ELT(NRANGE), ETA(NRANGE)
          DOUBLE PRECISION, INTENT(IN) :: SHP1(NRANGE),SHP2(NRANGE),
     &                                    SHP3(NRANGE),SHZ(NRANGE)
          DOUBLE PRECISION, INTENT(IN) :: VAL(NPOIN2,NPLAN,2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE INTERP_RECVCHAR_11
     &      (VAL,N,IKLE,ELT,SHP,NELEM,NPOIN,NRANGE,IELM)
          USE DECLARATIONS_SPECIAL
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: N,NELEM,NPOIN,NRANGE,IELM
          INTEGER, INTENT(IN) :: IKLE(NELEM,*)
          INTEGER, INTENT(IN) :: ELT(NRANGE)
          DOUBLE PRECISION, INTENT(IN) :: SHP(3,NRANGE)
          DOUBLE PRECISION, INTENT(IN) :: VAL(NPOIN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE INTRODUCE_RECVCHAR(VAL,N,NPOIN,NOMB,NARRV)
          USE DECLARATIONS_SPECIAL
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: N,NPOIN,NOMB,NARRV
          DOUBLE PRECISION, INTENT(INOUT) :: VAL(NPOIN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE INTRODUCE_RECVCHAR_MOD(VAL,NPOIN,NARRV)
          USE DECLARATIONS_SPECIAL
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: NPOIN,NARRV
          DOUBLE PRECISION, INTENT(INOUT) :: VAL(NPOIN)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
!V6P2 New subroutine
      INTERFACE
        SUBROUTINE INVERT(RN, N, NP)
          USE DECLARATIONS_SPECIAL
          IMPLICIT NONE
      INTEGER N, NP
      DOUBLE PRECISION RN(NP,NP)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PRINT_HEAPCHAR(MESSAGE,NOMB,NCHARA)
          USE DECLARATIONS_SPECIAL
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: NOMB,NCHARA
          CHARACTER(LEN=*), INTENT(IN) :: MESSAGE
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PRINT_SENDCHAR(MESSAGE,NOMB,NSEND)
          USE DECLARATIONS_SPECIAL
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: NOMB,NSEND
          CHARACTER(LEN=*), INTENT(IN) :: MESSAGE
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE PRINT_RECVCHAR(MESSAGE,NOMB,NARRV)
          USE DECLARATIONS_SPECIAL
          IMPLICIT NONE
          INTEGER, INTENT(IN) :: NOMB,NARRV
          CHARACTER(LEN=*), INTENT(IN) :: MESSAGE
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE SCHAR41
     &( U , V , W , DT , NRK , X , Y , ZSTAR , Z , IKLE2 , IBOR ,
     &  XPLOT , YPLOT , ZPLOT , DX , DY , DZ , SHP , SHZ , ELT , ETA ,
     &  NSP   , NPLOT , NPOIN2 , NELEM2 , NPLAN , SURDET ,
     &  SENS  , TEST  , IFAPAR, NCHDIM,NCHARA)
      USE BIEF_DEF
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER         , INTENT(IN)    :: SENS,NPLAN,NCHDIM
      INTEGER         , INTENT(IN)    :: NPOIN2,NELEM2,NPLOT,NRK
      INTEGER         , INTENT(IN)    :: IKLE2(NELEM2,3)
      INTEGER         , INTENT(INOUT) :: ELT(NPLOT),NSP(NPLOT),NCHARA
      DOUBLE PRECISION, INTENT(IN)    :: U(NPOIN2,NPLAN),V(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: W(NPOIN2,NPLAN),SURDET(NELEM2)
      DOUBLE PRECISION, INTENT(INOUT) :: XPLOT(NPLOT),YPLOT(NPLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: ZPLOT(NPLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: SHP(3,NPLOT),SHZ(NPLOT)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN2),Y(NPOIN2),DT
      DOUBLE PRECISION, INTENT(IN)    :: Z(NPOIN2,NPLAN),ZSTAR(NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: DX(NPLOT),DY(NPLOT),TEST(NPLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: DZ(NPLOT)
      INTEGER         , INTENT(IN)    :: IBOR(NELEM2,5,NPLAN-1)
      INTEGER         , INTENT(INOUT) :: ETA(NPLOT)
      INTEGER         , INTENT(IN)    :: IFAPAR(6,*)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE ADD_CHAR41
     & ( U , V , W , DT , NRK , X , Y , ZSTAR , Z , IKLE2 , IBOR ,
     &   XPLOT , YPLOT , ZPLOT , DX , DY , DZ , SHP , SHZ , ELT , ETA,
     &   NSP , ISPDONE, NPLOT , NPOIN2 , NELEM2 , NPLAN ,
     &   SURDET , SENS , TEST, IFAPAR, NOMB,NARRV)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER         , INTENT(IN)    :: SENS,NPLAN,NOMB,NARRV
      INTEGER         , INTENT(IN)    :: NPOIN2,NELEM2,NPLOT,NRK
      INTEGER         , INTENT(IN)    :: IKLE2(NELEM2,3)
      INTEGER         , INTENT(INOUT) :: ELT(NPLOT),NSP(NPLOT)
      INTEGER         , INTENT(INOUT) :: ISPDONE(NPLOT)
      DOUBLE PRECISION, INTENT(IN)    :: U(NPOIN2,NPLAN),V(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: W(NPOIN2,NPLAN),SURDET(NELEM2)
      DOUBLE PRECISION, INTENT(INOUT) :: XPLOT(NPLOT),YPLOT(NPLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: ZPLOT(NPLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: SHP(3,NPLOT),SHZ(NPLOT)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN2),Y(NPOIN2),DT
      DOUBLE PRECISION, INTENT(IN)    :: Z(NPOIN2,NPLAN),ZSTAR(NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: DX(NPLOT),DY(NPLOT),TEST(NPLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: DZ(NPLOT)
      INTEGER         , INTENT(IN)    :: IBOR(NELEM2,5,NPLAN-1)
      INTEGER         , INTENT(INOUT) :: ETA(NPLOT)
      INTEGER, INTENT(IN)             :: IFAPAR(6,*)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE ADD_CHAR41_MOD
     & ( U , V , W , DT , NRK , X , Y , ZSTAR , Z , IKLE2 , IBOR ,
     &   XPLOT,YPLOT,ZPLOT,DX,DY,DZ,SHP1,SHP2,SHP3,SHZ,ELT,ETA,
     &   NSP , ISPDONE, NPLOT , NPOIN2 , NELEM2 , NPLAN ,
     &   SURDET , SENS , TEST, IFAPAR, NOMB,NARRV)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER         , INTENT(IN)    :: SENS,NPLAN,NOMB,NARRV
      INTEGER         , INTENT(IN)    :: NPOIN2,NELEM2,NPLOT,NRK
      INTEGER         , INTENT(IN)    :: IKLE2(NELEM2,3)
      INTEGER         , INTENT(INOUT) :: ELT(NPLOT),NSP(NPLOT)
      INTEGER         , INTENT(INOUT) :: ISPDONE(NPLOT)
      DOUBLE PRECISION, INTENT(IN)    :: U(NPOIN2,NPLAN),V(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(IN)    :: W(NPOIN2,NPLAN),SURDET(NELEM2)
      DOUBLE PRECISION, INTENT(INOUT) :: XPLOT(NPLOT),YPLOT(NPLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: ZPLOT(NPLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: SHP1(NPLOT),SHP2(NPLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: SHP3(NPLOT),SHZ(NPLOT)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN2),Y(NPOIN2),DT
      DOUBLE PRECISION, INTENT(IN)    :: Z(NPOIN2,NPLAN),ZSTAR(NPLAN+1)
      DOUBLE PRECISION, INTENT(INOUT) :: DX(NPLOT),DY(NPLOT),TEST(NPLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: DZ(NPLOT)
      INTEGER         , INTENT(IN)    :: IBOR(NELEM2,5)
      INTEGER         , INTENT(INOUT) :: ETA(NPLOT)
      INTEGER, INTENT(IN)             :: IFAPAR(6,*)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE SCHAR11
     & ( U , V , DT , NRK , X , Y , IKLE , IFABOR ,
     &   XPLOT , YPLOT , DX , DY , SHP , ELT , NSP ,
     &   NPLOT , NPOIN , NELEM , NELMAX , SURDET , SENS , TEST,
     &   IFAPAR, MESH,NCHDIM,NCHARA)
      USE BIEF_DEF
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER         , INTENT(IN)    :: SENS,NCHDIM
      INTEGER         , INTENT(IN)    :: NPOIN,NELEM,NELMAX,NPLOT,NRK
      INTEGER         , INTENT(IN)    :: IKLE(NELMAX,3),IFABOR(NELMAX,3)
      INTEGER         , INTENT(INOUT) :: ELT(NPLOT),NCHARA
      INTEGER         , INTENT(OUT)   :: NSP(NPLOT)
      DOUBLE PRECISION, INTENT(IN)    :: U(NPOIN),V(NPOIN),SURDET(NELEM)
      DOUBLE PRECISION, INTENT(INOUT) :: XPLOT(NPLOT),YPLOT(NPLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: SHP(3,NPLOT)
      DOUBLE PRECISION, INTENT(IN)    :: DT
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN),Y(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: DX(NPLOT),DY(NPLOT),TEST(NPLOT)
      INTEGER, INTENT(IN)             :: IFAPAR(6,*)
      TYPE (BIEF_MESH), INTENT(INOUT) :: MESH
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE ADD_CHAR11
     & ( U , V , DT , NRK , X , Y , IKLE , IFABOR ,
     &   XPLOT , YPLOT , DX , DY , SHP , ELT , NSP , ISPDONE,
     &   NPLOT , NPOIN , NELEM , NELMAX , SURDET , SENS , TEST,
     &   IFAPAR, NOMB,NARRV)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER         , INTENT(IN)    :: SENS,NOMB,NARRV
      INTEGER         , INTENT(IN)    :: NPOIN,NELEM,NELMAX,NPLOT,NRK
      INTEGER         , INTENT(IN)    :: IKLE(NELMAX,3),IFABOR(NELMAX,3)
      INTEGER         , INTENT(INOUT) :: ELT(NPLOT),NSP(NPLOT)
      INTEGER         , INTENT(INOUT) :: ISPDONE(NPLOT)
      DOUBLE PRECISION, INTENT(IN)    :: U(NPOIN),V(NPOIN),SURDET(NELEM)
      DOUBLE PRECISION, INTENT(INOUT) :: XPLOT(NPLOT),YPLOT(NPLOT)
      DOUBLE PRECISION, INTENT(INOUT) :: SHP(3,NPLOT)
      DOUBLE PRECISION, INTENT(IN)    :: DT
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN),Y(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: DX(NPLOT),DY(NPLOT),TEST(NPLOT)
      INTEGER, INTENT(IN) :: IFAPAR(6,*)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE UPDATE_TEST(TEST,MESH,SHP1,SHP2,SHP3,NPOINT)
      USE BIEF_DEF
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER NPOINT
      DOUBLE PRECISION TEST(NPOINT),SHP1(NPOINT),
     &SHP2(NPOINT),SHP3(NPOINT)
      TYPE(BIEF_MESH), INTENT(INOUT)   :: MESH
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE SEND_RECV_TOMAWAC(U,UTILD,UCONV,VCONV,WCONV,DT,NRK,
     &              X, Y, ZSTAR, Z,
     &              IKLE, IFABOR, XCONV, YCONV, ZCONV, DX, DY, DZ,
     &              SHP1,SHP2,SHP3, SHZ, ELT, ETA, ITRAV1,ITRAV2,NARRV,
     &              NPOIN2, NELEM, NPLAN, SURDET,
     &              TEST,NPOIN,NCHDIM,NCHARA,NOMB,MESH,LAST_NOMB)
      USE BIEF_DEF
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(INOUT)          :: NELEM,NPOIN,NPOIN2
      INTEGER, INTENT(IN)             :: NOMB,NPLAN
      TYPE(BIEF_OBJ)  , INTENT(INOUT) :: U
      TYPE(BIEF_OBJ)  , INTENT(INOUT) :: UTILD
      DOUBLE PRECISION, INTENT(IN)    :: UCONV(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: VCONV(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: WCONV(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: Y(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: Z(NPOIN2,NPLAN),ZSTAR(NPLAN+1)
      DOUBLE PRECISION, INTENT(INOUT) :: ZCONV(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(INOUT) :: DX(NPOIN),DY(NPOIN),DZ(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: SHP1(NPOIN),SHP2(NPOIN),
     &                    SHP3(NPOIN),SHZ(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: SURDET(NELEM)
      DOUBLE PRECISION, INTENT(IN)    :: DT
      INTEGER, INTENT(IN)             :: IKLE(NELEM,3)
      INTEGER, INTENT(IN)             :: IFABOR(NELEM,*)
      INTEGER, INTENT(INOUT)          :: ELT(NPOIN),ETA(NPOIN)
      INTEGER, INTENT(INOUT)          :: ITRAV1(NPOIN),ITRAV2(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: TEST(NPOIN)
      TYPE(BIEF_MESH) , INTENT(INOUT) :: MESH
      DOUBLE PRECISION, INTENT(INOUT) :: XCONV(NPOIN2,NPLAN),
     &                                   YCONV(NPOIN2,NPLAN)
      INTEGER NRK,NCHARA,NARRV,NCHDIM,LAST_NOMB
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE SCARACT
     & ( U , UTILD , UCONV , VCONV , WCONV , X , Y , ZSTAR ,
     &   XCONV , YCONV , ZCONV , DX , DY , DZ , Z , SHP , SHZ , SURDET ,
     &   DT , IKLE , IFABOR , ELT , ETA , ITRAV1, ITRAV2, IELM ,
     &   IELMU , NELEM , NELMAX , NOMB , NPOIN , NPOIN2 , NDP , NPLAN ,
     &   LV , MSK , MASKEL , MESH , FAC , TEST , STEST , INITLOC)
      USE BIEF_DEF
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NELEM,NELMAX,NPOIN,NPOIN2
      INTEGER, INTENT(IN)             :: NOMB,NDP,NPLAN,IELM,IELMU,LV
      TYPE(BIEF_OBJ)  , INTENT(IN)    :: U
      TYPE(BIEF_OBJ)  , INTENT(INOUT) :: UTILD
      DOUBLE PRECISION, INTENT(IN)    :: UCONV(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: VCONV(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: WCONV(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: Y(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: Z(NPOIN2,NPLAN),ZSTAR(NPLAN)
      DOUBLE PRECISION, INTENT(OUT)   :: ZCONV(NPOIN2,NPLAN)
      DOUBLE PRECISION, INTENT(OUT)   :: DX(NPOIN),DY(NPOIN),DZ(NPOIN)
      DOUBLE PRECISION, INTENT(OUT)   :: SHP(NDP,NPOIN),SHZ(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: MASKEL(NELMAX)
      DOUBLE PRECISION, INTENT(IN)    :: SURDET(NELEM)
      DOUBLE PRECISION, INTENT(IN)    :: DT
      INTEGER, INTENT(IN)             :: IKLE(NELMAX,NDP)
      INTEGER, INTENT(IN)             :: IFABOR(NELMAX,*)
      INTEGER, INTENT(OUT)            :: ELT(NPOIN),ETA(NPOIN)
      INTEGER, INTENT(OUT)            :: ITRAV1(NPOIN),ITRAV2(NPOIN)
      LOGICAL, INTENT(IN)             :: MSK,INITLOC
      DOUBLE PRECISION, INTENT(OUT)   :: TEST(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: FAC(NPOIN)
      TYPE(BIEF_MESH) , INTENT(INOUT) :: MESH
      TYPE(BIEF_OBJ)  , INTENT(INOUT) :: STEST,XCONV,YCONV
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE STRESS
     &( TAUWAV, TSTOT , F     , USNEW , TWNEW , Z0NEW , FREQ  , DFREQ ,
     &  TETA  , SINTET, COSTET, ROAIR , ROEAU , XKAPPA, BETAM , DECAL ,
     &  GRAVIT, NPOIN2, NPLAN , NF    , XTAUW , YTAUW , TAUHF )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NPOIN2, NPLAN , NF
      DOUBLE PRECISION ROAIR , ROEAU , XKAPPA , BETAM , DECAL , GRAVIT
      DOUBLE PRECISION TAUWAV(NPOIN2), USNEW(NPOIN2), TWNEW(NPOIN2)
      DOUBLE PRECISION  Z0NEW(NPOIN2), FREQ(NF) , DFREQ(NF)
      DOUBLE PRECISION TSTOT(NPOIN2,NPLAN,NF), F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION TETA(NPLAN), SINTET(NPLAN), COSTET(NPLAN)
      DOUBLE PRECISION XTAUW(NPOIN2) , YTAUW(NPOIN2), TAUHF(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE TAUTOT
     &( TAUT  , UVENT , TAUW  , CDRAG , ALPHA , XKAPPA, ZVENT , SEUIL ,
     &  GRAVIT, ITR   , ITRMIN, ITRMAX)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  ITRMIN, ITRMAX, ITR
      DOUBLE PRECISION TAUT  , UVENT , TAUW  , ALPHA , XKAPPA , ZVENT
      DOUBLE PRECISION SEUIL , CDRAG , GRAVIT
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE TETMOY
     &( TETAM , F     , COSTET, SINTET, NPLAN , FREQ  , DFREQ , NF    ,
     &  NPOIN2, TAILF , COSMOY, SINMOY, TAUXC , TAUXS )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NF    , NPLAN , NPOIN2
      DOUBLE PRECISION TAILF
      DOUBLE PRECISION TETAM(NPOIN2) , DFREQ(NF)    , COSMOY(NPOIN2)
      DOUBLE PRECISION COSTET(NPLAN) , SINTET(NPLAN), SINMOY(NPOIN2)
      DOUBLE PRECISION TAUXC(NPOIN2) , TAUXS(NPOIN2)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF), FREQ(NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE TOTNRJ
     &( VARIAN, F     , FREQ  , DFREQ , TAILF , NF    , NPLAN , NPOIN2)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER          NF    , NPLAN , NPOIN2
      DOUBLE PRECISION TAILF , VARIAN(NPOIN2), FREQ(NF), DFREQ(NF)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE TRANSF
     &( FA    , FR    , FREQ  , DFREQ , COSTET, SINTET, UC    , VC    ,
     &  XK    , KNEW  , NEWF  , NEWF1 , TAUX1 , TAUX2 , NPOIN2, NPLAN ,
     &  NF    , RAISF , LT    , GRADEB, GRAPRD)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER          NPOIN2, NPLAN , NF    , LT    , GRADEB, GRAPRD
      INTEGER          KNEW(NPOIN2)  , NEWF(NPOIN2)  , NEWF1(NPOIN2)
      DOUBLE PRECISION RAISF
      DOUBLE PRECISION FA(NPOIN2,NPLAN,NF),FR(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION FREQ(NF),DFREQ(NF),COSTET(NPLAN),SINTET(NPLAN)
      DOUBLE PRECISION UC(NPOIN2),VC(NPOIN2),TAUX1(NPOIN2),TAUX2(NPOIN2)
      DOUBLE PRECISION XK(NPOIN2,NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE USTAR1
     &( USTAR , Z0    , TAUWAV, UV    , VV    , CDRAG , ALPHA , XKAPPA,
     &  ZVENT , GRAVIT, NPOIN2)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NPOIN2
      DOUBLE PRECISION USTAR(NPOIN2) , Z0(NPOIN2) , TAUWAV(NPOIN2)
      DOUBLE PRECISION    UV(NPOIN2) , VV(NPOIN2)
      DOUBLE PRECISION CDRAG , ALPHA , XKAPPA , ZVENT, GRAVIT
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE USTAR2
     &( USTAR , UV    , VV    , NPOIN2)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NPOIN2
      DOUBLE PRECISION USTAR(NPOIN2) , UV(NPOIN2) , VV(NPOIN2)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE VARTEL
     &( VAR, X, Y, DEPTH, UC, VC, ZREPOS, TRA01, F, NPLAN, NF, NPOIN2)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER  NPOIN2,NPLAN,NF
      DOUBLE PRECISION F (NPOIN2,NPLAN,NF) , TRA01(NPOIN2)
      DOUBLE PRECISION X (NPOIN2) , Y (NPOIN2) , DEPTH(NPOIN2)
      DOUBLE PRECISION UC(NPOIN2) , VC(NPOIN2) , VAR(NPOIN2)
      DOUBLE PRECISION ZREPOS
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE VENUTI
     &(X,Y,NPOIN,NVEN,BINVEN,NBOR,NPTFR,AT,DDC,TV1,TV2,U1,V1,U2,V2)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NVEN,NPOIN,NPTFR
      INTEGER, INTENT(IN)             :: NBOR(NPTFR,2)
      DOUBLE PRECISION, INTENT(IN)    :: X(NPOIN),Y(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: U1(NPOIN),V1(NPOIN)
      DOUBLE PRECISION, INTENT(INOUT) :: U2(NPOIN),V2(NPOIN)
      DOUBLE PRECISION, INTENT(IN)    :: AT,DDC
      DOUBLE PRECISION, INTENT(INOUT) :: TV1,TV2
      CHARACTER(LEN=3), INTENT(IN)    :: BINVEN
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE VITFON(UWBM,F,XK,DEPTH,DFREQ,NF,NPOIN2,NPLAN,BETA)
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER, INTENT(IN)             :: NF,NPLAN,NPOIN2
      DOUBLE PRECISION, INTENT(INOUT) :: UWBM(NPOIN2),BETA(NPOIN2)
      DOUBLE PRECISION, INTENT(IN)    :: F(NPOIN2,NPLAN,NF)
      DOUBLE PRECISION, INTENT(IN)    :: XK(NPOIN2,NF)
      DOUBLE PRECISION, INTENT(IN)    :: DEPTH(NPOIN2),DFREQ(NF)
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE WAC
     &(PART, U_TEL, V_TEL, H_TEL, FX_WAC, FY_WAC, UV_WAC, VV_WAC,
     & CODE, T_TEL, DT_TEL,NIT_TEL,PERCOU_WAC,
     & DIRMOY_TEL,HM0_TEL,TPR5_TEL)
      USE BIEF_DEF
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER,           INTENT(IN)      :: PART,NIT_TEL,PERCOU_WAC
      CHARACTER(LEN=24), INTENT(IN)      :: CODE
      TYPE(BIEF_OBJ),    INTENT(IN)      :: U_TEL,V_TEL,H_TEL
      TYPE(BIEF_OBJ),    INTENT(INOUT)   :: DIRMOY_TEL,HM0_TEL,TPR5_TEL
      TYPE(BIEF_OBJ),    INTENT(INOUT)   :: FX_WAC,FY_WAC
      TYPE(BIEF_OBJ),    INTENT(INOUT)   :: UV_WAC,VV_WAC
      DOUBLE PRECISION,  INTENT(IN)      :: DT_TEL,T_TEL
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE WNSCOU
     &( CK2   , FREQ  , DEPTH )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      DOUBLE PRECISION CK2   , FREQ  , DEPTH
        END SUBROUTINE
      END INTERFACE
!
!-----------------------------------------------------------------------
!
      INTERFACE
        SUBROUTINE WPOWER
     &( POWER , F     , FREQ  , DFREQ , CG    , TAILF , NF    , NPLAN ,
     &  NPOIN2, ROEAU )
      USE DECLARATIONS_SPECIAL
      IMPLICIT NONE
      INTEGER          NF    , NPLAN , NPOIN2
      DOUBLE PRECISION TAILF , POWER(NPOIN2), FREQ(NF), DFREQ(NF)
      DOUBLE PRECISION F(NPOIN2,NPLAN,NF), CG(NPOIN2,NF)
      DOUBLE PRECISION ROEAU
        END SUBROUTINE
      END INTERFACE
!
!=======================================================================
!
      END MODULE INTERFACE_TOMAWAC

