!                    *****************************
                     MODULE DECLARATIONS_TELEMAC3D
!                    *****************************
!
!
!***********************************************************************
! TELEMAC3D   V6P2                                   21/08/2010
!***********************************************************************
!
!brief    DECLARATION OF PRINCIPAL TELEMAC3D VARIABLES
!
!history  J-M HERVOUET (LNH)
!+
!+
!+   LINKED TO BIEF 5.0
!
!history  N.DURAND (HRW), S.E.BOURBAN (HRW)
!+        13/07/2010
!+        V6P0
!+   Translation of French comments within the FORTRAN sources into
!+   English comments
!
!history  N.DURAND (HRW), S.E.BOURBAN (HRW)
!+        21/08/2010
!+        V6P0
!+   Creation of DOXYGEN tags for automated documentation and
!+   cross-referencing of the FORTRAN sources
!
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
      USE BIEF_DEF
!
!       NOTE: THIS MODULE IS ORGANISED IN 10 PARTS
!
!       (1) VECTORS (WILL BE DECLARED AS BIEF_OBJ STRUCTURES)
!       (2) MATRICES (WILL BE DECLARED AS BIEF_OBJ STRUCTURES)
!       (3) BLOCKS (WILL BE DECLARED AS BIEF_OBJ STRUCTURES)
!       (4) INTEGERS
!       (5) LOGICAL VALUES
!       (6) REALS
!       (7) STRINGS
!       (8) SLVCFG STRUCTURES
!       (9) MESH STRUCTURE
!      (10) ALIASES
!
!-----------------------------------------------------------------------
! (1) VECTORS (REAL AND INTEGER)
!-----------------------------------------------------------------------
!
!
!     3D VELOCITY COMPONENTS AT PREVIOUS TIMESTEP (TIME N)
!
      TYPE(BIEF_OBJ), TARGET :: UN,VN,WN
!
!     3D VELOCITY COMPONENTS AFTER ADVECTION
!
      TYPE(BIEF_OBJ), TARGET :: UC,VC,WC
!
!     3D VELOCITY COMPONENTS AFTER DIFFUSION
!
      TYPE(BIEF_OBJ), TARGET :: UD,VD,WD
!
!     3D VELOCITY COMPONENTS AT CURRENT TIMESTEP (TIME N+1)
!
      TYPE(BIEF_OBJ), TARGET :: U,V,W
!
!     EXPLICIT SOURCE TERMS ON VELOCITIES
!
      TYPE(BIEF_OBJ), TARGET :: S0U,S0V,S0W
!
!     IMPLICIT SOURCE TERMS ON VELOCITIES U
!
      TYPE(BIEF_OBJ), TARGET :: S1U,S1V,S1W
! 
!     RIGHT-HAND SIDE ON VELOCITIES EQUATIONS
!
      TYPE(BIEF_OBJ), TARGET :: SMU,SMV
!
!     PRESCRIBED VELOCITY COMPONENTS ON THE BOTTOM
!
      TYPE(BIEF_OBJ), TARGET :: UBORF,VBORF,WBORF
!
!     PRESCRIBED VELOCITY COMPONENTS ON THE LATERAL BOUNDARY
!
      TYPE(BIEF_OBJ), TARGET :: UBORL,VBORL,WBORL
!
!     PRESCRIBED VELOCITY COMPONENTS AT THE FREE SURFACE
!
      TYPE(BIEF_OBJ), TARGET :: UBORS,VBORS,WBORS
!
!     ORIGINAL PRESCRIBED VALUES AT THE FREE SURFACE
!
      TYPE(BIEF_OBJ), TARGET :: TRBORSAVE,UBORSAVE,VBORSAVE
      TYPE(BIEF_OBJ), TARGET :: WBORSAVE,KBORSAVE,EBORSAVE
!
!     (FRICTION VELOCITY)**2 FOR BOTTOM AND LATERAL BOUNDARIES
!
      TYPE(BIEF_OBJ), TARGET :: UETCAR,UETCAL
!
!     LOGARITHMIC LAW FOR U-VELOCITY COMPONENT, ON THE BOTTOM: NU*DU/DN = AUBORF*U + BUBORF
!
      TYPE(BIEF_OBJ), TARGET :: AUBORF,BUBORF
!
!     LOGARITHMIC LAW FOR U-VELOCITY COMPONENT, ON THE LATERAL BOUNDARIES: NU*DU/DN = AUBORL*U + BUBORL
!
      TYPE(BIEF_OBJ), TARGET :: AUBORL,BUBORL
!
!     LOGARITHMIC LAW FOR U-VELOCITY COMPONENT, AT THE FREE SURFACE: NU*DU/DN = AUBORS*U + BUBORS
!
      TYPE(BIEF_OBJ), TARGET :: AUBORS,BUBORS
!
!     LOGARITHMIC LAW FOR V-VELOCITY COMPONENT, ON THE BOTTOM: NU*DV/DN = AVBORF*V + BVBORF
!
      TYPE(BIEF_OBJ), TARGET :: AVBORF,BVBORF
!
!     LOGARITHMIC LAW FOR V-VELOCITY COMPONENT, ON THE LATERAL BOUNDARIES: NU*DV/DN = AVBORL*V + BVBORL
!
      TYPE(BIEF_OBJ), TARGET :: AVBORL,BVBORL
!
!     LOGARITHMIC LAW FOR V-VELOCITY COMPONENT, AT THE FREE SURFACE: NU*DV/DN = AVBORS*V + BVBORS
!
      TYPE(BIEF_OBJ), TARGET :: AVBORS,BVBORS
!
!     LOGARITHMIC LAW FOR W-VELOCITY COMPONENT, ON THE BOTTOM: NU*DW/DN = AWBORF*W + BWBORF
!
      TYPE(BIEF_OBJ), TARGET :: AWBORF,BWBORF
!
!     LOGARITHMIC LAW FOR W-VELOCITY COMPONENT, ON THE LATERAL BOUNDARIES: NU*DW/DN = AWBORL*W + BWBORL
!
      TYPE(BIEF_OBJ), TARGET :: AWBORL,BWBORL
!
!     LOGARITHMIC LAW FOR W-VELOCITY COMPONENT, AT THE FREE SURFACE: NU*DW/DN = AWBORS*W + BWBORS
!
      TYPE(BIEF_OBJ), TARGET :: AWBORS,BWBORS
!
!     TYPES OF BOUNDARY CONDITIONS FOR VELOCITY COMPONENTS ON THE BOTTOM
!
      TYPE(BIEF_OBJ), TARGET :: LIUBOF,LIVBOF,LIWBOF
!
!     TYPES OF BOUNDARY CONDITIONS FOR U ON THE LATERAL BOUNDARIES
!
      TYPE(BIEF_OBJ), TARGET :: LIUBOL,LIVBOL,LIWBOL
      TYPE(BIEF_OBJ), TARGET :: LIUBOL_USER,LIVBOL_USER
!
!     TYPES OF BOUNDARY CONDITIONS FOR VELOCITY COMPONENTS AT THE FREE SURFACE
!
      TYPE(BIEF_OBJ), TARGET :: LIUBOS,LIVBOS,LIWBOS
!
!     'COLOUR' OF BOUNDARY NODES (TAKEN IN BOUNDARY CONDITIONS FILE)
!
      TYPE(BIEF_OBJ), TARGET :: BOUNDARY_COLOUR
!
!     PLANE NUMBER OF LAST PLANE WHICH HAS A CRUSHED LAYER ABOVE IT
!
      TYPE(BIEF_OBJ), TARGET :: IPBOT
!
!     SIGMA-TRANSFORMED VERTICAL VELOCITY COMPONENT
!
      TYPE(BIEF_OBJ), TARGET :: WS
!
!     DYNAMIC PRESSURE AT TIME N+1 AND TIME N (NON-HYDROSTATIC)
!
      TYPE(BIEF_OBJ), TARGET :: DP,DPN
!
!     HYDROSTATIC PRESSURE (NON-HYDROSTATIC)
!
      TYPE(BIEF_OBJ), TARGET :: PH
!
!     PRESCRIBED DYNAMIC PRESSURE ON BOTTOM, LATERAL BOUNDARIES AND FREE SURFACE
!
      TYPE(BIEF_OBJ), TARGET :: PBORF, PBORL, PBORS
!
!     TYPE OF BOUNDARY CONDITIONS FOR DYNAMIC PRESSURE
!
      TYPE(BIEF_OBJ), TARGET :: LIPBOF, LIPBOL, LIPBOS
!
!     K OF K-EPSILON MODEL AT PREVIOUS TIMESTEP (TIME N)
!
      TYPE(BIEF_OBJ), TARGET :: AKN
!
!     K OF K-EPSILON MODEL AFTER ADVECTION
!
      TYPE(BIEF_OBJ), TARGET :: AKC
!
!     K OF K-EPSILON MODEL AT TIME N+1
!
      TYPE(BIEF_OBJ), TARGET :: AK
!
!     EXPLICIT SOURCE TERMA FOR K IN K-EPSILON MODEL
!
      TYPE(BIEF_OBJ), TARGET :: S0AK
!
!     IMPLICIT SOURCE TERMA FOR K IN K-EPSILON MODEL
!
      TYPE(BIEF_OBJ), TARGET :: S1AK
!
!     PRESCRIBED K OF K-EPSILON MODEL ON: LATERAL BOUNDARY
!                                         FREE SURFACE
!                                         BOTTOM
!
      TYPE(BIEF_OBJ), TARGET :: KBORL,KBORS,KBORF
!
!     COEFFICIENTS OF LOGARITHMIC LAW FOR K OF K-EPSILON MODEL, ON THE BOTTOM
!                                                               FREE SURFACE
!
      TYPE(BIEF_OBJ), TARGET :: AKBORF,BKBORF,AKBORL
      TYPE(BIEF_OBJ), TARGET :: BKBORL,AKBORS,BKBORS
!
!     TYPES OF BOUNDARY CONDITIONS FOR K OF K-EPSILON MODEL ON THE BOTTOM
!                                                        LATERAL BOUNDARY
!                                                            FREE SURFACE
      TYPE(BIEF_OBJ), TARGET :: LIKBOF,LIKBOL,LIKBOS
!
!     EPSILON OF K-EPSILON MODEL AT PREVIOUS TIMESTEP (TIME N)
!
      TYPE(BIEF_OBJ), TARGET :: EPN
!
!     EPSILON OF K-EPSILON MODEL AFTER ADVECTION
!
      TYPE(BIEF_OBJ), TARGET :: EPC
!
!     EPSILON OF K-EPSILON MODEL AT TIME N+1
!
      TYPE(BIEF_OBJ), TARGET :: EP
!
!     EXPLICIT/IMPLICIT SOURCE TERM OF EPSILON IN K-EPSILON MODEL
!
      TYPE(BIEF_OBJ), TARGET :: S0EP,S1EP
!
!     PRESCRIBED EPSILON OF K-EPSILON MODEL ON THE BOTTOM
!                                        LATERAL BOUNDARY
!                                            FREE SURFACE
!
      TYPE(BIEF_OBJ), TARGET :: EBORF,EBORL,EBORS
!
!     COEFFICIENTS IN LOGARITHMIC LAW FOR EPSILON OF K-EPSILON MODEL, ON THE BOTTOM
!                                                                  LATERAL BOUNDARY
!                                                                      FREE SURFACE
      TYPE(BIEF_OBJ), TARGET :: AEBORF,AEBORL,AEBORS
      TYPE(BIEF_OBJ), TARGET :: BEBORF,BEBORL,BEBORS
!
!     TYPES OF BOUNDARY CONDITIONS FOR EPSILON OF K-EPSILON MODEL ON THE BOTTOM
!                                                              LATERAL BOUNDARY
!                                                                  FREE SURFACE
      TYPE(BIEF_OBJ), TARGET :: LIEBOF,LIEBOL,LIEBOS
!
!     VERTICALLY INTEGRATED VELOCITY COMPONENTS
!
      TYPE(BIEF_OBJ), TARGET :: U2D,V2D
!
!     VERTICALLY INTEGRATED VELOCITY COMPONENTS ON BOUNFDARIES
!    
      TYPE(BIEF_OBJ), TARGET :: UBOR2D,VBOR2D
!
!     VERTICALLY INTEGRATED VELOCITY COMPONENTS AT PREVIOUS TIME STEP
!
      TYPE(BIEF_OBJ), TARGET :: UN2D,VN2D
!
!     SOURCE TERMS ON VELOCITIES
!
      TYPE(BIEF_OBJ), TARGET :: FU,FV
!
!     WAVE STRESSES FROM ARTEMIS OR TOMAWAC
!
      TYPE(BIEF_OBJ), TARGET :: FXH,FYH
! 
!     FLUXES ON BOUNDARIES
!
      TYPE(BIEF_OBJ), TARGET :: FLBOR,FLBLIM
!
!     ADVECTION FIELD
!
      TYPE(BIEF_OBJ), TARGET :: UCONV,VCONV,WCONV
!
!     VERTICAL VELOCITY IN TRANSFORMED MESH
!
      TYPE(BIEF_OBJ), TARGET :: WSCONV
!
!     ADVECTION FIELD FOR CHARACTERISTICS
!
      TYPE(BIEF_OBJ), TARGET :: UCONVC,VCONVC
!
!     PSEUDO-VISCOSITY IN WAVE EQUATION
!
      TYPE(BIEF_OBJ), TARGET :: NUWAVE
!
!     PIECE-WISE LINEAR FUNCTION, AND ITS GRADIENT
!     USED WITH "COMPATIBILITY OF FREE SURFACE GRADIENT"
!
      TYPE(BIEF_OBJ), TARGET :: ZCONV,GRAZCO
!
!     D**-1 IN WAVE EQUATION (SEE BOOK)
!
      TYPE(BIEF_OBJ), TARGET :: DM1
!
!     EDGE BY EDGE FLUXES (AND ASSEMBLED IN PARALLEL VERSION)
!
      TYPE(BIEF_OBJ), TARGET :: FLODEL,FLOPAR
!
!     LIMITATION OF FLUXES
!
      TYPE(BIEF_OBJ), TARGET :: FLULIM
!
!     VOLUME AROUND POINTS AT TIME N+1, NOT ASSEMBLED (VOLU)
!                                       ASSEMBLED IN PARALLEL (VOLUPAR)
!
      TYPE(BIEF_OBJ), TARGET :: VOLU,VOLUPAR
!
!     VOLUME AROUND POINTS AT TIME N
!
      TYPE(BIEF_OBJ), TARGET :: VOLUN,VOLUNPAR
!
!     VARIOUS VOLUMES (AT AN INTERMEDIATE TIME STEP)
!
      TYPE(BIEF_OBJ), TARGET :: VOLUT,VOLU3D,VOLU3DPAR
!
!     INTEGRAL OF 2D BASES (SCALAR AND ASSEMBLED IN PARALLEL)
!
      TYPE(BIEF_OBJ), TARGET :: VOLU2D,V2DPAR
!
!     INVERSE OF INTEGRAL OF BASES IN 2D, IN 3D
!
      TYPE(BIEF_OBJ), TARGET :: UNSV2D,UNSV3D
!  
!     INTERNAL FLUXES, PER NODE
!
      TYPE(BIEF_OBJ), TARGET :: FLUINT
! 
!     FLUX AT BOUNDARIES, AND ASSEMBLED FORM IN PARALLEL
!
      TYPE(BIEF_OBJ), TARGET :: FLUEXT,FLUEXTPAR
!
!     FLUXES INTEGRATED ALONG THE VERTICAL
!
      TYPE(BIEF_OBJ), TARGET :: FLINT2
!
!     ABSOLUTE VALUE OF THE VORTICITY
!
      TYPE(BIEF_OBJ), TARGET :: ROTAT
!
!     RELATIVE DENSITY = (RHO-RHO0)/RHO0
!
      TYPE(BIEF_OBJ), TARGET :: DELTAR
!
!     RICHARDSON NUMBER
!
      TYPE(BIEF_OBJ), TARGET :: RI
!
!     FRICTION COEFFICIENT ON THE BOTTOM
!
      TYPE(BIEF_OBJ), TARGET :: RUGOF
!
!     FRICTION COEFFICIENT ON THE LATERAL BOUNDARY
!
      TYPE(BIEF_OBJ), TARGET :: RUGOL
!
!     ADIMENSIONAL FRICTION COEFFICIENT
!
      TYPE(BIEF_OBJ), TARGET :: CF
!
!     WIND VELOCITY
!
      TYPE(BIEF_OBJ), TARGET :: WIND
!
!     ATMOSPHERIC PRESSURE
!
      TYPE(BIEF_OBJ), TARGET :: PATMOS
!
!     PARAMETERS FOR GLOBAL MASS AND FLUX BALANCES
!
      TYPE(BIEF_OBJ), TARGET :: MASINI,MASSE,MASSEN
!
!     FLUX (ACCROSS THE BOUNDARIES)
!
      TYPE(BIEF_OBJ), TARGET :: FLUX
!
!     CUMULATED FLUXES OF TRACERS SINCE BEGINNING OF COMPUTATION
!
      TYPE(BIEF_OBJ), TARGET :: FLUCUM
!
!     DEPTH AT TIME N+1, AT TIME TN
!
      TYPE(BIEF_OBJ), TARGET :: H,HN
!
!     PROPAGATION DEPTH, I.E. DEPTH INTO THE TERM DIV(HU)
!
      TYPE(BIEF_OBJ), TARGET :: HPROP
!
!     HIGH WATER MARK, HIGH WATER TIME
!
      TYPE(BIEF_OBJ), TARGET :: MAXZ,TMAXZ
!
!     VARIATION OF DEPTH : H(N+1)-H(N)
!
      TYPE(BIEF_OBJ), TARGET :: DH
!
!     RIGHT-HAND SIDE FOR WATER DEPTH
!
      TYPE(BIEF_OBJ), TARGET :: SMH
!
!     PRESCRIBED DEPTH ON LATERAL BOUNDARIES
!
      TYPE(BIEF_OBJ), TARGET :: HBOR
!
!     RAIN IN M/S MULTIPLIED BY VOLU2D, AND VERSION ASSEMBLED IN PARALLEL
!
      TYPE(BIEF_OBJ), TARGET :: PLUIE,PARAPLUIE
!
!     BLOCK OF VARIABLES TO BE ADVECTED BY CHARACTERISTICS
!
      TYPE(BIEF_OBJ), TARGET :: FN3D,FC3D
!
!     BLOCK OF VARIOUS BIEF_OBJ STRUCTURES FOR VARIABLES TO BE ADVECTED
!
      TYPE(BIEF_OBJ), TARGET :: BL_FN,BL_FC,BL_S0F,BL_FSC
      TYPE(BIEF_OBJ), TARGET :: BL_BOL,BL_BORL
!
!     VERTICAL COORDINATES FOR PROPAGATION STEP
!
      TYPE(BIEF_OBJ), TARGET :: ZPROP
!
!     BOTTOM ELEVATION
!
      TYPE(BIEF_OBJ), TARGET :: ZF
!
!     BOTTOM COORDINATES GIVEN PER ELEMENT
!
      TYPE(BIEF_OBJ), TARGET :: ZFE
!
!     PERCENTUAL MESH PLANES
!
      TYPE(BIEF_OBJ), TARGET :: ZSTAR
!
!     Z: DISTRIBUTION
!
      TYPE(BIEF_OBJ), TARGET :: ZT
!
!     DH/DT
!
      TYPE(BIEF_OBJ), TARGET :: DSSUDT
!
!     PRESCRIBED ELEVATIONS OF PLANES
!
      TYPE(BIEF_OBJ), TARGET :: ZPLANE
!
!     TYPE OF SIGMA TRANSFORMATION
!
      TYPE(BIEF_OBJ), TARGET :: TRANSF_PLANE
!
!     COORDINATES IN THE TRANSFORMED MESH FOR THE METHOD OF CHARACTERISTICS
!
      TYPE(BIEF_OBJ), TARGET :: ZCHAR
!
!     MASK OF ELEMENTS
!
      TYPE(BIEF_OBJ), TARGET :: MASKEL
!
!     MASK OF NODES
!
      TYPE(BIEF_OBJ), TARGET :: MASKPT
!
!     3D MASK OF BOUNDARY ELEMENTS (CASE WITH MASKING)
!
      TYPE(BIEF_OBJ), TARGET :: MASKBR
!
!     3D MASK OF BOUNDARY ELEMENTS (WORKING ARRAY FOR DEBIMP_3D)
!
      TYPE(BIEF_OBJ), TARGET :: MASKTR
!
!     POSITIONS OF FLOATING BODIES (X,Y, Z AND Z IN TRANSFORMED MESH)
!
      TYPE(BIEF_OBJ), TARGET :: XFLOT,YFLOT,ZFLOT,ZSFLOT
!
!     BARYCENTRIC COORDINATES OF FLOATING BODIES, AT THE FOOT OF CHARACTERISTICS
!     HORIZONTAL AND VERTICAL
!
      TYPE(BIEF_OBJ), TARGET :: SHPFLO,SHZFLO
!
!     TIME-STEPS FOR INITIAL AND FINAL RELEASE OF FLOATING BODIES
!
      TYPE(BIEF_OBJ), TARGET :: DEBFLO,FINFLO
!> @brief
C numeros des elements 2dh, au pied des courbes caracteristiques, dans lesquels se trouve a cet instant chacun des flotteurs
      TYPE(BIEF_OBJ), TARGET :: ELTFLO
!> @brief
C numeros des plans, au pied des courbes caracteristiques, dans lesquels se trouve a cet instant chacun des flotteurs
      TYPE(BIEF_OBJ), TARGET :: ETAFLO
!> @brief
C table de connectivite bidon utilisee pour la sortie des trajectoires sous forme de maillage
      TYPE(BIEF_OBJ), TARGET :: IKLFLO
!> @brief WORKING ARRAY
C tableau de travail
      TYPE(BIEF_OBJ), TARGET :: TRAFLO
!
!     TYPE OF BOUNDARY CONDITIONS ON DEPTH (AND VALUE OF USER SAVED IF THOMPSON)
!
      TYPE(BIEF_OBJ), TARGET :: LIHBOR,LIHBOR_USER
!
!     LIQUID BOUNDARY NUMNER OF BOUNDARY POINTS, OF BOUNDARY ELEMENTS
!
      TYPE(BIEF_OBJ), TARGET :: NUMLIQ,NUMLIQ_ELM
!
!     PROPAGATION BC TYPES (TELEMAC2D'S PROPAG)
!
      TYPE(BIEF_OBJ), TARGET :: LIMPRO
!
!     RIGHT HAND SIDE FOR THE LINEAR EQUATIONS IN 3D
!
      TYPE(BIEF_OBJ), TARGET :: SEM3D
!
!     RIGHT HAND SIDE FOR THE LINEAR EQUATIONS IN 2D
!
      TYPE(BIEF_OBJ), TARGET :: SEM2D
!
!     ELEMENT-ORIENTED WORKING ARRAY
!
      TYPE(BIEF_OBJ), TARGET :: TE1
!> @brief ELEMENT-ORIENTED WORKING ARRAY
C tableau de travail par element 2d
      TYPE(BIEF_OBJ), TARGET :: TE2
!> @brief ELEMENT-ORIENTED WORKING ARRAY
C tableau de travail par element 2d
      TYPE(BIEF_OBJ), TARGET :: TE3
!> @brief PIECE-WISE LINEAR FREE SURFACE
C
      TYPE(BIEF_OBJ), TARGET :: ZFLATS
!> @brief VOID VECTOR STRUCTURE
C structure vide
      TYPE(BIEF_OBJ), TARGET :: SVIDE
!
!     RIGHT HAND SIDE OF CONTINUITY EQUATION WHEN SOURCES
!
      TYPE(BIEF_OBJ), TARGET :: SOURCES
!> @brief
C vitesse de chute du sediment
      TYPE(BIEF_OBJ), TARGET :: WCHU
!> @brief THICKNESS OF SOLID FRACTION OF THE BED LAYER ( EPAI=DZ/(1+IVIDE), DZ BED LAYER THICKNESS )
C epaisseurs des mailles discretisant le lit ( epai=dz/(1+ivide) )
      TYPE(BIEF_OBJ), TARGET :: EPAI
!> @brief VOID RATIO (GIBSON MODEL ONLY)
C indice des vides aux points du maillage (modele de gibson)
      TYPE(BIEF_OBJ), TARGET :: IVIDE
!> @brief TIME COUNTER FOR CONSOLIDATION MODEL (MULTILAYER MODEL)
C compteur de temps (modele multi-couches)
      TYPE(BIEF_OBJ), TARGET :: TEMP
!
!     CONCENTRATION OF MUD BED LAYER (MULTILAYER MODEL)
!
      TYPE(BIEF_OBJ), TARGET :: CONC
!
!     THICKNESS OF FRESH DEPOSIT (FLUID MUD LAYER)
!
      TYPE(BIEF_OBJ), TARGET :: HDEP
!> @brief EROSION FLUX
C flux d'erosion en chaque point 2d
      TYPE(BIEF_OBJ), TARGET :: FLUER
!
!     PROBABILITY OF DEPOSIT
!
      TYPE(BIEF_OBJ), TARGET :: PDEPO
!
!     RIDIG BED ELEVATION
!
      TYPE(BIEF_OBJ), TARGET :: ZR
!
!     EQUILIBRIUM CONCENTRATION
!
      TYPE(BIEF_OBJ), TARGET :: CREF
!
!     AVERAGE DIAMETER OF GRAINS
!
      TYPE(BIEF_OBJ), TARGET :: DMOY
!
!     NUMBER OF POINTS WITHIN THE BED ALONG THE VERTICAL
!
      TYPE(BIEF_OBJ), TARGET :: NPF
!
!     VECTOR OF SIZE NDP*NELEM (NUMBER OF POINTS IN THE ELEMENT * NELEM)     
!
      TYPE(BIEF_OBJ), TARGET :: WEL
!
!-----------------------------------------------------------------------
! (2) MATRICES
!-----------------------------------------------------------------------
!
!
!     SUPG NON SYMMETRIC MATRIX
!
      TYPE(BIEF_OBJ), TARGET :: MSUPG
!
!     MURD NON SYMMETRIC MATRIX
!
      TYPE(BIEF_OBJ), TARGET :: MMURD
!
!     DIFFUSION MATRIX
!
      TYPE(BIEF_OBJ), TARGET :: MDIFF
!
!     MURD MATRIX FOR TIDAL FLATS VERSION
!
      TYPE(BIEF_OBJ), TARGET :: MURD_TF
!
!     WORKING MATRICES
!
      TYPE(BIEF_OBJ), TARGET :: MTRA1,MTRA2
!
!     2D BOUNDARY MATRIX
!
      TYPE(BIEF_OBJ), TARGET :: MBOR2D
!
!     WORKING 2D MATRIX
!
      TYPE(BIEF_OBJ), TARGET :: MATR2H
!
!-----------------------------------------------------------------------
! (3) BLOCKS
!-----------------------------------------------------------------------
!
!> @brief
C traceurs au pas precedent
      TYPE(BIEF_OBJ), TARGET :: TAN
!> @brief
C
      TYPE(BIEF_OBJ), TARGET :: TAC
!> @brief CONCENTRATION OF TRACERS
C traceurs au pas en cours
      TYPE(BIEF_OBJ), TARGET :: TA
!
!     EXPLICIT SOURCE TERM FOR TRACERS
!
      TYPE(BIEF_OBJ), TARGET :: S0TA
!> @brief
C terme source explicite, implicite pour les traceurs
      TYPE(BIEF_OBJ), TARGET :: S1TA
!> @brief PRESCRIBED TRACERS ON THE BOTTOM
C
      TYPE(BIEF_OBJ), TARGET :: TABORF
!> @brief PRESCRIBED TRACERS ON THE LATERAL BOUNDARY
C
      TYPE(BIEF_OBJ), TARGET :: TABORL
!> @brief PRESCRIBED TRACERS AT THE FREE SURFACE
C
      TYPE(BIEF_OBJ), TARGET :: TABORS
!> @brief LOGARITHMIC LAW FOR TRACERS: NU*DTA/DN = ATABO*TA + BTABO
C loi log sur traceurs : atabo*ta + btabo, au fond
      TYPE(BIEF_OBJ), TARGET :: ATABOF
!> @brief LOGARITHMIC LAW FOR TRACERS: NU*DTA/DN = ATABO*TA + BTABO
C loi log sur traceurs : atabo*ta + btabo, au fond
      TYPE(BIEF_OBJ), TARGET :: BTABOF
!> @brief LOGARITHMIC LAW FOR TRACERS: NU*DTA/DN = ATABO*TA + BTABO
C loi log sur traceurs : atabo*ta + btabo, sur les parois laterales
      TYPE(BIEF_OBJ), TARGET :: ATABOL
!> @brief LOGARITHMIC LAW FOR TRACERS: NU*DTA/DN = ATABO*TA + BTABO
C loi log sur traceurs : atabo*ta + btabo, sur les parois laterales
      TYPE(BIEF_OBJ), TARGET :: BTABOL
!> @brief LOGARITHMIC LAW FOR TRACERS: NU*DTA/DN = ATABO*TA + BTABO
C loi log sur traceurs : atabo*ta + btabo, en surface
      TYPE(BIEF_OBJ), TARGET :: ATABOS
!> @brief LOGARITHMIC LAW FOR TRACERS: NU*DTA/DN = ATABO*TA + BTABO
C loi log sur traceurs : atabo*ta + btabo, en surface
      TYPE(BIEF_OBJ), TARGET :: BTABOS
!> @brief TYPES OF BOUNDARY CONDITIONS FOR TRACERS ON THE BOTTOM
C type de conditions aux limites sur traceurs au fond
      TYPE(BIEF_OBJ), TARGET :: LITABF
!> @brief TYPES OF BOUNDARY CONDITIONS FOR TRACERS ON THE LATERAL BOUNDARY
C type de conditions aux limites sur traceurs sur les parois laterales
      TYPE(BIEF_OBJ), TARGET :: LITABL
!> @brief TYPES OF BOUNDARY CONDITIONS FOR TRACERS AT THE FREE SURFACE
C type de conditions aux limites sur traceurs en surface
      TYPE(BIEF_OBJ), TARGET :: LITABS
!> @brief VISCOSITY
C coefficients de viscosite pour la vitesse
      TYPE(BIEF_OBJ), TARGET :: VISCVI
!> @brief DIFFUSIVITY FOR TRACERS
C coefficients de viscosite pour les traceurs
      TYPE(BIEF_OBJ), TARGET :: VISCTA
!> @brief BOTTOM GRADIENTS
C
      TYPE(BIEF_OBJ), TARGET :: GRADZF
!> @brief FREE SURFACE GRADIENT (BLOCK OF 2 COMPONENTS)
C
      TYPE(BIEF_OBJ), TARGET :: GRADZS
!> @brief
C
      TYPE(BIEF_OBJ), TARGET :: GRADZN
!
!     2D MASK, FOR TELEMAC2D COMPATIBILITY
!
      TYPE(BIEF_OBJ), TARGET :: MASK,MASK_3D
!
!     BLOCKS OF ARRAYS FOR THE USER
!
      TYPE(BIEF_OBJ), TARGET :: PRIVE
!
!     BLOCKS OF ARRAYS FOR THE USER
!
      TYPE(BIEF_OBJ), TARGET :: MAT2D, TM1
!
!     BLOCKS THAT WILL CONTAIN WORK STRUCTURES
!
      TYPE(BIEF_OBJ), TARGET :: TRAV3,TRAV2,ITRAV3
!
      TYPE(BIEF_OBJ), TARGET :: VARSOR, VARCL
!
      TYPE(BIEF_OBJ), TARGET :: VARSO3
!
!     VALUES OF ADVECTED VARIABLES AT SOURCES
!
      TYPE(BIEF_OBJ), TARGET :: U_SCE,V_SCE,W_SCE,AK_SCE,EP_SCE,TA_SCE
!
!     VOID BLOCK FOR CALL COMPATIBILITY
!
      TYPE(BIEF_OBJ), TARGET :: BVIDE
C
C-----------------------------------------------------------------------
C (4) INTEGERS
C-----------------------------------------------------------------------
C KEYWORDS AND PARAMETERS
C
!> @brief
C maximum de points sources
      INTEGER, PARAMETER :: MAXSCE = 100
!> @brief
C maximum de frontieres liquides
      INTEGER, PARAMETER :: MAXFRO = 100
!> @brief
C maximum number of tracers
      INTEGER, PARAMETER :: MAXTRA = 20
!> @brief
C maximum de variables de sortie
      INTEGER, PARAMETER :: MAXVAR = 100
!> @brief
C
      INTEGER, PARAMETER :: MAXVA3 = 100
!> @brief NUMBER OF TIME STEPS
C nombre total de pas de temps
      INTEGER NIT
!> @brief NUMBER OF HORIZONTAL PLANES
C nombre de plans horizontaux
      INTEGER NPLAN
!> @brief NUMBER OF TRACERS
C nombre de traceurs actifs
      INTEGER NTRAC
!> @brief
C
      INTEGER NTRACER
!> @brief PRINTOUT PERIOD FOR FLOATING BODIES
C periode pour les sorties de flotteurs
      INTEGER FLOPRD
!> @brief NUMBER OF DROGUES
C nombre de flotteurs
      INTEGER NFLOT
!> @brief
      INTEGER GRAPRD
!> @brief LISTING PRINTOUT PERIOD
C periode pour les sorties listing
      INTEGER LISPRD
!> @brief NUMBER OF FIRST TIME STEP FOR GRAPHIC PRINTOUTS
C numero du premier pas de temps pour les sorties graphiques
      INTEGER GRADEB
!> @brief NUMBER OF FIRST TIME STEP FOR LISTING PRINTOUTS
C numero du premier pas de temps pour les sorties listing
      INTEGER LISDEB
!> @brief NUMBER OF BOTTOM SMOOTHINGS
C nombre de lissages du fond
      INTEGER LISFON
!> @brief NUMBER OF SUB ITERATIONS FOR NON LINEARITIES
C nombre de sous iterations pour les non linearites
      INTEGER NSOUSI
!> @brief
C numero du plan intermediaire
      INTEGER NPLINT
!> @brief HORIZONTAL TURBULENCE MODEL
C modele de turbulence horizontal
      INTEGER ITURBH
!> @brief VERTICAL TURBULENCE MODEL
C modele de turbulence vertical
      INTEGER ITURBV
!> @brief TURBULENCE MODEL FOR THE BOTTOM
C regime de turbulence pour le fond
      INTEGER LISRUF
!> @brief TURBULENCE MODEL FOR LATERAL SOLID BOUNDARIES
C regime de turbulence pour les parois laterales
      INTEGER LISRUL
!> @brief INITIAL GUESS FOR DEPTH
C ordre du tir initial pour la hauteur
      INTEGER IORDRH
!> @brief SPATIAL PROJECTION TYPE
C type de projection spatiale
      INTEGER PROTYP
!> @brief
C nombre de points sources
      INTEGER NSCE
!> @brief
C adresses des points sources dans le maillage 2d
      INTEGER ISCE(MAXSCE)
!> @brief
C adresses des plans des points sources trouves
      INTEGER KSCE(MAXSCE)
!> @brief
C
      INTEGER NREJEU
!> @brief SCHEME FOR ADVECTION OF VELOCITIES
C schema pour la convection des vitesses
      INTEGER SCHCVI
!
!     SCHEME FOR ADVECTION OF TRACERS
!
      INTEGER SCHCTA(MAXTRA)
!
!     SCHEME FOR ADVECTION OF K-EPSILON
!
      INTEGER SCHCKE
!
!     SCHEME FOR ADVECTION OF DEPTH
!
      INTEGER SCHCH
!
!     SCHEME FOR DIFFUSION OF VELOCITIES
!
      INTEGER SCHDVI
!
!     SCHEME FOR DIFFUSION OF TRACERS
!
      INTEGER SCHDTA
!
!     SCHEME FOR DIFFUSION OF K-EPSILON
!
      INTEGER SCHDKE
!> @brief MAXIMUM NUMBER OF RECORDS OF FLOATING BODY POSITIONS
C nombre maximal d'enregistrements des positions successives des flotteurs
      INTEGER NITFLO
!> @brief TREATMENT ON TIDAL FLATS FOR VELOCITIES
C traitement sur les bancs decouvrants pour les vitesses
      INTEGER TRBAVI
!> @brief TREATMENT ON TIDAL FLATS FOR TRACERS
C traitement sur les bancs decouvrants pour les traceurs
      INTEGER TRBATA
!> @brief TREATMENT ON TIDAL FLATS FOR K-EPSILON
C traitement sur les bancs decouvrants pour le k-epsilon
      INTEGER TRBAKE
!> @brief NUMBER OF BOUNDARIES WITH PRESCRIBED DISCHARGE
C
      INTEGER NDEBIT
!> @brief NUMBER OF BOUNDARIES WITH PRESCRIBED ELEVATION
C
      INTEGER NCOTE
!> @brief NUMBER OF BOUNDARIES WITH PRESCRIBED VELOCITY
C
      INTEGER NVIT
!> @brief ORIGINAL DATE OF TIME
C tableau contenant la date de l'origine des temps
      INTEGER MARDAT(3)
!> @brief ORIGINAL HOUR OF TIME
C tableau contenant l'heure de l'origine des temps
      INTEGER MARTIM(3)
!> @brief VECTOR LENGTH
C longueur du vecteur
      INTEGER LVMAC
!> @brief NUMBER OF ARRAYS IN BLOCK PRIVE
C nombre de tableaux prives
      INTEGER NPRIV
!> @brief RANK OF TEMPERATURE IN TRACERS
C
      INTEGER IND_T
!> @brief RANK OF SALINITY
C
      INTEGER IND_S
!> @brief
C
      INTEGER NDP
!> @brief LAW OF BOTTOM FRICTION
C loi de frottement sur le fond
      INTEGER KFROT
!> @brief LAW OF FRICTION ON LATERAL BOUNDARIES
C loi de frottement sur les parois laterales
      INTEGER KFROTL
!> @brief MATRIX STORAGE
C stockage des matrices
      INTEGER OPTASS
!> @brief
C
      INTEGER PRODUC
!> @brief OPTION FOR THE TREATMENT OF TIDAL FLATS
C option de traitement des bancs decouvrants
      INTEGER OPTBAN
!
!     TREATMENT OF NEGATIVE DEPTHS
!
      INTEGER OPT_HNEG
!> @brief
C
      INTEGER OPDVIT,OPTSOU
!
!     SUPG OPTION
!
      INTEGER OPTSUP(4)
!> @brief
C
      INTEGER OPTASS2D
!
!     3D DISCRETISATION TYPE
!
      INTEGER IELM3
!
!     2D DISCRETISATION TYPES, HORIZONTAL, VERTICAL
!
      INTEGER IELM2H,IELM2V
!
!
!
      INTEGER IELM0, IELMH, IELMU, IELM1, IELMX
!
!     NUMBER OF LAYERS OF 3D ELEMENTS (NPLAN - 1)
!
      INTEGER NETAGE
!> @brief
C nombre de variables traitees dans le bilan
      INTEGER NVBIL
!> @brief MAXIMUM NUMBER OF HORIZONTAL PLANES WITHIN THE BED (GIBSON MODEL)
C nombre maximum de plans horizontaux discretisant le fond vaseux (modele de gibson)
      INTEGER NPFMAX
!> @brief NUMBER OF LAYERS WITHIN THE BED (MULTILAYER MODEL)
C nombre de couches discretisant le fond vaseux (modele de tassement multi-couches)
      INTEGER NCOUCH
!> @brief MIXING LENGTH MODEL
C modele de longueur de melange
      INTEGER MIXING
!> @brief DAMPING FUNCTION
C fonction d'amortissement
      INTEGER DAMPING
!> @brief VELOCITY PROFILES
C profils de vitesse
      INTEGER PROFVEL(MAXFRO)
!> @brief TREATMENT OF FLUXES AT THE BOUNDARIES
C traitement des flux aux frontieres
      INTEGER DIRFLU(MAXFRO)
!> @brief VELOCITY VERTICAL PROFILES
C profils de vitesse sur la verticale
      INTEGER VERPROVEL(MAXFRO)
!
!     TRACERS VERTICAL PROFILES
!
      INTEGER VERPROTRA(MAXFRO*MAXTRA)
! 
!     NUMBER OF LIQUID BOUNDARIES, OF SOLID BOUNDARIES
!     FIRST AND LAST POINTS OF THESE BOUNDARIES
!
      INTEGER NFRLIQ,NFRSOL
      INTEGER DEBLIQ(MAXFRO),FINLIQ(MAXFRO)
      INTEGER DEBSOL(MAXFRO),FINSOL(MAXFRO)
!
!     CHOICE OF MESH TRANSFORMATION
!
      INTEGER TRANSF
!
!     OPTION FOR THE DIFFUSION
!
      INTEGER OPTDIF
!
!     CHOICE OF DENSITY LAW
!
      INTEGER DENLAW
!
!     DELWAQ PRINTOUT PERIOD
!
      INTEGER WAQPRD
!
!     ORIGIN COORDINATES
!
      INTEGER I_ORIG,J_ORIG
!
!     NUMBER OF POINTS GIVEN FOR EACH DISCHARGE-ELEVATIONS CURVES
!
      INTEGER PTS_CURVES(MAXFRO)
!
!     STAGE-DISCHARGE CURVES
!
      INTEGER STA_DIS_CURVES(MAXFRO)
!
!     KEYWORD DEBUGGER
!
      INTEGER DEBUG
!
!     SKIN FRICTION
!
      INTEGER ICR
!
!     Equilibrium transport formula
!
      INTEGER ICQ
!      
!     RECORD NUMBER IN THE WAVE DRIVEN CURRENTS FILE
!
      INTEGER NPTH
!
!     GEOMETRY FILE NUMBER
!
      INTEGER T3DGEO
!
!     BOUNDARY CONDITIONS FILE NUMBER
!
      INTEGER T3DCLI
!
!     PREVIOUS COMPUTATION FILE NUMBER
!
      INTEGER T3DPRE
!
!     RESULT FILE NUMBER
!
      INTEGER T3DRES
!
!     BOTTOM TOPOGRAPHY FILE NUMBER
!
      INTEGER T3DFON
!
!     FILE NUMBER FOR SCOPE
!
      INTEGER T3DSCO
!
!     2D RESULT FILE NUMBER
!
      INTEGER T3DHYD
!
!     FORMATTED DATA FILE 1
!
      INTEGER T3DFO1
!
!     FORMATTED DATA FILE 2
!
      INTEGER T3DFO2
!
!     BINARY DATA FILE 1
!
      INTEGER T3DBI1
!
!     BINARY DATA FILE 2
!
      INTEGER T3DBI2
!
!
!
      INTEGER T3DSED
!
!     
!
      INTEGER T3DSUS
!
!     REFERENCE FILE NUMBER
!
      INTEGER T3DREF
!
!     LIQUID BOUNDARIES FILE NUMBER
!
      INTEGER T3DIMP
!
!     FILES FOR DELWAQ
!
      INTEGER T3DDL1,T3DDL2,T3DDL3,T3DDL4,T3DDL5,T3DDL6,T3DDL7,T3DDL8
      INTEGER T3DDL9,T3DL10,T3DL11
!
!     STAGE-DISCHARGE CURVES FILE NUMBER
!
      INTEGER T3DPAR
!
!     SOURCES FILE NUMBER
!
      INTEGER T3DVEF
!
!     BINARY RESULTS FILE NUMBER
!
      INTEGER T3DRBI
!
!     FORMATTED RESULTS FILE NUMBER
!
      INTEGER T3DRFO
!
!     MIGRHYCAR STEERING FILE
!
      INTEGER T3DMIG
!
!     NUMBER OF VARIABLES TO BE ADVECTED BY A GIVEN SCHEME
!     AND THEIR LIST IN THE LIST OF ADVECTED VARIABLES
!     S_ADV: ASSOCIATED ADVECTION SCHEME
!     NOM_ADV: RANK TO FIND THE NAME IN TEXT3 
!
      INTEGER N_ADV(0:15),LIST_ADV(100,0:15),S_ADV(5+MAXTRA)
      INTEGER NOM_ADV(5+MAXTRA)
!
!     COUPLING PERIODS FOR SISYPHE AND TOMAWAC 
!
      INTEGER PERCOU_SIS,PERCOU_WAC
!
!     BOUNDARY CONDITION ON THE BOTTOM 
!
      INTEGER BC_BOTTOM
!
!     THOMPSON BOUNDARY CONDITIONS 
!
      INTEGER FRTYPE(MAXFRO)
!
!     VERTICAL VELOCITY DERIVATIVES
!
      INTEGER LINLOG
!
!-----------------------------------------------------------------------
! (5) LOGICAL VALUES
!-----------------------------------------------------------------------
!
! LOGICAL STEERING PARAMETERS
!
      LOGICAL DEBU,   PROP
!
!     IF YES, CORIOLIS
!
      LOGICAL CORIOL
!
!     IF YES, WIND TAKEN INTO ACCOUNT
!
      LOGICAL VENT
!
!     AIR PRESSURE
!
      LOGICAL ATMOS
!
!     IF YES, SEDIMENT
!
      LOGICAL SEDI
!
!     IF YES, TIDAL FLATS
!
      LOGICAL BANDEC
!
!     IF YES, PROPAGATION LINEARISED
!
      LOGICAL PROLIN
!
!     IF YES, MASS BALANCE
!
      LOGICAL BILMAS
!> @brief
C
      LOGICAL INFMAS
!> @brief
C
      LOGICAL SIGMAG
!> @brief IF YES, HYDROSTATIC INCONSISTENCY FILTER
C si oui, filtre les inconsistances hydrostatiques
      LOGICAL INCHYD
!> @brief
      LOGICAL SORIMP(MAXVAR), SORG2D(MAXVAR)
!> @brief
      LOGICAL SORIM3(MAXVA3), SORG3D(MAXVA3)
!> @brief IF YES, 2D CONTINUATION
C si oui, suite 2d
      LOGICAL SUIT2
!> @brief IF YES, RAIN OR EVAPORATION
C si oui, pluie ou evaporation
      LOGICAL RAIN
!> @brief IF YES, STABILISED INITIAL CONDITION
C si oui, consolidation initiale stabilisee
      LOGICAL CONSOL
!> @brief IF YES, ELEMENTS MASKED BY USER
C si oui, elements masques par l'utilisateur
      LOGICAL MSKUSE
!> @brief DIF(I) WILL SAY IF DIFFUSION SOLVER I IS USED FOR AT LEAST ONE OF THE VARIABLES
      LOGICAL DIF(0:2)
!> @brief
      LOGICAL SPHERI
!> @brief IF YES, THERE ARE MASKED ELEMENTS
C si oui, presence d'elements masques
      LOGICAL MSK
!> @brief
      LOGICAL CLIPH
!> @brief IF YES, LISTING PRINTOUT
C si oui, sortie listing
      LOGICAL LISTIN
!> @brief IF YES, INFORMATION PRINTED ON LISTING
C si oui, informations a restituer sur le listing
      LOGICAL INFOGR
!> @brief IF YES, VARIABLES FOR SUBIEF3D
C si oui, variables pour subief3d
      LOGICAL VARSUB
!> @brief IF YES, VALIDATION
C si oui, validation
      LOGICAL VALID
!> @brief IF YES, MULTILAYER CONSOLIDATION MODEL
C si oui, modele de tassement multi-couches
      LOGICAL TASSE
!> @brief IF YES, GIBSON CONSOLIDATION MODEL
C si oui, modele de tassement de gibson
      LOGICAL GIBSON
!> @brief IF YES, INFLUENCE OF TURBULENCE ON SETTLING VELOCITY
C si oui, influence de la turbulence sur la vitesse de chute
      LOGICAL TURBWC
!> @brief IF YES, COHESIVE SEDIMENT
C si oui, sediment cohesif
      LOGICAL SEDCO
!> @brief IF YES, NON-HYDROSTATIC VERSION
C si oui, version non-hydrostatique
      LOGICAL NONHYD
!> @brief
C
      LOGICAL CONPRO
!> @brief FOR INITIALISATION OF K-EPSILON (SET IN CONDIM)
C
      LOGICAL AKEP
!> @brief FOR INITIALISATION OF K-OMEGA (SET IN CONDIM)
C
      LOGICAL AKOM
!> @brief IF YES, INITIAL TIME RESET TO ZERO IN A COMPUTATION CONTINUED
C si oui, remise a zero du temps
      LOGICAL RAZTIM
!> @brief IF YES, DYNAMIC PRESSURE IN WAVE EQUATION
C si oui, pression dynamique dans l'equation d'onde
      LOGICAL DPWAVEQ
!
!     IF YES, DYNAMIC BOUNDARY CONDITION
!
      LOGICAL CLDYN
!
!     IF YES, SALINITY FOR DELWAQ
!
      LOGICAL SALI_DEL
!
!     IF YES, TEMPERATURE FOR DELWAQ
!
      LOGICAL TEMP_DEL
!
!     IF YES, VELOCITY FOR DELWAQ
!
      LOGICAL VELO_DEL
!
!     IF YES, DIFFUSION FOR DELWAQ
!
      LOGICAL DIFF_DEL
!
!     IF YES, WAVE DRIVEN CURRENTS
!
      LOGICAL COUROU
!
!     IF YES, BYPASS VOID VOLUMES
!
      LOGICAL BYPASS
!
!     PROJECTION OF VELOCITY ON LATERAL SOLID BOUNDARIES
!
      LOGICAL VELPROLAT
!
!     PROJECTION OF VELOCITY ON BOTTOM
!
      LOGICAL VELPROBOT
!
!     FOR CALCULATING FLUXES OF ADVECTED VARIABLES
!
      LOGICAL CALCFLU(5+MAXTRA)
!
!     FOR TAKING INTO ACCOUNT RAIN IN ADVECTION OF VARIABLES
!
      LOGICAL CALCRAIN(5+MAXTRA)
!
!     OIL SPILL MODEL
!
      LOGICAL SPILL_MODEL
!
!     THOMFR (TRUE IF ONE OF THE VALIUES IN FRTYPE IS 2)
!
      LOGICAL THOMFR
!
!-----------------------------------------------------------------------
! (6) REALS
!-----------------------------------------------------------------------
!
!     TIME
!
      DOUBLE PRECISION AT
!
!     TIMESTEP
!
      DOUBLE PRECISION DT
!
!     DURATION
!
      DOUBLE PRECISION DUREE
!
!     GRAVITY ACCELERATION
!
      DOUBLE PRECISION GRAV
!
!     CORIOLIS COEFFICIENT
!
      DOUBLE PRECISION FCOR
!
!     DRAG COEFFICIENT OF WIND
!
      DOUBLE PRECISION FAIR
!
!     WIND VELOCITY ALONG X, AND Y
!
      DOUBLE PRECISION FUAIR,FVAIR
!
!     AIR TEMPERATURE
!
      DOUBLE PRECISION TAIR
!
!     WATER DENSITY AT REFERENCE CONCENTRATION
!
      DOUBLE PRECISION RHO0
!
!     FRICTION COEFFICIENT FOR THE BOTTOM
!
      DOUBLE PRECISION RUGOF0
!
!     FRICTION COEFFICIENT FOR LATERAL SOLID BOUNDARIES
!
      DOUBLE PRECISION RUGOL0
!
!     ZERO
!
      DOUBLE PRECISION ZERO
!
!     MINIMAL VALUE FOR DEPTH
!
      DOUBLE PRECISION HMIN
!
!     MEAN DEPTH FOR LINEARIZATION
!
      DOUBLE PRECISION HAULIN
!
!     COEFFICIENT FOR HORIZONTAL DIFFUSION OF VELOCITIES
!
      DOUBLE PRECISION DNUVIH
!
!     COEFFICIENT FOR VERTICAL DIFFUSION OF VELOCITIES
!
      DOUBLE PRECISION DNUVIV
!
!     COEFFICIENT FOR HORIZONTAL DIFFUSION OF TRACERS
!
      DOUBLE PRECISION DNUTAH
!
!     COEFFICIENT FOR VERTICAL DIFFUSION OF TRACERS
!
      DOUBLE PRECISION DNUTAV
!
!     INITIAL DEPTH
!
      DOUBLE PRECISION HAUTIN
!
!     INITIAL ELEVATION
!
      DOUBLE PRECISION COTINI
!
!     RAIN OR EVAPORATION IN MM PER DAY
!
      DOUBLE PRECISION RAIN_MMPD
!
!     IMPLICITATION FOR DEPTH
!
      DOUBLE PRECISION TETAH
!
!     IMPLICITATION FOR VELOCITIES
!
      DOUBLE PRECISION TETAU
!
!     IMPLICITATIONS FOR DIFFUSION ?
!
      DOUBLE PRECISION TETAD,TETADI
!
!     MASS-LUMPING FOR DEPTH, DIFFUSION, VELOCITIES
!
      DOUBLE PRECISION AGGLOH,AGGLOD,AGGLOU
!
!     ARRAY OF PRESCRIBED FLOWRATES, ELEVATIONS, VELOCITIES
!
      DOUBLE PRECISION DEBIMP(MAXFRO),COTIMP(MAXFRO),VITIMP(MAXFRO)
!
!     BETA EXPANSION COEFFICIENT FOR TRACERS
!
      DOUBLE PRECISION BETAC(MAXTRA)
!
!     REFERENCE CONCENTRATION OF TRACERS
!
      DOUBLE PRECISION T0AC(MAXTRA)
!
!     INITIAL VALUES OF TRACERS
!
      DOUBLE PRECISION TRAC0(MAXTRA)
!
!     DENSITY OF THE SEDIMENT
!
      DOUBLE PRECISION RHOS
!
!     CRITICAL SHEAR STRESS FOR DEPOSITION
!
      DOUBLE PRECISION TOCD
!
!     CONCENTRATION (G/L) OF FRESH DEPOSITS
!
      DOUBLE PRECISION CFDEP
!
!     REFERENCE BED LAYER THICKNESS FOR NEW LAYER CREATION
!
      DOUBLE PRECISION EPAI0
!
!     TIMESTEP FOR CONSOLIDATION
!
      DOUBLE PRECISION DTC
!
!     CONCENTRATION (G/L) OF THE CONSOLIDATED MUD
!
      DOUBLE PRECISION CFMAX
!
!     EROSION COEFFICIENT (EMPIRICAL PARTHENIADES COEFFICIENT)
!
      DOUBLE PRECISION MPART
!
!     CRITICAL SHEAR STRESS FOR EROSION (FRESH DEPOSIT)
!
      DOUBLE PRECISION TOCE
!
!     FLOCULATION COEFFICIENT
!
      DOUBLE PRECISION TURBA
!
!     COEFFICIENT RELATIVE TO FLOC DESTRUCTION
!
      DOUBLE PRECISION TURBB
!
!     CONSOLIDATION TIME SCALE (ONLY FOR MULTILAYER MODEL)
!
      DOUBLE PRECISION TREST(30)
!
!     CONSTANT SEDIMENT SETTLING VELOCITY (M/S)
!
      DOUBLE PRECISION WCHU0
!> @brief MEAN DIAMETER OF THE SEDIMENT
C diametre moyen des grains
      DOUBLE PRECISION D50
!> @brief GEOGRAPHICAL LATITUDE IN GRAD, POSITIVE FOR NORTHERN AND NEGATIVE ON SOUTHERN HEMISPHERE
C
      DOUBLE PRECISION PHILAT
!> @brief UPWIND COEFFICIENT (BETWEEN 0 AND 1)
C
      DOUBLE PRECISION DELTA
!> @brief HORIZONTAL CORIOLIS PARAMETERS
C
      DOUBLE PRECISION FHOR
!> @brief VERTICAL CORIOLIS PARAMETERS
C
      DOUBLE PRECISION FVER
!> @brief LATITUDE OF THE ORIGIN POINT
C latitude du point origine
      DOUBLE PRECISION LATIT
!> @brief LONGITUDE OF THE ORIGIN POINT
C longitude du point origine
      DOUBLE PRECISION LONGIT
!> @brief NORTH
C nord
      DOUBLE PRECISION NORD
!> @brief FREE SURFACE GRADIENT COMPATIBILITY IN WAVE EQUATION
C compatibilite du gradient de surface libre
      DOUBLE PRECISION TETAZCOMP
!> @brief ABSCISSAE F SOURCES
C abscisses des sources
      DOUBLE PRECISION XSCE(MAXSCE)
!> @brief ORDINATES OF SOURCES
C ordonnees des sources
      DOUBLE PRECISION YSCE(MAXSCE)
!> @brief ELEVATIONS OF SOURCES
C cotes des points sources donnes
      DOUBLE PRECISION ZSCE(MAXSCE)
!> @brief VELOCITIES OF THE SOURCES ALONG X
C vitesse des sources selon x
      DOUBLE PRECISION USCE(MAXSCE)
!> @brief VELOCITIES OF THE SOURCES ALONG Y
C vitesse des sources selon y
      DOUBLE PRECISION VSCE(MAXSCE)
!> @brief WATER DISCHARGE OF SOURCES TAKEN FROM STEERING FILE
C debits des sources dans le fichier cas
      DOUBLE PRECISION QSCE(MAXSCE)
!> @brief WATER DISCHARGE OF SOURCES COMPUTED WITH T3D_DEBSCE (VARIATIONS IN TIME)
C debits des sources calcule dans t3d_debsce
      DOUBLE PRECISION QSCE2(MAXSCE)
!> @brief VALUE OF THE TRACERS AT THE SOURCES TAKEN FROM STEERING FILE
C valeurs des traceurs des sources dans le fichier cas
      DOUBLE PRECISION TASCE(MAXSCE,MAXTRA)
!> @brief PRESCRIBED VALUES OF TRACERS AT LIQUID BOUNDARIES
C valeurs imposees des traceurs
      DOUBLE PRECISION TRACER(MAXFRO*MAXTRA)
!> @brief RATIO BETWEEN SKIN FRICTION AND MEAN DIAMETER
C ratio entre la rugosite de peau et le diametre moyen des grains
      DOUBLE PRECISION KSPRATIO
!> @brief SHIELDS PARAMETER
C parametre de shields
      DOUBLE PRECISION AC
!
!     FLUX AT BOUNDARIES
!
      DOUBLE PRECISION FLUX_BOUNDARIES(MAXFRO)
!
!     FOR STORING DISCHARGE-ELEVATION CURVES
!
      DOUBLE PRECISION, ALLOCATABLE :: QZ(:,:,:)
!
!     THRESHOLD DEPTH FOR WIND
!
      DOUBLE PRECISION HWIND
!
!     CUMULATED FLUXES OF WATER SINCE BEGINNING OF COMPUTATION
!
      DOUBLE PRECISION FLUXTOTCUM
!
!     INITIAL, PAST AND PRESENT MASS OF WATER
!
      DOUBLE PRECISION MASINI_WATER, MASSEN_WATER,MASSE_WATER
!
!     THRESHOLD FOR VISCOSITY CORRECTION ON TIDAL FLATS
!
      DOUBLE PRECISION HLIM
!
!-----------------------------------------------------------------------
! (7) STRINGS
!-----------------------------------------------------------------------
!
!     TITLE
!
      CHARACTER(LEN=72) TITCAS
!> @brief
C
      CHARACTER(LEN=72) SORT3D,SORT2D
!> @brief
C
      CHARACTER(LEN=72) VARIMP
!> @brief
C
      CHARACTER(LEN=72) VARIM3
!> @brief INITIAL CONDITIONS
C conditions initiales
      CHARACTER(LEN=72) CDTINI
!> @brief ELEMENT
C element
      CHARACTER(LEN=72) ELEMENT
!> @brief
C
      CHARACTER(LEN=3)  BINGEO
!> @brief
C binaire du fichier de resultats
      CHARACTER(LEN=3)  BINRES
!> @brief
C
      CHARACTER(LEN=3)  BINPRE
!> @brief
C
      CHARACTER(LEN=3)  BINHYD
!> @brief
C
      CHARACTER(LEN=20) EQUA
!> @brief
C
      CHARACTER(LEN=32) VARCLA(10)
!> @brief NAMES OF VARIABLES RECOGNISED FROM RESULTS AND GEOMETRY FILES
C noms des variables reconnues dans les fichiers de resultat et de geometrie
      CHARACTER(LEN=32) TEXTE(MAXVAR)
!> @brief NAMES OF VARIABLES RECOGNISED FROM PREVIOUS COMPUTATION FILE
C noms des variables reconnues dans le fichier de calcul precedent
      CHARACTER(LEN=32) TEXTPR(MAXVAR)
!> @brief
C
      CHARACTER(LEN=32) TEXT3(MAXVA3)
!> @brief
C
      CHARACTER(LEN=32) TEXTP3(MAXVA3)
!> @brief
C binaire du fichier des resultats sedimentologiques
      CHARACTER(LEN=3) BIRSED
!> @brief
C binaire du fichier du calcul sedimentologique precedent
      CHARACTER(LEN=3) BISUIS
!> @brief NAMES OF TRACERS
C noms des traceurs
      CHARACTER(LEN=32) NAMETRAC(32)
C
C-----------------------------------------------------------------------
C (8) SLVCFG STRUCTURES
C-----------------------------------------------------------------------
C
!> @brief SOLVER FOR DIFFUSION OF VELOCITIES
C solveur pour la diffusion des vitesses
      TYPE(SLVCFG) :: SLVDVI
!> @brief SOLVER FOR PROPAGATION
C solveur pour la propagation
      TYPE(SLVCFG) :: SLVPRO
!> @brief SOLVER FOR DIFFUSION OF K-EPSILON
C solveur pour la diffusion du k-epsilon
      TYPE(SLVCFG) :: SLVDKE
!> @brief SOLVER FOR DIFFUSION OF TRACERS
C solveur pour la diffusion des traceurs
      TYPE(SLVCFG) :: SLVDTA(MAXTRA)
!> @brief SOLVER FOR VERTICAL VELOCITY COMPONENT
C solveur pour la vitesse verticale
      TYPE(SLVCFG) :: SLVW
!> @brief SOLVER FOR DIFFUSION OF THE SEDIMENT
C solveur pour la diffusion du sediment
      TYPE(SLVCFG) :: SLVDSE
!> @brief SOLVER FOR PPE (NON-HYDROSTATIC)
C solveur pour ppe
      TYPE(SLVCFG) :: SLVPOI
!> @brief SOLVER FOR PROJECTION (NON-HYDROSTATIC)
C solveur pour la projection
      TYPE(SLVCFG) :: SLVPRJ
C
c-----------------------------------------------------------------------
C (9) MESH STRUCTURE(S)
C-----------------------------------------------------------------------
C 2 SEPARATE MESHES, 2D AS USUAL AND 3D WITH SIGMA-MESH SPECIFIC
C FEATURES, SEE ALMESH.F
C
!> @brief 2D MESH WITH SIGMA-MESH SPECIFIC FEATURES
C maillage 2d
      TYPE(BIEF_MESH) :: MESH2D
!> @brief 3D MESH WITH SIGMA-MESH SPECIFIC FEATURES
! maillage 3d
      TYPE(BIEF_MESH) :: MESH3D
!
!-----------------------------------------------------------------------
! (10) ALIASES
!-----------------------------------------------------------------------
!
!     DECLARATION OF POINTERS FOR ALIASES
!     TARGETS ARE ALLOCATED AND POINTED TO IN POINT_TELEMAC3D
!
!     ALIASES FOR WORKING VECTORS, REAL 3D, INTEGER 3D, REAL 2D
!
!
!     BIEF_OBJ STRUCTURES FOR ARRAYS OF DIMENSION NPOIN3
!
      TYPE(BIEF_OBJ), POINTER :: T3_01,T3_02,T3_03,T3_04,T3_05
      TYPE(BIEF_OBJ), POINTER :: T3_06,T3_07,T3_08,T3_09,T3_10
      TYPE(BIEF_OBJ), POINTER :: T3_11,T3_12,T3_13,T3_14,T3_15
      TYPE(BIEF_OBJ), POINTER :: T3_16,T3_17,T3_18
!
!     BIEF_OBJ STRUCTURES FOR INTEGER ARRAYS
!
      TYPE(BIEF_OBJ), POINTER :: IT1, IT2, IT3, IT4
!
!     BIEF_OBJ STRUCTURE FOR LOCAL WORK, DIMENSION NPOIN2
!
      TYPE(BIEF_OBJ), POINTER :: T2_01,T2_02,T2_03,T2_04,T2_05
      TYPE(BIEF_OBJ), POINTER :: T2_06,T2_07,T2_08,T2_09,T2_10
      TYPE(BIEF_OBJ), POINTER :: T2_11,T2_12,T2_13,T2_14,T2_15
      TYPE(BIEF_OBJ), POINTER :: T2_16,T2_17,T2_18,T2_19,T2_20
      TYPE(BIEF_OBJ), POINTER :: T2_21,T2_22,T2_23
!
!     2D NODE COORDINATES
!
      TYPE(BIEF_OBJ), POINTER :: X2,Y2
!
!
!
      TYPE(BIEF_OBJ), POINTER :: Z2
!
!     3D NODE COORDINATES
!
      TYPE(BIEF_OBJ), POINTER :: X3,Y3,Z3
!
!     2D WORKING MATRIX ALLOCATED WITH THE MESH
!
      TYPE(BIEF_OBJ), POINTER :: MTRA2D
!> @brief 2D ELEMENT-ORIENTED WORKING FIELD ALLOCATED WITH THE MESH
C tableau de travail
      TYPE(BIEF_OBJ), POINTER :: W2
!> @brief 3D ELEMENT-ORIENTED WORKING FIELD ALLOCATED WITH THE MESH
C tableau de travail
      TYPE(BIEF_OBJ), POINTER :: W1
!> @brief BASE TRIANGLE SURFACES
C
      TYPE(BIEF_OBJ), POINTER :: SURFA2
!> @brief TRIANGLE SURFACES, IN 3D
C
      TYPE(BIEF_OBJ), POINTER :: SURFA3
!> @brief LATERAL BOUNDARY NORMAL VECTORS DEFINED AT THE NODES
C composantes du vecteur normal aux points frontieres
      TYPE(BIEF_OBJ), POINTER :: XNEBOR2
!> @brief LATERAL BOUNDARY NORMAL VECTORS DEFINED AT THE NODES
C composantes du vecteur normal aux points frontieres
      TYPE(BIEF_OBJ), POINTER :: YNEBOR2
!> @brief 2D NORMAL VECTORS DEFINED PER BOUNDARY SEGMENT
C
      TYPE(BIEF_OBJ), POINTER :: XSGBOR2
!> @brief 2D NORMAL VECTORS DEFINED PER BOUNDARY SEGMENT
C
      TYPE(BIEF_OBJ), POINTER :: YSGBOR2
!> @brief 3D NORMAL VECTORS DEFINED PER BOUNDARY ELEMENT
C
      TYPE(BIEF_OBJ), POINTER :: XSGBOR3
!> @brief 3D NORMAL VECTORS DEFINED PER BOUNDARY ELEMENT
C
      TYPE(BIEF_OBJ), POINTER :: YSGBOR3
!> @brief 3D NORMAL VECTORS DEFINED PER BOUNDARY ELEMENT
C
      TYPE(BIEF_OBJ), POINTER :: ZSGBOR3
!> @brief CONNECTIVITY TABLES IN 2D  : (ELEMENT NUMBER AND LOCAL NODE NUMBER) --> GLOBAL NODE NUMBER
C table de connectivite pour les elements 2d
      TYPE(BIEF_OBJ), POINTER :: IKLE2
!> @brief CONNECTIVITY TABLES IN 3D : (ELEMENT NUMBER AND LOCAL NODE NUMBER) --> GLOBAL NODE NUMBER
C table de connectivite pour les elements 3d
      TYPE(BIEF_OBJ), POINTER :: IKLE3
!> @brief CONNECTIVITY TABLES IN 2D : (NODE BOUNDARY NUMBER) --> GLOBAL NODE NUMBER
C correspondance numerotation frontiere et numerotation globale en 2d
      TYPE(BIEF_OBJ), POINTER :: NBOR2
!> @brief CONNECTIVITY TABLES IN 3D : (NODE BOUNDARY NUMBER) --> GLOBAL NODE NUMBER
C correspondance numerotation frontiere et numerotation globale en 3d
      TYPE(BIEF_OBJ), POINTER :: NBOR3
!> @brief COORDINATES OF POINTS IN THE 3D MESH
C coordonnees du maillage 3d
      DOUBLE PRECISION, DIMENSION(:), POINTER :: X
!> @brief COORDINATES OF POINTS IN THE 3D MESH
C coordonnees du maillage 3d
      DOUBLE PRECISION, DIMENSION(:), POINTER :: Y
!> @brief COORDINATES OF POINTS IN THE 3D MESH
C coordonnees du maillage 3d
      DOUBLE PRECISION, DIMENSION(:), POINTER :: Z
!> @brief NUMBER OF ELEMENTS IN THE 2D MESH
C nombre total d'elements dans le maillage 2d
      INTEGER, POINTER:: NELEM2
!> @brief NUMBER OF ELEMENTS IN THE 3D MESH
C nombre total d'elements dans le maillage 3d
      INTEGER, POINTER:: NELEM3
!> @brief MAXIMUM NUMBER OF ELEMENTS IN THE 2D MESH
C nombre maximal d'elements dans le maillage 2d
      INTEGER, POINTER:: NELMAX2
!> @brief MAXIMUM NUMBER OF ELEMENTS IN THE 3D MESH
C nombre maximal d'elements dans le maillage 3d
      INTEGER, POINTER:: NELMAX3
!> @brief NUMBER OF BOUNDARY POINTS IN THE 2D MESH
C nombre de points frontiere du maillage 2d
      INTEGER, POINTER:: NPTFR2
!> @brief NUMBER OF BOUNDARY POINTS IN THE 3D MESH
C nombre de points sur les cotes 3d
      INTEGER, POINTER:: NPTFR3
!> @brief
C
      INTEGER, POINTER:: NELEB, NELEBX
!> @brief MAXIMUM NUMBER OF BOUNDARY POINTS IN THE 2D MESH
C
      INTEGER, POINTER:: NPTFRX2
!> @brief MAXIMUM NUMBER OF BOUNDARY POINTS IN THE 3D MESH
C
      INTEGER, POINTER:: NPTFRX3
!> @brief DIMENSION OF 2D SPACE
C
      INTEGER, POINTER:: DIM2
!> @brief DIMENSION OF 3D SPACE
C
      INTEGER, POINTER:: DIM3
!> @brief TYPE OF 2D ELEMENT
C
      INTEGER, POINTER:: TYPELM2
!> @brief TYPE OF 3D ELEMENT
C
      INTEGER, POINTER:: TYPELM3
!> @brief NUMBER OF POINTS IN THE 2D MESH
C nombre de points du maillage 2d
      INTEGER, POINTER:: NPOIN2
!> @brief NUMBER OF POINTS IN THE 3D MESH
C nombre de points du maillage 3d
      INTEGER, POINTER:: NPOIN3
!> @brief MAXIMUM NUMBER OF POINTS IN THE 2D MESH
C
      INTEGER, POINTER:: NPMAX2
!> @brief MAXIMUM NUMBER OF POINTS IN THE 3D MESH
C
      INTEGER, POINTER:: NPMAX3
!> @brief MAXIMUM NUMBER OF POINTS NEIGHBOURS OF A POINT IN 2D
C
      INTEGER, POINTER:: MXPTVS2
!> @brief MAXIMUM NUMBER OF POINTS NEIGHBOURS OF A POINT IN 3D
C
      INTEGER, POINTER:: MXPTVS3
!> @brief MAXIMUM NUMBER OF ELEMENTS NEIGHBOURS OF A POINT IN 2D
C
      INTEGER, POINTER:: MXELVS2
!> @brief MAXIMUM NUMBER OF ELEMENTS NEIGHBOURS OF A POINT IN 3D
C
      INTEGER, POINTER:: MXELVS3
!> @brief VECTOR LENGTH OF THE MACHINE (LV2=LV3, FOR SIGMA MESH)
C longueur du vecteur pour la vectorisation
      INTEGER, POINTER:: LV
C
C-----------------------------------------------------------------------
C (11) CONSTANTS INITIALISED IN CSTKEP AND CREF_FREDSOE (FOR ZREF)
C-----------------------------------------------------------------------
C
!> @brief VON KARMAN CONSTANT
C constante de karman
      DOUBLE PRECISION :: KARMAN
!> @brief K-EPSILON CONSTANT
C constante du modele k-epsilon
      DOUBLE PRECISION :: CMU
!> @brief K-EPSILON CONSTANT
C constante du modele k-epsilon
      DOUBLE PRECISION :: C1
!> @brief K-EPSILON CONSTANT
C constante du modele k-epsilon
      DOUBLE PRECISION :: C2
!> @brief K-EPSILON CONSTANT
C constante du modele k-epsilon
      DOUBLE PRECISION :: SIGMAK
!> @brief K-EPSILON CONSTANT
C constante du modele k-epsilon
      DOUBLE PRECISION :: SIGMAE
!> @brief K-EPSILON CONSTANT
C constante du modele k-epsilon
      DOUBLE PRECISION :: VIRT
!
!     SCHMIDT NUMBER
!
      DOUBLE PRECISION :: SCHMIT
!
!     MINIMUM K
!
      DOUBLE PRECISION :: KMIN
!
!     MAXIMUM K
!
      DOUBLE PRECISION :: KMAX
!
!     MINIMUM EPSILON
!
      DOUBLE PRECISION :: EMIN
!
!     MAXIMUM EPSILON
!
      DOUBLE PRECISION :: EMAX
!
!     PRANDTL NUMBER
!
      DOUBLE PRECISION :: PRANDTL
!
!     K-OMEGA MODEL CONSTANTS
!
      DOUBLE PRECISION :: ALPHA,BETA,BETAS,OMSTAR
!
!
!
      TYPE(BIEF_OBJ), TARGET :: ZREF
C-----------------------------------------------------------------------
C
C      12) TELEMAC-3D FILES
C
C-----------------------------------------------------------------------
C
!
!     MAXIMUM NUMBER OF FILES
!
      INTEGER, PARAMETER :: MAXLU_T3D = 44
!
!     DATA STRUCTURE WITH DATA ON FILES
!
      TYPE(BIEF_FILE) :: T3D_FILES(MAXLU_T3D)
C
      SAVE
C
      END MODULE DECLARATIONS_TELEMAC3D
