#/usr/bin/env python
# -*- coding: latin-1 -*-
TelemacdicoEn = {
}
TelemacdicoFr = {
}

DicoCasFrToCata = {
  "NOMBRE DE COUPES HORIZONTALES":"NUMBER_OF_HORIZONTAL_CROSS_SECTIONS",
  "NOMBRE DE COUPES VERTICALES":"NUMBER_OF_VERTICAL_CROSS_SECTIONS",
  "NUMERO DU PREMIER ENREGISTREMENT POUR LES COUPES":"NUMBER_OF_FIRST_RECORD_FOR_CROSS_SECTIONS",
  "PERIODE DE SORTIE DES COUPES":"PRINTOUT_PERIOD_FOR_CROSS_SECTIONS",
  "PLAN DE REFERENCE POUR CHAQUE COUPE HORIZONTALE":"REFERENCE_LEVEL_FOR_EACH_HORIZONTAL_CROSS_SECTION",
  "NOMBRE DE POINTS DE DISCRETISATION POUR LES COUPES VERTICALES":"NUMBER_OF_NODES_FOR_VERTICAL_CROSS_SECTION_DISCRETIZATION",
  "HAUTEUR PAR RAPPORT AU PLAN DE REFERENCE":"ELEVATION_FROM_REFERENCE_LEVEL",
  "ABSCISSES DES SOMMETS DE LA COUPE VERTICALE 1":"ABSCISSAE_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_1",
  "ORDONNEES DES SOMMETS DE LA COUPE VERTICALE 1":"ORDINATES_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_1",
  "ABSCISSES DES SOMMETS DE LA COUPE VERTICALE 2":"ABSCISSAE_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_2",
  "ORDONNEES DES SOMMETS DE LA COUPE VERTICALE 2":"ORDINATES_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_2",
  "ABSCISSES DES SOMMETS DE LA COUPE VERTICALE 3":"ABSCISSAE_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_3",
  "ORDONNEES DES SOMMETS DE LA COUPE VERTICALE 3":"ORDINATES_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_3",
  "ABSCISSES DES SOMMETS DE LA COUPE VERTICALE 4":"ABSCISSAE_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_4",
  "ORDONNEES DES SOMMETS DE LA COUPE VERTICALE 4":"ORDINATES_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_4",
  "ABSCISSES DES SOMMETS DE LA COUPE VERTICALE 5":"ABSCISSAE_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_5",
  "ORDONNEES DES SOMMETS DE LA COUPE VERTICALE 5":"ORDINATES_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_5",
  "ABSCISSES DES SOMMETS DE LA COUPE VERTICALE 6":"ABSCISSAE_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_6",
  "ORDONNEES DES SOMMETS DE LA COUPE VERTICALE 6":"ORDINATES_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_6",
  "ABSCISSES DES SOMMETS DE LA COUPE VERTICALE 7":"ABSCISSAE_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_7",
  "ORDONNEES DES SOMMETS DE LA COUPE VERTICALE 7":"ORDINATES_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_7",
  "ABSCISSES DES SOMMETS DE LA COUPE VERTICALE 8":"ABSCISSAE_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_8",
  "ORDONNEES DES SOMMETS DE LA COUPE VERTICALE 8":"ORDINATES_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_8",
  "ABSCISSES DES SOMMETS DE LA COUPE VERTICALE 9":"ABSCISSAE_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_9",
  "ORDONNEES DES SOMMETS DE LA COUPE VERTICALE 9":"ORDINATES_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_9",
  "DISTORSION ENTRE VERTICALE ET HORIZONTALE":"DISTORSION_BETWEEN_VERTICAL_AND_HORIZONTAL",
  "FICHIER FORTRAN":"FORTRAN_FILE",
  "FICHIER DES PARAMETRES":"STEERING_FILE",
  "FICHIER DES RESULTATS 3D":"RD_RESULT_FILE",
  "FORMAT DU FICHIER DES RESULTATS 3D":"RD_RESULT_FILE_FORMAT",
  "FICHIER DES COUPES HORIZONTALES":"HORIZONTAL_CROSS_SECTION_FILE",
  "FORMAT DU FICHIER DES COUPES HORIZONTALES":"HORIZONTAL_CROSS_SECTION_FILE_FORMAT",
  "FICHIER DES COUPES VERTICALES":"VERTICAL_CROSS_SECTION_FILE",
  "FORMAT DU FICHIER DES COUPES VERTICALES":"VERTICAL_CROSS_SECTION_FILE_FORMAT",
  "NUMERO DE VERSION":"RELEASE",
  "BINAIRE DU FICHIER DES RESULTATS 3D":"RD_RESULT_FILE_BINARY",
  "BINAIRE DES FICHIERS DES COUPES":"CROSS_SECTION_FILE_BINARY",
  "FICHIER DE GEOMETRIE":"GEOMETRY_FILE",
  "FORMAT DU FICHIER DE GEOMETRIE":"GEOMETRY_FILE_FORMAT",
  "BINAIRE DU FICHIER DE GEOMETRIE":"GEOMETRY_FILE_BINARY",
  "DICTIONNAIRE":"DICTIONARY",
  "LISTE DES FICHIERS":"LIST_OF_FILES",
  "DESCRIPTION DES LIBRAIRIES":"DESCRIPTION_OF_LIBRARIES",
  "EXECUTABLE PAR DEFAUT":"DEFAULT_EXECUTABLE",
  "EXECUTABLE PARALLELE PAR DEFAUT":"DEFAULT_PARALLEL_EXECUTABLE",
}

DicoCasEnToCata = {
  'NUMBER OF HORIZONTAL CROSS SECTIONS':'NUMBER_OF_HORIZONTAL_CROSS_SECTIONS',
  'NUMBER OF VERTICAL CROSS SECTIONS':'NUMBER_OF_VERTICAL_CROSS_SECTIONS',
  'NUMBER OF FIRST RECORD FOR CROSS SECTIONS':'NUMBER_OF_FIRST_RECORD_FOR_CROSS_SECTIONS',
  'PRINTOUT PERIOD FOR CROSS SECTIONS':'PRINTOUT_PERIOD_FOR_CROSS_SECTIONS',
  'REFERENCE LEVEL FOR EACH HORIZONTAL CROSS SECTION':'REFERENCE_LEVEL_FOR_EACH_HORIZONTAL_CROSS_SECTION',
  'NUMBER OF NODES FOR VERTICAL CROSS SECTION DISCRETIZATION':'NUMBER_OF_NODES_FOR_VERTICAL_CROSS_SECTION_DISCRETIZATION',
  'ELEVATION FROM REFERENCE LEVEL':'ELEVATION_FROM_REFERENCE_LEVEL',
  'ABSCISSAE OF THE VERTICES OF VERTICAL CROSS SECTION 1':'ABSCISSAE_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_1',
  'ORDINATES OF THE VERTICES OF VERTICAL CROSS SECTION 1':'ORDINATES_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_1',
  'ABSCISSAE OF THE VERTICES OF VERTICAL CROSS SECTION 2':'ABSCISSAE_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_2',
  'ORDINATES OF THE VERTICES OF VERTICAL CROSS SECTION 2':'ORDINATES_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_2',
  'ABSCISSAE OF THE VERTICES OF VERTICAL CROSS SECTION 3':'ABSCISSAE_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_3',
  'ORDINATES OF THE VERTICES OF VERTICAL CROSS SECTION 3':'ORDINATES_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_3',
  'ABSCISSAE OF THE VERTICES OF VERTICAL CROSS SECTION 4':'ABSCISSAE_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_4',
  'ORDINATES OF THE VERTICES OF VERTICAL CROSS SECTION 4':'ORDINATES_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_4',
  'ABSCISSAE OF THE VERTICES OF VERTICAL CROSS SECTION 5':'ABSCISSAE_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_5',
  'ORDINATES OF THE VERTICES OF VERTICAL CROSS SECTION 5':'ORDINATES_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_5',
  'ABSCISSAE OF THE VERTICES OF VERTICAL CROSS SECTION 6':'ABSCISSAE_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_6',
  'ORDINATES OF THE VERTICES OF VERTICAL CROSS SECTION 6':'ORDINATES_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_6',
  'ABSCISSAE OF THE VERTICES OF VERTICAL CROSS SECTION 7':'ABSCISSAE_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_7',
  'ORDINATES OF THE VERTICES OF VERTICAL CROSS SECTION 7':'ORDINATES_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_7',
  'ABSCISSAE OF THE VERTICES OF VERTICAL CROSS SECTION 8':'ABSCISSAE_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_8',
  'ORDINATES OF THE VERTICES OF VERTICAL CROSS SECTION 8':'ORDINATES_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_8',
  'ABSCISSAE OF THE VERTICES OF VERTICAL CROSS SECTION 9':'ABSCISSAE_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_9',
  'ORDINATES OF THE VERTICES OF VERTICAL CROSS SECTION 9':'ORDINATES_OF_THE_VERTICES_OF_VERTICAL_CROSS_SECTION_9',
  'DISTORSION BETWEEN VERTICAL AND HORIZONTAL':'DISTORSION_BETWEEN_VERTICAL_AND_HORIZONTAL',
  'FORTRAN FILE':'FORTRAN_FILE',
  'STEERING FILE':'STEERING_FILE',
  '3D RESULT FILE':'RD_RESULT_FILE',
  '3D RESULT FILE FORMAT':'RD_RESULT_FILE_FORMAT',
  'HORIZONTAL CROSS SECTION FILE':'HORIZONTAL_CROSS_SECTION_FILE',
  'HORIZONTAL CROSS SECTION FILE FORMAT':'HORIZONTAL_CROSS_SECTION_FILE_FORMAT',
  'VERTICAL CROSS SECTION FILE':'VERTICAL_CROSS_SECTION_FILE',
  'VERTICAL CROSS SECTION FILE FORMAT':'VERTICAL_CROSS_SECTION_FILE_FORMAT',
  'RELEASE':'RELEASE',
  '3D RESULT FILE BINARY':'RD_RESULT_FILE_BINARY',
  'CROSS SECTION FILE BINARY':'CROSS_SECTION_FILE_BINARY',
  'GEOMETRY FILE':'GEOMETRY_FILE',
  'GEOMETRY FILE FORMAT':'GEOMETRY_FILE_FORMAT',
  'GEOMETRY FILE BINARY':'GEOMETRY_FILE_BINARY',
  'DICTIONARY':'DICTIONARY',
  'LIST OF FILES':'LIST_OF_FILES',
  'DESCRIPTION OF LIBRARIES':'DESCRIPTION_OF_LIBRARIES',
  'DEFAULT EXECUTABLE':'DEFAULT_EXECUTABLE',
  'DEFAULT PARALLEL EXECUTABLE':'DEFAULT_PARALLEL_EXECUTABLE',
}
DicoEnumCasFrToEnumCasEn = {
'RD_RESULT_FILE_FORMAT':{
  "SERAFIN":"SERAFIN",
  "SERAFIND":"SERAFIND",
  "MED":"MED",
},

'HORIZONTAL_CROSS_SECTION_FILE_FORMAT':{
  "SERAFIN":"SERAFIN",
  "SERAFIND":"SERAFIND",
  "MED":"MED",
},

'VERTICAL_CROSS_SECTION_FILE_FORMAT':{
  "SERAFIN":"SERAFIN",
  "SERAFIND":"SERAFIND",
  "MED":"MED",
},

'RD_RESULT_FILE_BINARY':{
  "STD":"STD",
  "IBM":"IBM",
  "I3E":"I3E",
},

'CROSS_SECTION_FILE_BINARY':{
  "STD":"STD",
  "I3E":"I3E",
},

'GEOMETRY_FILE_FORMAT':{
  "SERAFIN":"SERAFIN",
  "SERAFIND":"SERAFIND",
  "MED":"MED",
},

'GEOMETRY_FILE_BINARY':{
  "STD":"STD",
  "I3E":"I3E",
},

}
